package(default_visibility = ["//visibility:public"])

cc_library(
    includes = ["."],
    name = "u360",
    srcs = [
        "types/TRACKER_OUTPUT_SIDE_T.h",
        "types/VEHICLE_CONFIG_FLT_T.h",
        "types/VEHICLE_DATA_FLT_T.h",
        "types/racam_enums.h",
        "types/u360_tracker_wrapper.h",
    ],
    hdrs = [
        "types/TRACKER_OUTPUT_SIDE_T.h",
        "types/VEHICLE_CONFIG_FLT_T.h",
        "types/VEHICLE_DATA_FLT_T.h",
        "types/racam_enums.h",
        "types/u360_tracker_wrapper.h",
    ],
    strip_include_prefix = "types",
    # deps = [
    #     "//Math_Library/development:dependencies",
    # ],
)
