target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_FILE})

target_include_directories(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR})

target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_common_functions.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_reset.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_object_matching.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_group_paths.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_debug_interface.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_debug_writer.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_modify_grid_cals.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_path_rotation.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_persistent_handler.h)
target_sources(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR}/pt_types.h)
target_sources(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR}/pt_directions.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_output_factory.h)
target_sources(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR}/pt_persistent_t.h)
target_sources(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR}/pt_iface.h)
target_sources(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR}/pt_input_t.h)
target_sources(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR}/pt_output_t.h)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_host_lane.h)
target_sources(PT PUBLIC ${CMAKE_CURRENT_LIST_DIR}/pt_instance.h)

target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_modify_grid_cals.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_iface.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_common_functions.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_reset.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_object_matching.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_group_paths.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_debug_interface.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_debug_writer.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_persistent_handler.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_path_rotation.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_output_factory.c)
target_sources(PT PRIVATE ${CMAKE_CURRENT_LIST_DIR}/pt_host_lane.c)
