set(tmp_cmake_folder ${CMAKE_FOLDER})
set(CMAKE_FOLDER ${CMAKE_FOLDER}/modules)

add_subdirectory(calibrations)
add_subdirectory(common)
add_subdirectory(dc_dummy_generator)
add_subdirectory(drivability_classification)
add_subdirectory(host)
add_subdirectory(math)
add_subdirectory(contour_downselection)
add_subdirectory(contour_initialization)
add_subdirectory(detection_clustering)
add_subdirectory(detection_processing)
add_subdirectory(dummy_generator)
add_subdirectory(measurement_association)
add_subdirectory(measurement_update)
add_subdirectory(postprocessing)
add_subdirectory(time_update)

set(CMAKE_FOLDER ${tmp_cmake_folder})
