import os
import argparse
import logging, coloredlogs

from python_src.ct_export_cal_check_files import create_cal_check_files
from python_src.ct_export_cal_header import create_header
from python_src.ct_export_cal_printing import create_cal_printing
from python_src.ct_export_customer_cals import create_customer_specific_c_file
from python_src.ct_export_update_calibration import create_update_calibration_files
from python_src.ct_export_customer_data_stream import create_customer_data_stream_xml
from python_src.ct_parser import parse_calibration_xml


class Validate_Xml_Path_Input(argparse.Action):
    """Class which is inheriting from Action and defining a user specific action for validation
    of the calibration tool input."""
    def __call__(self, parser: argparse.ArgumentParser, namespace: argparse.Namespace, path: str, option_string: str=None) -> None:
        """Private function to call the validation routine of the given input."""
        setattr(namespace, self.dest, path)
        # Try to open file at given path and throw an error if this is not possible.
        try:
            open(path, "r")
        except IOError as e:
            logging.critical("Error: %s: %s.", e.filename, e.strerror)


if __name__ == '__main__':
    """
    Main function of the calibration tool which expects specific prerequisites as shown in README.md and generates
    customer specific calibrations.

    Args:
        component_xml_path (str) : Path pointing to the main calibration xml of a component.

    Returns:
        Autogenerated calibration files.

    """
    # Enable support for colored logging messages and modify the format
    coloredlogs.install(fmt='[%(levelname)s] (%(asctime)s) - %(message)s', level='DEBUG')

    # define command line options
    # this also generates --help and error handling
    CLI = argparse.ArgumentParser(
        description='Parse calibration xml files and generate calibrations for given component.')
    CLI.add_argument("component_xml_path", help='Path pointing to a components main xml cal file', action=Validate_Xml_Path_Input)

    # parse the command line and put out info to the command line
    args = CLI.parse_args()
    logging.info("Invoked cal tool with %s.", args.component_xml_path)

    # get basic information from argument
    calibration_path = os.path.abspath(os.path.join(args.component_xml_path, os.pardir, os.pardir))
    core_calibration_path = os.path.abspath(os.path.join(args.component_xml_path, os.pardir))

    # Call main function for parsing of xml sheets
    core_cal_dict, customers_cal_dicts, generic_cal_info = parse_calibration_xml(args.component_xml_path, calibration_path)

    # Generate files
    core_structure_name = generic_cal_info.core_structure_name
    create_header(core_cal_dict, core_calibration_path, generic_cal_info, core_structure_name)
    create_cal_check_files(core_cal_dict, core_calibration_path, generic_cal_info, core_structure_name)
    create_cal_printing(core_cal_dict, core_calibration_path, generic_cal_info, core_structure_name)
    for customer in generic_cal_info.customers:    
        customer_calibration_path = os.path.join(calibration_path, customer)
        create_customer_specific_c_file(core_cal_dict, customer_calibration_path, generic_cal_info, customer, core_structure_name)
        create_customer_data_stream_xml(core_cal_dict, customer_calibration_path, generic_cal_info, customer, core_structure_name)
        
        customers_cal_dict = customers_cal_dicts[customer]        
        customer_structure_name = generic_cal_info.customer_structure_name
        create_header(customers_cal_dict, customer_calibration_path, generic_cal_info, customer_structure_name)
        create_cal_check_files(customers_cal_dict, customer_calibration_path, generic_cal_info, customer_structure_name)
        create_cal_printing(customers_cal_dict, customer_calibration_path, generic_cal_info, customer_structure_name)
        create_customer_specific_c_file(customers_cal_dict, customer_calibration_path, generic_cal_info, customer, customer_structure_name)
        create_customer_data_stream_xml(customers_cal_dict, customer_calibration_path, generic_cal_info, customer, customer_structure_name)
        
        all_calibration = tmp = {**core_cal_dict, **customers_cal_dict}
        public_cal_dict = {k: v for k, v in all_calibration.items() if not v.f_is_constant}
        public_structure_name = generic_cal_info.public_structure_name
        create_header(public_cal_dict, customer_calibration_path, generic_cal_info, public_structure_name)
        create_cal_check_files(public_cal_dict, customer_calibration_path, generic_cal_info, public_structure_name)
        create_cal_printing(public_cal_dict, customer_calibration_path, generic_cal_info, public_structure_name)
        create_customer_specific_c_file(public_cal_dict, customer_calibration_path, generic_cal_info, customer, public_structure_name)
        create_customer_data_stream_xml(public_cal_dict, customer_calibration_path, generic_cal_info, customer, public_structure_name)
        
        Ff = generic_cal_info.component_name
        update_calibration_methods = {
            Ff + "_Update_Core_Cal_By_Public" : (core_structure_name, public_structure_name),
            Ff + "_Update_Core_Cal_By_Core" : (core_structure_name, core_structure_name),
            Ff + "_Update_Customer_Cal_By_Public" : (customer_structure_name, public_structure_name),
        }
        calibrations_dict_of_dicts = {
            core_structure_name: core_cal_dict,
            customer_structure_name: customers_cal_dict,
            public_structure_name: public_cal_dict,
        }
        create_update_calibration_files(generic_cal_info, customer_calibration_path, generic_cal_info.component_name.lower() + "_update_calibration",
        update_calibration_methods, calibrations_dict_of_dicts)
    
    

    logging.info("Execution of Cal Tool succeeded.")
