# Global options:

[mypy]

# General options:
python_version = 3.6
files = *.py,src/*.py
mypy_path = src


[mypy-*]

# Static checks:
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_any_unimported = True
no_implicit_optional = True
strict_optional = True
check_untyped_defs = True
warn_return_any = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unused_ignores = True
ignore_missing_imports = True
