/*================================================================================*\
 * Copyright 2022 Aptiv Advanced Safety and User Experience. All rights reserved. *
 * Confidential - Restricted Aptiv information. Do not disclose.                  *
\*================================================================================*/
#ifndef VEHICLE_DATA_FLT_T_H
#define VEHICLE_DATA_FLT_T_H

#include "reuse.h"
#include "tracker_constants_selector.h"
#include "PRNDL_state_T.h"
#include "Vector_2d.h"
#include "Basic_Math_Structs.h"
#include "OTHER_SENSORS_OBJECT_FLT_T.h"
#include "ROLLING_COUNT_T.h"
#include "host_wheel_direction_t.h"

/**
 * This structure holds all of the vehicle related data such as speed, yawrate, and curvature.
 * \ingroup host_vehicle

 */
typedef struct
{
   /** @name Inputs
    * This section contains all Tracker Inputs that have to be filled outside before the Tracker is being called.
    */
   /**@{*/

   float32_T abs_speed; /**< [m/s] absolute speed of host vehicle (always corrected in vehicleProcessing)*/

   float32_T yawrate; /**< [rad/s] yaw-rate of host vehicle, a turn to the right is positive*/

   float32_T steering_angle; /**< [rad] steering angle of front axle*/

   float32_T rear_axle_steering_angle; /**< [rad] steering angle of rear axle*/

   float32_T rear_axle_position; /**< [m] longitudinal  coordinate (in VCS) of rear axle. In general this is the negative distance
                                  * from front bumper (Aptiv coordinate system origin) to rear axle.*/

   float32_T wheelbase; /**< [m] distance from rear to front_axle (distance between axles)*/

   float32_T lane_width_external; /**< [m] Lane width received from vehicle*/

   float32_T lane_center_offset_external; /**< [m] Egos lane center offset received from vehicle*/

   float32_T host_vehicle_length; /**< [m] egos length*/

   float32_T host_vehicle_width; /**< [m] egos width*/

   float32_T curve_radius; /**< [m] radius of curvature calculated from Core 0 */

   /* If vcs_long_acc is not received from host, it's kept on its initialization value 0.0m/(s*s).
      If vcs_lat_acc is not received from host, it's kept on its initialization value 0.0m/(s*s).
    */
   float32_T vcs_long_acc; /**< [m/s^2] longitudinal acceleration of the vehicle at origin of VCS */
   float32_T vcs_lat_acc;  /**< [m/s^2] lateral acceleration of the vehicle at origin of VCS */

   uint32_t vehicle_data_timestamp; /**< [ms] timestamp at which vehicle data was captured */
   uint32_t max_value_mastertime;   /**< is the maximum value of the timestamp before it starts with zero. The value is needed to
                                     * compute   the correct difference between two timestamps if one restarted with zero and the
                                     * other   not yet*/

   Host_Wheel_Direction_T host_wheel_direction; /**< The direction in which the host wheels turn*/

   PRNDL_state_T prndl; /**< position of gear select*/

   uint8_t turn_signal; /**< turn signal*/

   uint8_t f_reverse_gear : 1; /**< flag indicating manual vehicle is in reverse gear*/

   uint8_t f_trailer_present : 1; /**< flag indicating that a trailer is present*/

   uint8_t f_traffic_side : 1; /**< flag indicating traffic side, 0 - Right hand traffic , 1 - Left hand traffic*/

   uint8_t f_mastertime_consistent : 1; /**< flag indicating if the mastertime value is consistent*/

   OTHER_SENSOR_RECEIVED_DATA_FLT_T other_sensors_received_data[NUMBER_OF_RSDS_SENSORS_IN_CAR]; /**< This entry is deprecated and
                                                                                                   no longer required as input to
                                                                                                   the tracker */
   /**@}*/

   /** @name Outputs
    * This section contains all Tracker Outputs that are being generated by the Tracker and may be used by other functions as well.
    */
   /**@{*/
   Vector_2d_T vcs_time_update; /**< [m] Vector describing the spatial movement of the VCS origin during 1 cycle \ingroup
                                   ac_host_movement_compensation*/
   float32_T speed;             /**< [m/s] compensated speed of host vehicle */
   float32_T speed_raw;         /**< [m/s] signed speed of host vehicle */
   float32_T speed_estimated;   /**< [m/s] estimated speed of host vehicle (instantly from stationary detections) */

   /*
      As currently acceleration is the absolute value derived by vcs_long_acc and vcs_lat_acc, this value
      is also zero 0.0m/(s*s), if the components are not set.
   */
   float32_T acceleration; /**< [m/s^2] signed acceleration of host vehicle */

   /* the velocity components are calculated from abs_speed and yaw_rate */
   float32_T vcs_long_vel; /**< [m/s] longitudinal velocity of the vehicle at the origin of VCS*/
   float32_T vcs_lat_vel;  /**< [m/s] lateral velocity of the vehicle at the origin of VCS*/

   float32_T rear_axle_sideslip; /**< [rad] sideslip angle at the rear axle */
   float32_T vcs_sideslip;       /**< [rad] sideslip angle at the origin of VCS */
   float32_T cos_vcs_sideslip;   /**< cosine of vcs_sideslip */
   float32_T sin_vcs_sideslip;   /**< sine of vcs_sideslip */

   float32_T host_curvature_fast; /**< [1/m] curvature of the host path, fast filtering. A right turn leads to positive curvature
                                     values, a left turn leads to a negative curvature. \ingroup Host_Curvature */
   float32_T host_curvature_slow; /**< [1/m] curvature of the host path, slow filtering. A right turn leads to positive curvature
                                     values, a left turn leads to a negative curvature. \ingroup Host_Curvature */

   uint8_t f_host_curvature_calculated : 1; /**< flag indicating that host_curvature_fast and host_curvature_slow have been
                                               calculated in the current cycle \ingroup Host_Curvature*/
   uint8_t f_speed_corrected : 1;           /**< flag indicating if host speed has been corrected */
   uint8_t f_speed_estimated : 1;           /**< flag indicating if host speed has been estimated */
   /**@}*/

   /** @name Internals
    * This section contains all Tracker Internals that may be subject to changes at any time and shall not be used by any other
    * function!
    */
   /**@{*/
   Angle_T yaw_per_cycle; /**< [rad] yaw difference to yaw of host vehicle in last call, a turn to the right is positive \ingroup
                             ac_host_movement_compensation */

   ROLLING_COUNT_T rolling_count_vehicle_data; /**< rolling count for vehicleProcessing. Will be increased by one each time
                                                * vehicleProcessing is called. Used for debugging. */

   uint8_t f_reverse : 1;              /**< flag indicating vehicle is in reverse */
   uint8_t f_abs_curvature_LT_cal : 1; /**< Flag indicating that host_curvature_slow is smaller than
                                          k_ad_clothoid_curvature_threshold */
   /**@}*/
} VEHICLE_DATA_FLT_T;

#endif
