#ifndef TRACKER_OUTPUT_INTERFACE_VERSION_DATE_H
#define TRACKER_OUTPUT_INTERFACE_VERSION_DATE_H

/*================================================================================*\
 * Copyright 2022 Aptiv Advanced Safety and User Experience. All rights reserved. *
 * Confidential - Restricted Aptiv information. Do not disclose.                  *
\*================================================================================*/

#include "VERSION_NUMBER_T.h"
#include "Shared_Toolbox_Version_Check.h"
#include "TRACKER_OUTPUT_INTERFACE_VERSION_CONTENT.h"

#define TRACKER_OUTPUT_INTERFACE_VERSION_YEAR (21)
#define TRACKER_OUTPUT_INTERFACE_VERSION_MONTH (7)
#define TRACKER_OUTPUT_INTERFACE_VERSION_DAY (29)
#define TRACKER_OUTPUT_INTERFACE_VERSION_ITERATION (0)

/* PRQA S 3453 ++*/ /* macro is used to steer macros => impossible to use a function */
#define TRACKER_OUTPUT_INTERFACE_VERSION_INTEGER SHARED_TOOLBOX_COMPUTE_VERSION_INTEGER_FROM_NAME(TRACKER_OUTPUT_INTERFACE)

#define TRACKER_OUTPUT_INTERFACE_VERSION_INSUFFICIENT(REQUIRED_VERSION_YEAR, REQUIRED_VERSION_MONTH, REQUIRED_VERSION_DAY, REQUIRED_VERSION_ITERATION) (SHARED_TOOLBOX_VERSION_INSUFFICIENT_CHECK((TRACKER_OUTPUT_INTERFACE_VERSION_INTEGER), REQUIRED_VERSION_YEAR, REQUIRED_VERSION_MONTH, REQUIRED_VERSION_DAY, REQUIRED_VERSION_ITERATION))
#define TRACKER_OUTPUT_INTERFACE_VERSION_EQUALS(REQUIRED_VERSION_YEAR, REQUIRED_VERSION_MONTH, REQUIRED_VERSION_DAY, REQUIRED_VERSION_ITERATION) (SHARED_TOOLBOX_VERSION_EQUALS_CHECK((TRACKER_OUTPUT_INTERFACE_VERSION_INTEGER), REQUIRED_VERSION_YEAR, REQUIRED_VERSION_MONTH, REQUIRED_VERSION_DAY, REQUIRED_VERSION_ITERATION))

/* PRQA S 3453 --*/ /* macro is used to steer macros => impossible to use a function */

extern VERSION_NUMBER_T Get_Tracker_Output_Interface_Version(void);
#endif
