include(cmake/CreateUTConfiguration.cmake)
create_ut_configuration()

add_subdirectory(calibrations)
add_subdirectory(common)
add_subdirectory(container_view)
add_subdirectory(embedded_list)
add_subdirectory(fifo)
add_subdirectory(memory_pool)
add_subdirectory(shared_files)
add_subdirectory(sg_calculate_detection_importance)
add_subdirectory(sg_combine_detections)
add_subdirectory(sg_contour_downselection)
add_subdirectory(sg_contour_initialization)
add_subdirectory(sg_core)
add_subdirectory(sg_critical_region)
add_subdirectory(sg_detection_clustering)
add_subdirectory(sg_determine_drivability_class)
add_subdirectory(sg_downselect_input_detections)
add_subdirectory(sg_host)
add_subdirectory(sg_iface)
add_subdirectory(sg_math)
add_subdirectory(sg_measurement_association)
add_subdirectory(sg_measurement_update)
add_subdirectory(sg_postprocessing)
add_subdirectory(sg_stationary_geometries)
add_subdirectory(sg_stationary_geometries_impl)
add_subdirectory(sg_stationary_geometries_with_timer)
add_subdirectory(sg_time_update)
add_subdirectory(unique_id_handler)
add_subdirectory(variant_specific)

# conditional adding RSPP unit tests, should be fixed
if(${RSPP_VARIANT} STREQUAL "A")
    message("Configuring unit tests for RSPP: " ${RSPP_VARIANT})
    add_subdirectory(sg_rspp)
else()
    message("Not configuring unit tests for RSPP, not supported variant: " ${RSPP_VARIANT})
endif()

if(SG_DC_ENABLED)
    add_subdirectory(dc_drivability_classification)
    add_subdirectory(dc_dummy_generator)
    if (SG_DRIVABILITY_CLASSIFICATION_TOOLING_WRAPPER)
       add_subdirectory(dc_drivability_classification_wrapper)
    endif()
endif()