target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_FILE})

target_include_directories(LCDA PUBLIC ${CMAKE_CURRENT_LIST_DIR})

target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_debug_interface.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_debug_writer.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_create_bsw_zone.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_create_cvw_zone.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_common_functions.h)
target_sources(LCDA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/lcda_core_input_t.h)
target_sources(LCDA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/lcda_core_output_t.h)
target_sources(LCDA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/lcda_iface.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_bsw.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_cvw.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_elc.h)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_slc.h)
target_sources(LCDA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/lcda_types.h)
target_sources(LCDA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/lcda_persistent_t.h)
target_sources(LCDA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/lcda_instance.h)

target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_debug_interface.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_debug_writer.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_create_bsw_zone.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_create_cvw_zone.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_common_functions.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_iface.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_bsw.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_cvw.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_elc.c)
target_sources(LCDA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/lcda_process_slc.c)
