include(cmake/CreateUTConfiguration.cmake)
create_ut_configuration()

add_subdirectory(calibrations)
add_subdirectory(common)
add_subdirectory(container_view)
add_subdirectory(dc_drivability_classification)
add_subdirectory(embedded_list)
add_subdirectory(fifo)
add_subdirectory(memory_pool)
add_subdirectory(sg_calculate_detection_importance)
add_subdirectory(sg_combine_detections)
add_subdirectory(sg_core)
add_subdirectory(sg_detection_clustering)
add_subdirectory(sg_determine_drivability_class)
add_subdirectory(sg_downselect_input_detections)
add_subdirectory(sg_host)
add_subdirectory(sg_iface)
add_subdirectory(sg_math)
add_subdirectory(sg_measurement_association)
add_subdirectory(sg_measurement_update)
add_subdirectory(sg_contour_downselection)
add_subdirectory(sg_contour_initialization)
add_subdirectory(sg_postprocessing)
add_subdirectory(sg_time_update)
add_subdirectory(unique_id_handler)
