target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_FILE})

target_include_directories(RECW PUBLIC ${CMAKE_CURRENT_LIST_DIR})

target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw.h)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_car_wash_detection.h)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_crash_prob_steer_brake.h)
target_sources(RECW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/recw_core_input_t.h)
target_sources(RECW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/recw_core_output_t.h)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_debug_writer.h)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_debug_interface.h)
target_sources(RECW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/recw_iface.h)
target_sources(RECW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/recw_instance.h)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_object_validator.h)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_output_debouncer.h)
target_sources(RECW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/recw_persistent_t.h)
target_sources(RECW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/recw_types.h)

target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw.c)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_car_wash_detection.c)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_crash_prob_steer_brake.c)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_debug_writer.c)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_debug_interface.c)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_iface.c)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_object_validator.c)
target_sources(RECW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/recw_output_debouncer.c)
