target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_FILE})

target_include_directories(TA PUBLIC ${CMAKE_CURRENT_LIST_DIR})

target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_collision_filter.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_constants.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_common_functions.h)
target_sources(TA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ta_core_input_t.h)
target_sources(TA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ta_core_output_t.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_debug_interface.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_debug_writer.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_factory.h)
target_sources(TA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ta_iface.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_intersection_analyzer.h)
target_sources(TA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ta_instance_t.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_object_filter.h)
target_sources(TA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ta_persistent_t.h)
target_sources(TA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ta_types.h)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_warn_logic.h)

target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_collision_filter.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_constants.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_common_functions.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_debug_interface.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_debug_writer.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_factory.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_iface.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_intersection_analyzer.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_object_filter.c)
target_sources(TA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ta_warn_logic.c)
