#Build Steps
#mkdir Build

#Debug Mode:
#Complier MSVC
#	Step1 cmake -G "Visual Studio 11 Win64" ..
#	Step2 cmake --build . --target ALL_BUILD --config Debug

#Compiler GNU CXX
#	Step1 cmake ..
#	Step2 make

##########################
### Project definition ###
##########################

cmake_minimum_required(VERSION 4.0)
cmake_policy(SET CMP0002 NEW)
cmake_policy(SET CMP0003 NEW)
cmake_policy(SET CMP0010 NEW)
cmake_policy(SET CMP0011 NEW)

set(CMAKE_CXX_STANDARD 11)
set(buildtype ${CMAKE_BUILD_TYPE})
string(TOUPPER "${buildtype}" buildtypeToUpper)
message("Build Type is : ${buildtypeToUpper}")

if(NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Build type can be Debug or Release")
	set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS ${CMAKE_CONFIGURATION_TYPES})
endif()

# Setting Source projects
set(SOURCE_PROJECT "${CMAKE_CURRENT_LIST_DIR}/..")

# set path for Common includes
set(COMMON_INC "${SOURCE_PROJECT}/Common_Headers")
set(COMMON_STRUCTURES "${SOURCE_PROJECT}/Common_Structures")

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU") 
	set(CMAKE_CXX_FLAGS "-fPIC")
	set(CFLAGS"-fPIC")
else()
	if(WIN32)
		add_compile_options(/bigobj)
	endif()
endif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")

#output path
set(OUTPUT_PATH "${CMAKE_CURRENT_LIST_DIR}/../output/")

# Set Project Names
set(BORDNET_DECODER_PROJ "${SOURCE_PROJECT}/BordNetDecoder")
set(AUTO_GEN_FILES_PROJ "${SOURCE_PROJECT}/Auto_Gen_Files")
#set(RR_AUTO_GEN_FILES_PROJ "${SOURCE_PROJECT}/Auto_Gen_Files_RR")
set(PCAN_LOWRR_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_LOWRR_Decoder")
set(PCAN_LOWRL_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_LOWRL_Decoder")
set(PCAN_LOWFL_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_LOWFL_Decoder")
set(PCAN_LOWFR_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_LOWFR_Decoder")
set(PCAN_MIDFL_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_MIDFL_Decoder")
set(PCAN_MIDFR_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_MIDFR_Decoder")
set(PCAN_MIDRL_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_MIDRL_Decoder")
set(PCAN_MIDRR_DECODER_PROJ "${SOURCE_PROJECT}/PCAN_MIDRR_Decoder")
set(CROSS_PLATFORM_PROJ "${SOURCE_PROJECT}/Cross_Platform")
set(UTILITY_PROJ "${SOURCE_PROJECT}/Utility")
set(MDF_LOG_PROJ "${SOURCE_PROJECT}/mdf_log")
set(VCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/VCAN_Extractor")
set(PCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/PCAN_Extractor")
set(VCAN_MAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/VCAN_MAN_Extractor")
set(NISSAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/NISSAN_Extractor")
set(HONDA_PCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/HONDA_PCAN_Extractor")
set(STLA_SRR6P_VCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/STLA_SRR6P_VCAN_Extractor")
set(STLA_FLR4_ETH_EXTRACTOR_PROJ "${SOURCE_PROJECT}/STLA_FLR4_ETH_Extractor")
set(STLA_FLR4P_SOMEIP_EXTRACTOR_PROJ "${SOURCE_PROJECT}/STLA_FLR4P_SOMEIP_Extractor")
set(STLA_FLR4P_ADCAM_EXTRACTOR_PROJ "${SOURCE_PROJECT}/STLA_FLR4P_ADCAM_Extractor")

#Traton PROJECT
set(TRATON_SRR6P_VCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/TRATON_SRR6P_VCAN_Extractor")
#TRATON 
set(TRATON_SRR6P_VCAN_FC_DECODER_PROJ "${SOURCE_PROJECT}/TRATON_SRR6P_VCAN_FC_Decoder")
set(TRATON_SRR6P_VCAN_RR_DECODER_PROJ "${SOURCE_PROJECT}/TRATON_SRR6P_VCAN_RR_Decoder")
set(TRATON_SRR6P_VCAN_RL_DECODER_PROJ "${SOURCE_PROJECT}/TRATON_SRR6P_VCAN_RL_Decoder")
#set(TRATON_SRR6P_VCAN_FC_DECODER_PROJ "${SOURCE_PROJECT}/TRATON_SRR6P_VCAN_FC_Decoder")

set(VCAN_BPIL_LEFT_DECODER_PROJ "${SOURCE_PROJECT}/VcanBpilLeftDecoder")
set(VCAN_BPIL_RIGHT_DECODER_PROJ "${SOURCE_PROJECT}/VcanBpilRightDecoder")

set(VCAN_ECU_DECODER_PROJ "${SOURCE_PROJECT}/VCANECU_Decoder")
set(VCAN_LOW_DECODER_PROJ "${SOURCE_PROJECT}/VCANLow_Decoder")
set(VCAN_MAN_DECODER_PROJ "${SOURCE_PROJECT}/VCANMAN_FC_Decoder")
set(VCAN_MAN_LEFT_DECODER_PROJ "${SOURCE_PROJECT}/VCANMAN_LEFT_Decoder")
set(VCAN_MAN_RIGHT_DECODER_PROJ "${SOURCE_PROJECT}/VCANMAN_RIGHT_Decoder")

set(NISSAN_FL_DECODER_PROJ "${SOURCE_PROJECT}/NISSAN_FL_Decoder")
set(NISSAN_FR_DECODER_PROJ "${SOURCE_PROJECT}/NISSAN_FR_Decoder")
set(NISSAN_RL_DECODER_PROJ "${SOURCE_PROJECT}/NISSAN_RL_Decoder")
set(NISSAN_RR_DECODER_PROJ "${SOURCE_PROJECT}/NISSAN_RR_Decoder")

set(HONDA_PCAN_RL_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_PCAN_RL_Decoder")
set(HONDA_PCAN_RR_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_PCAN_RR_Decoder")
set(HONDA_PCAN_FR_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_PCAN_FR_Decoder")
set(HONDA_PCAN_FL_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_PCAN_FL_Decoder")

set(HONDA_VCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/HONDA_VCAN_Extractor")
set(HONDA_VCAN_RL_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_VCAN_RL_Decoder")
set(HONDA_VCAN_RR_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_VCAN_RR_Decoder")
set(HONDA_VCAN_FL_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_VCAN_FL_Decoder")
set(HONDA_VCAN_FR_DECODER_PROJ "${SOURCE_PROJECT}/HONDA_VCAN_FR_Decoder")

set(RNA_VCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/RNA_VCAN_Extractor")
set(RNA_VCAN_FL_DECODER_PROJ "${SOURCE_PROJECT}/RNA_VCAN_FL_Decoder")
set(RNA_VCAN_FR_DECODER_PROJ "${SOURCE_PROJECT}/RNA_VCAN_FR_Decoder")
set(RNA_VCAN_RL_DECODER_PROJ "${SOURCE_PROJECT}/RNA_VCAN_RL_Decoder")
set(RNA_VCAN_RR_DECODER_PROJ "${SOURCE_PROJECT}/RNA_VCAN_RR_Decoder")
set(RNA_RT_RANGE_DECODER_PROJ "${SOURCE_PROJECT}/RNA_RT_RANGE_Decoder")

set(CEER_PCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/CEER_PCAN_Extractor")
set(CEER_PCAN_RL_DECODER_PROJ "${SOURCE_PROJECT}/CEER_PCAN_RL_Decoder")
set(CEER_PCAN_RR_DECODER_PROJ "${SOURCE_PROJECT}/CEER_PCAN_RR_Decoder")
set(CEER_PCAN_FR_DECODER_PROJ "${SOURCE_PROJECT}/CEER_PCAN_FR_Decoder")
set(CEER_PCAN_FL_DECODER_PROJ "${SOURCE_PROJECT}/CEER_PCAN_FL_Decoder")

#set(AUTO_GEN_FILES_PROJ "${SOURCE_PROJECT}/Auto_Gen_Files")
set(STLA_SRR6P_VCAN_RL_DECODER_PROJ "${SOURCE_PROJECT}/STLA_SRR6P_VCAN_RL_Decoder")
set(STLA_SRR6P_VCAN_RR_DECODER_PROJ "${SOURCE_PROJECT}/STLA_SRR6P_VCAN_RR_Decoder")
set(STLA_SRR6P_VCAN_FR_DECODER_PROJ "${SOURCE_PROJECT}/STLA_SRR6P_VCAN_FR_Decoder")
set(STLA_SRR6P_VCAN_FL_DECODER_PROJ "${SOURCE_PROJECT}/STLA_SRR6P_VCAN_FL_Decoder")

set(STLA_FLR4_ETH_DECODER_PROJ "${SOURCE_PROJECT}/STLA_FLR4_ETH_Decoder")

set(STLA_FLR4P_SOMEIP_DECODER_PROJ "${SOURCE_PROJECT}/STLA_FLR4P_SOMEIP_Decoder")
set(STLA_FLR4P_ADCAM_DECODER_PROJ "${SOURCE_PROJECT}/STLA_FLR4P_ADCAM_Decoder")

set(COMMON_STRUCTURES_PROJ "${SOURCE_PROJECT}/Common_Structures")
set(SCAN_EXTRACTOR_PROJ "${SOURCE_PROJECT}/SCAN_Extractor")
set(SCAN_DECODER_PROJ "${SOURCE_PROJECT}/SCAN_Decoder")
set(SOME_IP_EXTRACTOR_PROJ "${SOURCE_PROJECT}/SOME_IP_Extractor")
set(SOMIP_DECODER_PROJ "${SOURCE_PROJECT}/SOMIP_Decoder")
set(ORCASToolVerification_PROJECT "${SOURCE_PROJECT}/ORCASToolVerification")

#BMW_SP25 SOMEIP
set(BMWL2_SOMEIP_DECODER_WRAPPER_PROJ "${SOURCE_PROJECT}/BMWL2_SOMEIP_Decoder_Wrapper")
set(BMWL2_SRR7P_SOMEIP_DECODER_PROJ "${SOURCE_PROJECT}/BMWL2_SRR7P_SOMEIP_Decoder")
set(BMWL2_FLR7_SOMEIP_DECODER_PROJ "${SOURCE_PROJECT}/BMWL2_FLR7_SOMEIP_Decoder")
set(BMWL2_IPFFAR_SOMEIP_Decoder_PROJ "${SOURCE_PROJECT}/BMWL2_IPFFAR_SOMEIP_Decoder")
#BMW_SP25 DLT
set(BMWL2_DLT_EXTRACTOR_PROJ "${SOURCE_PROJECT}/BMWL2_DLT_Extractor")
set(BMWL2_DLT_IPNEXT_DECODER_PROJ "${SOURCE_PROJECT}/BMWL2_IPNEXT_DLT_Decoder")


 

add_subdirectory("${AUTO_GEN_FILES_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/Auto_Gen_Files")
#add_subdirectory("${RR_AUTO_GEN_FILES_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/Auto_Gen_Files_RR")
#TRATON
add_subdirectory("${TRATON_SRR6P_VCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/TRATON_SRR6P_VCAN_Extractor")
add_subdirectory("${TRATON_SRR6P_VCAN_FC_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/TRATON_SRR6P_VCAN_FC_Decoder")
add_subdirectory("${TRATON_SRR6P_VCAN_RR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/TRATON_SRR6P_VCAN_RR_Decoder")
add_subdirectory("${TRATON_SRR6P_VCAN_RL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/TRATON_SRR6P_VCAN_RL_Decoder")

add_subdirectory("${CROSS_PLATFORM_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/Cross_Platform")
add_subdirectory("${UTILITY_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/Utility")
add_subdirectory("${MDF_LOG_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/mdf_log")
add_subdirectory("${PCAN_LOWRR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_LOWRR_Decoder")
add_subdirectory("${PCAN_LOWRL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_LOWRL_Decoder")
add_subdirectory("${PCAN_LOWFL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_LOWFL_Decoder")
add_subdirectory("${PCAN_LOWFR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_LOWFR_Decoder")
add_subdirectory("${PCAN_MIDFL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_MIDFL_Decoder")
add_subdirectory("${PCAN_MIDFR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_MIDFR_Decoder")
add_subdirectory("${PCAN_MIDRL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_MIDRL_Decoder")
add_subdirectory("${PCAN_MIDRR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_MIDRR_Decoder")

add_subdirectory("${PCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/PCAN_Extractor")
add_subdirectory("${VCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VCAN_Extractor")
add_subdirectory("${VCAN_BPIL_LEFT_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VcanBpilLeftDecoder")
add_subdirectory("${VCAN_BPIL_RIGHT_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VcanBpilRightDecoder")

add_subdirectory("${VCAN_ECU_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VCANECU_Decoder")
add_subdirectory("${VCAN_LOW_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VCANLow_Decoder")

add_subdirectory("${VCAN_MAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VCAN_MAN_Extractor")
add_subdirectory("${VCAN_MAN_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VCANMAN_FC_Decoder")
add_subdirectory("${VCAN_MAN_LEFT_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VCANMAN_LEFT_Decoder")
add_subdirectory("${VCAN_MAN_RIGHT_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/VCANMAN_RIGHT_Decoder")

add_subdirectory("${NISSAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/NISSAN_Extractor")
add_subdirectory("${NISSAN_FL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/NISSAN_FL_Decoder")
add_subdirectory("${NISSAN_FR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/NISSAN_FR_Decoder")
add_subdirectory("${NISSAN_RL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/NISSAN_RL_Decoder")
add_subdirectory("${NISSAN_RR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/NISSAN_RR_Decoder")

add_subdirectory("${HONDA_PCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_PCAN_Extractor")
add_subdirectory("${HONDA_PCAN_RL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_PCAN_RL_Decoder")
add_subdirectory("${HONDA_PCAN_RR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_PCAN_RR_Decoder")
add_subdirectory("${HONDA_PCAN_FR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_PCAN_FR_Decoder")
add_subdirectory("${HONDA_PCAN_FL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_PCAN_FL_Decoder")


add_subdirectory("${HONDA_VCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_VCAN_Extractor")
add_subdirectory("${HONDA_VCAN_RL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_VCAN_RL_Decoder")
add_subdirectory("${HONDA_VCAN_RR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_VCAN_RR_Decoder")
add_subdirectory("${HONDA_VCAN_FL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_VCAN_FL_Decoder")
add_subdirectory("${HONDA_VCAN_FR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/HONDA_VCAN_FR_Decoder")

add_subdirectory("${RNA_VCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/RNA_VCAN_Extractor")
add_subdirectory("${RNA_VCAN_FL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/RNA_VCAN_FL_Decoder")
add_subdirectory("${RNA_VCAN_FR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/RNA_VCAN_FR_Decoder")
add_subdirectory("${RNA_VCAN_RL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/RNA_VCAN_RL_Decoder")
add_subdirectory("${RNA_VCAN_RR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/RNA_VCAN_RR_Decoder")
add_subdirectory("${RNA_RT_RANGE_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/RNA_RT_RANGE_Decoder")

add_subdirectory("${CEER_PCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/CEER_PCAN_Extractor")
add_subdirectory("${CEER_PCAN_FL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/CEER_PCAN_FL_Decoder")
add_subdirectory("${CEER_PCAN_FR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/CEER_PCAN_FR_Decoder")
add_subdirectory("${CEER_PCAN_RL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/CEER_PCAN_RL_Decoder")
add_subdirectory("${CEER_PCAN_RR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/CEER_PCAN_RR_Decoder")

add_subdirectory("${STLA_SRR6P_VCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_SRR6P_VCAN_Extractor")
add_subdirectory("${STLA_SRR6P_VCAN_FL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_SRR6P_VCAN_FL_Decoder")
add_subdirectory("${STLA_SRR6P_VCAN_FR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_SRR6P_VCAN_FR_Decoder")
add_subdirectory("${STLA_SRR6P_VCAN_RL_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_SRR6P_VCAN_RL_Decoder")
add_subdirectory("${STLA_SRR6P_VCAN_RR_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_SRR6P_VCAN_RR_Decoder")

add_subdirectory("${STLA_FLR4_ETH_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_FLR4_ETH_Extractor")
add_subdirectory("${STLA_FLR4_ETH_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_FLR4_ETH_Decoder")

add_subdirectory("${STLA_FLR4P_SOMEIP_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_FLR4P_SOMEIP_Extractor")
add_subdirectory("${STLA_FLR4P_SOMEIP_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_FLR4P_SOMEIP_Decoder")
add_subdirectory("${STLA_FLR4P_ADCAM_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_FLR4P_ADCAM_Extractor")
add_subdirectory("${STLA_FLR4P_ADCAM_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/STLA_FLR4P_ADCAM_Decoder")

#BMW_SP25 SOMEIP
add_subdirectory("${BMWL2_SOMEIP_DECODER_WRAPPER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/BMWL2_SOMEIP_Decoder_Wrapper")
add_subdirectory("${BMWL2_SRR7P_SOMEIP_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/BMWL2_SRR7P_SOMEIP_Decoder")
add_subdirectory("${BMWL2_FLR7_SOMEIP_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/BMWL2_FLR7_SOMEIP_Decoder")
add_subdirectory("${BMWL2_IPFFAR_SOMEIP_Decoder_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/BMWL2_IPFFAR_SOMEIP_Decoder")
#BMW_SP25 DLT
add_subdirectory("${BMWL2_DLT_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/BMWL2_DLT_Extractor")
add_subdirectory("${BMWL2_DLT_IPNEXT_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/BMWL2_IPNEXT_DLT_Decoder")

add_subdirectory("${COMMON_STRUCTURES_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/Common_Structures")

add_subdirectory("${SCAN_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/SCAN_Extractor")
add_subdirectory("${SCAN_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/SCAN_Decoder")

add_subdirectory("${SOME_IP_EXTRACTOR_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/SOME_IP_Extractor")
add_subdirectory("${SOMIP_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/SOMIP_Decoder")

add_subdirectory("${BORDNET_DECODER_PROJ}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/BordNetDecoder")
add_subdirectory("${ORCASToolVerification_PROJECT}/CMake" "${CMAKE_CURRENT_BINARY_DIR}/ORCASToolVerification")

set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT "BordNetDecoder" ) 
project (BordNetDecoder)

add_definitions(-D_CRT_SECURE_NO_WARNINGS)
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU") 
	add_definitions(${CMAKE_CXX_FLAGS} "-rdynamic")
	add_definitions(${CMAKE_CFLAGS} "-rdynamic")
endif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
