##########################
### Project definition ###
##########################
cmake_minimum_required(VERSION 4.0)

set(PROJECTNAME  "STLA_FLR4P_SOMEIP_Decoder")
project(${PROJECTNAME})


set(STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}/..")

set(SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMEIP_Decoder.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SomeIpDecoderBase.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SomeIpDecoderBase_V70001.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SomeIpDecoderBase_V10201.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/ISTLA_FLR4P_SomeIp_Decoder.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/ISTLA_FLR4P_SomeIp_Decoder_V70001.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/ISTLA_FLR4P_SomeIp_Decoder_V10201.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/ISTLA_FLR4P_SomeIp_DecoderAPI.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMIPCommonHeader.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMIPCommonHeader_V70001.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMIPCommonHeader_V10201.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/Resource.rc")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/Version.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/ReleaseNotes_STLA_FLR4P_SOMEIP.txt")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMEIP_Decoder.cpp")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMEIP_Decoder_V70001.cpp")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMEIP_Decoder_V10201.cpp")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SomeIp_DecoderAPI.cpp")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMEIP_Decoder_V70001.h")
list(APPEND SOURCE_ALL "${STLA_FLR4P_SOMEIP_DECODER_ROOT_PATH}/STLA_FLR4P_SOMEIP_Decoder_V10201.h")



set(target_name ${PROJECTNAME})
add_library(${target_name} SHARED "")


target_include_directories(${target_name} PRIVATE ${COMMON_STRUCTURES})

target_sources(${target_name} PRIVATE ${SOURCE_ALL})

if(OUTPUT_PATH)
set_target_properties(${target_name} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												ARCHIVE_OUTPUT_DIRECTORY "${OUTPUT_PATH}")												 				
endif(OUTPUT_PATH)

if(MSVC)
	target_compile_definitions(${target_name} PRIVATE  _WIN_PLATFORM) 
endif(MSVC)
