"""Provides a Bazel interface to run the Xtensa simulator and profiler"""

load(":constants.bzl", "XTENSA_CORE")

def _run_windows_profiler(ctx, env, bbe_profiler, profiler_output_file, test_elf, profiler_input_file):
    """
    Run the profiler on windows.

    Args:
        ctx: Context passed in from rule.
        env: Environment variables to set in the shell.
        bbe_profiler: Execution path for the BBE profiler (xt-gprof.ext)
        profiler_output_file: Output file with profiler information
        test_elf: The ELF file that is being profiled
        profiler_input_file: Input file generated by xt-run.exe

    Notes:
        The profiler output must be piped to the output file destination,
        which is not supported by Bazel. So, two separate methods are provided
        to facilitate the required run_shell call for Windows and Linux.
    """
    bat = ctx.actions.declare_file(profiler_input_file.basename + "-cmd.bat")

    # Most Windows binaries built with MSVC use a certain argument quoting
    # scheme. Bazel uses that scheme too to quote arguments. However,
    # cmd.exe uses different semantics, so Bazel's quoting is wrong here.
    # To fix that we write the command to a .bat file so no command line
    # quoting or escaping is required.

    ctx.actions.write(
        output = bat,
        # Do not use lib/shell.bzl's shell.quote() method, because that uses
        # Bash quoting syntax, which is different from cmd.exe's syntax.
        content = bbe_profiler.to_list()[0].path.replace("/", "\\") + " \"%s\" \"%s\" > \"%s\"" % (
            test_elf.path.replace("/", "\\"),
            profiler_input_file.path.replace("/", "\\"),
            profiler_output_file.path.replace("/", "\\"),
        ),
        is_executable = True,
    )
    ctx.actions.run(
        inputs = [test_elf, profiler_input_file],
        tools = [bat, bbe_profiler],
        outputs = [profiler_output_file],
        executable = "cmd.exe",
        arguments = ["/C", bat.path.replace("/", "\\")],
        mnemonic = "RunProfiler",
        progress_message = "Running profiler",
        env = env,
    )

def _run_linux_profiler(ctx, env, bbe_profiler, profiler_output_file, test_elf, profiler_input_file):
    """
    Run the profiler on linux.

    Args:
        ctx: Context passed in from rule.
        env: Environment variables to set in the shell.
        bbe_profiler: Execution path for the BBE profiler (xt-gprof.ext)
        profiler_output_file: Output file with profiler information
        test_elf: The ELF file that is being profiled
        profiler_input_file: Input file generated by xt-run.exe

    Notes:
        The profiler output must be piped to the output file destination,
        which is not supported by Bazel. So, two separate methods are provided
        to facilitate the required run_shell call for Windows and Linux.
    """
    ctx.actions.run_shell(
        tools = [bbe_profiler, test_elf, profiler_input_file],
        outputs = [profiler_output_file],
        command = bbe_profiler.to_list()[0].path + " \"$1\" \"$2\" > \"$3\"",
        arguments = [test_elf.path, profiler_input_file.path, profiler_output_file.path],
        env = env,
        progress_message = "Running the profiler for {}".format(bbe_profiler),
    )

def _run_windows_simulator(ctx, env, bbe_simulator, test_elf, file_prefix, simulator_output_files):
    """
    Run the profiler on windows.

    Args:
        ctx: Context passed in from rule.
        env: Environment variables to set in the shell.
        bbe_simulator: Execution path for the BBE profiler (xt-gprof.ext)
        test_elf: The ELF file that is being profiled
        file_prefix: Directory name and file prefix for the output files.
        simulator_output_files: Output files generated by xt-run.exe

    Notes:
        Using the run_shell option here to facilitate support for the "profile" option
        of the client_commands command line option for the xt-run tool.

        --profile=<filename> - This only outputs the .cyc profile information.
    """
    bat = ctx.actions.declare_file(ctx.attr.name + "-sim-cmd.bat")

    # The --mem_model option enables the summary output. Disable it here if setting is false.
    if ctx.attr.show_summary:
        summary = ""
    else:
        summary = "--nosummary"

    # Most Windows binaries built with MSVC use a certain argument quoting
    # scheme. Bazel uses that scheme too to quote arguments. However,
    # cmd.exe uses different semantics, so Bazel's quoting is wrong here.
    # To fix that we write the command to a .bat file so no command line
    # quoting or escaping is required.

    ctx.actions.write(
        output = bat,
        # Do not use lib/shell.bzl's shell.quote() method, because that uses
        # Bash quoting syntax, which is different from cmd.exe's syntax.
        content = bbe_simulator.to_list()[0].path.replace("/", "\\") + " --console --mem_model --client_cmds=\"%s\" %s %s" % (
            # "--profile=" + profile_output_file.path,
            "profile --force-suffix --all " + file_prefix.replace("/", "\\"),
            summary,
            test_elf.path.replace("/", "\\"),
        ),
        is_executable = True,
    )
    ctx.actions.run(
        inputs = [test_elf],
        tools = [bat, bbe_simulator],
        outputs = simulator_output_files,
        executable = "cmd.exe",
        arguments = ["/C", bat.path.replace("/", "\\")],
        mnemonic = "RunSimulator",
        progress_message = "Running simulator",
        env = env,
    )

def _run_linux_simulator(ctx, env, bbe_simulator, test_elf, file_prefix, simulator_output_files):
    """
    Run the profiler on linux.

    Args:
        ctx: Context passed in from rule.
        env: Environment variables to set in the shell.
        bbe_simulator: Execution path for the BBE profiler (xt-gprof.ext)
        test_elf: The ELF file that is being profiled
        file_prefix: Directory name and file prefix for the output files.
        simulator_output_files: Output files generated by xt-run.exe

    Notes:
        Using the run_shell option here to facilitate support for the "profile" option
        of the client_commands command line option for the xt-run tool.

        --profile=<filename> - This only outputs the .cyc profile information.
    """
    summary = ""
    if ctx.attr.show_summary:
        summary = "--summary"

    ctx.actions.run_shell(
        tools = [bbe_simulator, test_elf],
        outputs = simulator_output_files,
        command = bbe_simulator.to_list()[0].path + " --console --mem_model --client_cmds=\"$1\" $2 $3",
        arguments = [
            "profile --force-suffix --all " + file_prefix,
            summary,
            test_elf.path,
        ],
        env = env,
        progress_message = "Running the simulation for {}".format(bbe_simulator),
    )

def _bbe_simulator_imp(ctx):
    bbe_simulator = depset(direct = ctx.files.bbe_simulator)

    for fi in ctx.attr.srcs.files.to_list():
        if fi.basename.endswith(".elf"):
            test_elf = fi

    env = {
        "XTENSA_CORE": ctx.attr.xtensa_core,
        "XTENSA_SYSTEM": ctx.files.xtensa_system_path[0].path,
        "XTENSAD_LICENSE_FILE": ctx.attr.license_server,
        "PATH": "",  # The path MUST be set or the simulator crashes with a segmentation fault.
    }

    profile_output_dir = ctx.actions.declare_directory(ctx.attr.name + "/profile_outputs")
    profiler_output_prefix = ctx.attr.name + "/"
    file_prefix = profiler_output_prefix + "profile_outputs/gmon.out"
    profile_output_prefix = profile_output_dir.path + "/gmon.out"

    simulator_output_files_depset = depset([
        ctx.actions.declare_file(file_prefix + ".cyc"),  # This is the default profiler selection.
        ctx.actions.declare_file(file_prefix + ".cyc.incl"),
        ctx.actions.declare_file(file_prefix + ".bdelay"),
        ctx.actions.declare_file(file_prefix + ".bdelay.incl"),
        ctx.actions.declare_file(file_prefix + ".cyc"),
        ctx.actions.declare_file(file_prefix + ".cyc.incl"),
        ctx.actions.declare_file(file_prefix + ".dcmiss"),
        ctx.actions.declare_file(file_prefix + ".dcmiss.incl"),
        ctx.actions.declare_file(file_prefix + ".dcmiss_cyc"),
        ctx.actions.declare_file(file_prefix + ".dcmiss_cyc.incl"),
        ctx.actions.declare_file(file_prefix + ".icmiss"),
        ctx.actions.declare_file(file_prefix + ".icmiss.incl"),
        ctx.actions.declare_file(file_prefix + ".icmiss_cyc"),
        ctx.actions.declare_file(file_prefix + ".icmiss_cyc.incl"),
        ctx.actions.declare_file(file_prefix + ".insn"),
        ctx.actions.declare_file(file_prefix + ".insn.incl"),
        ctx.actions.declare_file(file_prefix + ".interlock"),
        ctx.actions.declare_file(file_prefix + ".interlock.incl"),
        ctx.actions.declare_file(file_prefix + ".unc_ifetch"),
        ctx.actions.declare_file(file_prefix + ".unc_ifetch.incl"),
        ctx.actions.declare_file(file_prefix + ".unc_load"),
        ctx.actions.declare_file(file_prefix + ".unc_load.incl"),
    ])

    simulator_output_files = []
    simulator_output_files.append(profile_output_dir)
    simulator_output_files.extend(simulator_output_files_depset.to_list())

    if ctx.attr.is_windows:
        _run_windows_simulator(ctx, env, bbe_simulator, test_elf, profile_output_prefix, simulator_output_files)
    else:
        _run_linux_simulator(ctx, env, bbe_simulator, test_elf, profile_output_prefix, simulator_output_files)

    profiler_output_list = []
    if ctx.attr.run_profiler:
        bbe_profiler = depset(direct = ctx.files.bbe_profiler)
        for fi in simulator_output_files_depset.to_list():
            profiler_output_file = ctx.actions.declare_file(profiler_output_prefix + fi.basename + ".txt")
            profiler_output_list.append(profiler_output_file)

            if ctx.attr.is_windows:
                _run_windows_profiler(ctx, env, bbe_profiler, profiler_output_file, test_elf, fi)
            else:
                _run_linux_profiler(ctx, env, bbe_profiler, profiler_output_file, test_elf, fi)

        output_files = depset(
            direct = profiler_output_list,
            transitive = [simulator_output_files_depset],
        )

    else:
        output_files = simulator_output_files_depset

    return [
        DefaultInfo(files = output_files),
    ]

_run_bbe_sim = rule(
    implementation = _bbe_simulator_imp,
    attrs = {
        "srcs": attr.label(mandatory = True, doc = "BBE Library to simulate"),
        "bbe_simulator": attr.label(mandatory = True, cfg = "exec", allow_files = True),
        "bbe_profiler": attr.label(mandatory = True, cfg = "exec", allow_files = True),
        "license_server": attr.string(mandatory = False, default = "27001@nlnhsrk-is21.aptiv.com", doc = "License address"),
        "xtensa_core": attr.string(mandatory = False, default = "BBE32_R43_20230911", doc = "The name of the core for which the toolchain is configured. Only one is allowed per toolchain instance."),
        "xtensa_system_path": attr.label(
            mandatory = True,
            allow_files = True,
            default = "@build_config//:config",
            doc = "Directory path to add to xtensa-system that are required by the compiler. Typically, a directory is provided via filegroup. *NOTE: if an absolute path is provided, your build will not be hermetic!*",
        ),
        "is_windows": attr.bool(mandatory = True),
        "show_summary": attr.bool(mandatory = False, default = False, doc = "Show the summary of the simulator output."),
        "run_profiler": attr.bool(mandatory = False, default = False),
    },
    fragments = ["cpp"],
    toolchains = ["@bazel_tools//tools/cpp:toolchain_type"],
)

def run_bbe_sim(name, srcs, **kwargs):
    """
    Run the simulator for the BBE.

    Args:
        name: Name of the rule.
        srcs: The BBE32 binary build to be tested.
        **kwargs: further keyword arguments, e.g. `visibility`
            Additional supported arguments:
                run_profiler: If true, also runs and outputs the profile information from xt-gprof
                show_summary: Adds the --summary command line option to output the profile summary.

    """
    run_bbe_sim_impl = _run_bbe_sim

    run_bbe_sim_impl(
        name = name,
        srcs = srcs,
        bbe_simulator = select({
            "@bazel_tools//src/conditions:host_windows": "@bbe_windows//:tools/RI-2023.11-win32/XtensaTools/bin/xt-run.exe",
            "//conditions:default": "@bbe_linux//:tools/RI-2023.11-linux/XtensaTools/bin/xt-run",
        }),
        bbe_profiler = select({
            "@bazel_tools//src/conditions:host_windows": "@bbe_windows//:tools/RI-2023.11-win32/XtensaTools/bin/xt-gprof.exe",
            "//conditions:default": "@bbe_linux//:tools/RI-2023.11-linux/XtensaTools/bin/xt-gprof",
        }),
        xtensa_core = XTENSA_CORE,
        xtensa_system_path = "@build_config//:config",
        is_windows = select({
            "@bazel_tools//src/conditions:host_windows": True,
            "//conditions:default": False,
        }),
        **kwargs
    )
