##########################
### Project definition ###
##########################
cmake_minimum_required(VERSION 3.2)

set(project_name  "PCAN_Extractor")
project(${project_name})

set(PCAN_PROJECT_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}/..")
set(PCAN_COMMON_STRUCTURES "${CMAKE_CURRENT_LIST_DIR}/../../Common_Structures")


set(SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderLowRR.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderLowRR.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Source/pcanLowRRBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Source/pcanLowRRBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Source/pcanLowRRBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Source/pcanLowRRBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Source/pcanLowRRBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Include/pcanLowRRBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Include/pcanLowRRBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Include/pcanLowRRBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Include/pcanLowRRBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Include/pcanLowRRBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Include/pcanLowRRBaseA430_SOP3.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderLowRL.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderLowRL.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Source/pcanLowRLBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Source/pcanLowRLBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Source/pcanLowRLBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Source/pcanLowRLBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Source/pcanLowRLBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Include/pcanLowRLBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Include/pcanLowRLBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Include/pcanLowRLBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Include/pcanLowRLBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Include/pcanLowRLBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Include/pcanLowRLBaseA430_SOP3.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderLowFL.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderLowFL.cpp")

list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderLow.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderLow.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderMid.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderMid.cpp")

list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Source/pcanLowFLBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Source/pcanLowFLBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Source/pcanLowFLBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Source/pcanLowFLBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Source/pcanLowFLBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Include/pcanLowFLBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Include/pcanLowFLBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Include/pcanLowFLBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Include/pcanLowFLBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Include/pcanLowFLBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Include/pcanLowFLBaseA430_SOP3.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderLowFR.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderLowFR.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Source/pcanLowFRBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Source/pcanLowFRBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Source/pcanLowFRBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Source/pcanLowFRBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Source/pcanLowFRBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Include/pcanLowFRBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Include/pcanLowFRBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Include/pcanLowFRBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Include/pcanLowFRBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Include/pcanLowFRBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Include/pcanLowFRBaseA430_SOP3.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderMidFL.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderMidFL.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Source/pcanMidFLBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Source/pcanMidFLBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Source/pcanMidFLBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Source/pcanMidFLBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Source/pcanMidFLBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Include/pcanMidFLBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Include/pcanMidFLBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Include/pcanMidFLBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Include/pcanMidFLBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Include/pcanMidFLBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Include/pcanMidFLBaseA430_SOP3.h")

list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderMidFR.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderMidFR.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Source/pcanMidFRBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Source/pcanMidFRBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Source/pcanMidFRBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Source/pcanMidFRBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Source/pcanMidFRBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Include/pcanMidFRBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Include/pcanMidFRBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Include/pcanMidFRBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Include/pcanMidFRBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Include/pcanMidFRBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Include/pcanMidFRBaseA430_SOP3.h")

list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderMidRL.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderMidRL.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Source/pcanMidRLBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Source/pcanMidRLBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Source/pcanMidRLBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Source/pcanMidRLBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Source/pcanMidRLBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Include/pcanMidRLBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Include/pcanMidRLBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Include/pcanMidRLBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Include/pcanMidRLBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Include/pcanMidRLBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Include/pcanMidRLBaseA430_SOP3.h")

list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Include/pcanDecoderMidRR.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/Source/PcanDecoderMidRR.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Source/pcanMidRRBaseA310.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Source/pcanMidRRBaseA390.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Source/pcanMidRRBaseA410.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Source/pcanMidRRBaseA480.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Source/pcanMidRRBaseA430_SOP3.cpp")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Include/pcanMidRRBase.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Include/pcanMidRRBaseA310.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Include/pcanMidRRBaseA390.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Include/pcanMidRRBaseA410.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Include/pcanMidRRBaseA480.h")
list(APPEND SOURCES "${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Include/pcanMidRRBaseA430_SOP3.h")

source_group(TREE ${PCAN_PROJECT_ROOT_PATH} FILES ${SOURCES})

set(target_name ${project_name})
add_library(${target_name} STATIC "")

#link libraries
target_link_libraries (${target_name} Mdf_Log)
target_link_libraries(${target_name} CrossPlatform)


target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RR/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_RL/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FL/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_LOW_FR/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FL/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_FR/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RL/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/PCAN_MID_RR/Include)
target_include_directories(${target_name} PUBLIC ${PCAN_PROJECT_ROOT_PATH}/Include)


target_include_directories(${target_name} PUBLIC ${BORDNET_DECODER_PROJ})

target_include_directories(${target_name} PUBLIC ${PCAN_COMMON_STRUCTURES})

target_sources(${target_name} PRIVATE ${SOURCES})

#link include directories
target_include_directories(${target_name} PUBLIC ${COMMON_INC})
target_include_directories(${target_name} PRIVATE ${COMMON_INC}/pugixml)

if(OUTPUT_PATH)
set_target_properties(${target_name} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												ARCHIVE_OUTPUT_DIRECTORY "${OUTPUT_PATH}") 				
endif(OUTPUT_PATH)

# Structure Alignment
if(MSVC)
	if(${CMAKE_GENERATOR} STREQUAL "Visual Studio 16 2019")
		target_compile_definitions(${project_name} PRIVATE  WINDOWS_IGNORE_PACKING_MISMATCH) 
	endif()
endif(MSVC)

if(MSVC)
	target_compile_definitions(${target_name} PRIVATE _MBCS _WIN_PLATFORM) 
endif(MSVC)

if(UNIX)
	if(BUILD_FOR_32_BIT)
		set_target_properties(${target_name} PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
	endif(BUILD_FOR_32_BIT)

	#For Debugging in Linux...
	target_compile_options(${target_name} PRIVATE "$<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:-g>")

endif(UNIX)