#!/bin/bash
# ============================================================================
#  Gen8 iND13400 - Build & Test Launcher (Bash version)
#  Runs bazelisk builds via Git Bash / WSL2 to bypass Windows 32K cmd limit.
#  Usage: bash STEP2_BUILD_OUTPUT_FILES.sh
# ============================================================================

set -e

# Navigate to repo root (three levels up from tools/python/testing_framework)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/../../.."
REPO_ROOT="$(pwd)"
echo ""
echo "  Repo Root: $REPO_ROOT"
echo ""

# Enable long paths in Git to avoid "Filename too long" errors
git config --global core.longpaths true 2>/dev/null || true

# --- Credential Setup: Ensure .netrc exists for JFrog/Bazel authentication ---
if [ ! -f "$HOME/.netrc" ]; then
  # Running in WSL - try to copy .netrc from Windows user profile
  WIN_USER=$(cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r' || true)
  if [ -z "$WIN_USER" ]; then
    # Fallback: scan /mnt/c/Users for .netrc
    for d in /mnt/c/Users/*/; do
      if [ -f "${d}.netrc" ] && [ "$(basename "$d")" != "Public" ] && [ "$(basename "$d")" != "Default" ]; then
        cp "${d}.netrc" "$HOME/.netrc"
        chmod 600 "$HOME/.netrc"
        echo "  [INFO] Copied .netrc from ${d} to WSL home"
        break
      fi
    done
  elif [ -f "/mnt/c/Users/$WIN_USER/.netrc" ]; then
    cp "/mnt/c/Users/$WIN_USER/.netrc" "$HOME/.netrc"
    chmod 600 "$HOME/.netrc"
    echo "  [INFO] Copied .netrc from Windows user ($WIN_USER) to WSL home"
  fi
  if [ ! -f "$HOME/.netrc" ]; then
    echo "  [WARNING] ~/.netrc not found! Run repo_init.py on Windows first."
    echo "            Builds may fail with 401 authentication errors."
  fi
fi

# --- WSL/Linux user.bazelrc: Disable remote cache & BES (no API key locally) ---
# Also fix Windows-specific paths and workspace_status_command CRLF issues
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Fix CRLF line endings on all .sh scripts used by the build (Windows line endings break bash)
  find "$REPO_ROOT/software/common/versions/linkstamp" -name "*.sh" -exec sed -i 's/\r$//' {} \; -exec chmod +x {} \;
  find "$REPO_ROOT/tools/bazel/scripts" -name "*.sh" -exec sed -i 's/\r$//' {} \; -exec chmod +x {} \;
  # Fix awa.sh if present
  if [ -f "$REPO_ROOT/awa.sh" ]; then
    sed -i 's/\r$//' "$REPO_ROOT/awa.sh"
    chmod +x "$REPO_ROOT/awa.sh"
  fi

  # Generate a Linux-appropriate user.bazelrc if not present or is a Windows one
  if [ ! -f "$REPO_ROOT/user.bazelrc" ] || grep -q "C:/" "$REPO_ROOT/user.bazelrc" 2>/dev/null; then
    # Save Windows version as backup if it exists
    if [ -f "$REPO_ROOT/user.bazelrc" ] && grep -q "C:/" "$REPO_ROOT/user.bazelrc" 2>/dev/null; then
      cp "$REPO_ROOT/user.bazelrc" "$REPO_ROOT/user.bazelrc.win_backup"
    fi

    cat >"$REPO_ROOT/user.bazelrc" <<'EOF'
# =============================================================================
# WSL/Linux local user.bazelrc (auto-generated by STEP2_BUILD_OUTPUT_FILES.sh)
# =============================================================================

# Disable remote cache (no ARB API key available locally)
build --remote_cache=

# Disable Build Event Service (no API key)
build --bes_backend=
build --bes_results_url=

# Cache downloaded repos/archives so subsequent builds don't re-fetch
build --repository_cache=~/.cache/bazel_repo_cache

# Use most CPU cores
build --jobs=HOST_CPUS*.8

# Skip stamping for dev builds
build --nostamp
EOF
    echo "  [INFO] Generated Linux user.bazelrc (remote cache disabled)"
  else
    echo "  [INFO] Existing Linux user.bazelrc found - keeping it."
  fi

elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
  # Generate a Windows-appropriate user.bazelrc if not present
  if [ ! -f "$REPO_ROOT/user.bazelrc" ]; then
    cat >"$REPO_ROOT/user.bazelrc" <<'EOF'
# =============================================================================
# Windows local user.bazelrc (auto-generated by STEP2_BUILD_OUTPUT_FILES.sh)
# =============================================================================

# Short output base to avoid Windows long path failures (32K limit)
startup --output_base=C:/bzl

# Use 80% of CPU cores for parallel builds
common --jobs=HOST_CPUS*.8

# Only download top-level build outputs, not all intermediates
build --remote_download_toplevel

# Skip stamping for dev builds (prevents cache invalidation on every commit)
build --nostamp

# Disable Build Event Service for local dev (saves network I/O)
build --bes_backend=
build --bes_results_url=

# Local disk cache for faster rebuilds
build --disk_cache=C:/bzl_cache

# Use available RAM efficiently
build --local_resources=memory=HOST_RAM*.8

build --experimental_guard_against_concurrent_changes=false

# Use param files to avoid Windows 32K command-line limit (for xt-clang/BBE32)
build:windows --features=compiler_param_file

# Short temp dir for unit tests (avoids long path issues)
test:windows --@bazel_platform//quality/ut:tmp_dir=C:/tmp
EOF
    echo "  [INFO] Generated Windows user.bazelrc (short paths + disk cache)"
  else
    echo "  [INFO] Existing Windows user.bazelrc found - keeping it."
  fi
fi

# Detect environment and set bazelisk path
if command -v bazelisk &>/dev/null; then
  BZL="bazelisk"
elif [ -f "./bazelisk" ]; then
  BZL="./bazelisk"
elif [ -f "./bazelisk.exe" ]; then
  BZL="./bazelisk.exe"
else
  echo "  [ERROR] bazelisk not found in PATH or repo root."
  exit 1
fi

# On Windows (Git Bash/MSYS2), use short output_base to reduce path lengths
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
  BZL="$BZL --output_base=C:/b"
  echo "  [INFO] Windows detected - using --output_base=C:/b"
fi
# On WSL2/Linux, no output_base override needed (no 32K limit)

# Colors for output (defined early so prerequisite checks can use them)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# --- Pre-build Prerequisite Checks ---
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  NEED_APT_UPDATE=true

  # Check mono (required for DvrlStreamTool.exe)
  if ! command -v mono &>/dev/null || ! mono --version &>/dev/null; then
    echo ""
    echo -e "  ${YELLOW}[INFO]${NC} 'mono' not found. Installing mono-complete..."
    sudo apt-get update -qq && NEED_APT_UPDATE=false
    sudo apt-get install -y -qq mono-complete
    if ! command -v mono &>/dev/null; then
      echo -e "  ${RED}[ERROR]${NC} Failed to install mono-complete. Please install manually:"
      echo "         sudo apt install -y mono-complete"
      exit 1
    fi
    echo -e "  ${GREEN}[OK]${NC} mono-complete installed successfully."
  elif ! dpkg -s libmono-system-windows-forms4.0-cil &>/dev/null 2>&1; then
    echo ""
    echo -e "  ${YELLOW}[INFO]${NC} mono found but missing System.Windows.Forms. Installing..."
    if $NEED_APT_UPDATE; then sudo apt-get update -qq && NEED_APT_UPDATE=false; fi
    sudo apt-get install -y -qq libmono-system-windows-forms4.0-cil
    echo -e "  ${GREEN}[OK]${NC} Mono Windows.Forms assembly installed."
  fi

  # Check libc6-i386 / 32-bit support (required for WindRiver Diab compiler)
  if ! dpkg -s libc6-i386 &>/dev/null 2>&1 && ! dpkg -s libc6:i386 &>/dev/null 2>&1; then
    echo ""
    echo -e "  ${YELLOW}[INFO]${NC} 32-bit libraries not found. Installing (required for WindRiver dcc)..."
    if $NEED_APT_UPDATE; then sudo apt-get update -qq && NEED_APT_UPDATE=false; fi
    sudo dpkg --add-architecture i386 2>/dev/null || true
    sudo apt-get update -qq
    sudo apt-get install -y -qq libc6:i386 libstdc++6:i386 zlib1g:i386
    echo -e "  ${GREEN}[OK]${NC} 32-bit libraries installed."
  fi
fi

# Initialize last command tracking
LAST_CMD=""
LAST_CMD_LABEL=""

# ============================================================================
#  FUNCTIONS
# ============================================================================

print_menu() {
  echo "============================================================================"
  echo "  Gen8 iND13400 - Build and Test Menu"
  echo "============================================================================"
  echo ""
  echo "  --- Clean ---"
  echo "   1)  Bazel Clean"
  echo "   2)  Bazel Clean --expunge  (full deep clean)"
  echo ""
  echo "  --- Satellite-CAN Builds (Default) ---"
  echo "   3)  FLR8  Satellite-CAN"
  echo "   4)  SRR8P Satellite-CAN"
  echo ""
  echo "  --- Satellite-SomeIP Builds ---"
  echo "   5)  FLR8  Satellite-SomeIP"
  echo "   6)  SRR8P Satellite-SomeIP"
  echo ""
  echo "  --- Standalone Builds ---"
  echo "   7)  FLR8  Standalone"
  echo "   8)  SRR8P Standalone"
  echo ""
  echo "  --- Ashok Leyland (AL) Build ---"
  echo "   9)  SRR8P AL-CAN              (CAN + tracker)"
  echo ""
  echo "  --- Unit Tests ---"
  echo "  10)  Run ALL Unit Tests"
  echo "  11)  Run BBE-specific Unit Tests"
  echo ""
  echo "  --- Coverage ---"
  echo "  12)  Generate Full Coverage Report"
  echo ""
  echo "  --- Coverity Static Analysis ---"
  echo "  13)  Coverity R52  (FLR8)"
  echo "  14)  Coverity R52  (SRR8P)"
  echo "  15)  Coverity BBE32 (FLR8)"
  echo "  16)  Coverity BBE32 (SRR8P)"
  echo ""
  echo "  --- Compile Database ---"
  echo "  17)  Generate compile_commands.json"
  echo ""
  echo "  --- Advanced / Custom Build ---"
  echo "  18)  Custom Build with Optional Debug Flags"
  echo ""
  echo "   0)  Exit"
  echo "============================================================================"
}

collect_optional_flags() {
  echo ""
  echo "  Add optional flags? (Enter to skip, or type flags)"
  echo "    Examples: --enable_adc_logging=True --enable_cdc=True --noremote_accept_cached"
  read -rp "  Optional flags: " EXTRA_FLAGS
}

run_build() {
  local label="$1"
  shift
  local cmd="$BZL build $*"
  LAST_CMD="$cmd"
  LAST_CMD_LABEL="$label"
  echo ""
  echo -e "  ${CYAN}[BUILD]${NC} $label"
  echo "  Command: $cmd"
  echo ""
  # Remove stale bazel-bin dir/symlink so Bazel can recreate its symlink
  rm -rf "$REPO_ROOT/bazel-bin" 2>/dev/null || true
  set +e
  eval "$cmd"
  local exit_code=$?
  set -e
  post_build $exit_code
}

run_cmd() {
  local label="$1"
  shift
  local cmd="$BZL $*"
  echo ""
  echo -e "  ${CYAN}[$label]${NC}"
  echo "  Command: $cmd"
  echo ""
  # Remove stale bazel-bin dir/symlink so Bazel can recreate its symlink
  rm -rf "$REPO_ROOT/bazel-bin" 2>/dev/null || true
  set +e
  eval "$cmd"
  local exit_code=$?
  set -e
  post_build $exit_code
}

post_build() {
  local exit_code=$1
  echo ""
  if [ $exit_code -eq 0 ]; then
    echo -e "  ${GREEN}[SUCCESS]${NC} Build completed successfully."
    # Create Windows-accessible junction for bazel-bin/bazel-out
    create_windows_links
  else
    echo -e "  ${RED}[FAILED]${NC} Build failed with error code: $exit_code"
  fi
  post_build_menu
}

# Create Windows-compatible directory junctions so build outputs are accessible
# from Windows Explorer (Linux symlinks on NTFS aren't visible to Windows)
create_windows_links() {
  # Only needed when running in WSL on a Windows filesystem
  if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    return
  fi

  # Resolve the output base from the execroot symlink Bazel always creates
  local execroot_link="$REPO_ROOT/bazel-Core_Radar_Gen8_iND13400"
  if [ ! -L "$execroot_link" ]; then
    # Try alternate name patterns Bazel might use
    execroot_link=$(find "$REPO_ROOT" -maxdepth 1 -name "bazel-*" -type l ! -name "bazel-bin" ! -name "bazel-out" ! -name "bazel-testlogs" | head -1)
  fi

  if [ -z "$execroot_link" ] || [ ! -L "$execroot_link" ]; then
    echo -e "  ${YELLOW}[WARN]${NC} No Bazel execroot symlink found - cannot create output links."
    return
  fi

  local execroot
  execroot=$(readlink -f "$execroot_link")
  local bin_outputs="$execroot/bazel-out/k8-fastbuild/bin/outputs"

  if [ ! -d "$bin_outputs" ]; then
    # Fall back to searching for the outputs directory
    bin_outputs=$(find "$execroot/bazel-out" -maxdepth 3 -path "*/bin/outputs" -type d 2>/dev/null | head -1)
  fi

  if [ -z "$bin_outputs" ] || [ ! -d "$bin_outputs" ]; then
    echo -e "  ${YELLOW}[WARN]${NC} Build outputs directory not found in Bazel output tree."
    return
  fi

  # If repo is on /mnt/* (Windows drive), replicate the same folder structure
  # as a Windows build: bazel-bin/ contains outputs/, software/, external/, temp/, etc.
  if [[ "$REPO_ROOT" == /mnt/* ]]; then
    local bin_dir
    bin_dir=$(dirname "$bin_outputs")

    # Remove Bazel's symlink (points to Linux FS, not accessible from Windows)
    rm -f "$REPO_ROOT/bazel-bin" 2>/dev/null

    # Copy full bin directory to match Windows bazel-bin structure
    cp -r "$bin_dir" "$REPO_ROOT/bazel-bin" 2>/dev/null \
      && echo -e "  ${GREEN}[OUTPUT]${NC} Build outputs copied to: bazel-bin/" \
      && echo -e "  ${CYAN}        ${NC} (same structure as Windows build - accessible from Explorer)" \
      && echo -e "  ${CYAN}        ${NC} Contents: outputs/ software/ external/ temp/"
  else
    # Native Linux filesystem - just create a symlink
    local bin_dir
    bin_dir=$(dirname "$bin_outputs")
    rm -f "$REPO_ROOT/bazel-bin" 2>/dev/null
    ln -sf "$bin_dir" "$REPO_ROOT/bazel-bin" 2>/dev/null
    echo -e "  ${GREEN}[OUTPUT]${NC} bazel-bin -> $bin_dir"
  fi
}

post_build_menu() {
  # Flush any buffered terminal escape sequences (e.g. cursor position reports)
  # that Windows Terminal + WSL may inject as spurious input
  read -r -t 0.1 -n 1000 _ 2>/dev/null || true
  echo ""
  echo "  ========================================"
  echo "   What would you like to do next?"
  echo "  ========================================"
  if [ -n "$LAST_CMD" ]; then
    echo "    R)  Retry last build: $LAST_CMD_LABEL"
    echo "    V)  Retry with --verbose_failures"
  fi
  echo "    M)  Back to Main Menu"
  echo "    0)  Exit"
  echo "  ========================================"
  read -rp "  Select [R/V/M/0]: " post_choice
  case "${post_choice^^}" in
    R)
      if [ -z "$LAST_CMD" ]; then
        echo "  [ERROR] No previous command to retry."
        post_build_menu
      else
        echo ""
        echo -e "  ${CYAN}[RETRY]${NC} $LAST_CMD_LABEL"
        echo "  Command: $LAST_CMD"
        echo ""
        set +e
        eval "$LAST_CMD"
        local rc=$?
        set -e
        post_build $rc
      fi
      ;;
    V)
      if [ -z "$LAST_CMD" ]; then
        echo "  [ERROR] No previous command to retry."
        post_build_menu
      else
        echo ""
        echo -e "  ${CYAN}[RETRY+VERBOSE]${NC} $LAST_CMD_LABEL"
        echo "  Command: $LAST_CMD --verbose_failures"
        echo ""
        set +e
        eval "$LAST_CMD --verbose_failures"
        local rc=$?
        set -e
        post_build $rc
      fi
      ;;
    M) main_menu ;;
    0) exit 0 ;;
    *)
      echo "  [ERROR] Invalid selection."
      post_build_menu
      ;;
  esac
}

custom_build() {
  echo ""
  echo "  ====== Custom Build Configuration ======"
  echo ""

  # --- Step 1: Pick config variant ---
  echo "  Select platform config:"
  echo "    1) FLR8"
  echo "    2) SRR8P"
  read -rp "  Config [1-2]: " cfg_choice
  case "$cfg_choice" in
    1) CONFIG="--config=flr8" ;;
    2) CONFIG="--config=srr8p" ;;
    *)
      echo "  [ERROR] Invalid config."
      return
      ;;
  esac
  echo ""

  # --- Step 2: Pick vehicle communication ---
  echo "  Select vehicle communication variant:"
  echo "    1) CAN        (default)"
  echo "    2) SomeIP     (Ethernet high-det)"
  echo "    3) None       (standalone / tracker)"
  echo "    4) AL CAN Standalone  (SRR8P only)"
  read -rp "  VehCom [1-4]: " veh_choice
  VEH_COM=""
  case "$veh_choice" in
    1) VEH_COM="--veh_com=can" ;;
    2) VEH_COM="--veh_com=someip" ;;
    3) VEH_COM="--veh_com=none" ;;
    4) VEH_COM="--veh_com=al_can_standalone" ;;
  esac
  echo ""

  # --- Step 3: Tracker variant ---
  TRACKER=""
  if [ "$veh_choice" == "3" ]; then
    echo "  Select tracker variant:"
    echo "    1) platform_flr8_standalone"
    echo "    2) platform_srr8p_standalone"
    echo "    3) platform_srr8p_2_sensor_fusion"
    echo "    4) disabled"
    echo "    5) partner_sensor"
    echo "    6) Skip (none)"
    read -rp "  Tracker [1-6]: " trk_choice
    case "$trk_choice" in
      1) TRACKER="--tracker_variant=platform_flr8_standalone" ;;
      2) TRACKER="--tracker_variant=platform_srr8p_standalone" ;;
      3) TRACKER="--tracker_variant=platform_srr8p_2_sensor_fusion" ;;
      4) TRACKER="--tracker_variant=disabled" ;;
      5) TRACKER="--tracker_variant=partner_sensor" ;;
    esac
    echo ""
  fi
  if [ "$veh_choice" == "4" ]; then
    TRACKER="--tracker_variant=AL --enable_features=true"
  fi

  # --- Step 4: Board and MARS revision ---
  read -rp "  Board version [EDU/A0/B0/A2P4] (default=B0, Enter to skip): " BOARD_VER
  BOARD_FLAG=""
  [ -n "$BOARD_VER" ] && BOARD_FLAG="--chandra_hw_rev=$BOARD_VER"

  read -rp "  MARS HW revision [A0/B0] (default=B0, Enter to skip): " MARS_VER
  MARS_FLAG=""
  [ -n "$MARS_VER" ] && MARS_FLAG="--mars_hw_rev=$MARS_VER"
  echo ""

  # --- Step 5: BBE ASIC/FPGA ---
  read -rp "  BBE config [asic/fpga] (default=asic, Enter to skip): " BBE_CFG
  BBE_FLAG=""
  [ -n "$BBE_CFG" ] && BBE_FLAG="--bbe_asic_fpga=$BBE_CFG"
  echo ""

  # --- Step 6: ROT Generation ---
  read -rp "  ROT generation [rot_gen7v1/rot_gen7v2/rot_gen8] (default=rot_gen8, Enter to skip): " ROT_VAL
  ROT_FLAG=""
  [ -n "$ROT_VAL" ] && ROT_FLAG="--rot_gen=$ROT_VAL"
  echo ""

  # --- Step 7: Optional debug flags ---
  echo "  ====== Optional Debug / Feature Flags (y to enable, Enter to skip) ======"
  echo ""
  DBG_FLAGS=""

  echo "  --- Logging and Profiling ---"
  read -rp "  Enable ADC Logging?                [y/N]: " f1
  [[ "${f1,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_adc_logging=True"

  read -rp "  Enable CDC Logging?                [y/N]: " f2
  [[ "${f2,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_cdc=True"

  read -rp "  Enable Chirp Profiling?            [y/N]: " f3
  [[ "${f3,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_chirp_profiling=True"

  read -rp "  Enable UART?                       [y/N]: " f4
  [[ "${f4,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_uart=True"

  read -rp "  Enable Stream Re-generation?       [y/N]: " f5
  [[ "${f5,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_stream_generation=True"

  echo ""
  echo "  --- Safety / Monitor Disable ---"
  read -rp "  Disable Stack Monitor (R52)?       [y/N]: " f6
  [[ "${f6,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --disable_stack_monitor_r52=true"

  read -rp "  Disable Program Flow Monitor?      [y/N]: " f7
  [[ "${f7,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --disable_pfm=true"

  read -rp "  Disable Internal Watchdog?         [y/N]: " f8
  [[ "${f8,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --disable_int_wdg=true"

  read -rp "  Disable Static Register Safety?    [y/N]: " f9
  [[ "${f9,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --static_register_safety_enabled=false"

  read -rp "  Stub Tracker (disable tracker)?    [y/N]: " f9a
  [[ "${f9a,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --stub_tracker=true"

  echo ""
  echo "  --- Test Patterns / Injection ---"
  read -rp "  Enable Test Pattern Gen?           [y/N]: " f10
  [[ "${f10,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --config=use_test_pattern_gen"

  read -rp "  Enable MARS Test Pattern?          [y/N]: " f11
  [[ "${f11,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --config=configure_MARS_test_pattern"

  read -rp "  Enable MARS ADC Test?              [y/N]: " f11a
  [[ "${f11a,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --config=enable_mars_adc_test"

  read -rp "  Enable RESI Mode?                  [y/N]: " f12
  [[ "${f12,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --config=configure_RESI_MODE"

  echo ""
  echo "  --- Testing Frameworks ---"
  read -rp "  Enable Integration Testing (SWE5)? [y/N]: " f13
  if [[ "${f13,,}" == "y" ]]; then
    DBG_FLAGS="$DBG_FLAGS --Integration_Testing=true"
    read -rp "  Enable Anglefinding IT?            [y/N]: " f13a
    [[ "${f13a,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --Anglefinding_IT=true"
  fi

  read -rp "  Enable SQT Test Cases?             [y/N]: " f14
  [[ "${f14,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_sqt_testcases=true"

  read -rp "  Enable SIT Test Cases?             [y/N]: " f15
  [[ "${f15,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_sit_testcases=true"

  read -rp "  Disable XCP Fault Injection Tests? [y/N]: " f15a
  [[ "${f15a,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_XCP_FAULT_INJECTION_testcases=false"

  read -rp "  Enable Bench Testing?              [y/N]: " f16
  [[ "${f16,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_bench_testing=true"

  read -rp "  Enable MCAL Test?                  [y/N]: " f17
  [[ "${f17,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --enable_mcal_test=true"

  echo ""
  echo "  --- NVM / SIL / Alignment ---"
  read -rp "  Enable Alignment NVM Test?         [y/N]: " f18
  [[ "${f18,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --alignment_nvm_test=true"

  read -rp "  Enable PSP SIL Config?             [y/N]: " f19
  [[ "${f19,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --psp_sil_config=True"

  echo ""
  echo "  --- Cache ---"
  read -rp "  Bypass Remote Cache?               [y/N]: " f20
  [[ "${f20,,}" == "y" ]] && DBG_FLAGS="$DBG_FLAGS --noremote_accept_cached"

  echo ""

  # --- Extra raw flags ---
  read -rp "  Enter any additional raw bazelisk flags (Enter to skip): " RAW_FLAGS
  echo ""

  # --- Assemble and execute ---
  run_build "Custom Build ($CONFIG)" "//:gen8 $CONFIG $VEH_COM $TRACKER $BOARD_FLAG $MARS_FLAG $BBE_FLAG $ROT_FLAG $DBG_FLAGS $RAW_FLAGS $EXTRA_FLAGS"
}

# ============================================================================
#  MAIN MENU LOOP
# ============================================================================

main_menu() {
  while true; do
    print_menu
    echo ""
    # Flush any buffered terminal escape sequences before reading input
    read -r -t 0.1 -n 1000 _ 2>/dev/null || true
    read -rp "Select an option [0-18]: " choice

    case "$choice" in
      0) exit 0 ;;
      1)
        echo ""
        echo "  [CLEAN] Running bazelisk clean ..."
        $BZL clean
        echo "  [CLEAN] Done."
        post_build_menu
        ;;
      2)
        echo ""
        echo "  [EXPUNGE] Running bazelisk clean --expunge ..."
        $BZL clean --expunge
        echo "  [EXPUNGE] Done. All cached build outputs removed."
        post_build_menu
        ;;
      3)
        collect_optional_flags
        run_build "Satellite-CAN FLR8" "//:gen8 --config=flr8 $EXTRA_FLAGS"
        ;;
      4)
        collect_optional_flags
        run_build "Satellite-CAN SRR8P" "//:gen8 --config=srr8p $EXTRA_FLAGS"
        ;;
      5)
        collect_optional_flags
        run_build "Satellite-SomeIP FLR8" "//:gen8 --config=flr8 --veh_com=someip $EXTRA_FLAGS"
        ;;
      6)
        collect_optional_flags
        run_build "Satellite-SomeIP SRR8P" "//:gen8 --config=srr8p --veh_com=someip $EXTRA_FLAGS"
        ;;
      7)
        collect_optional_flags
        run_build "Standalone-FLR8" "//:gen8 --config=flr8 --veh_com=none --tracker_variant=platform_flr8_standalone $EXTRA_FLAGS"
        ;;
      8)
        collect_optional_flags
        run_build "Standalone-SRR8P" "//:gen8 --config=srr8p --veh_com=none --tracker_variant=platform_srr8p_standalone $EXTRA_FLAGS"
        ;;
      9)
        collect_optional_flags
        run_build "AL-SRR8P (Ashok Leyland CAN + Tracker)" "//:gen8 --config=srr8p --veh_com=al_can_standalone --tracker_variant=AL --enable_features=true $EXTRA_FLAGS"
        ;;
      10)
        run_cmd "TEST" "test //:all_unit_tests --test_output=all"
        ;;
      11)
        run_cmd "TEST" "test //:tests_bbe --test_output=all"
        ;;
      12)
        run_cmd "COVERAGE" "test //coverage:report"
        ;;
      13)
        run_cmd "COVERITY" "build //software/r52:windriver_r52_cov --config=flr8"
        ;;
      14)
        run_cmd "COVERITY" "build //software/r52:windriver_r52_cov --config=srr8p"
        ;;
      15)
        run_cmd "COVERITY" "build //software/bbe32:xtensa_bbe32_cov --config=flr8"
        ;;
      16)
        run_cmd "COVERITY" "build //software/bbe32:xtensa_bbe32_cov --config=srr8p"
        ;;
      17)
        run_cmd "COMPILEDB" "run //:compiledb"
        ;;
      18)
        collect_optional_flags
        custom_build
        ;;
      *)
        echo ""
        echo "  [ERROR] Invalid selection: \"$choice\""
        echo ""
        ;;
    esac
  done
}

# Cleanup: Restore Windows user.bazelrc on exit (if we backed it up)
cleanup() {
  if [ -f "$REPO_ROOT/user.bazelrc.win_backup" ]; then
    mv "$REPO_ROOT/user.bazelrc.win_backup" "$REPO_ROOT/user.bazelrc"
  fi
}
trap cleanup EXIT

# Start
main_menu
