set(REL_PATH Fusion360/common)

set(SRC_LOCAL
    ${REL_PATH}/include/f360_get_reference_point_orth_side.h
    ${REL_PATH}/include/f360_get_reference_point_para_side.h
    ${REL_PATH}/include/f360_update_object_reference_point.h
    ${REL_PATH}/include/f360_update_object_reference_point_support_functions.h
    ${REL_PATH}/include/f360_reference_point_support_functions.h
    ${REL_PATH}/include/f360_calculate_curvi_position.h
    ${REL_PATH}/include/f360_check_if_point_is_inside_box.h
    ${REL_PATH}/include/f360_circle.h
    ${REL_PATH}/include/f360_clear_cluster.h
    ${REL_PATH}/include/f360_clear_det_assoc_obj_props.h
    ${REL_PATH}/include/f360_clear_object_track.h
    ${REL_PATH}/include/f360_clusters_preprocessing.h
    ${REL_PATH}/include/f360_convert_object_prev_vcs_to_current_vcs.h
    ${REL_PATH}/include/f360_convert_vcs_posn_to_tcs_posn.h
    ${REL_PATH}/include/f360_dead_zone.h
    ${REL_PATH}/include/f360_define_dead_zone.h
    ${REL_PATH}/include/f360_define_simplified_dead_zone.h
    ${REL_PATH}/include/f360_find_detection_inliers.h
    ${REL_PATH}/include/f360_find_closest_valid_sep_on_given_side.h
    ${REL_PATH}/include/f360_find_interval_in_array.h
    ${REL_PATH}/include/f360_get_edge_tcs_start_and_end_point.h
    ${REL_PATH}/include/f360_get_track_bbox_in_vcs.h
    ${REL_PATH}/include/f360_intersections.h
    ${REL_PATH}/include/f360_kill_cluster.h
    ${REL_PATH}/include/f360_kill_obj_trk.h
    ${REL_PATH}/include/f360_points_with_extreme_azimuth.h
    ${REL_PATH}/include/f360_push_reduced_id.h
    ${REL_PATH}/include/f360_random_number_generation.h
    ${REL_PATH}/include/f360_range_rates.h
    ${REL_PATH}/include/f360_rectangle.h
    ${REL_PATH}/include/f360_sanity_check.h
    ${REL_PATH}/include/f360_handle_spd_and_acc_when_stopping.h
    ${REL_PATH}/include/f360_side_of_host.h
    ${REL_PATH}/include/f360_sort_priority.h
    ${REL_PATH}/include/f360_sorted_clusters_mgmt.h
    ${REL_PATH}/include/f360_sorted_tracks_mgmt.h
    ${REL_PATH}/include/f360_statistical_tests.h
    ${REL_PATH}/include/f360_terminate_clusters.h
    ${REL_PATH}/include/f360_try_to_dealiase_range_rate.h
    ${REL_PATH}/include/f360_vcs_long_sorted_dets_support_functions.h
    ${REL_PATH}/include/f360_visibility_info.h
    ${REL_PATH}/include/f360_allocate_id_for_initialized_object.h
    ${REL_PATH}/include/f360_associate_detection_to_object.h
    ${REL_PATH}/include/f360_calc_dist_to_edge.h
    ${REL_PATH}/include/f360_determine_cross_moving_obj.h     
    ${REL_PATH}/include/f360_calc_predicted_range_rate.h
    ${REL_PATH}/include/f360_check_if_objects_can_overlap_significantly.h
    ${REL_PATH}/include/f360_cluster_detection_downselection.h
    ${REL_PATH}/source/f360_get_reference_point_orth_side.cpp
    ${REL_PATH}/source/f360_get_reference_point_para_side.cpp
    ${REL_PATH}/source/f360_update_object_reference_point.cpp
    ${REL_PATH}/source/f360_update_object_reference_point_support_functions.cpp
    ${REL_PATH}/source/f360_reference_point_support_functions.cpp
    ${REL_PATH}/source/f360_associate_detection_to_object.cpp
    ${REL_PATH}/source/f360_bounding_box.cpp
    ${REL_PATH}/source/f360_calc_dist_to_edge.cpp
    ${REL_PATH}/source/f360_determine_cross_moving_obj.cpp
    ${REL_PATH}/source/f360_calc_predicted_range_rate.cpp
    ${REL_PATH}/source/f360_calculate_curvi_position.cpp
    ${REL_PATH}/source/f360_calculate_priority.cpp
    ${REL_PATH}/source/f360_check_if_point_is_inside_box.cpp
    ${REL_PATH}/source/f360_circle.cpp
    ${REL_PATH}/source/f360_clear_cluster.cpp
    ${REL_PATH}/source/f360_clear_det_assoc_obj_props.cpp
    ${REL_PATH}/source/f360_clear_object_track.cpp
    ${REL_PATH}/source/f360_clusters_preprocessing.cpp
    ${REL_PATH}/source/f360_convert_object_prev_vcs_to_current_vcs.cpp
    ${REL_PATH}/source/f360_convert_tcs_posn_to_vcs_posn.cpp
    ${REL_PATH}/source/f360_convert_vcs_posn_to_tcs_posn.cpp
    ${REL_PATH}/source/f360_define_dead_zone.cpp
    ${REL_PATH}/source/f360_define_simplified_dead_zone.cpp
    ${REL_PATH}/source/f360_find_detection_inliers.cpp
    ${REL_PATH}/source/f360_find_closest_valid_sep_on_given_side.cpp
    ${REL_PATH}/source/f360_get_edge_tcs_start_and_end_point.cpp
    ${REL_PATH}/source/f360_get_track_bbox_in_vcs.cpp
    ${REL_PATH}/source/f360_intersections.cpp
    ${REL_PATH}/source/f360_kill_cluster.cpp
    ${REL_PATH}/source/f360_kill_obj_trk.cpp
    ${REL_PATH}/source/f360_math_func.cpp
    ${REL_PATH}/source/f360_norm_heading_angle.cpp
    ${REL_PATH}/source/f360_point.cpp
    ${REL_PATH}/source/f360_push_reduced_id.cpp
    ${REL_PATH}/source/f360_random_number_generation.cpp
    ${REL_PATH}/source/f360_range_rates.cpp
    ${REL_PATH}/source/f360_rectangle.cpp
    ${REL_PATH}/source/f360_rotate_state_covariance_matrix.cpp
    ${REL_PATH}/source/f360_sanity_check.cpp
    ${REL_PATH}/source/f360_handle_spd_and_acc_when_stopping.cpp
    ${REL_PATH}/source/f360_sort_priority.cpp
    ${REL_PATH}/source/f360_sorted_clusters_mgmt.cpp
    ${REL_PATH}/source/f360_sorted_tracks_mgmt.cpp
    ${REL_PATH}/source/f360_statistical_tests.cpp
    ${REL_PATH}/source/f360_terminate_clusters.cpp
    ${REL_PATH}/source/f360_try_to_dealiase_range_rate.cpp
    ${REL_PATH}/source/f360_vcs_long_sorted_dets_support_functions.cpp
    ${REL_PATH}/source/f360_vector.cpp
    ${REL_PATH}/source/f360_visibility_info.cpp
    ${REL_PATH}/source/f360_allocate_id_for_initialized_object.cpp
    ${REL_PATH}/source/f360_angle.cpp
    ${REL_PATH}/source/f360_polygon.cpp
    ${REL_PATH}/source/f360_line.cpp
    ${REL_PATH}/source/f360_object_track.cpp
    ${REL_PATH}/source/f360_check_if_objects_can_overlap_significantly.cpp
    ${REL_PATH}/source/f360_cluster_detection_downselection.cpp
)

set(SRC ${SRC} ${SRC_LOCAL})
