FUNCTION(math_library_generate_mak)
OPTION(MLMathLibrary_GENERATE_MAKE "Generate *.mak and _lnk files for the MathLibrary" On)
IF(MLMathLibrary_GENERATE_MAKE)
	# Since the MathLibrary folder structure is very simple it makes no sense to
	# automatically generate the *.mak files.
	# Generate the linker files only.

	set(LNK_FOLDER ${CMAKE_CURRENT_SOURCE_DIR}/../ml_core/_lnk)

	GET_TARGET_PROPERTY(MLMathLibrary_SOURCES MLMathLibrary SOURCES)
	SET(MLMathLibrary_SOURCE_FILE_NAMES "")
	FOREACH(MLMathLibrary_SOURCE ${MLMathLibrary_SOURCES})
		get_filename_component(MLMathLibrary_SOURCE_FILE_EXT "${MLMathLibrary_SOURCE}" EXT)
		IF(MLMathLibrary_SOURCE_FILE_EXT STREQUAL ".c")
			get_filename_component(MLMathLibrary_SOURCE_FILE_NAME "${MLMathLibrary_SOURCE}" NAME_WE)
			LIST(APPEND MLMathLibrary_SOURCE_FILE_NAMES ${MLMathLibrary_SOURCE_FILE_NAME})
		ENDIF()
	ENDFOREACH()

	SET(MLMathLibrary_BSS ${MLMathLibrary_SOURCE_FILE_NAMES})
	LIST(TRANSFORM MLMathLibrary_BSS APPEND ".o (.bss)")
	list(JOIN MLMathLibrary_BSS "\n" MLMathLibrary_BSS)
	SET(MLMathLibrary_BSS_FILE "${LNK_FOLDER}/core2_sharedtoolbox_bss.lcf")
	FILE(WRITE ${MLMathLibrary_BSS_FILE} "/********************************************************************\n")
	FILE(APPEND ${MLMathLibrary_BSS_FILE} "* Copyright 2021 Aptiv, All Rights Reserved.\n")
	FILE(APPEND ${MLMathLibrary_BSS_FILE} "********************************************************************/\n")
	FILE(APPEND ${MLMathLibrary_BSS_FILE} "\n")
	FILE(APPEND ${MLMathLibrary_BSS_FILE} ${MLMathLibrary_BSS})

	SET(MLMathLibrary_DATA ${MLMathLibrary_SOURCE_FILE_NAMES})
	LIST(TRANSFORM MLMathLibrary_DATA APPEND ".o (.data)")
	list(JOIN MLMathLibrary_DATA "\n" MLMathLibrary_DATA)
	SET(MLMathLibrary_DATA_FILE "${LNK_FOLDER}/core2_sharedtoolbox_data.lcf")
	FILE(WRITE ${MLMathLibrary_DATA_FILE} "/********************************************************************\n")
	FILE(APPEND ${MLMathLibrary_DATA_FILE} "* Copyright 2021 Aptiv, All Rights Reserved.\n")
	FILE(APPEND ${MLMathLibrary_DATA_FILE} "********************************************************************/\n")
	FILE(APPEND ${MLMathLibrary_DATA_FILE} "\n")
	FILE(APPEND ${MLMathLibrary_DATA_FILE} ${MLMathLibrary_DATA})

	SET(MLMathLibrary_TXT ${MLMathLibrary_SOURCE_FILE_NAMES})
	LIST(TRANSFORM MLMathLibrary_TXT APPEND ".o (.text_vle)")
	list(JOIN MLMathLibrary_TXT "\n" MLMathLibrary_TXT)
	SET(MLMathLibrary_TXT_FILE "${LNK_FOLDER}/core2_sharedtoolbox_txt.lcf")
	FILE(WRITE ${MLMathLibrary_TXT_FILE} "/********************************************************************\n")
	FILE(APPEND ${MLMathLibrary_TXT_FILE} "* Copyright 2021 Aptiv, All Rights Reserved.\n")
	FILE(APPEND ${MLMathLibrary_TXT_FILE} "********************************************************************/\n")
	FILE(APPEND ${MLMathLibrary_TXT_FILE} "\n")
	FILE(APPEND ${MLMathLibrary_TXT_FILE} ${MLMathLibrary_TXT})
ENDIF()
ENDFUNCTION()
