repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.1
  hooks:
  - id: clang-format
    name: format C code
    types_or: [c++, c]
    additional_dependencies: [--trusted-host, pypi.org, --trusted-host, pypi.python.org, --trusted-host, files.pythonhosted.org]
    exclude: |
      (?x)^(
        common/support/ti/.*     | # TI support libraries - These are application dependencies provided by TI.
        common/ti/.*             | # TI drivers and utilities - Provided by TI.
      )$
-   repo: https://github.com/Warchant/pre-commit-buildifier
    rev: 0.0.2
    hooks:
    -   id: buildifier
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-merge-conflict
    additional_dependencies: [--trusted-host, pypi.org, --trusted-host, pypi.python.org, --trusted-host, files.pythonhosted.org]
  - id: end-of-file-fixer
    additional_dependencies: [--trusted-host, pypi.org, --trusted-host, pypi.python.org, --trusted-host, files.pythonhosted.org]
    # types_or: [c++, c]
    exclude: |
      (?x)^(
          .*html                                                    | # HTML files
          .*url                                                     | # URL files
      )$
  - id: trailing-whitespace
    additional_dependencies: [--trusted-host, pypi.org, --trusted-host, pypi.python.org, --trusted-host, files.pythonhosted.org]
    # types_or: [c++, c]
    exclude: |
      (?x)^(
          .*html                                                    | # HTML files
          .*url                                                     | # URL files
      )$
  - id: check-shebang-scripts-are-executable
    additional_dependencies: [--trusted-host, pypi.org, --trusted-host, pypi.python.org, --trusted-host, files.pythonhosted.org]
  - id: check-executables-have-shebangs
    additional_dependencies: [--trusted-host, pypi.org, --trusted-host, pypi.python.org, --trusted-host, files.pythonhosted.org]
- repo: https://github.com/psf/black
  rev: 22.8.0
  hooks:
  - id: black
    name: "black: format python"
    args: [--config, tools/preCommit/pyproject.toml]
    exclude: |
      (?x)^(
        software/app/mss/networking/enet/core/tools/.*  | # Enet Tools Dir
        tools/python/uniflash/uart_uniflash.py          | # Exclude uart_uniflash.py, since this is delivered by Ti
      )$
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    name: "flake8: lint python"
    args: [--config, tools/preCommit/f8_python.ini]
    types: [python]
    additional_dependencies: [flake8-docstrings, flake8-bugbear, flake8-builtins, flake8-comprehensions]
    exclude: |
      (?x)^(
        .*__init__.py                                   | # Ignore __init__.py files
      )$
  - id: flake8
    name: "flake8: lint bazel"
    args: [--config, tools/preCommit/f8_bazel.ini]
    types: [bazel]
    additional_dependencies: [flake8-docstrings]
