[flake8]
#E251 - unexpected spaces around keyword / parameter equals: rule attributes not known in python.
#E302 - expected 2 blank lines, found 1
#E305 - expected 2 blank lines after class or function definition, found 1
#F821 - undefined name: load statements are not known in python.
#D400 - First line should end with a period: conflicting with Stardoc.
#D100 - Missing docstring in public module: in Build Files it is not needed to define for each rule a docstring.
#D207 - the doc is under-intenDed
#E721 - do not compare types, use 'isinstance()': not supported by Starlark
#W504 - line break after binary operator
#E131 - continuation line unaligned for hanging indent
#E711 - Comparison to None should be 'cond is None:': 'is' is not supported in .bzl files
ignore=E251,E302,E305,F821,D400,D100,D207,E721,W504,E131,E711
max-line-length=320
