from pathlib import Path
from typing import Iterator
import logging

from .periodic_message import PeriodicMessage

logger = logging.getLogger(__name__)


def generate_setTimer(periodic_messages: list[PeriodicMessage]) -> Iterator[str]:
    """
    Method to create the set timer functions of the capl script.

    Args:
        periodic_messages: list of periodic messages defined by user that contains
            all the information regarding the messages.

    Yields:
        CAPL lines of the set_timer functions.
    """
    for message in periodic_messages:
        if type(message.id) == str:
            yield f"void sqts_set_period_{message.id}(long duration)"
            yield "{"
            yield f"  setTimer({message.id}_timer, duration);"
            yield "}"

    yield "/* Autogenerated CAPL script via capl_generation.py */"


def generate_periodic_trans(periodic_messages: list[PeriodicMessage]) -> Iterator[str]:
    """
    Method to create the periodic transmition functions of the capl script.

    Args:
        periodic_messages: list of periodic messages defined by user that contains
            all the information regarding the messages.

    Yields:
        CAPL lines of the start and stop stransmission functions.
    """
    for message in periodic_messages:
        if type(message.id) == str:
            yield f"void sqts_start_{message.id}()"
            yield "{"
            yield f"    active_{message.id} = 1;"
            yield "}"
            yield f"void sqts_stop_{message.id}()"
            yield "{"
            yield f"    active_{message.id} = 0;"
            yield "}"


def generate_on_timer(periodic_messages: list[PeriodicMessage]) -> Iterator[str]:
    """
    Method to create the on timer functions of the capl script.

    Args:
        periodic_messages: list of periodic messages defined by user that contains
            all the information regarding the messages.

    Yields:
        CAPL lines of the on timer events.
    """
    for message in periodic_messages:
        if type(message.id) == str:
            yield f"on timer {message.id}_timer"
            yield "{"
            yield f"  if(active_{message.id} == 1)"
            yield "   {"
            yield f"      output(msg_{message.id});"
            yield "   }"
            yield "}"


def generate_onstart(periodic_messages: list[PeriodicMessage]) -> Iterator[str]:
    """
    Method to create the on start function of the capl script.

    Args:
        periodic_messages: list of periodic messages defined by user that contains
            all the information regarding the messages.

    Yields:
        CAPL lines of the on start event.
    """
    yield "on start"
    yield "{"

    for message in periodic_messages:
        if type(message.id) == str:
            # Set messages to can channel
            yield f"   msg_{message.id}.can = {message.channel};"
            # Setting timers with start delay and periodicity
            yield "   setTimerCyclic(" + message.id + "_timer," + str(message.start_delay_ms) + "," + str(message.period_ms) + ");"
            # For for each message
            yield f"   for(i = 0; i < elCount(data_{message.id}); i++) {{"
            yield f"      msg_{message.id}" + f".Byte(i) = data_{message.id}[i];"
            yield "   }"

    yield "}"


def variables_generator(periodic_messages: list[PeriodicMessage]) -> Iterator[str]:
    """
    Method to create the variables section of the capl script.

    Args:
        periodic_messages: list of periodic messages defined by user that contains
            all the information regarding the messages.

    Yields:
        CAPL lines of the variables section.
    """
    yield "variables"
    yield "{"

    for message in periodic_messages:
        if type(message.id) == str:
            # timer
            yield "   mstimer " + message.id + "_timer;"
            # message
            yield "   message " + message.id + " msg_" + message.id + ";"
            # flag
            yield "   int active_" + message.id + " = 1;"
            data_str = ','.join([hex(b) for b in message.data])
            # bytes content
            yield "   byte data_" + message.id + f"[{len(message.data)}] = {{" + data_str + "};"

    yield "   int i;"
    yield "}"


def generate_capl_script(filename: Path, periodic_messages: list[PeriodicMessage]) -> None:
    """
    Method that calls all the other methods required to generate the whole capl script.

    Args:
        filename: The filename anf path where the new capl script will be saved.
        periodic_messages: list of periodic messages defined by user that contains
            all the information regarding the messages.
    """
    logger.debug(f'Generating {filename.absolute()} CAPL script to send periodic messages...')
    with open(filename, "w") as new:
        for line in ["includes", "{", "", "}"]:
            print(line, file=new)

        for line in variables_generator(periodic_messages):
            print(line, file=new)

        for line in generate_onstart(periodic_messages):
            print(line, file=new)

        for line in generate_on_timer(periodic_messages):
            print(line, file=new)

        for line in generate_periodic_trans(periodic_messages):
            print(line, file=new)

        for line in generate_setTimer(periodic_messages):
            print(line, file=new)

    logger.debug('CAPL script generated.')

###############################################################################
#                               Revision History
###############################################################################
#
# MM/DD/YYYY  Name/
#             Initials    JIRA     Explanation of changes done here.
#    Date        By      AAA-####      Description
# ----------  ---------  --------  ----------------------------------
# 04/10/2023  LACHE       FKU-849   Initial creation
# 05/11/2023  ABPA        FKU-736   Added trace logging.
