/*================================================================================*\
 * Copyright 2022 Aptiv Advanced Safety and User Experience. All rights reserved. *
 * Confidential - Restricted Aptiv information. Do not disclose.                  *
\*================================================================================*/
#ifndef DETECTION_FLT_T_H
#define DETECTION_FLT_T_H

#include "reuse.h"
#include "motion_status_T.h"
#include "GLOBAL_INDEX_T.h"


typedef enum
{
   DET_AZ_CONFIDENCE_HIGH             = (0),
   DET_AZ_CONFIDENCE_MID_HIGH         = (1),
   DET_AZ_CONFIDENCE_MID_LOW          = (2),
   DET_AZ_CONFIDENCE_LOW              = (3),
   DET_AZ_CONFIDENCE_NUMBER_OF_LEVELS = (4)
} Detection_Azimuth_Confidence_T;

/**
 * This structure contains both the raw detection data form the DSP plus a large number of derived quantities and flags which are used throughout the tracker code.
 * \note
 * The data in the structure only applies to a particular scan, it is not carried over from scan to scan.
 */

typedef struct
{
   /** @name Inputs
    * This section contains all Tracker Inputs that have to be filled outside before the Tracker is being called.
    */
   /**@{*/
   float32_T                      amplitude;                    /**< [dBsm] amplitude of detection */

   float32_T                      range;                        /**< [m] range of detection */

   float32_T                      range_sd;                     /**< [m] standard deviation of the range of the detection */

   float32_T                      range_rate_raw;               /**< [m/s] range rate of detection (denoted raw since possibly still aliased) */

   float32_T                      range_rate_raw_sd;            /**< [m/s] standard deviation of the range rate of the detection (denoted raw since possibly still aliased) */

   float32_T                      azimuth_raw;                  /**< [rad] raw azimuth of detection from the sensor before correcting for polarity and alignment */

   float32_T                      azimuth_raw_sd;               /**< [rad] standard deviation of the raw azimuth of detection from the sensor before correcting for polarity and alignment */

   float32_T                      detection_snr;                /**< [dB] SNR of the detection */

   Detection_Azimuth_Confidence_T azimuth_confidence;           /**< confidence of azimuth angle */

   /**
    *  This is a bit field with the following bits:
    *  - Bit 0: This bit is directly accessible as \ref valid_level_bit_valid.     \copydetails valid_level_bit_valid
    *  - Bit 1: This bit is directly accessible as \ref valid_level_bit_hvc        \copydetails valid_level_bit_hvc
    *  - Bit 2: This bit is directly accessible as \ref valid_level_bit_angle_jump \copydetails valid_level_bit_angle_jump
    *  - Bit 3: This bit is directly accessible as \ref valid_level_bit_low_snr    \copydetails valid_level_bit_low_snr
    *  - Bit 4: This bit is directly accessible as \ref valid_level_bit_mixer_bias \copydetails valid_level_bit_mixer_bias
    */
   uint8_t                        valid_level;

   uint8_t                        f_near_target_discrimination; /**< flag indicating that raw signal processing picked up a target in the neighboring bin(small target next to a large target) */
   uint8_t                        f_bi_static;                  /**< flag indicating possible angle jumps due to bi-static phenomenon (similar to angle jumps for SRR3 sensors) */

   /*
    * The super resolution flag can be either set at the tracker input or calculated inside tracker. If signal is not given at input and must be calculated inside the tracker, its result is stored inside
    * DETECTION_TRACKER_INTERNAL_T:f_super_resolution.
    */
   uint8_t                        f_super_resolution;           /**< flag indicating that the detection is derived using super resolution algorithms */
   /**@}*/

   /** @name Outputs
    * This section contains all Tracker Outputs that are being generated by the Tracker and may be used by other functions as well.
    */
   /**@{*/
   float32_T                      azimuth;                     /**< [rad] azimuth of detection in local coordinates (azimuth_raw corrected for polarity and alignment)*/
   float32_T                      cos_azimuth;                 /**< cosine of azimuth*/
   float32_T                      sin_azimuth;                 /**< sine of azimuth */

   float32_T                      x_vcs;                       /**< [m] longitudinal position of detection in VCS coordinates*/
   float32_T                      y_vcs;                       /**< [m] lateral position of detection in VCS coordinates*/
   float32_T                      azimuth_vcs;                 /**< [rad] azimuth of detection in VCS-aligned coordinates (with origin still at sensor) */
   float32_T                      cos_azimuth_vcs;             /**< cosine of azimuth_vcs*/
   float32_T                      sin_azimuth_vcs;             /**< sine of azimuth_vcs*/

   float32_T                      range_rate;                  /**< [m/s] dealiased range rate of detection*/
   float32_T                      range_rate_comp;             /**< [m/s] range rate that would be observed if host was stationary */
   float32_T                      motion_threshold;            /**< [m/s] threshold that was used for motion status determination */
   motion_status_T                motion_status;               /**< available values are STATIONARY (unused), MOVING, and AMBIGUOUS */

   GLOBAL_INDEX_T                 gidx;                        /**< globally unique id across all sets of detections*/
   int8_t                         id;                          /**< unique id number */

   int8_t                         assigned_obj_idx;            /**< idx of associated object (-1 indicates no associated object)*/
   int8_t                         indirectly_assigned_obj_idx; /**< idx of indirectly (through tracklet) associated object (-1 indicates no bounding object)  */
   int8_t                         in_bounds_of_obj_idx;        /**< idx of bounding object (-1 indicates no bounding object)  */
#ifndef TRACKER_SUPPRESS_ASSOCIATION_ID_FIELDS_IN_DETECTIONS
   int8_t                         assigned_obj_id;             /**< id of associated object (-1 indicates no associated object) */
   int8_t                         indirectly_assigned_obj_id;  /**< id of indirectly (through tracklet) associated object (-1 indicates no bounding object) */
   int8_t                         in_bounds_of_obj_id;         /**< id of bounding object (-1 indicates no bounding object) */
#endif

   /**
    *  \brief \ref valid_level converted into its bits.
    *  \details If set to FALSE this detection is not to be used.
    * */
   uint8_t         valid_level_bit_valid            : 1;

   /**
    *  \brief \ref valid_level converted into its bits.
    *  \details Host vehicle clutter. This detection is believed to stem from a reflection within the bumper of the host.
    */
   uint8_t         valid_level_bit_hvc              : 1;

   /**
    * \brief \ref valid_level converted into its bits.
    *  \details Angle jump. This detection is believed to have a faulty azimuth angle.
    */
   uint8_t         valid_level_bit_angle_jump       : 1;

   /**
    *  \brief \ref valid_level converted into its bits.
    *   \details Low SNR. This detection has a low signal to noise ratio.
    */
   uint8_t         valid_level_bit_low_snr          : 1;

   /**
    * \brief \ref valid_level converted into its bits.
    *  \details DSP has a threshold for mixer bias. A detection with signal-amplitude below mixer bias threshold
    * will be reported with this flag set to TRUE.
    */
   uint8_t         valid_level_bit_mixer_bias       : 1;

   uint8_t                        f_is_obstructed_detection        : 1; /**< flag indicating if detection is obstructed by a cluttered region */
   uint8_t                        f_valid                          : 1; /**< flag indicating the detection is valid and additional processing should be done with */
   uint8_t                        f_valid_host_veh_clutter         : 1; /**< flag indicating the detection is host vehicle clutter and additional processing should be done with */
   uint8_t                        f_multi_bounce                   : 1; /**< flag indicating that a detection is probably caused by multi-bounce (\sa DETECTION_FLT_T::f_multi_bounce_dealiased may also
                                                                         * be TRUE at the same time)*/
   uint8_t                        f_multi_bounce_dealiased         : 1; /**< flag indicating that a detection is probably caused by range rate aliased multi-bounce (\sa DETECTION_FLT_T::f_multi_bounce
                                                                         * may also be TRUE at the same time) */
   uint8_t                        f_stationary_bounce              : 1; /**< flag indicating that a detection is probably caused by stationary-bounce*/

   uint8_t                        f_apparent_azimuth_error_in_band : 1; /**< flag indicating that the apparent azimuth error is around +/- 20-25 degrees*/
   uint8_t                        f_wheel_spin                     : 1; /**< flag indicating that the detection may have a bad range rate caused by wheel spin*/
   uint8_t                        f_wheel_spin_close_by            : 1; /**< This detection may not be wheel spin but is quite close to a wheel spin detection. This may indicate a faulty range rate
                                                                         * measurement */
   uint8_t                        f_host_water_spray               : 1; /**< flag indicating that the detection may be caused by host water spray*/

   uint8_t                        f_on_trailer_box                 : 1; /**< flag indicating that the detection is believed to be on the trailer box in truck applications. By default, this will be set
                                                                         * to false and is only changed to true if kink angle estimation is active*/

   uint8_t                        f_inside_exclusion_region        : 1; /**< Deprecated, always set to FALSE*/
   /**@}*/
} DETECTION_FLT_T;

#endif

