##########################
### Project definition ###
##########################
cmake_minimum_required(VERSION 4.0)

set(project_name  "STLA_SMALL_VCAN_Extractor")
project(${project_name})

set(STLA_SMALL_VCAN_PROJECT_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}/..")
set(STLA_SMALL_VCAN_COMMON_STRUCTURES "${CMAKE_CURRENT_LIST_DIR}/../../Common_Structures")
set(STLA_SMALL_SRR7P_VCAN_RL_INTERFACEFILES "${CMAKE_CURRENT_LIST_DIR}/../../STLA_SMALL_SRR7P_VCAN_RL_Decoder")
set(STLA_SMALL_SRR7P_VCAN_RR_INTERFACEFILES "${CMAKE_CURRENT_LIST_DIR}/../../STLA_SMALL_SRR7P_VCAN_RR_Decoder")
set(STLA_SMALL_FLR7_VCAN_INTERFACEFILES "${CMAKE_CURRENT_LIST_DIR}/../../STLA_SMALL_FLR7_VCAN_Decoder")

set(SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/Include/STLA_SMALL_SRR7P_VcanDecoderRL.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/Source/STLA_SMALL_SRR7P_VcanDecoderRL.cpp")

list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/Include/STLA_SMALL_SRR7P_VcanDecoderRR.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/Source/STLA_SMALL_SRR7P_VcanDecoderRR.cpp")


list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/Include/STLA_SMALL_FLR7_VcanDecoderFC.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/Source/STLA_SMALL_FLR7_VcanDecoderFC.cpp")


list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RL/Source/STLA_SMALL_SRR7P_VcanRLBase.cpp")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RL/Source/STLA_SMALL_SRR7P_VcanRLBase_V2.cpp")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RL/Include/STLA_SMALL_SRR7P_VcanBaseRL.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RL/Include/STLA_SMALL_SRR7P_VcanBaseRL_V2.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RL/Include/STLA_SMALL_SRR7P_VcanRLBase.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RL/Include/STLA_SMALL_SRR7P_VcanRLBase_V2.h")

list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RR/Source/STLA_SMALL_SRR7P_VcanRRBase.cpp")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RR/Source/STLA_SMALL_SRR7P_VcanRRBase_V2.cpp")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RR/Include/STLA_SMALL_SRR7P_VcanBaseRR.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RR/Include/STLA_SMALL_SRR7P_VcanBaseRR_V2.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RR/Include/STLA_SMALL_SRR7P_VcanRRBase.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RR/Include/STLA_SMALL_SRR7P_VcanRRBase_V2.h")


list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_FLR7_VCAN_FC/Source/STLA_SMALL_FLR7_VcanFCBase.cpp")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_FLR7_VCAN_FC/Source/STLA_SMALL_FLR7_VcanFCBase_V2.cpp")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_FLR7_VCAN_FC/Include/STLA_SMALL_FLR7_VcanBaseFC.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_FLR7_VCAN_FC/Include/STLA_SMALL_FLR7_VcanBaseFC_V2.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_FLR7_VCAN_FC/Include/STLA_SMALL_FLR7_VcanFCBase.h")
list(APPEND SOURCES "${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_FLR7_VCAN_FC/Include/STLA_SMALL_FLR7_VcanFCBase_V2.h")

source_group(TREE ${STLA_SMALL_VCAN_PROJECT_ROOT_PATH} FILES ${SOURCES})

set(target_name ${project_name})
add_library(${target_name} STATIC "")

#link libraries
target_link_libraries (${target_name} Mdf_Log)
target_link_libraries(${target_name} CrossPlatform)

target_include_directories(${target_name} PUBLIC ${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RL/Include)
target_include_directories(${target_name} PUBLIC ${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_SRR7P_VCAN_RR/Include)
target_include_directories(${target_name} PUBLIC ${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/STLA_SMALL_FLR7_VCAN_FC/Include)


target_include_directories(${target_name} PUBLIC ${STLA_SMALL_VCAN_PROJECT_ROOT_PATH}/Include)

target_include_directories(${target_name} PUBLIC ${BORDNET_DECODER_PROJ})
target_include_directories(${target_name} PUBLIC ${STLA_SMALL_VCAN_COMMON_STRUCTURES})
target_include_directories(${target_name} PUBLIC ${STLA_SMALL_SRR7P_VCAN_RL_INTERFACEFILES})
target_include_directories(${target_name} PUBLIC ${STLA_SMALL_SRR7P_VCAN_RR_INTERFACEFILES})
target_include_directories(${target_name} PUBLIC ${STLA_SMALL_FLR7_VCAN_INTERFACEFILES})

target_sources(${target_name} PRIVATE ${SOURCES})

#link include directories
target_include_directories(${target_name} PUBLIC ${COMMON_INC})
target_include_directories(${target_name} PRIVATE ${COMMON_INC}/pugixml)

if(OUTPUT_PATH)
set_target_properties(${target_name} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												ARCHIVE_OUTPUT_DIRECTORY "${OUTPUT_PATH}") 				
endif(OUTPUT_PATH)

# Structure Alignment
if(MSVC)
	if(${CMAKE_GENERATOR} STREQUAL "Visual Studio 16 2019")
		target_compile_definitions(${project_name} PRIVATE  WINDOWS_IGNORE_PACKING_MISMATCH) 
	endif()
endif(MSVC)

# Multi Byte Character Set
if(MSVC)
	target_compile_definitions(${target_name} PRIVATE _MBCS _WIN_PLATFORM) 
endif(MSVC)


if(UNIX)
	if(BUILD_FOR_32_BIT)
		set_target_properties(${target_name} PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
	endif(BUILD_FOR_32_BIT)

	#For Debugging in Linux...
	target_compile_options(${target_name} PRIVATE "$<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:-g>")

endif(UNIX)