package(default_visibility = ["//visibility:public"])

cc_library(
    includes = ["."],
    name = "SIL_Library",
    hdrs = [
        "Radar_Config.h",
        "Tracker_Wrapper.h",
    ],
    strip_include_prefix = "",
)
