cmake_minimum_required(VERSION 4.0)

set(project_name "BMWL2_SOMEIP_Decoder_Wrapper")
project(${project_name})

set(target_name ${project_name})

add_library(${target_name} STATIC "")


set(PRJ_ROOT_PATH "${BMWL2_SOMEIP_DECODER_WRAPPER_PROJ}")
set(SOURCE_PATH "${PRJ_ROOT_PATH}/Source")
set(INCLUDE_PATH "${PRJ_ROOT_PATH}/Include")
set(INCLUDE_INTERFACE_PATH "${PRJ_ROOT_PATH}/../BMWL2_SRR7P_SOMEIP_Decoder")
set(INCLUDE_INTERFACE_PATH "${PRJ_ROOT_PATH}/../BMWL2_IPFFAR_SOMEIP_Decoder")
set(INCLUDE_INTERFACE_PATH "${PRJ_ROOT_PATH}/../BMWL2_FLR7_SOMEIP_Decoder")
set(INCLUDE_INTERFACE_PATH "${PRJ_ROOT_PATH}/../Utility")
set(COMMON_STRUCTURES_PATH "${PRJ_ROOT_PATH}/../Common_Structures")

list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_Decoder.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_Decoder.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_Decoder.cpp")
#list(APPEND SOURCE_FILES "${SOURCE_PATH}/Utility.cpp")


list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIPBase.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I250.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I290.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I330.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I360.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I380.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I390.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I420.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I430.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIPBase.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I290.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I330.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I360.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I380.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I390.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I420.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I430.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIPBase.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I290.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I330.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I360.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I380.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I390.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I420.cpp")
list(APPEND SOURCE_FILES "${SOURCE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I430.cpp")

list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIPBase.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIPBase.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIPBase.h")
#list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Utility.h")

list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_Decoder.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_Decoder.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_Decoder.h")

list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I250.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I290.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I330.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I360.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I380.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I390.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I420.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_SRR7P_SOMEIP_I430.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I290.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I330.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I360.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I380.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I390.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I420.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_FRL7_SOMEIP_I430.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I290.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I330.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I360.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I380.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I390.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I420.h")
list(APPEND SOURCE_FILES "${INCLUDE_PATH}/Wrapper_BMWL2_IPFFAR_SOMEIP_I430.h")

#link include directories
target_include_directories(${target_name} PUBLIC ${COMMON_INC})
target_include_directories(${target_name} PRIVATE ${COMMON_INC}/pugixml)

target_sources(${target_name} PRIVATE ${SOURCE_FILES})
target_include_directories(${target_name} PRIVATE ${INCLUDE_PATH})
target_include_directories(${target_name} PRIVATE ${BORDNET_DECODER_PROJ})
target_include_directories(${target_name} PUBLIC ${INCLUDE_INTERFACE_PATH})
target_include_directories(${target_name} PUBLIC ${COMMON_STRUCTURES_PATH})

target_link_libraries(${target_name} CrossPlatform)
if(OUTPUT_PATH)
set_target_properties(${target_name} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_PATH}"
												ARCHIVE_OUTPUT_DIRECTORY "${OUTPUT_PATH}") 				
endif(OUTPUT_PATH)

# Structure Alignment
if(MSVC)
	if(${CMAKE_GENERATOR} STREQUAL "Visual Studio 16 2019")
		target_compile_definitions(${project_name} PRIVATE  WINDOWS_IGNORE_PACKING_MISMATCH) 
	endif()
endif(MSVC)

if(MSVC)
	target_compile_definitions(${target_name} PRIVATE  _WIN_PLATFORM) 
endif(MSVC)
if(UNIX)
	if(BUILD_FOR_32_BIT)
		set_target_properties(${target_name} PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
	endif(BUILD_FOR_32_BIT)
	
	add_definitions(${CMAKE_CFLAGS} "-fPIC")

	#For Debugging in Linux...
	target_compile_options(${target_name} PRIVATE "$<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:-g>")
	
	

	find_package (Threads)
	target_link_libraries (${target_name} ${CMAKE_THREAD_LIBS_INIT})

endif(UNIX)

