/** \file
 * This file contains unit tests for content of f360_random_number_generation.cpp file
 */

#include "f360_random_number_generation.h"

#include <array>
#include <utility>
#include <cstdio>
#include <cmath>

#include <CppUTest/TestHarness.h>

using namespace f360_variant_A;

/** \defgroup  f360_random_number_generation
 *  @{
 */

 /** \brief
  * Tests random generation of numbers.
  */
TEST_GROUP(f360_random_number_generation)
{};

/** \purpose
 * Verify that numbers sampled from the random generator with different seeds are different.
 * Since the random number generator is pseudorandom, it's enough to check that for two seeds the
 * first drawn number is different.
 * \req
 * NA
 */
TEST(f360_random_number_generation, Generate_Random_Number_different_samples_for_different_seeds)
{
   /** \action
    * - Set the random seed
    * - Draw a number
    * - Set a different seed
    * - Draw another number
    */
   Init_Random_Number_Generator(1);
   uint32_t draw_1 = Generate_Random_Number();
   Init_Random_Number_Generator(0);
   uint32_t draw_2 = Generate_Random_Number();

   /** \result
    * The drawn numbers must be different.
    */
   char text_failure[100];
   sprintf(text_failure, "%d and %d are not different\n", draw_1, draw_2);
   CHECK_TRUE_TEXT(draw_1 != draw_2, text_failure);
}

/** \purpose
 * Verify that numbers sampled from the random generator with the same seeds are the same.
 * \req
 * NA
 */
TEST(f360_random_number_generation, Generate_Random_Number_same_sample_for_same_seed)
{
   /** \precond
    * - Random number generator seed = 1
    * - Number of draws = 1e5
    */
   uint32_t seed = 1;
   const static size_t num_of_draws = static_cast<size_t>(1e5);

   /** \action
    * - Set random number generator seed.
    * - Draw random numbers and store them in an array.
    * - Set the seed back to the initial value.
    * - Draw random numbers and store them in another array.
    */
   Init_Random_Number_Generator(seed);
   std::array<uint32_t, num_of_draws> draws_0;
   for (size_t i = 0; i < num_of_draws; i++)
   {
      draws_0[i] = Generate_Random_Number();
   }

   Init_Random_Number_Generator(seed);
   std::array<uint32_t, num_of_draws> draws_1;
   for (size_t i = 0; i < num_of_draws; i++)
   {
      draws_1[i] = Generate_Random_Number();
   }

   /** \result
    * The arrays of random numbers must match exactly.
    */
   char text_failure[100];
   bool are_equal = std::equal(std::begin(draws_0), std::end(draws_0), std::begin(draws_1));
   sprintf(text_failure, "samples generated by the same seed are different\n");
   CHECK_TRUE_TEXT(are_equal, text_failure);
}

/** \purpose
 * Verify indices sampled from the random generator with the same seed are the same.
 * \req
 * NA
 */
TEST(f360_random_number_generation, Generate_Random_Index_same_sample_for_same_seed)
{
   /** \precond
    * - Random number generator seed = 1
    * - Maximum index to draw = 10
    * - Number of draws = 1e5
    */
   uint32_t seed = 1;
   uint32_t max_index = 10;
   const static size_t num_of_draws = static_cast<size_t>(1e5);

   /** \action
    * - Set random number generator seed.
    * - Draw random indices and store them in an array.
    * - Set the seed back to the initial value.
    * - Draw random indices and store them in another array.
    */
   Init_Random_Number_Generator(seed);
   std::array<uint32_t, num_of_draws> draws_0;
   for (size_t i = 0; i < num_of_draws; i++)
   {
      draws_0[i] = Generate_Random_Index(max_index);
   }

   Init_Random_Number_Generator(seed);
   std::array<uint32_t, num_of_draws> draws_1;
   for (size_t i = 0; i < num_of_draws; i++)
   {
      draws_1[i] = Generate_Random_Index(max_index);
   }

   /** \result
    * The arrays of random indices must match exactly.
    */
   char text_failure[100];
   bool are_equal = std::equal(std::begin(draws_0), std::end(draws_0), std::begin(draws_1));
   sprintf(text_failure, "samples generated by the same seed are different\n");
   CHECK_TRUE_TEXT(are_equal, text_failure);
}

/** \purpose
 * Verify indices sampled from the random generator are within the expected bounds.
 * Seed = 1.
 * \req
 * NA
 */
TEST(f360_random_number_generation, Generate_Random_Index_range_seed_1)
{
   /** \precond
    * - Maximum index to draw (max_index) = 10
    * - Number of draws = 1e5
    * - Initialize random number generator with seed = 1
    */
   uint32_t max_index = 10;
   const static size_t num_of_draws = static_cast<size_t>(1e5);
   Init_Random_Number_Generator(1);

   uint32_t value = 0;
   char text_failure[100];
   for (size_t i = 0; i < num_of_draws; i++)
   {
      /** \action
       * Draw from the uniform distribution
       */
      value = Generate_Random_Index(max_index);

      /** \result
       * The drawn value is within the interval [0, max_index].
       */
      sprintf(text_failure, "value (%d) is not within the expected bounds: [%d, %d]\n", value, 0, max_index);
      CHECK_TRUE_TEXT(max_index >= value, text_failure);
   }
}

/** \purpose
 * Verify indices sampled from the random generator are within the expected bounds.
 * Seed = 0
 * \req
 * NA
 */
TEST(f360_random_number_generation, Generate_Random_Index_range_seed_0)
{
   /** \precond
    * - Maximum index to draw (max_index) = 100
    * - Number of draws = 1e5
    * - Initialize random number generator with seed = 0
    */
   uint32_t max_index = 100;
   const static size_t num_of_draws = static_cast<size_t>(1e5);
   Init_Random_Number_Generator(0);

   uint32_t value = 0;
   char text_failure[100];
   for (size_t i = 0; i < num_of_draws; i++)
   {
      /** \action
       * Draw from the uniform distribution
       */
      value = Generate_Random_Index(max_index);

      /** \result
       * The drawn value is within the interval [0, max_index].
       */
      sprintf(text_failure, "value (%d) is not within the expected bounds: [%d, %d]\n", value, 0, max_index);
      CHECK_TRUE_TEXT(max_index >= value, text_failure);
   }
}

/** \purpose
 * Verify the mean and variance of a large sample of random indices.
 * \req
 * NA
 */
TEST(f360_random_number_generation, Generate_Random_Index_moments)
{
   /** \precond
    * - Maximum index to draw (max_index) = 10
    * - Number of draws = 1e5
    * - Initialize random number generator with seed = 1
    */
   uint32_t max_index = 10;
   const static size_t num_of_draws = static_cast<size_t>(1e5);
   Init_Random_Number_Generator(1);

   /** \action
    * - Draw a large sample of random indices.
    * - Compute sample mean.
    * - Compute sample variance.
    */
   uint32_t sum = 0;
   std::array<uint32_t, num_of_draws> draws;
   for (size_t i = 0; i < draws.size(); i++)
   {
      draws[i] = Generate_Random_Index(max_index);
      sum += draws[i];
   }

   // Compute mean
   float32_t mean = static_cast<float32_t>(sum) / static_cast<float32_t>(draws.size());
   
   // Compute variance
   float32_t diff_sq = 0.0f;
   for (auto draw : draws)
   {
      diff_sq += std::pow(draw - mean, 2.0f);
   }   
   float32_t variance = diff_sq / static_cast<float32_t>(draws.size() - 1);

   /** \result
    * The sample mean and variance must not exceed a difference of 1% from the expected mean and variance.
    * - Expected mean: max_index / 2
    * - Expected variance: ((max_index + 1)^2 - 1) / 12
    */
   float32_t expected_mean = max_index / 2.0f;
   float32_t expected_var = (static_cast<float32_t>(std::pow(max_index + 1, 2.0f) - 1)) / 12.0f;
   float32_t threshold_ratio = 0.01f;
   DOUBLES_EQUAL_TEXT(expected_mean, mean, threshold_ratio * expected_mean, "sample mean is not within the allowed range\n");
   DOUBLES_EQUAL_TEXT(expected_var, variance, threshold_ratio * expected_var, "sample variance is not within the allowed range\n");
}
/** @}*/
