#ifndef DGPS_STREAM_H
#define DGPS_STREAM_H

/********************************************************************************************
* Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
* XML uses version 1 of the base file.
* File Name: DGPS_STREAM
* Created:    27-04-2026     13:17:33
* From XML file: DGPS_STREAM.xml
* Set Description:   Logging Structure/Interface structure 
* Tool Version: 5. 1. 0
* Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

 #ifdef PC_RESIM 
#include <stdio.h>
#endif/*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/

/* Macros For ARRAY Sizes */
#define DGPS_TARGET_COUNT   (1U)
#define DGPS_STREAM_NUMBER   (94U)

/*Macro For Structure Version*/
#define DGPS_STREAM_VERSION    (1U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_DGPS_STREAM    (376U)

/*Macro for size of Sub structures*/
#define SIZE_OF_DC_Latitude_Longitude    (16U)
#define SIZE_OF_DC_Target_Latitude_Longitude    (16U)
#define SIZE_OF_DC_Pos_Local    (8U)
#define SIZE_OF_DC_Range_Local    (8U)
#define SIZE_OF_DC_Vel_Yaw_Local    (16U)
#define SIZE_OF_DC_Rate_Vehicle    (12U)
#define SIZE_OF_DC_Range_Foward    (12U)
#define SIZE_OF_DC_Range_Lateral    (12U)
#define SIZE_OF_DC_Heading_Pitch_Roll    (12U)
#define SIZE_OF_DC_Range_Vehicle    (12U)
#define SIZE_OF_DC_Veh_Dimension    (12U)
#define SIZE_OF_DC_Velocity    (16U)
#define SIZE_OF_DC_Target_Velocity    (16U)
#define SIZE_OF_DC_Velocity_Level    (8U)
#define SIZE_OF_DC_Rate_Level    (12U)
#define SIZE_OF_DC_Altitude    (4U)
#define SIZE_OF_DC_Accel_Vehicle    (12U)
#define SIZE_OF_DC_Accel_Level    (16U)
#define SIZE_OF_DC_Date_Time    (32U)
#define SIZE_OF_DC_GPS_Status    (16U)
#define SIZE_OF_DC_DGPS_Data    (376U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_Latitude_Longitude_Tag   /*Offset Start byte of the Structure DC_Latitude_Longitude is 0 bytes*/
{
   double   Poslat;
   double   PosLon;
} DC_Latitude_Longitude_T;

typedef struct DC_Target_Latitude_Longitude_Tag   /*Offset Start byte of the Structure DC_Target_Latitude_Longitude is 16 bytes*/
{
   double   Poslat;
   double   PosLon;
} DC_Target_Latitude_Longitude_T;

typedef struct DC_Pos_Local_Tag   /*Offset Start byte of the Structure DC_Pos_Local is 32 bytes*/
{
   float32_t   POS_LOCALX;
   float32_t   POS_LOCALY;
} DC_Pos_Local_T;

typedef struct DC_Range_Local_Tag   /*Offset Start byte of the Structure DC_Range_Local is 40 bytes*/
{
   float32_t   RANGE_LOCAL_DELTAX;
   float32_t   RANGE_LOCAL_DELTAY;
} DC_Range_Local_T;

typedef struct DC_Vel_Yaw_Local_Tag   /*Offset Start byte of the Structure DC_Vel_Yaw_Local is 48 bytes*/
{
   float32_t   Vel_Local_X;
   float32_t   Vel_Local_Y;
   float32_t   AngleLocalYaw;
   float32_t   AngleLocalTrack;
} DC_Vel_Yaw_Local_T;

typedef struct DC_Rate_Vehicle_Tag   /*Offset Start byte of the Structure DC_Rate_Vehicle is 64 bytes*/
{
   float32_t   AngRateX;
   float32_t   AngRateY;
   float32_t   AngRateZ;
} DC_Rate_Vehicle_T;

typedef struct DC_Range_Foward_Tag   /*Offset Start byte of the Structure DC_Range_Foward is 76 bytes*/
{
   float32_t   RangePosForward;
   float32_t   RangeVelForward;
   float32_t   RangeTimeToCollisionForward;
} DC_Range_Foward_T;

typedef struct DC_Range_Lateral_Tag   /*Offset Start byte of the Structure DC_Range_Lateral is 88 bytes*/
{
   float32_t   RangePosLateral;
   float32_t   RangeVelLateral;
   float32_t   RangeTimeToCollisionLateral;
} DC_Range_Lateral_T;

typedef struct DC_Heading_Pitch_Roll_Tag   /*Offset Start byte of the Structure DC_Heading_Pitch_Roll is 100 bytes*/
{
   float32_t   AngleHeading;
   float32_t   AnglePitch;
   float32_t   AngleRoll;
} DC_Heading_Pitch_Roll_T;

typedef struct DC_Range_Vehicle_Tag   /*Offset Start byte of the Structure DC_Range_Vehicle is 112 bytes*/
{
   float32_t   RangeTargetVehicleLength;
   float32_t   RangeTargetVehicleWidth;
   float32_t   RangeTargetVehicleNumber;
} DC_Range_Vehicle_T;

typedef struct DC_Veh_Dimension_Tag   /*Offset Start byte of the Structure DC_Veh_Dimension is 124 bytes*/
{
   float32_t   VehicleLength;
   float32_t   VehicleWidth;
   float32_t   VehicleHeight;
} DC_Veh_Dimension_T;

typedef struct DC_Velocity_Tag   /*Offset Start byte of the Structure DC_Velocity is 136 bytes*/
{
   float32_t   VelNorth;
   float32_t   VelEast;
   float32_t   VelDown;
   float32_t   Speed2D;
} DC_Velocity_T;

typedef struct DC_Target_Velocity_Tag   /*Offset Start byte of the Structure DC_Target_Velocity is 152 bytes*/
{
   float32_t   VelNorth;
   float32_t   VelEast;
   float32_t   VelDown;
   float32_t   Speed3D;
} DC_Target_Velocity_T;

typedef struct DC_Velocity_Level_Tag   /*Offset Start byte of the Structure DC_Velocity_Level is 168 bytes*/
{
   float32_t   VelForward;
   float32_t   VelLateral;
} DC_Velocity_Level_T;

typedef struct DC_Rate_Level_Tag   /*Offset Start byte of the Structure DC_Rate_Level is 176 bytes*/
{
   float32_t   AngRateForward;
   float32_t   AngRateLateral;
   float32_t   AngRateDown;
} DC_Rate_Level_T;

typedef struct DC_Altitude_Tag   /*Offset Start byte of the Structure DC_Altitude is 188 bytes*/
{
   float32_t   PosAlt;
} DC_Altitude_T;

typedef struct DC_Accel_Vehicle_Tag   /*Offset Start byte of the Structure DC_Accel_Vehicle is 192 bytes*/
{
   float32_t   Accel_X;
   float32_t   Accel_Y;
   float32_t   Accel_Z;
} DC_Accel_Vehicle_T;

typedef struct DC_Accel_Level_Tag   /*Offset Start byte of the Structure DC_Accel_Level is 204 bytes*/
{
   float32_t   AccelForward;
   float32_t   AccelLateral;
   float32_t   AccelDown;
   float32_t   AccelSlip;
} DC_Accel_Level_T;

typedef struct DC_Date_Time_Tag   /*Offset Start byte of the Structure DC_Date_Time is 220 bytes*/
{
   float32_t   TimeYear;
   float32_t   TimeCentury;
   float32_t   TimeMonth;
   float32_t   TimeDay;
   float32_t   TimeHSecond;
   float32_t   TimeSecond;
   float32_t   TimeMinute;
   float32_t   TimeHour;
} DC_Date_Time_T;

typedef struct DC_GPS_Status_Tag   /*Offset Start byte of the Structure DC_GPS_Status is 252 bytes*/
{
   float32_t   GpsNumSats;
   float32_t   GpsPosMode;
   float32_t   GpsVelMode;
   float32_t   GpsAttMode;
} DC_GPS_Status_T;

typedef struct DC_DGPS_Data_Tag   /*Offset Start byte of the Structure DC_DGPS_Data is 268 bytes*/
{
   DC_Latitude_Longitude_T   Latitude_Longitude_Host;
   DC_Pos_Local_T   Pos_Local;
   DC_Vel_Yaw_Local_T   Vel_Yaw_Local;
   DC_Rate_Vehicle_T   Rate_Vehicle_Host;
   DC_Range_Foward_T   Range_Forward_Host;
   DC_Range_Lateral_T   Range_Lateral_Host;
   DC_Heading_Pitch_Roll_T   Host_Heading_Pitch_Roll;
   DC_Velocity_T   Velocity_Host;
   DC_Velocity_Level_T   Velocity_Level_Host;
   DC_Rate_Level_T   Rate_Level_Host;
   DC_Altitude_T   Altitude_Host;
   DC_Accel_Level_T   Accel_Level_Host;
   DC_Accel_Vehicle_T   Accel_Vehicle_Host;
   DC_Date_Time_T   Date_Time;
   DC_GPS_Status_T   Gps_Status_Host;
   DC_Range_Local_T   Range_Local_Host;
   DC_Veh_Dimension_T   Veh_Dimension_Host;
   DC_Heading_Pitch_Roll_T   Target_Heading_Pitch_Roll[DGPS_TARGET_COUNT];
   DC_Target_Velocity_T   Target_Velocity[DGPS_TARGET_COUNT];
   DC_Velocity_Level_T   Target_Velocity_Level[DGPS_TARGET_COUNT];
   DC_Accel_Level_T   Target_Accel_Level[DGPS_TARGET_COUNT];
   DC_Accel_Vehicle_T   Target_Accel_Vehicle[DGPS_TARGET_COUNT];
   DC_Rate_Vehicle_T   Target_Rate_Vehicle[DGPS_TARGET_COUNT];
   DC_Date_Time_T   Target_Date_Time;
   DC_Altitude_T   Altitude_Target;
   DC_Latitude_Longitude_T   Latitude_Longitude_Target[DGPS_TARGET_COUNT];
   DC_Range_Vehicle_T   Range_Vehicle[DGPS_TARGET_COUNT];
   DC_Rate_Level_T   Target_Rate_Level;
} DC_DGPS_Data_T;

#else

typedef struct DC_Latitude_Longitude_Tag
{
   double   PosLon;
   double   Poslat;
} DC_Latitude_Longitude_T;

typedef struct DC_Target_Latitude_Longitude_Tag
{
   double   PosLon;
   double   Poslat;
} DC_Target_Latitude_Longitude_T;

typedef struct DC_Pos_Local_Tag
{
   float32_t   POS_LOCALY;
   float32_t   POS_LOCALX;
} DC_Pos_Local_T;

typedef struct DC_Range_Local_Tag
{
   float32_t   RANGE_LOCAL_DELTAY;
   float32_t   RANGE_LOCAL_DELTAX;
} DC_Range_Local_T;

typedef struct DC_Vel_Yaw_Local_Tag
{
   float32_t   AngleLocalTrack;
   float32_t   AngleLocalYaw;
   float32_t   Vel_Local_Y;
   float32_t   Vel_Local_X;
} DC_Vel_Yaw_Local_T;

typedef struct DC_Rate_Vehicle_Tag
{
   float32_t   AngRateZ;
   float32_t   AngRateY;
   float32_t   AngRateX;
} DC_Rate_Vehicle_T;

typedef struct DC_Range_Foward_Tag
{
   float32_t   RangeTimeToCollisionForward;
   float32_t   RangeVelForward;
   float32_t   RangePosForward;
} DC_Range_Foward_T;

typedef struct DC_Range_Lateral_Tag
{
   float32_t   RangeTimeToCollisionLateral;
   float32_t   RangeVelLateral;
   float32_t   RangePosLateral;
} DC_Range_Lateral_T;

typedef struct DC_Heading_Pitch_Roll_Tag
{
   float32_t   AngleRoll;
   float32_t   AnglePitch;
   float32_t   AngleHeading;
} DC_Heading_Pitch_Roll_T;

typedef struct DC_Range_Vehicle_Tag
{
   float32_t   RangeTargetVehicleNumber;
   float32_t   RangeTargetVehicleWidth;
   float32_t   RangeTargetVehicleLength;
} DC_Range_Vehicle_T;

typedef struct DC_Veh_Dimension_Tag
{
   float32_t   VehicleHeight;
   float32_t   VehicleWidth;
   float32_t   VehicleLength;
} DC_Veh_Dimension_T;

typedef struct DC_Velocity_Tag
{
   float32_t   Speed2D;
   float32_t   VelDown;
   float32_t   VelEast;
   float32_t   VelNorth;
} DC_Velocity_T;

typedef struct DC_Target_Velocity_Tag
{
   float32_t   Speed3D;
   float32_t   VelDown;
   float32_t   VelEast;
   float32_t   VelNorth;
} DC_Target_Velocity_T;

typedef struct DC_Velocity_Level_Tag
{
   float32_t   VelLateral;
   float32_t   VelForward;
} DC_Velocity_Level_T;

typedef struct DC_Rate_Level_Tag
{
   float32_t   AngRateDown;
   float32_t   AngRateLateral;
   float32_t   AngRateForward;
} DC_Rate_Level_T;

typedef struct DC_Altitude_Tag
{
   float32_t   PosAlt;
} DC_Altitude_T;

typedef struct DC_Accel_Vehicle_Tag
{
   float32_t   Accel_Z;
   float32_t   Accel_Y;
   float32_t   Accel_X;
} DC_Accel_Vehicle_T;

typedef struct DC_Accel_Level_Tag
{
   float32_t   AccelSlip;
   float32_t   AccelDown;
   float32_t   AccelLateral;
   float32_t   AccelForward;
} DC_Accel_Level_T;

typedef struct DC_Date_Time_Tag
{
   float32_t   TimeHour;
   float32_t   TimeMinute;
   float32_t   TimeSecond;
   float32_t   TimeHSecond;
   float32_t   TimeDay;
   float32_t   TimeMonth;
   float32_t   TimeCentury;
   float32_t   TimeYear;
} DC_Date_Time_T;

typedef struct DC_GPS_Status_Tag
{
   float32_t   GpsAttMode;
   float32_t   GpsVelMode;
   float32_t   GpsPosMode;
   float32_t   GpsNumSats;
} DC_GPS_Status_T;

typedef struct DC_DGPS_Data_Tag
{
   DC_Rate_Level_T   Target_Rate_Level;
   DC_Range_Vehicle_T   Range_Vehicle[DGPS_TARGET_COUNT];
   DC_Latitude_Longitude_T   Latitude_Longitude_Target[DGPS_TARGET_COUNT];
   DC_Altitude_T   Altitude_Target;
   DC_Date_Time_T   Target_Date_Time;
   DC_Rate_Vehicle_T   Target_Rate_Vehicle[DGPS_TARGET_COUNT];
   DC_Accel_Vehicle_T   Target_Accel_Vehicle[DGPS_TARGET_COUNT];
   DC_Accel_Level_T   Target_Accel_Level[DGPS_TARGET_COUNT];
   DC_Velocity_Level_T   Target_Velocity_Level[DGPS_TARGET_COUNT];
   DC_Target_Velocity_T   Target_Velocity[DGPS_TARGET_COUNT];
   DC_Heading_Pitch_Roll_T   Target_Heading_Pitch_Roll[DGPS_TARGET_COUNT];
   DC_Veh_Dimension_T   Veh_Dimension_Host;
   DC_Range_Local_T   Range_Local_Host;
   DC_GPS_Status_T   Gps_Status_Host;
   DC_Date_Time_T   Date_Time;
   DC_Accel_Vehicle_T   Accel_Vehicle_Host;
   DC_Accel_Level_T   Accel_Level_Host;
   DC_Altitude_T   Altitude_Host;
   DC_Rate_Level_T   Rate_Level_Host;
   DC_Velocity_Level_T   Velocity_Level_Host;
   DC_Velocity_T   Velocity_Host;
   DC_Heading_Pitch_Roll_T   Host_Heading_Pitch_Roll;
   DC_Range_Lateral_T   Range_Lateral_Host;
   DC_Range_Foward_T   Range_Forward_Host;
   DC_Rate_Vehicle_T   Rate_Vehicle_Host;
   DC_Vel_Yaw_Local_T   Vel_Yaw_Local;
   DC_Pos_Local_T   Pos_Local;
   DC_Latitude_Longitude_T   Latitude_Longitude_Host;
} DC_DGPS_Data_T;

extern void Print_DGPS_STREAM_Traces_Header(FILE* CfilePtr[],DC_DGPS_Data_T* debug);
extern void Print_DGPS_STREAM_Traces_Data(FILE* CfilePtr[],DC_DGPS_Data_T* debug, unsigned int Scan_Index_Self);
extern void Print_DGPS_STREAM_Xml_Traces(FILE* CfilePtr,DC_DGPS_Data_T* debug);
extern void Reverse_Array_DGPS_STREAM(DC_DGPS_Data_T* debug);
extern int Get_DGPS_STREAM_CSV_Split_Files_Num_Count();
#endif/*PC_Resim*/


/*=========================================================================================*
* File Revision History (top to bottom: first revision to last revision)
*==========================================================================================
*
* Date           time        userid    (Description on following lines: SCR #, etc.)
* ----------- -------- --------------------------------------------------------------------
* 27-04-2026     13:17:33    jjyr0p    Do not make any changes it's an auto generated file
*
*=========================================================================================*/


#endif /*DGPS_STREAM_H*/
