#ifndef GT_INPUT_STREAM_H
#define GT_INPUT_STREAM_H

/********************************************************************************************
* Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
* XML uses version 2 of the base file.
* File Name: GT_INPUT_STREAM
* Created:    18-12-2025     11:43:58
* From XML file: GT_INPUT_STREAM.xml
* Set Description:   Logging Structure/Interface structure 
* Tool Version: 5. 1. 0
* Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

 #ifdef PC_RESIM 
#include <stdio.h>
#endif/*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/

/* Macros For ARRAY Sizes */
#define NUMBER_OF_SIMULATED_TRACKS   (1000U)
#define DC_GT_INPUT_STREAM_NUMBER   (93U)

/*Macro For Structure Version*/
#define GT_INPUT_STREAM_VERSION    (2U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_GT_INPUT_STREAM    (84008U)

/*Macro for size of Sub structures*/
#define SIZE_OF_DC_GT_TrackObject    (84U)
#define SIZE_OF_DC_GT_Logging_Hdr    (8U)
#define SIZE_OF_DC_GT_Logging_Data    (84008U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_GT_TrackObject_Tag   /*Offset Start byte of the Structure DC_GT_TrackObject is 0 bytes*/
{
   float32_t   vcs_long_posn;
   float32_t   vcs_lat_posn;
   float32_t   vcs_long_vel;
   float32_t   vcs_lat_vel;
   float32_t   vcs_long_accel;
   float32_t   vcs_lat_accel;
   float32_t   vcs_long_vel_rel;
   float32_t   vcs_lat_vel_rel;
   float32_t   vcs_heading;
   float32_t   iso_long_posn;
   float32_t   iso_lat_posn;
   float32_t   iso_long_vel;
   float32_t   iso_lat_vel;
   float32_t   iso_long_accel;
   float32_t   iso_lat_accel;
   float32_t   iso_long_vel_rel;
   float32_t   iso_lat_vel_rel;
   float32_t   iso_heading;
   float32_t   speed;
   float32_t   length;
   float32_t   width;
} DC_GT_TrackObject_T;

typedef struct DC_GT_Logging_Hdr_Tag   /*Offset Start byte of the Structure DC_GT_Logging_Hdr is 84 bytes*/
{
   uint32_t   Sec_Size;
   uint16_t   Sec_Checksum;
   uint16_t   Sec_Compatibility;
} DC_GT_Logging_Hdr_T;

typedef struct DC_GT_Logging_Data_Tag   /*Offset Start byte of the Structure DC_GT_Logging_Data is 92 bytes*/
{
   DC_GT_TrackObject_T   object[NUMBER_OF_SIMULATED_TRACKS];
   DC_GT_Logging_Hdr_T   Header;
} DC_GT_Logging_Data_T;

#else

typedef struct DC_GT_TrackObject_Tag
{
   float32_t   width;
   float32_t   length;
   float32_t   speed;
   float32_t   iso_heading;
   float32_t   iso_lat_vel_rel;
   float32_t   iso_long_vel_rel;
   float32_t   iso_lat_accel;
   float32_t   iso_long_accel;
   float32_t   iso_lat_vel;
   float32_t   iso_long_vel;
   float32_t   iso_lat_posn;
   float32_t   iso_long_posn;
   float32_t   vcs_heading;
   float32_t   vcs_lat_vel_rel;
   float32_t   vcs_long_vel_rel;
   float32_t   vcs_lat_accel;
   float32_t   vcs_long_accel;
   float32_t   vcs_lat_vel;
   float32_t   vcs_long_vel;
   float32_t   vcs_lat_posn;
   float32_t   vcs_long_posn;
} DC_GT_TrackObject_T;

typedef struct DC_GT_Logging_Hdr_Tag
{
   uint16_t   Sec_Compatibility;
   uint16_t   Sec_Checksum;
   uint32_t   Sec_Size;
} DC_GT_Logging_Hdr_T;

typedef struct DC_GT_Logging_Data_Tag
{
   DC_GT_Logging_Hdr_T   Header;
   DC_GT_TrackObject_T   object[NUMBER_OF_SIMULATED_TRACKS];
} DC_GT_Logging_Data_T;

extern void Print_GT_INPUT_STREAM_Traces_Header(FILE* CfilePtr[],DC_GT_Logging_Data_T* debug);
extern void Print_GT_INPUT_STREAM_Traces_Data(FILE* CfilePtr[],DC_GT_Logging_Data_T* debug, unsigned int Scan_Index_Self);
extern void Print_GT_INPUT_STREAM_Xml_Traces(FILE* CfilePtr,DC_GT_Logging_Data_T* debug);
extern void Reverse_Array_GT_INPUT_STREAM(DC_GT_Logging_Data_T* debug);
extern int Get_GT_INPUT_STREAM_CSV_Split_Files_Num_Count();
#endif/*PC_Resim*/


/*=========================================================================================*
* File Revision History (top to bottom: first revision to last revision)
*==========================================================================================
*
* Date           time        userid    (Description on following lines: SCR #, etc.)
* ----------- -------- --------------------------------------------------------------------
* 18-12-2025     11:43:58    jjyr0p    Do not make any changes it's an auto generated file
*
*=========================================================================================*/


#endif /*GT_INPUT_STREAM_H*/
