#ifndef ROT_ISO_OBJECT_STREAM_H
#define ROT_ISO_OBJECT_STREAM_H

/********************************************************************************************
 * Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
 * XML uses version 1 of the base file.
 * File Name: ROT_ISO_OBJECT_STREAM
 * Created:    07-08-2025     19:09:04
 * From XML file: ROT_ISO_OBJECT_STREAM.xml
 * Set Description:   Logging Structure/Interface structure
 * Tool Version: 5. 1. 0
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

#ifdef PC_RESIM
#include <stdio.h>
#endif /*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/
#include "stream_header.h"

/* Macros For ARRAY Sizes */
#define DC_ROT_ISO_OBJECT_STREAM_NUMBER        (81U)
#define DC_ROT_NUMBER_OF_REDUCED_OBJECT_TRACKS (1000U)
#define NUM_STATE_VARIANCE                     (6U)
#define NUM_STATE_COVARIANCE                   (3U)
#define ISO_ROT_NUM_TOTAL_RADAR_SENSORS        (1U)
#define TWO                                    (2U)
#define THREE                                  (3U)

/*Macro For Structure Version*/
#define ROT_ISO_OBJECT_STREAM_VERSION (1U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_ROT_ISO_OBJECT_STREAM (208072U)

/*Macro for size of Sub structures*/
#define SIZE_OF_Stream_Hdr                                 (16U)
#define SIZE_OF_DC_ROT_ISO_Object_Output                   (208U)
#define SIZE_OF_DC_ROT_Core_Info_Faults_Bit_Field          (4U)
#define SIZE_OF_DC_ROT_Host_Info_Faults_Bit_Field          (4U)
#define SIZE_OF_DC_ROT_Raw_Detection_Faults_Bit_Field      (4U)
#define SIZE_OF_DC_ROT_Radar_Sensor_Faults_Bit_Fields      (4U)
#define SIZE_OF_DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field (4U)
#define SIZE_OF_DC_ROT_Object_Faults_Bit_Field             (4U)
#define SIZE_OF_DC_ROT_All_SCL_Faults                      (28U)
#define SIZE_OF_DC_ROT_ISO_Object_List_Log                 (208056U)
#define SIZE_OF_DC_ROT_ISO_Object_Stream                   (208072U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_ROT_ISO_Object_Output_Tag /*Offset Start byte of the Structure DC_ROT_ISO_Object_Output is 16 bytes*/
{
   float32_t iso_x_posn;
   float32_t iso_y_posn;
   float32_t iso_x_vel;
   float32_t iso_relative_x_vel;
   float32_t iso_y_vel;
   float32_t iso_relative_y_vel;
   float32_t iso_x_acc;
   float32_t iso_relative_x_acc;
   float32_t iso_y_acc;
   float32_t iso_relative_y_acc;
   float32_t iso_orientation;
   float32_t iso_orientation_var;
   float32_t iso_orientation_rate;
   float32_t iso_orientation_rate_var;
   float32_t iso_x_posn_var;
   float32_t iso_y_posn_var;
   float32_t iso_xy_posn_cov;
   float32_t iso_x_vel_var;
   float32_t iso_y_vel_var;
   float32_t iso_xy_vel_cov;
   float32_t iso_x_acc_var;
   float32_t iso_y_acc_var;
   float32_t iso_xy_acc_cov;
   float32_t speed;
   float32_t tang_accel;
   float32_t length;
   float32_t length_var;
   float32_t width;
   float32_t width_var;
   float32_t time_since_created;
   float32_t time_since_published;
   float32_t time_since_stage_start;
   float32_t existence_probability;
   float32_t mirror_prob;
   float32_t radar_cross_section;
   float32_t otg_height;
   float32_t confidence_level;
   float32_t probability_pedestrian;
   float32_t probability_car;
   float32_t probability_motorcycle;
   float32_t probability_bicycle;
   float32_t probability_truck;
   float32_t probability_undet;
   float32_t probability_underdrivable_ocg;
   float32_t movable_prob;
   int32_t id;
   uint32_t unique_id;
   uint32_t ndets;
   uint32_t num_dets_used_in_rr_msmt_update;
   uint16_t sensor_src;
   uint8_t reference_point;
   uint8_t object_status;
   uint8_t object_class;
   uint8_t movement_status;
   uint8_t occlusion_status;
   uint8_t underdrivable_status_ocg;
   uint8_t drivable_status_sg;
   uint8_t drivable_confidence_sg;
   uint8_t f_onguardrail;
   uint8_t trk_fltr_type;
} DC_ROT_ISO_Object_Output_T;

typedef struct DC_ROT_Core_Info_Faults_Bit_Field_Tag /*Offset Start byte of the Structure DC_ROT_Core_Info_Faults_Bit_Field is 224 bytes*/
{
   uint16_t K_Unused16_1;
   uint8_t K_Unused8_1;
   bitfield8_t time_us_no_increase : 1;
   bitfield8_t cnt_loops_no_increase : 1;
   bitfield8_t elapsed_time_below_lower_limit : 1;
   bitfield8_t elapsed_time_above_upper_limit : 1;
   bitfield8_t ununsed : 4;
} DC_ROT_Core_Info_Faults_Bit_Field_T;

typedef struct DC_ROT_Host_Info_Faults_Bit_Field_Tag /*Offset Start byte of the Structure DC_ROT_Host_Info_Faults_Bit_Field is 228 bytes*/
{
   uint16_t K_Unused16_1;
   uint8_t K_Unused8_1;
   bitfield8_t vehicle_index_no_increase : 1;
   bitfield8_t host_speed_invalid : 1;
   bitfield8_t host_yawrate_invalid : 1;
   bitfield8_t host_longitudinal_acceleration_invalid : 1;
   bitfield8_t host_lateral_acceleration_invalid : 1;
   bitfield8_t ununsed : 3;
} DC_ROT_Host_Info_Faults_Bit_Field_T;

typedef struct DC_ROT_Raw_Detection_Faults_Bit_Field_Tag /*Offset Start byte of the Structure DC_ROT_Raw_Detection_Faults_Bit_Field is 232 bytes*/
{
   uint16_t K_Unused16_1;
   uint8_t K_Unused8_1;
   bitfield8_t range_is_invalid : 1;
   bitfield8_t range_rate_is_invalid : 1;
   bitfield8_t azimuth_is_invalid : 1;
   bitfield8_t elevation_is_invalid : 1;
   bitfield8_t unused : 4;
} DC_ROT_Raw_Detection_Faults_Bit_Field_T;

typedef struct DC_ROT_Radar_Sensor_Faults_Bit_Fields_Tag /*Offset Start byte of the Structure DC_ROT_Radar_Sensor_Faults_Bit_Fields is 236 bytes*/
{
   uint8_t reserved[THREE];
   bitfield8_t look_index_no_increase : 1;
   bitfield8_t sensor_vs_tracker_timestamp_divergence : 1;
   bitfield8_t unused : 6;
} DC_ROT_Radar_Sensor_Faults_Bit_Fields_T;

typedef struct DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field_Tag /*Offset Start byte of the Structure DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field is 240 bytes*/
{
   uint8_t reserved[THREE];
   bitfield8_t mounting_pos_is_invalid : 1;
   bitfield8_t polarity_is_invalid : 1;
   bitfield8_t boresight_angle_is_invalid : 1;
   bitfield8_t unused : 5;
} DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field_T;

typedef struct DC_ROT_Object_Faults_Bit_Field_Tag /*Offset Start byte of the Structure DC_ROT_Object_Faults_Bit_Field is 244 bytes*/
{
   uint16_t K_Unused16_1;
   uint8_t K_Unused8_1;
   bitfield8_t f_track_positions_faulty : 1;
   bitfield8_t f_track_velocities_faulty : 1;
   bitfield8_t f_track_accelerations_faulty : 1;
   bitfield8_t f_severe_angle_jump_presence_fault : 1;
   bitfield8_t unused : 4;
} DC_ROT_Object_Faults_Bit_Field_T;

typedef struct DC_ROT_All_SCL_Faults_Tag /*Offset Start byte of the Structure DC_ROT_All_SCL_Faults is 248 bytes*/
{
   DC_ROT_Core_Info_Faults_Bit_Field_T core_info_faults;
   DC_ROT_Host_Info_Faults_Bit_Field_T host_info_faults;
   DC_ROT_Raw_Detection_Faults_Bit_Field_T raw_detection_faults;
   DC_ROT_Radar_Sensor_Faults_Bit_Fields_T radar_sensor_faults[ISO_ROT_NUM_TOTAL_RADAR_SENSORS];
   DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field_T radar_sensor_calib_faults[ISO_ROT_NUM_TOTAL_RADAR_SENSORS];
   DC_ROT_Object_Faults_Bit_Field_T object_faults;
   uint8_t overall_fault_status;
   uint8_t reserved[TWO];
   uint8_t K_Unused8_1;
} DC_ROT_All_SCL_Faults_T;

typedef struct DC_ROT_ISO_Object_List_Log_Tag /*Offset Start byte of the Structure DC_ROT_ISO_Object_List_Log is 276 bytes*/
{
   uint32_t rot_object_list_timestamp_lsb;
   uint32_t rot_object_list_timestamp_msb;
   uint32_t tracker_start_timestamp_lsb;
   uint32_t tracker_start_timestamp_msb;
   DC_ROT_ISO_Object_Output_T rot_object_list[DC_ROT_NUMBER_OF_REDUCED_OBJECT_TRACKS];
   float32_t tracker_elapsed_time;
   uint32_t tracker_index;
   DC_ROT_All_SCL_Faults_T all_scl_faults;
   uint16_t number_of_objects;
   uint8_t reserved[TWO];
} DC_ROT_ISO_Object_List_Log_T;

typedef struct DC_ROT_ISO_Object_Stream_Tag /*Offset Start byte of the Structure DC_ROT_ISO_Object_Stream is 208332 bytes*/
{
   Stream_Hdr_T stream_hdr;
   DC_ROT_ISO_Object_List_Log_T iso_objects;
} DC_ROT_ISO_Object_Stream_T;

#else

typedef struct DC_ROT_ISO_Object_Output_Tag {
   uint8_t trk_fltr_type;
   uint8_t f_onguardrail;
   uint8_t drivable_confidence_sg;
   uint8_t drivable_status_sg;
   uint8_t underdrivable_status_ocg;
   uint8_t occlusion_status;
   uint8_t movement_status;
   uint8_t object_class;
   uint8_t object_status;
   uint8_t reference_point;
   uint16_t sensor_src;
   uint32_t num_dets_used_in_rr_msmt_update;
   uint32_t ndets;
   uint32_t unique_id;
   int32_t id;
   float32_t movable_prob;
   float32_t probability_underdrivable_ocg;
   float32_t probability_undet;
   float32_t probability_truck;
   float32_t probability_bicycle;
   float32_t probability_motorcycle;
   float32_t probability_car;
   float32_t probability_pedestrian;
   float32_t confidence_level;
   float32_t otg_height;
   float32_t radar_cross_section;
   float32_t mirror_prob;
   float32_t existence_probability;
   float32_t time_since_stage_start;
   float32_t time_since_published;
   float32_t time_since_created;
   float32_t width_var;
   float32_t width;
   float32_t length_var;
   float32_t length;
   float32_t tang_accel;
   float32_t speed;
   float32_t iso_xy_acc_cov;
   float32_t iso_y_acc_var;
   float32_t iso_x_acc_var;
   float32_t iso_xy_vel_cov;
   float32_t iso_y_vel_var;
   float32_t iso_x_vel_var;
   float32_t iso_xy_posn_cov;
   float32_t iso_y_posn_var;
   float32_t iso_x_posn_var;
   float32_t iso_orientation_rate_var;
   float32_t iso_orientation_rate;
   float32_t iso_orientation_var;
   float32_t iso_orientation;
   float32_t iso_relative_y_acc;
   float32_t iso_y_acc;
   float32_t iso_relative_x_acc;
   float32_t iso_x_acc;
   float32_t iso_relative_y_vel;
   float32_t iso_y_vel;
   float32_t iso_relative_x_vel;
   float32_t iso_x_vel;
   float32_t iso_y_posn;
   float32_t iso_x_posn;
} DC_ROT_ISO_Object_Output_T;

typedef struct DC_ROT_Core_Info_Faults_Bit_Field_Tag {
   bitfield8_t ununsed : 4;
   bitfield8_t elapsed_time_above_upper_limit : 1;
   bitfield8_t elapsed_time_below_lower_limit : 1;
   bitfield8_t cnt_loops_no_increase : 1;
   bitfield8_t time_us_no_increase : 1;
   uint8_t K_Unused8_1;
   uint16_t K_Unused16_1;
} DC_ROT_Core_Info_Faults_Bit_Field_T;

typedef struct DC_ROT_Host_Info_Faults_Bit_Field_Tag {
   bitfield8_t ununsed : 3;
   bitfield8_t host_lateral_acceleration_invalid : 1;
   bitfield8_t host_longitudinal_acceleration_invalid : 1;
   bitfield8_t host_yawrate_invalid : 1;
   bitfield8_t host_speed_invalid : 1;
   bitfield8_t vehicle_index_no_increase : 1;
   uint8_t K_Unused8_1;
   uint16_t K_Unused16_1;
} DC_ROT_Host_Info_Faults_Bit_Field_T;

typedef struct DC_ROT_Raw_Detection_Faults_Bit_Field_Tag {
   bitfield8_t unused : 4;
   bitfield8_t elevation_is_invalid : 1;
   bitfield8_t azimuth_is_invalid : 1;
   bitfield8_t range_rate_is_invalid : 1;
   bitfield8_t range_is_invalid : 1;
   uint8_t K_Unused8_1;
   uint16_t K_Unused16_1;
} DC_ROT_Raw_Detection_Faults_Bit_Field_T;

typedef struct DC_ROT_Radar_Sensor_Faults_Bit_Fields_Tag {
   bitfield8_t unused : 6;
   bitfield8_t sensor_vs_tracker_timestamp_divergence : 1;
   bitfield8_t look_index_no_increase : 1;
   uint8_t reserved[THREE];
} DC_ROT_Radar_Sensor_Faults_Bit_Fields_T;

typedef struct DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field_Tag {
   bitfield8_t unused : 5;
   bitfield8_t boresight_angle_is_invalid : 1;
   bitfield8_t polarity_is_invalid : 1;
   bitfield8_t mounting_pos_is_invalid : 1;
   uint8_t reserved[THREE];
} DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field_T;

typedef struct DC_ROT_Object_Faults_Bit_Field_Tag {
   bitfield8_t unused : 4;
   bitfield8_t f_severe_angle_jump_presence_fault : 1;
   bitfield8_t f_track_accelerations_faulty : 1;
   bitfield8_t f_track_velocities_faulty : 1;
   bitfield8_t f_track_positions_faulty : 1;
   uint8_t K_Unused8_1;
   uint16_t K_Unused16_1;
} DC_ROT_Object_Faults_Bit_Field_T;

typedef struct DC_ROT_All_SCL_Faults_Tag {
   uint8_t K_Unused8_1;
   uint8_t reserved[TWO];
   uint8_t overall_fault_status;
   DC_ROT_Object_Faults_Bit_Field_T object_faults;
   DC_ROT_Radar_Sensor_Calib_Faults_Bit_Field_T radar_sensor_calib_faults[ISO_ROT_NUM_TOTAL_RADAR_SENSORS];
   DC_ROT_Radar_Sensor_Faults_Bit_Fields_T radar_sensor_faults[ISO_ROT_NUM_TOTAL_RADAR_SENSORS];
   DC_ROT_Raw_Detection_Faults_Bit_Field_T raw_detection_faults;
   DC_ROT_Host_Info_Faults_Bit_Field_T host_info_faults;
   DC_ROT_Core_Info_Faults_Bit_Field_T core_info_faults;
} DC_ROT_All_SCL_Faults_T;

typedef struct DC_ROT_ISO_Object_List_Log_Tag {
   uint8_t reserved[TWO];
   uint16_t number_of_objects;
   DC_ROT_All_SCL_Faults_T all_scl_faults;
   uint32_t tracker_index;
   float32_t tracker_elapsed_time;
   DC_ROT_ISO_Object_Output_T rot_object_list[DC_ROT_NUMBER_OF_REDUCED_OBJECT_TRACKS];
   uint32_t tracker_start_timestamp_msb;
   uint32_t tracker_start_timestamp_lsb;
   uint32_t rot_object_list_timestamp_msb;
   uint32_t rot_object_list_timestamp_lsb;
} DC_ROT_ISO_Object_List_Log_T;

typedef struct DC_ROT_ISO_Object_Stream_Tag {
   DC_ROT_ISO_Object_List_Log_T iso_objects;
   Stream_Hdr_T stream_hdr;
} DC_ROT_ISO_Object_Stream_T;

extern void Print_ROT_ISO_OBJECT_STREAM_Traces_Header(FILE *CfilePtr[], DC_ROT_ISO_Object_Stream_T *debug);
extern void Print_ROT_ISO_OBJECT_STREAM_Traces_Data(FILE *CfilePtr[], DC_ROT_ISO_Object_Stream_T *debug, unsigned int Scan_Index_Self);
extern void Print_ROT_ISO_OBJECT_STREAM_Xml_Traces(FILE *CfilePtr, DC_ROT_ISO_Object_Stream_T *debug);
extern void Reverse_Array_ROT_ISO_OBJECT_STREAM(DC_ROT_ISO_Object_Stream_T *debug);
extern int Get_ROT_ISO_OBJECT_STREAM_CSV_Split_Files_Num_Count();
#endif /*PC_Resim*/

/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 07-08-2025     19:09:05    jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/

#endif /*ROT_ISO_OBJECT_STREAM_H*/
