#ifndef ROT_SAE_OBJECT_STREAM_H
#define ROT_SAE_OBJECT_STREAM_H

/********************************************************************************************
 * Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
 * XML uses version 1 of the base file.
 * File Name: ROT_SAE_OBJECT_STREAM
 * Created:    06-08-2025     13:47:03
 * From XML file: ROT_SAE_OBJECT_STREAM.xml
 * Set Description:   Logging Structure/Interface structure
 * Tool Version: 5. 1. 0
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

#ifdef PC_RESIM
#include <stdio.h>
#endif /*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/
#include "stream_header.h"

/* Macros For ARRAY Sizes */
#define DC_ROT_SAE_OBJECT_STREAM_NUMBER (70U)
#define DC_ROT_NUMBER_OF_OBJECT_TRACKS  (1000U)
#define UNUSED_THREE                    (3U)
#define SIX                             (6U)
#define THREE                           (3U)

/*Macro For Structure Version*/
#define ROT_SAE_OBJECT_STREAM_VERSION (1U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_ROT_SAE_OBJECT_STREAM (200032U)

/*Macro for size of Sub structures*/
#define SIZE_OF_Stream_Hdr                   (16U)
#define SIZE_OF_DC_ROT_SAE_Object_Log_Header (16U)
#define SIZE_OF_DC_ROT_SAE_Object_Log        (200U)
#define SIZE_OF_DC_ROT_SAE_Object_List_Log   (200016U)
#define SIZE_OF_DC_ROT_SAE_Object_Stream     (200032U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_ROT_SAE_Object_Log_Header_Tag /*Offset Start byte of the Structure DC_ROT_SAE_Object_Log_Header is 16 bytes*/
{
   uint32_t data_timstamp_us_lsb;
   uint32_t data_timstamp_us_msb;
   uint32_t num_elements;
   uint16_t K_Unused16_1;
   uint8_t version;
   uint8_t K_Unused8_1;
} DC_ROT_SAE_Object_Log_Header_T;

typedef struct DC_ROT_SAE_Object_Log_Tag /*Offset Start byte of the Structure DC_ROT_SAE_Object_Log is 32 bytes*/
{
   float vcs_xposn;
   float vcs_yposn;
   float vcs_xvel;
   float vcs_yvel;
   float vcs_xaccel;
   float vcs_yaccel;
   float vcs_heading;
   float vcs_pointing;
   float speed;
   float curvature;
   float tang_accel;
   float existence_probability;
   float otg_height;
   float state_variance[SIX];
   float supplemental_state_covariance[THREE];
   float confidenceLevel;
   float time_since_measurement;
   float time_since_cluster_created;
   float time_since_track_updated;
   float time_since_stage_start;
   float len1;
   float len2;
   float wid1;
   float wid2;
   float accuracy_length;
   float accuracy_width;
   float probability_pedestrian;
   float probability_car;
   float probability_motorcycle;
   float probability_bicycle;
   float probability_truck;
   float probability_undet;
   float probability_underdrivable;
   float movable_prob;
   float32_t radar_cross_section;
   uint32_t unique_id;
   uint16_t trkID;
   uint16_t reducedID;
   uint16_t ndets;
   uint16_t num_rr_inlier_dets;
   uint16_t num_dets_used_in_rr_msmt_update;
   uint8_t status;
   uint8_t reference_point;
   uint8_t reducedStatus;
   int8_t init_scheme;
   uint8_t object_class;
   uint8_t f_crossing;
   uint8_t f_moving;
   uint8_t f_moveable;
   uint8_t f_oncoming;
   uint8_t f_vehicular_trk;
   uint8_t f_onguardrail;
   uint8_t f_fast_moving;
   uint8_t underdrivable_status_ocg;
   uint8_t drivable_status_sg;
   uint8_t drivable_confidence_sg;
   uint8_t current_msmt_type;
   uint8_t trk_fltr_type;
   uint8_t padding;
} DC_ROT_SAE_Object_Log_T;

typedef struct DC_ROT_SAE_Object_List_Log_Tag /*Offset Start byte of the Structure DC_ROT_SAE_Object_List_Log is 232 bytes*/
{
   DC_ROT_SAE_Object_Log_Header_T f360header;
   DC_ROT_SAE_Object_Log_T object[DC_ROT_NUMBER_OF_OBJECT_TRACKS];
} DC_ROT_SAE_Object_List_Log_T;

typedef struct DC_ROT_SAE_Object_Stream_Tag /*Offset Start byte of the Structure DC_ROT_SAE_Object_Stream is 200248 bytes*/
{
   Stream_Hdr_T stream_hdr;
   DC_ROT_SAE_Object_List_Log_T sae_objects;
} DC_ROT_SAE_Object_Stream_T;

#else

typedef struct DC_ROT_SAE_Object_Log_Header_Tag {
   uint8_t K_Unused8_1;
   uint8_t version;
   uint16_t K_Unused16_1;
   uint32_t num_elements;
   uint32_t data_timstamp_us_msb;
   uint32_t data_timstamp_us_lsb;
} DC_ROT_SAE_Object_Log_Header_T;

typedef struct DC_ROT_SAE_Object_Log_Tag {
   uint8_t padding;
   uint8_t trk_fltr_type;
   uint8_t current_msmt_type;
   uint8_t drivable_confidence_sg;
   uint8_t drivable_status_sg;
   uint8_t underdrivable_status_ocg;
   uint8_t f_fast_moving;
   uint8_t f_onguardrail;
   uint8_t f_vehicular_trk;
   uint8_t f_oncoming;
   uint8_t f_moveable;
   uint8_t f_moving;
   uint8_t f_crossing;
   uint8_t object_class;
   int8_t init_scheme;
   uint8_t reducedStatus;
   uint8_t reference_point;
   uint8_t status;
   uint16_t num_dets_used_in_rr_msmt_update;
   uint16_t num_rr_inlier_dets;
   uint16_t ndets;
   uint16_t reducedID;
   uint16_t trkID;
   uint32_t unique_id;
   float32_t radar_cross_section;
   float movable_prob;
   float probability_underdrivable;
   float probability_undet;
   float probability_truck;
   float probability_bicycle;
   float probability_motorcycle;
   float probability_car;
   float probability_pedestrian;
   float accuracy_width;
   float accuracy_length;
   float wid2;
   float wid1;
   float len2;
   float len1;
   float time_since_stage_start;
   float time_since_track_updated;
   float time_since_cluster_created;
   float time_since_measurement;
   float confidenceLevel;
   float supplemental_state_covariance[THREE];
   float state_variance[SIX];
   float otg_height;
   float existence_probability;
   float tang_accel;
   float curvature;
   float speed;
   float vcs_pointing;
   float vcs_heading;
   float vcs_yaccel;
   float vcs_xaccel;
   float vcs_yvel;
   float vcs_xvel;
   float vcs_yposn;
   float vcs_xposn;
} DC_ROT_SAE_Object_Log_T;

typedef struct DC_ROT_SAE_Object_List_Log_Tag {
   DC_ROT_SAE_Object_Log_T object[DC_ROT_NUMBER_OF_OBJECT_TRACKS];
   DC_ROT_SAE_Object_Log_Header_T f360header;
} DC_ROT_SAE_Object_List_Log_T;

typedef struct DC_ROT_SAE_Object_Stream_Tag {
   DC_ROT_SAE_Object_List_Log_T sae_objects;
   Stream_Hdr_T stream_hdr;
} DC_ROT_SAE_Object_Stream_T;

extern void Print_ROT_SAE_OBJECT_STREAM_Traces_Header(FILE *CfilePtr[], DC_ROT_SAE_Object_Stream_T *debug);
extern void Print_ROT_SAE_OBJECT_STREAM_Traces_Data(FILE *CfilePtr[], DC_ROT_SAE_Object_Stream_T *debug, unsigned int Scan_Index_Self);
extern void Print_ROT_SAE_OBJECT_STREAM_Xml_Traces(FILE *CfilePtr, DC_ROT_SAE_Object_Stream_T *debug);
extern void Reverse_Array_ROT_SAE_OBJECT_STREAM(DC_ROT_SAE_Object_Stream_T *debug);
extern int Get_ROT_SAE_OBJECT_STREAM_CSV_Split_Files_Num_Count();
#endif /*PC_Resim*/

/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 06-08-2025     13:47:03    jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/

#endif /*ROT_SAE_OBJECT_STREAM_H*/
