#ifndef ROT_PROCESSED_DETECTION_STREAM_H
#define ROT_PROCESSED_DETECTION_STREAM_H

/********************************************************************************************
 * Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
 * XML uses version 2 of the base file.
 * File Name: ROT_PROCESSED_DETECTION_STREAM
 * Created:    28-08-2025     14:59:36
 * From XML file: ROT_PROCESSED_DETECTION_STREAM.xml
 * Set Description:   Logging Structure/Interface structure
 * Tool Version: 5. 1. 0
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

#ifdef PC_RESIM
#include <stdio.h>
#endif /*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/
#include "stream_header.h"

/* Macros For ARRAY Sizes */
#define DC_ROT_PROCESSED_DETECTION_STREAM_NUMBER (71U)
#define DC_ROT_MAX_NUMBER_OF_DETECTIONS          (9408U)
#define ROT_NUM_TOTAL_RADAR_SENSORS              (10U)
#define TWO                                      (2U)

/*Macro For Structure Version*/
#define ROT_PROCESSED_DETECTION_STREAM_VERSION (2U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_ROT_PROCESSED_DETECTION_STREAM (414984U)

/*Macro for size of Sub structures*/
#define SIZE_OF_Stream_Hdr                             (16U)
#define SIZE_OF_DC_ROT_Processed_Detection_List_Header (16U)
#define SIZE_OF_DC_ROT_Processed_Detection_Log         (44U)
#define SIZE_OF_DC_ROT_Sensor_Info_Log                 (100U)
#define SIZE_OF_DC_ROT_Processed_Detection_List_Log    (413968U)
#define SIZE_OF_DC_ROT_Processed_Detection_Stream      (414984U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_ROT_Processed_Detection_List_Header_Tag /*Offset Start byte of the Structure DC_ROT_Processed_Detection_List_Header is 16 bytes*/
{
   uint32_t data_timstamp_us_lsb;
   uint32_t data_timstamp_us_msb;
   uint32_t num_elements;
   uint16_t K_Unused16_1;
   uint8_t version;
   uint8_t K_Unused8_1;
} DC_ROT_Processed_Detection_List_Header_T;

typedef struct DC_ROT_Processed_Detection_Log_Tag /*Offset Start byte of the Structure DC_ROT_Processed_Detection_Log is 32 bytes*/
{
   float32_t vcs_x;
   float32_t vcs_y;
   float32_t iso_x;
   float32_t iso_y;
   float32_t rngrate_dealiased;
   float32_t rngrate_comp;
   uint16_t raw_det_id;
   uint16_t objTrkID;
   uint16_t clusterID;
   uint8_t sensorID;
   int8_t motion_status;
   uint8_t wheel_spin;
   uint8_t f_dealiased;
   uint8_t f_double_bounce;
   uint8_t f_FOV_edge;
   uint8_t f_rr_inlier;
   uint8_t f_used_in_rr_msmt_update;
   uint8_t f_close_target;
   uint8_t f_inside_gate;
   uint8_t f_ok_to_use;
   uint8_t f_on_guardrail;
   uint8_t reserved[TWO];
} DC_ROT_Processed_Detection_Log_T;

typedef struct DC_ROT_Sensor_Info_Log_Tag /*Offset Start byte of the Structure DC_ROT_Sensor_Info_Log is 76 bytes*/
{
   uint32_t timestamp_us_lsb;
   uint32_t timestamp_us_msb;
   float32_t vcs_long_posn;
   float32_t vcs_lat_posn;
   float32_t vcs_long_vel;
   float32_t vcs_lat_vel;
   float32_t vcs_height_offset_m;
   float32_t vcs_boresight_az_angle;
   float32_t vcs_boresight_elev_angle;
   float32_t iso_long_posn;
   float32_t iso_lat_posn;
   float32_t iso_long_vel;
   float32_t iso_lat_vel;
   float32_t iso_height_offset_m;
   float32_t iso_boresight_az_angle;
   float32_t iso_boresight_elev_angle;
   float32_t range_rate_interval_width;
   float32_t useful_fov[TWO];
   float32_t align_angle_az_rad;
   float32_t align_angle_el_rad;
   uint32_t padding_32;
   uint16_t look_index;
   uint16_t padding_16;
   uint8_t sensorID;
   uint8_t f_sens_valid;
   uint8_t new_measurement_update;
   int8_t mount_location;
   int8_t sensor_type;
   int8_t look_id;
   int8_t radar_polarity;
   uint8_t K_Unused8_1;
} DC_ROT_Sensor_Info_Log_T;

typedef struct DC_ROT_Processed_Detection_List_Log_Tag /*Offset Start byte of the Structure DC_ROT_Processed_Detection_List_Log is 176 bytes*/
{
   DC_ROT_Processed_Detection_List_Header_T f360header;
   DC_ROT_Processed_Detection_Log_T detection[DC_ROT_MAX_NUMBER_OF_DETECTIONS];
} DC_ROT_Processed_Detection_List_Log_T;

typedef struct DC_ROT_Processed_Detection_Stream_Tag /*Offset Start byte of the Structure DC_ROT_Processed_Detection_Stream is 414144 bytes*/
{
   Stream_Hdr_T stream_hdr;
   DC_ROT_Processed_Detection_List_Log_T detection_info;
   DC_ROT_Sensor_Info_Log_T sensorInfoLog[ROT_NUM_TOTAL_RADAR_SENSORS];
} DC_ROT_Processed_Detection_Stream_T;

#else

typedef struct DC_ROT_Processed_Detection_List_Header_Tag {
   uint8_t K_Unused8_1;
   uint8_t version;
   uint16_t K_Unused16_1;
   uint32_t num_elements;
   uint32_t data_timstamp_us_msb;
   uint32_t data_timstamp_us_lsb;
} DC_ROT_Processed_Detection_List_Header_T;

typedef struct DC_ROT_Processed_Detection_Log_Tag {
   uint8_t reserved[TWO];
   uint8_t f_on_guardrail;
   uint8_t f_ok_to_use;
   uint8_t f_inside_gate;
   uint8_t f_close_target;
   uint8_t f_used_in_rr_msmt_update;
   uint8_t f_rr_inlier;
   uint8_t f_FOV_edge;
   uint8_t f_double_bounce;
   uint8_t f_dealiased;
   uint8_t wheel_spin;
   int8_t motion_status;
   uint8_t sensorID;
   uint16_t clusterID;
   uint16_t objTrkID;
   uint16_t raw_det_id;
   float32_t rngrate_comp;
   float32_t rngrate_dealiased;
   float32_t iso_y;
   float32_t iso_x;
   float32_t vcs_y;
   float32_t vcs_x;
} DC_ROT_Processed_Detection_Log_T;

typedef struct DC_ROT_Sensor_Info_Log_Tag {
   uint8_t K_Unused8_1;
   int8_t radar_polarity;
   int8_t look_id;
   int8_t sensor_type;
   int8_t mount_location;
   uint8_t new_measurement_update;
   uint8_t f_sens_valid;
   uint8_t sensorID;
   uint16_t padding_16;
   uint16_t look_index;
   uint32_t padding_32;
   float32_t align_angle_el_rad;
   float32_t align_angle_az_rad;
   float32_t useful_fov[TWO];
   float32_t range_rate_interval_width;
   float32_t iso_boresight_elev_angle;
   float32_t iso_boresight_az_angle;
   float32_t iso_height_offset_m;
   float32_t iso_lat_vel;
   float32_t iso_long_vel;
   float32_t iso_lat_posn;
   float32_t iso_long_posn;
   float32_t vcs_boresight_elev_angle;
   float32_t vcs_boresight_az_angle;
   float32_t vcs_height_offset_m;
   float32_t vcs_lat_vel;
   float32_t vcs_long_vel;
   float32_t vcs_lat_posn;
   float32_t vcs_long_posn;
   uint32_t timestamp_us_msb;
   uint32_t timestamp_us_lsb;
} DC_ROT_Sensor_Info_Log_T;

typedef struct DC_ROT_Processed_Detection_List_Log_Tag {
   DC_ROT_Processed_Detection_Log_T detection[DC_ROT_MAX_NUMBER_OF_DETECTIONS];
   DC_ROT_Processed_Detection_List_Header_T f360header;
} DC_ROT_Processed_Detection_List_Log_T;

typedef struct DC_ROT_Processed_Detection_Stream_Tag {
   DC_ROT_Sensor_Info_Log_T sensorInfoLog[ROT_NUM_TOTAL_RADAR_SENSORS];
   DC_ROT_Processed_Detection_List_Log_T detection_info;
   Stream_Hdr_T stream_hdr;
} DC_ROT_Processed_Detection_Stream_T;

extern void Print_ROT_PROCESSED_DETECTION_STREAM_Traces_Header(FILE *CfilePtr[], DC_ROT_Processed_Detection_Stream_T *debug);
extern void Print_ROT_PROCESSED_DETECTION_STREAM_Traces_Data(FILE *CfilePtr[], DC_ROT_Processed_Detection_Stream_T *debug, unsigned int Scan_Index_Self);
extern void Print_ROT_PROCESSED_DETECTION_STREAM_Xml_Traces(FILE *CfilePtr, DC_ROT_Processed_Detection_Stream_T *debug);
extern void Reverse_Array_ROT_PROCESSED_DETECTION_STREAM(DC_ROT_Processed_Detection_Stream_T *debug);
extern int Get_ROT_PROCESSED_DETECTION_STREAM_CSV_Split_Files_Num_Count();
#endif /*PC_Resim*/

/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 28-08-2025     14:59:36    jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/

#endif /*ROT_PROCESSED_DETECTION_STREAM_H*/
