#ifndef SFL_STREAM_H
#define SFL_STREAM_H

/********************************************************************************************
 * Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
 * XML uses version 1 of the base file.
 * File Name: SFL_STREAM
 * Created:    11-09-2025     17:52:50
 * From XML file: SFL_STREAM.xml
 * Set Description:   Logging Structure/Interface structure
 * Tool Version: 5. 1. 0
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

#ifdef PC_RESIM
#include <stdio.h>
#endif /*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/

/* Macros For ARRAY Sizes */
#define DC_SFL_STREAM_NUMBER        (82U)
#define DC_PA_OBJ_NUMBER_OF_OBJECTS (250U)
#define DC_FBK_NUMBER_OF_SIDES      (2U)
#define DC_CTA_NUM_MODES            (2U)

/*Macro For Structure Version*/
#define SFL_STREAM_VERSION (1U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_SFL_STREAM (10732U)

/*Macro for size of Sub structures*/
#define SIZE_OF_DC_Recw_Output                (24U)
#define SIZE_OF_DC_Cta_Critical_Object        (40U)
#define SIZE_OF_DC_Cta_Output                 (164U)
#define SIZE_OF_DC_Lcda_Output                (64U)
#define SIZE_OF_DC_Ced_Critical_Object        (44U)
#define SIZE_OF_DC_Ced_Output                 (92U)
#define SIZE_OF_DC_Pt_Nearest_Path            (12U)
#define SIZE_OF_DC_Pt_Path_Object_Pair_Output (28U)
#define SIZE_OF_DC_Pt_Output                  (10004U)
#define SIZE_OF_DC_Vector_2D                  (8U)
#define SIZE_OF_DC_Scw_Output_Object          (72U)
#define SIZE_OF_DC_Scw_Output                 (148U)
#define SIZE_OF_DC_Ta_Critical_Object         (36U)
#define SIZE_OF_DC_Ta_Output                  (84U)
#define SIZE_OF_DC_Ltb_Critical_Object        (20U)
#define SIZE_OF_DC_Ltb_Output                 (44U)
#define SIZE_OF_DC_Esa_Critical_Object        (52U)
#define SIZE_OF_DC_Esa_Output                 (108U)
#define SIZE_OF_DC_SFL_Stream                 (10732U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_Recw_Output_Tag /*Offset Start byte of the Structure DC_Recw_Output is 0 bytes*/
{
   float32_t recw_crash_probability;
   float32_t recw_ttc_s;
   uint32_t recw_unique_id;
   float32_t ttc_threshold_alert_level_1_s;
   float32_t ttc_threshold_alert_level_2_s;
   uint8_t recw_id;
   uint8_t recw_alert_level;
   uint8_t recw_status;
   uint8_t K_Unused8_1;
} DC_Recw_Output_T;

typedef struct DC_Cta_Critical_Object_Tag /*Offset Start byte of the Structure DC_Cta_Critical_Object is 24 bytes*/
{
   uint32_t unique_id;
   float32_t objPoseX_m;
   float32_t objPoseY_m;
   float32_t objVelocityX_mps;
   float32_t objVelocityY_mps;
   float32_t heading_rad;
   float32_t ttc_s;
   float32_t intersection_point_x_m;
   float32_t brake_deceleration;
   uint8_t id;
   uint8_t alert_level;
   uint8_t f_brake_qualifier;
   uint8_t f_standstill_qualifier;
} DC_Cta_Critical_Object_T;

typedef struct DC_Cta_Output_Tag /*Offset Start byte of the Structure DC_Cta_Output is 64 bytes*/
{
   DC_Cta_Critical_Object_T most_critical_object_by_sides[DC_CTA_NUM_MODES][DC_FBK_NUMBER_OF_SIDES];
   uint16_t K_Unused16_1;
   uint8_t f_cta_enabled;
   uint8_t K_Unused8_1;
} DC_Cta_Output_T;

typedef struct DC_Lcda_Output_Tag /*Offset Start byte of the Structure DC_Lcda_Output is 228 bytes*/
{
   uint32_t bsw_unique_id[DC_FBK_NUMBER_OF_SIDES];
   uint32_t cvw_unique_id[DC_FBK_NUMBER_OF_SIDES];
   float32_t cvw_ttc_s[DC_FBK_NUMBER_OF_SIDES];
   uint32_t slc_unique_id[DC_FBK_NUMBER_OF_SIDES];
   float32_t slc_ttc_s[DC_FBK_NUMBER_OF_SIDES];
   float32_t slc_lane_change_probability[DC_FBK_NUMBER_OF_SIDES];
   uint8_t lcda_status;
   uint8_t f_bsw_enabled;
   uint8_t bsw_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t bsw_id[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_cvw_enabled;
   uint8_t cvw_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t cvw_id[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_slc_enabled;
   uint8_t slc_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t slc_id[DC_FBK_NUMBER_OF_SIDES];
} DC_Lcda_Output_T;

typedef struct DC_Ced_Critical_Object_Tag /*Offset Start byte of the Structure DC_Ced_Critical_Object is 292 bytes*/
{
   uint32_t unique_id;
   float32_t length_m;
   float32_t width_m;
   float32_t lat_pos_m;
   float32_t long_pos_m;
   float32_t speed_mps;
   float32_t heading_rad;
   float32_t predicted_lat_pos_m;
   float32_t ttc_s;
   float32_t ttp_s;
   uint8_t id;
   uint8_t type;
   uint8_t direction;
   uint8_t K_Unused8_1;
} DC_Ced_Critical_Object_T;

typedef struct DC_Ced_Output_Tag /*Offset Start byte of the Structure DC_Ced_Output is 336 bytes*/
{
   DC_Ced_Critical_Object_T ced_object[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_ced_enable;
   uint8_t ced_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t K_Unused8_1;
} DC_Ced_Output_T;

typedef struct DC_Pt_Nearest_Path_Tag /*Offset Start byte of the Structure DC_Pt_Nearest_Path is 428 bytes*/
{
   float32_t range_vcs_proj_to_path_segment;
   float32_t segment_heading_diff;
   uint16_t K_Unused16_1;
   uint8_t track_idx_nearest_path;
   uint8_t K_Unused8_1;
} DC_Pt_Nearest_Path_T;

typedef struct DC_Pt_Path_Object_Pair_Output_Tag /*Offset Start byte of the Structure DC_Pt_Path_Object_Pair_Output is 440 bytes*/
{
   float32_t range_at_zero;
   float32_t range_to_current_path_part;
   float32_t range_at_host_edge;
   float32_t length_of_trajectory;
   float32_t path_heading;
   uint16_t K_Unused16_1;
   uint8_t path_direction;
   uint8_t path_state;
   uint8_t track_match;
   uint8_t track_match_age;
   uint8_t track_match_last_cycle;
   uint8_t K_Unused8_1;
} DC_Pt_Path_Object_Pair_Output_T;

typedef struct DC_Pt_Output_Tag /*Offset Start byte of the Structure DC_Pt_Output is 468 bytes*/
{
   DC_Pt_Nearest_Path_T nearest_path_output[DC_PA_OBJ_NUMBER_OF_OBJECTS];
   DC_Pt_Path_Object_Pair_Output_T path_obj_pair_output[DC_PA_OBJ_NUMBER_OF_OBJECTS];
   uint16_t K_Unused16_1;
   uint8_t f_pt_operational;
   uint8_t K_Unused8_1;
} DC_Pt_Output_T;

typedef struct DC_Vector_2D_Tag /*Offset Start byte of the Structure DC_Vector_2D is 10472 bytes*/
{
   float32_t x;
   float32_t y;
} DC_Vector_2D_T;

typedef struct DC_Scw_Output_Object_Tag /*Offset Start byte of the Structure DC_Scw_Output_Object is 10480 bytes*/
{
   uint32_t unique_id;
   float32_t lateral_ttc_s;
   float32_t lateral_distance_m;
   DC_Vector_2D_T position_m;
   DC_Vector_2D_T velocity_mps;
   DC_Vector_2D_T acceleration_mps2;
   float32_t width_m;
   float32_t length_m;
   float32_t heading_rad;
   float32_t yawrate_radps;
   float32_t existence_probability;
   float32_t ttle_s;
   float32_t ttp_s;
   uint16_t age;
   uint16_t K_Unused16_1;
   uint8_t alert_level;
   uint8_t id;
   uint8_t type;
   uint8_t K_Unused8_1;
} DC_Scw_Output_Object_T;

typedef struct DC_Scw_Output_Tag /*Offset Start byte of the Structure DC_Scw_Output is 10552 bytes*/
{
   DC_Scw_Output_Object_T scw_object[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_scw_enabled;
   uint8_t f_scw_dyn_enabled;
   uint8_t f_scw_guardrail_enabled;
   uint8_t K_Unused8_1;
} DC_Scw_Output_T;

typedef struct DC_Ta_Critical_Object_Tag /*Offset Start byte of the Structure DC_Ta_Critical_Object is 10700 bytes*/
{
   DC_Vector_2D_T ta_waypoint_at_collision_m;
   float32_t ta_ttc_s;
   float32_t ta_ttp_s;
   float32_t ta_ttb_s;
   float32_t ta_decel_estimate_mps2;
   float32_t ta_distance_m;
   uint16_t K_Unused16_1;
   uint8_t ta_id;
   uint8_t ta_index;
   uint8_t ta_f_obj_in_danger_zone;
   uint8_t ta_f_obj_in_info_zone;
   uint8_t ta_f_obj_in_wing_zone;
   uint8_t K_Unused8_1;
} DC_Ta_Critical_Object_T;

typedef struct DC_Ta_Output_Tag /*Offset Start byte of the Structure DC_Ta_Output is 10736 bytes*/
{
   DC_Ta_Critical_Object_T ta_object[DC_FBK_NUMBER_OF_SIDES];
   uint16_t K_Unused16_1;
   uint8_t f_ta_enable;
   uint8_t ta_f_vehicle_state_relevant;
   uint8_t ta_most_critical_side;
   uint8_t ta_n_valid_objects;
   uint8_t ta_n_relevant_objects;
   uint8_t ta_n_critical_objects;
   uint8_t ta_algorithm_state;
   uint8_t ta_alert_level[DC_FBK_NUMBER_OF_SIDES];
   uint8_t K_Unused8_1;
} DC_Ta_Output_T;

typedef struct DC_Ltb_Critical_Object_Tag /*Offset Start byte of the Structure DC_Ltb_Critical_Object is 10820 bytes*/
{
   float32_t ltb_ttc_s;
   float32_t ltb_ttb_s;
   float32_t ltb_decel_estimate_mps2;
   float32_t ltb_distance_m;
   uint16_t K_Unused16_1;
   uint8_t ltb_id;
   uint8_t K_Unused8_1;
} DC_Ltb_Critical_Object_T;

typedef struct DC_Ltb_Output_Tag /*Offset Start byte of the Structure DC_Ltb_Output is 10840 bytes*/
{
   DC_Ltb_Critical_Object_T ltb_object[DC_FBK_NUMBER_OF_SIDES];
   uint8_t ltb_alert_level[DC_FBK_NUMBER_OF_SIDES];
   uint8_t ltb_most_critical_side;
   uint8_t K_Unused8_1;
} DC_Ltb_Output_T;

typedef struct DC_Esa_Critical_Object_Tag /*Offset Start byte of the Structure DC_Esa_Critical_Object is 10884 bytes*/
{
   float32_t width_m;
   float32_t length_m;
   float32_t long_pos_m;
   float32_t lat_pos_m;
   float32_t long_speed_mps;
   float32_t lat_speed_mps;
   float32_t ttc_s;
   float32_t ttp_s;
   float32_t timestamp_s;
   float32_t decel_to_reach_host_speed_mps2;
   float32_t long_distance_m;
   float32_t existence_prob;
   uint16_t K_Unused16_1;
   uint8_t id;
   uint8_t index;
} DC_Esa_Critical_Object_T;

typedef struct DC_Esa_Output_Tag /*Offset Start byte of the Structure DC_Esa_Output is 10936 bytes*/
{
   DC_Esa_Critical_Object_T esa_object[DC_FBK_NUMBER_OF_SIDES];
   uint8_t esa_status;
   uint8_t f_esa_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t K_Unused8_1;
} DC_Esa_Output_T;

typedef struct DC_SFL_Stream_Tag /*Offset Start byte of the Structure DC_SFL_Stream is 11044 bytes*/
{
   DC_Recw_Output_T recw_output;
   DC_Cta_Output_T cta_output;
   DC_Lcda_Output_T lcda_output;
   DC_Ced_Output_T ced_output;
   DC_Pt_Output_T pt_output;
   DC_Scw_Output_T scw_output;
   DC_Ta_Output_T ta_output;
   DC_Ltb_Output_T ltb_output;
   DC_Esa_Output_T esa_output;
} DC_SFL_Stream_T;

#else

typedef struct DC_Recw_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t recw_status;
   uint8_t recw_alert_level;
   uint8_t recw_id;
   float32_t ttc_threshold_alert_level_2_s;
   float32_t ttc_threshold_alert_level_1_s;
   uint32_t recw_unique_id;
   float32_t recw_ttc_s;
   float32_t recw_crash_probability;
} DC_Recw_Output_T;

typedef struct DC_Cta_Critical_Object_Tag {
   uint8_t f_standstill_qualifier;
   uint8_t f_brake_qualifier;
   uint8_t alert_level;
   uint8_t id;
   float32_t brake_deceleration;
   float32_t intersection_point_x_m;
   float32_t ttc_s;
   float32_t heading_rad;
   float32_t objVelocityY_mps;
   float32_t objVelocityX_mps;
   float32_t objPoseY_m;
   float32_t objPoseX_m;
   uint32_t unique_id;
} DC_Cta_Critical_Object_T;

typedef struct DC_Cta_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t f_cta_enabled;
   uint16_t K_Unused16_1;
   DC_Cta_Critical_Object_T most_critical_object_by_sides[DC_CTA_NUM_MODES][DC_FBK_NUMBER_OF_SIDES];
} DC_Cta_Output_T;

typedef struct DC_Lcda_Output_Tag {
   uint8_t slc_id[DC_FBK_NUMBER_OF_SIDES];
   uint8_t slc_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_slc_enabled;
   uint8_t cvw_id[DC_FBK_NUMBER_OF_SIDES];
   uint8_t cvw_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_cvw_enabled;
   uint8_t bsw_id[DC_FBK_NUMBER_OF_SIDES];
   uint8_t bsw_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_bsw_enabled;
   uint8_t lcda_status;
   float32_t slc_lane_change_probability[DC_FBK_NUMBER_OF_SIDES];
   float32_t slc_ttc_s[DC_FBK_NUMBER_OF_SIDES];
   uint32_t slc_unique_id[DC_FBK_NUMBER_OF_SIDES];
   float32_t cvw_ttc_s[DC_FBK_NUMBER_OF_SIDES];
   uint32_t cvw_unique_id[DC_FBK_NUMBER_OF_SIDES];
   uint32_t bsw_unique_id[DC_FBK_NUMBER_OF_SIDES];
} DC_Lcda_Output_T;

typedef struct DC_Ced_Critical_Object_Tag {
   uint8_t K_Unused8_1;
   uint8_t direction;
   uint8_t type;
   uint8_t id;
   float32_t ttp_s;
   float32_t ttc_s;
   float32_t predicted_lat_pos_m;
   float32_t heading_rad;
   float32_t speed_mps;
   float32_t long_pos_m;
   float32_t lat_pos_m;
   float32_t width_m;
   float32_t length_m;
   uint32_t unique_id;
} DC_Ced_Critical_Object_T;

typedef struct DC_Ced_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t ced_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t f_ced_enable;
   DC_Ced_Critical_Object_T ced_object[DC_FBK_NUMBER_OF_SIDES];
} DC_Ced_Output_T;

typedef struct DC_Pt_Nearest_Path_Tag {
   uint8_t K_Unused8_1;
   uint8_t track_idx_nearest_path;
   uint16_t K_Unused16_1;
   float32_t segment_heading_diff;
   float32_t range_vcs_proj_to_path_segment;
} DC_Pt_Nearest_Path_T;

typedef struct DC_Pt_Path_Object_Pair_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t track_match_last_cycle;
   uint8_t track_match_age;
   uint8_t track_match;
   uint8_t path_state;
   uint8_t path_direction;
   uint16_t K_Unused16_1;
   float32_t path_heading;
   float32_t length_of_trajectory;
   float32_t range_at_host_edge;
   float32_t range_to_current_path_part;
   float32_t range_at_zero;
} DC_Pt_Path_Object_Pair_Output_T;

typedef struct DC_Pt_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t f_pt_operational;
   uint16_t K_Unused16_1;
   DC_Pt_Path_Object_Pair_Output_T path_obj_pair_output[DC_PA_OBJ_NUMBER_OF_OBJECTS];
   DC_Pt_Nearest_Path_T nearest_path_output[DC_PA_OBJ_NUMBER_OF_OBJECTS];
} DC_Pt_Output_T;

typedef struct DC_Vector_2D_Tag {
   float32_t y;
   float32_t x;
} DC_Vector_2D_T;

typedef struct DC_Scw_Output_Object_Tag {
   uint8_t K_Unused8_1;
   uint8_t type;
   uint8_t id;
   uint8_t alert_level;
   uint16_t K_Unused16_1;
   uint16_t age;
   float32_t ttp_s;
   float32_t ttle_s;
   float32_t existence_probability;
   float32_t yawrate_radps;
   float32_t heading_rad;
   float32_t length_m;
   float32_t width_m;
   DC_Vector_2D_T acceleration_mps2;
   DC_Vector_2D_T velocity_mps;
   DC_Vector_2D_T position_m;
   float32_t lateral_distance_m;
   float32_t lateral_ttc_s;
   uint32_t unique_id;
} DC_Scw_Output_Object_T;

typedef struct DC_Scw_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t f_scw_guardrail_enabled;
   uint8_t f_scw_dyn_enabled;
   uint8_t f_scw_enabled;
   DC_Scw_Output_Object_T scw_object[DC_FBK_NUMBER_OF_SIDES];
} DC_Scw_Output_T;

typedef struct DC_Ta_Critical_Object_Tag {
   uint8_t K_Unused8_1;
   uint8_t ta_f_obj_in_wing_zone;
   uint8_t ta_f_obj_in_info_zone;
   uint8_t ta_f_obj_in_danger_zone;
   uint8_t ta_index;
   uint8_t ta_id;
   uint16_t K_Unused16_1;
   float32_t ta_distance_m;
   float32_t ta_decel_estimate_mps2;
   float32_t ta_ttb_s;
   float32_t ta_ttp_s;
   float32_t ta_ttc_s;
   DC_Vector_2D_T ta_waypoint_at_collision_m;
} DC_Ta_Critical_Object_T;

typedef struct DC_Ta_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t ta_alert_level[DC_FBK_NUMBER_OF_SIDES];
   uint8_t ta_algorithm_state;
   uint8_t ta_n_critical_objects;
   uint8_t ta_n_relevant_objects;
   uint8_t ta_n_valid_objects;
   uint8_t ta_most_critical_side;
   uint8_t ta_f_vehicle_state_relevant;
   uint8_t f_ta_enable;
   uint16_t K_Unused16_1;
   DC_Ta_Critical_Object_T ta_object[DC_FBK_NUMBER_OF_SIDES];
} DC_Ta_Output_T;

typedef struct DC_Ltb_Critical_Object_Tag {
   uint8_t K_Unused8_1;
   uint8_t ltb_id;
   uint16_t K_Unused16_1;
   float32_t ltb_distance_m;
   float32_t ltb_decel_estimate_mps2;
   float32_t ltb_ttb_s;
   float32_t ltb_ttc_s;
} DC_Ltb_Critical_Object_T;

typedef struct DC_Ltb_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t ltb_most_critical_side;
   uint8_t ltb_alert_level[DC_FBK_NUMBER_OF_SIDES];
   DC_Ltb_Critical_Object_T ltb_object[DC_FBK_NUMBER_OF_SIDES];
} DC_Ltb_Output_T;

typedef struct DC_Esa_Critical_Object_Tag {
   uint8_t index;
   uint8_t id;
   uint16_t K_Unused16_1;
   float32_t existence_prob;
   float32_t long_distance_m;
   float32_t decel_to_reach_host_speed_mps2;
   float32_t timestamp_s;
   float32_t ttp_s;
   float32_t ttc_s;
   float32_t lat_speed_mps;
   float32_t long_speed_mps;
   float32_t lat_pos_m;
   float32_t long_pos_m;
   float32_t length_m;
   float32_t width_m;
} DC_Esa_Critical_Object_T;

typedef struct DC_Esa_Output_Tag {
   uint8_t K_Unused8_1;
   uint8_t f_esa_alert[DC_FBK_NUMBER_OF_SIDES];
   uint8_t esa_status;
   DC_Esa_Critical_Object_T esa_object[DC_FBK_NUMBER_OF_SIDES];
} DC_Esa_Output_T;

typedef struct DC_SFL_Stream_Tag {
   DC_Esa_Output_T esa_output;
   DC_Ltb_Output_T ltb_output;
   DC_Ta_Output_T ta_output;
   DC_Scw_Output_T scw_output;
   DC_Pt_Output_T pt_output;
   DC_Ced_Output_T ced_output;
   DC_Lcda_Output_T lcda_output;
   DC_Cta_Output_T cta_output;
   DC_Recw_Output_T recw_output;
} DC_SFL_Stream_T;

extern void Print_SFL_STREAM_Traces_Header(FILE *CfilePtr[], DC_SFL_Stream_T *debug);
extern void Print_SFL_STREAM_Traces_Data(FILE *CfilePtr[], DC_SFL_Stream_T *debug, unsigned int Scan_Index_Self);
extern void Print_SFL_STREAM_Xml_Traces(FILE *CfilePtr, DC_SFL_Stream_T *debug);
extern void Reverse_Array_SFL_STREAM(DC_SFL_Stream_T *debug);
extern int Get_SFL_STREAM_CSV_Split_Files_Num_Count();
#endif /*PC_Resim*/

/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 11-09-2025     17:52:51    jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/

#endif /*SFL_STREAM_H*/
