#ifndef SG_STREAM_H
#define SG_STREAM_H

/********************************************************************************************
 * Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
 * XML uses version 0 of the base file.
 * File Name: SG_STREAM
 * Created:    09-10-2025     21:13:27
 * From XML file: SG_STREAM.xml
 * Set Description:   Logging Structure/Interface structure
 * Tool Version: 5. 1. 0
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

#ifdef PC_RESIM
#include <stdio.h>
#endif /*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/
#include "stream_header.h"

/* Macros For ARRAY Sizes */
#define DC_SG_MAX_NUM_OUTPUT_VERTICES (400U)
#define DC_SG_MAX_NUM_OUTPUT_CONTOURS (100U)

/*Macro For Structure Version*/
#define DC_SG_STREAM_NUMBER (84U)
#define SG_STREAM_VERSION   (1U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_SG_STREAM (12036U)

/*Macro for size of Sub structures*/
#define SIZE_OF_Stream_Hdr             (16U)
#define SIZE_OF_DC_Execution_Timestamp (8U)
#define SIZE_OF_DC_SG_Contour_Out      (8U)
#define SIZE_OF_DC_SG_Vertex_Out       (28U)
#define SIZE_OF_DC_SG_Stream           (12036U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_Execution_Timestamp_Tag /*Offset Start byte of the Structure DC_Execution_Timestamp is 16 bytes*/
{
   uint32_t ts_seconds;
   uint32_t ts_nanoseconds;
} DC_Execution_Timestamp_T;

typedef struct DC_SG_Contour_Out_Tag /*Offset Start byte of the Structure DC_SG_Contour_Out is 24 bytes*/
{
   uint32_t unique_id;
   uint16_t num_vertices;
   uint8_t type;
   uint8_t K_Unused8_1;
} DC_SG_Contour_Out_T;

typedef struct DC_SG_Vertex_Out_Tag /*Offset Start byte of the Structure DC_SG_Vertex_Out is 32 bytes*/
{
   float32_t position_x;
   float32_t position_y;
   float32_t position_variance_x;
   float32_t position_variance_y;
   float32_t position_covariance_xy;
   uint16_t cycles_since_created;
   uint16_t cycles_since_coasted;
   uint16_t K_Unused16_1;
   uint8_t drivability;
   uint8_t drivability_confidence;
} DC_SG_Vertex_Out_T;

typedef struct DC_SG_Stream_Tag /*Offset Start byte of the Structure DC_SG_Stream is 60 bytes*/
{
   Stream_Hdr_T stream_hdr;
   DC_Execution_Timestamp_T execution_timestamp_us;
   DC_Execution_Timestamp_T measurement_timestamp_us;
   DC_SG_Vertex_Out_T vertices[DC_SG_MAX_NUM_OUTPUT_VERTICES];
   DC_SG_Contour_Out_T contours[DC_SG_MAX_NUM_OUTPUT_CONTOURS];
   uint16_t num_contours;
   uint8_t f_valid;
   uint8_t K_Unused8_1;
} DC_SG_Stream_T;

#else

typedef struct DC_Execution_Timestamp_Tag {
   uint32_t ts_nanoseconds;
   uint32_t ts_seconds;
} DC_Execution_Timestamp_T;

typedef struct DC_SG_Contour_Out_Tag {
   uint8_t K_Unused8_1;
   uint8_t type;
   uint16_t num_vertices;
   uint32_t unique_id;
} DC_SG_Contour_Out_T;

typedef struct DC_SG_Vertex_Out_Tag {
   uint8_t drivability_confidence;
   uint8_t drivability;
   uint16_t K_Unused16_1;
   uint16_t cycles_since_coasted;
   uint16_t cycles_since_created;
   float32_t position_covariance_xy;
   float32_t position_variance_y;
   float32_t position_variance_x;
   float32_t position_y;
   float32_t position_x;
} DC_SG_Vertex_Out_T;

typedef struct DC_SG_Stream_Tag {
   uint8_t K_Unused8_1;
   uint8_t f_valid;
   uint16_t num_contours;
   DC_SG_Contour_Out_T contours[DC_SG_MAX_NUM_OUTPUT_CONTOURS];
   DC_SG_Vertex_Out_T vertices[DC_SG_MAX_NUM_OUTPUT_VERTICES];
   DC_Execution_Timestamp_T measurement_timestamp_us;
   DC_Execution_Timestamp_T execution_timestamp_us;
   Stream_Hdr_T stream_hdr;
} DC_SG_Stream_T;

extern void Print_SG_STREAM_Traces_Header(FILE *CfilePtr[], DC_SG_Stream_T *debug);
extern void Print_SG_STREAM_Traces_Data(FILE *CfilePtr[], DC_SG_Stream_T *debug, unsigned int Scan_Index_Self);
extern void Print_SG_STREAM_Xml_Traces(FILE *CfilePtr, DC_SG_Stream_T *debug);
extern void Reverse_Array_SG_STREAM(DC_SG_Stream_T *debug);
extern int Get_SG_STREAM_CSV_Split_Files_Num_Count();
#endif /*PC_Resim*/

/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 09-10-2025     21:13:27    jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/

#endif /*SG_STREAM_H*/
