#ifndef VSE_STREAM_H
#define VSE_STREAM_H

/********************************************************************************************
 * Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
 * XML uses version 1 of the base file.
 * File Name: VSE_STREAM
 * Created:    28-08-2025     14:26:35
 * From XML file: VSE_STREAM.xml
 * Set Description:   Logging Structure/Interface structure
 * Tool Version: 5. 1. 0
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/

#ifdef PC_RESIM
#include <stdio.h>
#endif /*PC_RESIM*/

#include "fixmac.h"

/* External Header Includes*/
#include "stream_header.h"

/* Macros For ARRAY Sizes */
#define DC_VSE_STREAM_NUMBER (83U)
#define NO_OF_COEFF          (6U)

/*Macro For Structure Version*/
#define VSE_STREAM_VERSION (1U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_VSE_STREAM (112U)

/*Macro for size of Sub structures*/
#define SIZE_OF_Stream_Hdr       (16U)
#define SIZE_OF_DC_Veh_Status_Ts (12U)
#define SIZE_OF_DC_Veh_Info      (32U)
#define SIZE_OF_DC_Veh_FS_Coeff  (52U)
#define SIZE_OF_DC_Vse_Stream    (112U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct DC_Veh_Status_Ts_Tag /*Offset Start byte of the Structure DC_Veh_Status_Ts is 16 bytes*/
{
   uint32_t ts_secs;
   uint32_t ts_nanosecs;
   uint16_t K_Unused16_1;
   uint8_t ts_status;
   uint8_t K_Unused8_1;
} DC_Veh_Status_Ts_T;

typedef struct DC_Veh_Info_Tag /*Offset Start byte of the Structure DC_Veh_Info is 28 bytes*/
{
   float32_t veh_speed;
   float32_t veh_yaw;
   float32_t veh_pitch;
   float32_t veh_roll;
   float32_t veh_steering_angle;
   uint8_t veh_speed_qf;
   uint8_t veh_yaw_qf;
   uint8_t veh_pitch_qf;
   uint8_t veh_roll_qf;
   uint8_t veh_steering_sign_status;
   uint8_t veh_ign_sts;
   uint8_t lros_drive_reverse;
   uint8_t lros_drive_dir;
   uint8_t gear_position;
   uint8_t yaw_rate_bias;
   int8_t veh_spd_comp_factor;
   uint8_t K_Unused8_1;
} DC_Veh_Info_T;

typedef struct DC_Veh_FS_Coeff_Tag /*Offset Start byte of the Structure DC_Veh_FS_Coeff is 60 bytes*/
{
   float32_t fs_az_coeff[NO_OF_COEFF];
   float32_t fs_el_coeff[NO_OF_COEFF];
   uint16_t K_Unused16_1;
   uint8_t sensor_posn;
   uint8_t enable_fs_calc;
} DC_Veh_FS_Coeff_T;

typedef struct DC_Vse_Stream_Tag /*Offset Start byte of the Structure DC_Vse_Stream is 112 bytes*/
{
   Stream_Hdr_T stream_hdr;
   DC_Veh_Info_T veh_params;
   DC_Veh_Status_Ts_T veh_data_ts;
   DC_Veh_FS_Coeff_T veh_fs_coeff_values;
} DC_Vse_Stream_T;

#else

typedef struct DC_Veh_Status_Ts_Tag {
   uint8_t K_Unused8_1;
   uint8_t ts_status;
   uint16_t K_Unused16_1;
   uint32_t ts_nanosecs;
   uint32_t ts_secs;
} DC_Veh_Status_Ts_T;

typedef struct DC_Veh_Info_Tag {
   uint8_t K_Unused8_1;
   int8_t veh_spd_comp_factor;
   uint8_t yaw_rate_bias;
   uint8_t gear_position;
   uint8_t lros_drive_dir;
   uint8_t lros_drive_reverse;
   uint8_t veh_ign_sts;
   uint8_t veh_steering_sign_status;
   uint8_t veh_roll_qf;
   uint8_t veh_pitch_qf;
   uint8_t veh_yaw_qf;
   uint8_t veh_speed_qf;
   float32_t veh_steering_angle;
   float32_t veh_roll;
   float32_t veh_pitch;
   float32_t veh_yaw;
   float32_t veh_speed;
} DC_Veh_Info_T;

typedef struct DC_Veh_FS_Coeff_Tag {
   uint8_t enable_fs_calc;
   uint8_t sensor_posn;
   uint16_t K_Unused16_1;
   float32_t fs_el_coeff[NO_OF_COEFF];
   float32_t fs_az_coeff[NO_OF_COEFF];
} DC_Veh_FS_Coeff_T;

typedef struct DC_Vse_Stream_Tag {
   DC_Veh_FS_Coeff_T veh_fs_coeff_values;
   DC_Veh_Status_Ts_T veh_data_ts;
   DC_Veh_Info_T veh_params;
   Stream_Hdr_T stream_hdr;
} DC_Vse_Stream_T;

extern void Print_VSE_STREAM_Traces_Header(FILE *CfilePtr[], DC_Vse_Stream_T *debug);
extern void Print_VSE_STREAM_Traces_Data(FILE *CfilePtr[], DC_Vse_Stream_T *debug, unsigned int Scan_Index_Self);
extern void Print_VSE_STREAM_Xml_Traces(FILE *CfilePtr, DC_Vse_Stream_T *debug);
extern void Reverse_Array_VSE_STREAM(DC_Vse_Stream_T *debug);
extern int Get_VSE_STREAM_CSV_Split_Files_Num_Count();
#endif /*PC_Resim*/

/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 28-08-2025     14:26:35    jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/

#endif /*VSE_STREAM_H*/
