target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_FILE})

target_include_directories(LTB PUBLIC ${CMAKE_CURRENT_LIST_DIR})

target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_debug_writer.h)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_debug_interface.h)
target_sources(LTB PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ltb_persistent_t.h)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb.h)
target_sources(LTB PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ltb_types.h)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_factory.h)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_time_calculation.h)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_warn_logic.h)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_common_functions.h)
target_sources(LTB PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ltb_iface.h)
target_sources(LTB PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ltb_core_input_t.h)
target_sources(LTB PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ltb_core_output_t.h)
target_sources(LTB PUBLIC ${CMAKE_CURRENT_LIST_DIR}/ltb_instance.h)

target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_debug_writer.c)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_debug_interface.c)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_iface.c)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb.c)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_factory.c)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_time_calculation.c)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_warn_logic.c)
target_sources(LTB PRIVATE ${CMAKE_CURRENT_LIST_DIR}/ltb_common_functions.c)
