"""
Bazel file defining all building blocks, local and remote.

Many times, developers will need to override the http_archive calls to develop their building block code locally.
To do this, use the override_repository flag during build.
This can be either added on the command line, or for convenience it can be added to a user.bazelrc file in the root of the repo.
Simply create this user.bazelrc file and add one of the following lines (or similar) and that parameter will be appended to all build commands.

Example for a repo named "my_repo":
common --override_repository=_main~_repo_rules~my_repo=../my_repo_git/
Absolute paths are supported, but differ between Windows and Unix.
Relative paths are supported, but are relative to the current directory where you are executing bazel.

If not using the user.bazelrc file, the build command might look like this:
bazel build //:gen7 --override_repository=_main~_repo_rules~my_repo=../my_repo_git/
"""

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

bazel_dep(name = "core_radar_reuse", repo_name = "reuse", version = "1.2.6")

http_archive(
    name = "iND13400_autosar_sip",
    integrity = "sha256-U34zKC8sLtb5hqiYAIavjvG1Os0h7nX/BeHeAcRBaIU=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/core_radar_gen8_ind13400_sip/v4/core-radar-gen8-ind13400-sip_v4.54.8.zip"],
)

# SPBB repository / v6.x for Chandra_B0 and MAP/RIDM
http_archive(
    name = "spbb",
    sha256 = "a64ea458e9a9a51cb7771532b396656ae7fd1f84bb9b281f5eb84050e467d1dd",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Gen8_iND13400_Signal_Processing/v8/Core_Radar_Gen8_iND13400_Signal_Processing_v8.12.0.zip"],
)

bazel_dep(name = "core_radar_swc_plt_appl_modemanager", version = "1.35.0", repo_name = "SWC_PLT_Appl_ModeManager")

bazel_dep(name = "core_radar_swc_plt_appl_diag", version = "2.45.0", repo_name = "SWC_PLT_Appl_Diag")

bazel_dep(name = "core_radar_swc_plt_appl_faultmgr", version = "2.46.0", repo_name = "SWC_PLT_Appl_FaultMgr")

bazel_dep(name = "core_radar_swc_plt_appl_iohwab", version = "1.29.0", repo_name = "SWC_PLT_Appl_IoHwAb")

bazel_dep(name = "core_radar_sensor_position", repo_name = "Sensor_Position", version = "0.0.22")

http_archive(
    name = "SWC_PLT_CDD_WdgHandler",
    sha256 = "f0275da6a60d596fc36ffcd739386d0ae8151de996b87b016cac0b7765f8d33e",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_SWC_PLT_CDD_WdgHandler/v0/Core_Radar_SWC_PLT_CDD_WdgHandler_v0.5.0.zip"],
)

bazel_dep(name = "core_radar_swc_plt_appl_ecu_sync", version = "1.5.6", repo_name = "SWC_PLT_Appl_TimeSync")

bazel_dep(name = "core_radar_math", repo_name = "rm", version = "0.2.3")

# AFBB repository
http_archive(
    name = "afbb",
    integrity = "sha256-KlUNYKMINPxsRjvcWTb/NvxQFGIN0QN8LHrfUCCTiDc=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Gen8_iND13400_Angle_Finding/v7/Core_Radar_Gen8_iND13400_Angle_Finding_v7.4.0.zip"],
)

# IDBB repository
http_archive(
    name = "idbb",
    integrity = "sha256-aMRq4B6NT1dT4Q0xWuTuf3NwTE4OeXzAWyf9jHUvkMc=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Interference_Detection/v4/Core_Radar_Interference_Detection_v4.0.7.zip"],
)

# DABB repository
http_archive(
    name = "dabb",
    integrity = "sha256-DbCXjMAW9eK09Mm1yiXBp2Dt94lYHI6+nH3Qenc2uTM=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Dynamic_Alignment/v20/Core_Radar_Dynamic_Alignment_v20.1.1.zip"],
)

# SABB repository
http_archive(
    name = "sabb",
    integrity = "sha256-sHSuLyhhtK4RGd4Z4BfbgB7xGFyKRh8jF89nSZm+SKU=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/core_radar_static_alignment/v9/core-radar-static-alignment_v9.1.1002.zip"],
)

# RCBB repository
http_archive(
    name = "rcbb",
    integrity = "sha256-ihqX3qiLAu+Y/JlS6WmYUl4mtSaKCi2uFfqFSKFuv28=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Capability/v3/Core_Radar_Capability_v3.25.2008.zip"],
)

# SHBB repository
http_archive(
    name = "shbb",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/core_radar_stream_handler/v2/Core_Radar_Stream_Handler_v2.5.1.zip"],
    integrity = "sha256-nCSmg9caerA5Lg9lEZ6GCm6ADWuVr0apboX2botdaiQ=",
)

# HILBB repository
http_archive(
    name = "hilbb",
    sha256 = "502c540ca530467812a8cc4698bd0e253d87e81999d0e0873af30b914c3367b4",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_HIL/v6/Core_Radar_HIL_v6.0.5.zip"],
)

# SDK Repo / v3.x for Chandra_B0 and Chandra_A0
http_archive(
    name = "iND13400_sdk",
    integrity = "sha256-1iWyMAD0kC3B5/dTkL+ZzZtsjmskH6umUcmvAe1T/MY=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/core_radar_gen8_ind13400_sdk/v3/core-radar-gen8-ind13400-sdk_v3.54.3.zip"],
)

http_archive(
    name = "boot",
    integrity = "sha256-OeYVgwIZ/t5z5+ZTVCgKpCgwKyYIyT6rcTtK+RrkO7g=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Gen8_iND13400_Boot/v2/Core_Radar_Gen8_iND13400_Boot_v2.1.7.zip"],
)

http_archive(
    name = "Calibration_Handler",
    sha256 = "dcfa451019372464b65b4bdae093b36b267bd3dd80b920f0fc4afaf602c6cbe6",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Calibration_Handler/v1/Core_Radar_Calibration_Handler_v1.0.5.zip"],
)

# This is default / Standard (768 AF Det) SMC for Satellite build
http_archive(
    name = "smc_flr8",  # Formerly named smc_flr8_can
    build_file = "//software/common/calibrations/smc:archive.BUILD",
    sha256 = "6865be93309e0d549b12ecf6e614b7de5ab0f36d95c7d8c509440964bb576ea7",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/SMC/Gen8/v35/FLR8/FLR8_A2_Aptiv_Standard_Satellite_3DMAP_Wdg_En_35_82_0_6_SMC_2026-08-31_05-08-14.zip"],
)

# This is Standard (768 AF Det) SMC for Standalone build
http_archive(
    name = "smc_flr8_standalone",
    build_file = "//software/common/calibrations/smc:archive.BUILD",
    sha256 = "6fd2996f90bc50d28a06c3d96d81b6ecbc435a3c72c7c6c4ad0fcf2d5e5b8cf6",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/SMC/Gen8/v35/FLR8/FLR8_A2_Aptiv_Standard_Standalone_3DMAP_Wdg_En_35_82_0_518_SMC_2026-08-31_05-09-00.zip"],
)

# This is High Det (2048 AF Det) SMC for High Det Variant (previously called Tiger)
http_archive(
    name = "smc_flr8_high_det",
    build_file = "//software/common/calibrations/smc:archive.BUILD",
    sha256 = "0c5deec79b364f1bd3e3a0729d0a6b7e3850b006a603002295274b310efca2b0",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/SMC/Gen8/v35/FLR8/FLR8_A2_Aptiv_HighDet_Satellite_3DMAP_Wdg_En_35_82_0_1030_SMC_2026-08-31_05-09-29.zip"],
)

http_archive(
    name = "usc_flr8",
    build_file = "//software/common/calibrations/usc:archive.BUILD",
    sha256 = "d709eaa5e8ed8dc94d950dbfb57e40ec1652d3eda2926251985da880949652bd",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/USC/Gen8/v8/FLR8/FLR8_EDU_Aptiv_Default_8_82_0_0_USC_2026-02-11_11-34-09_patch.zip"],
)

# This is default / Standard (768 AF Det) SMC for Satellite build
http_archive(
    name = "smc_srr8p",  # Formerly named smc_srr8p_can
    build_file = "//software/common/calibrations/smc:archive.BUILD",
    sha256 = "d228f1698cca650123833fd5e26ea9fce6adc2bdad2800bfc2e8af83f7006c21",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/SMC/Gen8/v35/SRR8P/SRR8P_A2_Aptiv_Standard_Satellite_3DMAP_Wdg_En_35_83_0_6_SMC_2026-08-31_05-17-16.zip"],
)

# This is Standard (768 AF Det ) SMC for Standalone build
http_archive(
    name = "smc_srr8p_standalone",
    build_file = "//software/common/calibrations/smc:archive.BUILD",
    sha256 = "a989a1659f5ef20c1b9c0cb641519de3a210731e33a1353bf67bb0029b96f2dd",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/SMC/Gen8/v35/SRR8P/SRR8P_A2_Aptiv_Standard_Standalone_3DMAP_Wdg_En_35_83_0_518_SMC_2026-08-31_05-17-44.zip"],
)

# This is Standard (768 AF Det) SMC for AL CAN Standalone build
http_archive(
    name = "smc_srr8p_al_can_standalone",
    build_file = "//software/common/calibrations/smc:archive.BUILD",
    sha256 = "72acf010831f9d8bd08fa5ef239230a20a16ba515d7138820638a9100898608e",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/SMC/Gen8/v35/SRR8P/SRR8P_B0_AshokLeyland_Standard_Standalone_3DMAP_Wdg_En_35_83_128_518_SMC_2026-09-02_04-40-29.zip"],
)

# This is High Det (2048 AF Det) SMC for High Det Variant (previously called Tiger)
http_archive(
    name = "smc_srr8p_high_det",
    build_file = "//software/common/calibrations/smc:archive.BUILD",
    sha256 = "9559e537c0385dba66ab690b83b6c8d179b05f79c7bb29c8f9498c12719ac19a",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/SMC/Gen8/v35/SRR8P/SRR8P_A2_Aptiv_HighDet_Satellite_3DMAP_Wdg_En_35_83_0_1030_SMC_2026-08-31_05-19-29.zip"],
)

http_archive(
    name = "usc_srr8p",
    build_file = "//software/common/calibrations/usc:archive.BUILD",
    sha256 = "7e39faf925b49eb94912cf93a4c07dc7e40d15decd98b0f8e9dce06e6b8d04cb",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-calibrations-local/USC/Gen8/v10/SRR8P/SRR8%2B_EDU_Aptiv_Default_10_83_0_0_USC_2026-02-11_11-38-53_patch.zip"],
)

bazel_dep(name = "core_radar_log_struct_gen", version = "1.34.0", repo_name = "StreamHeader_Gen")

http_archive(
    name = "quickflash",
    sha256 = "8bbcb66ddde7279abfb317962070cb40a5f7b2b2f39d9a36c2a730c63bfb47bd",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-common_3rd_party-local/QuickFlash/2.4.2/QuickFlash_2.4.2.zip"],
)

http_archive(
    name = "MAF_BIN_A",
    build_file_content = "exports_files([\"MAF.bin\",])",
    sha256 = "80b9cb2d594e3d4ea5d37ce0e774d9527cbcc7ef1140ad9e6ab7223498430b56",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-gen8_ind13400_3rd_party-local/indie/MAF/MAF_0x00001800_crc_0x280408a1.zip"],
)

http_archive(
    name = "MAF_BIN_B",
    build_file_content = "exports_files([\"MAF.bin\",])",
    sha256 = "3f6fa909f7641dfe3acc512fa3a332a55fb59dc8e78d741c275fd893030e1a12",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-gen8_ind13400_3rd_party-local/indie/MAF/MAF_0x10030603_crc_0xe7eb9a39.zip"],
)

http_archive(
    name = "rotbb",
    integrity = "sha256-GNGhhMNLxpVpTdx5Zm4pv2w5gxkxG+vPu8oZB1hjRiQ=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Object_Tracker/v3/Core_Radar_Object_Tracker_v3.1.2.zip"],
)

http_archive(
    name = "TOI_Char_Quality_Determination",
    sha256 = "6d26be82bd20f8f831dc6dc64c31b6d48bd9551a3df46a565aabf831f6819b35",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_TOI_Char_Quality_Determination/v1/Core_Radar_TOI_Char_Quality_Determination_v1.2.4.zip"],
)

git_repository(
    name = "sfl_core_bb",
    remote = "https://gitgerrit.asux.aptiv.com/CORECOMP/ALSW/SFL_SideFeatureLogic",
    tag = "v7.4.1",
    init_submodules = True,
    recursive_init_submodules = True,
    build_file = "//software/bbe32/Cust/SFL/SFL_Core:BUILD",
)

git_repository(
    name = "math_library_bb",
    remote = "https://gitgerrit.asux.aptiv.com/CORECOMP/ALSW/ML_MathLibrary",
    tag = "release/24_PI1_S5",
    build_file = "//software/bbe32/Cust/SFL/Math_Library:BUILD",
)

git_repository(
    name = "mode_manager_bb",
    remote = "https://gitgerrit.asux.aptiv.com/CORECOMP/ALSW/SFL_Mode_Manager",
    tag = "Release_AL_v2.2.0",
    build_file = "//software/bbe32/Cust/SFL/Mode_Manager:BUILD",
)

git_repository(
    name = "olp_bb",
    remote = "https://gitgerrit.asux.aptiv.com/CORECOMP/ALSW/OLP_ObjectListPostprocessor",
    tag = "Release_AL_v2.0.0",
    build_file = "//software/bbe32/Cust/OLP:BUILD",
)
