#pragma once
#include "DCMacros.h"
#include "DCCustomer.h"
#include "DCSensorType.h"

/**
 * Defines and initializes DC customer variants
 */
enum DCCustomerVariant {
   DC_BMW_SRR5_PLUS_SENSOR_VARIANT    = DC_GET_VARIANT(DC_CUSTOMER_BMW, DC_SENSOR_TYPE_SRR5_PLUS),
   DC_BMW_MRR3_SENSOR_VARIANT         = DC_GET_VARIANT(DC_CUSTOMER_BMW, DC_SENSOR_TYPE_MRR3),
   DC_FORD_MRR3_SENSOR_VARIANT        = DC_GET_VARIANT(DC_CUSTOMER_FORD, DC_SENSOR_TYPE_MRR3),
   DC_CHANGAN_SRR5_SENSOR_VARIANT     = DC_GET_VARIANT(DC_CUSTOMER_CHANGAN, DC_SENSOR_TYPE_SRR5),
   DC_RNA_SRR5_SENSOR_VARIANT         = DC_GET_VARIANT(DC_CUSTOMER_RNA, DC_SENSOR_TYPE_SRR5),
   DC_SCANIA_SRR3_SENSOR_VARIANT      = DC_GET_VARIANT(DC_CUSTOMER_SCANIA, DC_SENSOR_TYPE_SRR3),
   DC_NISSAN_SRR6_SENSOR_VARIANT      = DC_GET_VARIANT(DC_CUSTOMER_NISSAN, DC_SENSOR_TYPE_SRR6),
   DC_HONDA_SRR6PLUS_SENSOR_VARIANT   = DC_GET_VARIANT(DC_CUSTOMER_HONDA, DC_SENSOR_TYPE_SRR6_PLUS),
   DC_HKMC_SRR5_SENSOR_VARIANT        = DC_GET_VARIANT(DC_CUSTOMER_HKMC, DC_SENSOR_TYPE_SRR5),
   DC_TML_SRR5_SENSOR_VARIANT         = DC_GET_VARIANT(DC_CUSTOMER_TML, DC_SENSOR_TYPE_SRR5),
   DC_STLA_FLR4PLUS_SENSOR_VARIANT    = DC_GET_VARIANT(DC_CUSTOMER_STLA, DC_SENSOR_TYPE_FLR4_PLUS),
   DC_STLA_FLR4_SENSOR_VARIANT        = DC_GET_VARIANT(DC_CUSTOMER_STLA, DC_SENSOR_TYPE_FLR4),
   DC_STLA_SRR6PLUS_SENSOR_VARIANT    = DC_GET_VARIANT(DC_CUSTOMER_STLA, DC_SENSOR_TYPE_SRR6_PLUS),
   DC_MTNL_FLR4PLUS_SENSOR_VARIANT    = DC_GET_VARIANT(DC_CUSTOMER_MTNL, DC_SENSOR_TYPE_FLR4_PLUS),
   DC_BMW_SRR7PLUS_SENSOR_VARIANT     = DC_GET_VARIANT(DC_CUSTOMER_BMW, DC_SENSOR_TYPE_SRR7_PLUS),
   DC_BMW_FLR7_SENSOR_VARIANT         = DC_GET_VARIANT(DC_CUSTOMER_BMW, DC_SENSOR_TYPE_FLR7),
   DC_TRATON_SRR6PLUS_SENSOR_VARIANT  = DC_GET_VARIANT(DC_CUSTOMER_TRATON, DC_SENSOR_TYPE_SRR6_PLUS),
   DC_CEER_SRR7PLUS_SENSOR_VARIANT    = DC_GET_VARIANT(DC_CUSTOMER_CEER, DC_SENSOR_TYPE_SRR7_PLUS),
   DC_CEER_FLR7_SENSOR_VARIANT        = DC_GET_VARIANT(DC_CUSTOMER_CEER, DC_SENSOR_TYPE_FLR7),
   DC_GPO_SRR7PLUS_UWB_SENSOR_VARIANT = DC_GET_VARIANT(DC_CUSTOMER_GPO, DC_SENSOR_TYPE_SRR7_PLUS_UWB),
   DC_STLA_SRR7PLUS_SENSOR_VARIANT    = DC_GET_VARIANT(DC_CUSTOMER_STLA, DC_SENSOR_TYPE_SRR7_PLUS),
   DC_STLA_FLR7_SENSOR_VARIANT        = DC_GET_VARIANT(DC_CUSTOMER_STLA, DC_SENSOR_TYPE_FLR7),
   DC_GPO_SRR8PLUS_SENSOR_VARIANT     = DC_GET_VARIANT(DC_CUSTOMER_GPO, DC_SENSOR_TYPE_SRR8_PLUS),
   DC_GPO_FLR8_SENSOR_VARIANT         = DC_GET_VARIANT(DC_CUSTOMER_GPO, DC_SENSOR_TYPE_FLR8),
   DC_MAX_NUMBER_OF_CUSTOMER_VARIANT
};

/**
 * Defines and initializes DC look id
 */
enum DCLookID {
   DC_LOOK_ID_LRLL = 0,
   DC_LOOK_ID_LRML,
   DC_LOOK_ID_MRLL,
   DC_LOOK_ID_MRML,
};
