# -*- mode: python ; coding: utf-8 -*-
import os

# Get the IPS directory path
spec_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['ResimHTMLReport.py'],
    pathex=[spec_dir],
    binaries=[],
    datas=[
        ('Metadata', 'Metadata'),
        ('HTMLConfig.xml', '.'),
        ('Inputs.json', '.'),
    ],
    hiddenimports=[
        'IPS',
        'IPS.DataCollect',
        'IPS.DataCollect.dc_radar_hdf_datacollect',
        'IPS.DataCollect.parsercontext',
        'IPS.DataPrep',
        'IPS.DataPrep.dc_dataprep',
        'IPS.DataStore',
        'IPS.DataStore.radar_datastore',
        'IPS.DataStore.plot_datastore',
        'IPS.DataStore.json_datastore',
        'IPS.EventMan',
        'IPS.EventMan.data_event_mediator',
        'IPS.PlotConvert',
        'IPS.PlotConvert.dc_data_to_json_convert',
        'IPS.RepGen',
        'IPS.RepGen.dc_json_to_html_convert',
        'IPS.DashManager',
        'IPS.DashManager.report_dash',
        'IPS.Metadata',
        'IPS.Metadata.GEN7V2',
        'IPS.Metadata.GEN7V2.poi',
        'numpy',
        'pandas',
        'plotly',
        'plotly.graph_objects',
        'plotly.subplots',
        'plotly.io',
        'h5py',
        'matplotlib',
        'matplotlib.pyplot',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ResimHTMLReport',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
