/*===================================================================================*\
* FILE: dc_interface_autocode.cpp
*====================================================================================
* Copyright (C) 2024 Aptiv Advanced Safety and User Experience. All rights reserved.
* Confidential - Restricted Aptiv information. Do not disclose.
*------------------------------------------------------------------------------------
*
* DESCRIPTION:
*   This file contains interface between DC and SG autogenerated.
*
*   Applicable Standards (in order of precedence: highest first):
*     ESGW_4-2_PE-SWX_00-01-A01_EN "Aptiv C++ Coding Standards" [26-May-2019]
*     ESGW_4-2_PE-SWX_00-01-A02_EN "Delphi C Coding Standards" [12-Mar-2006]
*
\*===================================================================================*/

#include "dc_interface_autocode.h"

#include "rspp_host.h"

namespace sg
{
   namespace dc
   {
      void DCInterfaceAutocode::step(TimingInfo &m_timing_info,
                                     MATLAB::Internals_T &matlab_internals,
                                     const MATLAB::Host_T &host,
                                     const MATLAB::Input_Detections_List_T &detections_list,
                                     const MATLAB::Calibrations_T &cfg)
      {
         subsegmentController.step(m_timing_info, matlab_internals, host, detections_list, cfg);
      }
   }
}