#!/bin/bash
echo "#ifndef GITINFO_H_"
echo "#define GITINFO_H_"

echo
echo "/* DO NOT EDIT THIS FILE! */"
echo "/* This is an auto-generated file. */"
echo "/* DO NOT EDIT THIS FILE! */"
echo

hex_regex="^([[:alnum:]_]+)[[:space:]]+(0x[[:xdigit:]]+[uU]?$)"
num_regex="^([[:alnum:]_]+)[[:space:]]+([[:digit:]]+$)"
string_regex="^([[:alnum:]_]+)[[:space:]]+(.*$)"

files="bazel-out/*-status.txt"
for f in $files
do
    while IFS= read -r line; do
        if [[ "$line" =~ $hex_regex ]]; then
            echo "#define ${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
        elif [[ "$line" =~ $num_regex ]]; then
            echo "#define ${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
        elif [[ "$line" =~ $string_regex ]]; then
            echo "#define ${BASH_REMATCH[1]} \"${BASH_REMATCH[2]}\""
        fi

    done < "$f"
done

echo
echo "#endif"
echo
