#ifndef DSPACE_COMMON_INPUT_STRUCTURE_H
#define DSPACE_COMMON_INPUT_STRUCTURE_H

/********************************************************************************************
 * Copyright 2018 APTIV Technologies, Inc., All Rights Reserved
 * XML uses version 4 of the base file.
 * File Name: DSPACE_COMMON_INPUT_STRUCTURE
 * Created:    09-05-2023     10:59:15
 * From XML file: DSPACE_COMMON_INPUT_STRUCTURE.xml
 * Set Description:   Logging Structure/Interface structure
 * Tool Version: 5. 1. 0
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

// This is added to convert the structures in this file to 4 byte padding
#pragma pack(push, save_pack)
#pragma pack(push, 4)

#ifndef float32_t
typedef float float32_t;
#endif

/*Macros For ARRAY Sizes*/
#define DSPACE_SIMULATED_TRACKS   (256U)
#define NUMBER_OF_SELF_Detections (500U)
#define DSPACE                    (10U)

/*Macro For Structure Version*/
#define DSPACE_COMMON_INPUT_STRUCTURE_VERSION (3U)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_DSPACE_COMMON_INPUT_STRUCTURE (213848U)

/*Macro for size of Sub structures*/
#define SIZE_OF_Dspace_Logging_Hdr         (8U)
#define SIZE_OF_TrackObject                (68U)
#define SIZE_OF_Detections_Info_Logging    (28U)
#define SIZE_OF_Detections                 (56U)
#define SIZE_OF_Detections_Logging         (28028U)
#define SIZE_OF_Vehicle_Data_Input         (60U)
#define SIZE_OF_MOUNTING_POSITION_VALUES   (20U)
#define SIZE_OF_Vehicle_Geometry           (20U)
#define SIZE_OF_DSPACE_Common_Logging_Data (213848U)

#ifndef LITTLE_ENDIAN_STRUCTURE

typedef struct Dspace_Logging_Hdr_Tag /*Offset Start byte of the Structure Dspace_Logging_Hdr is 0 bytes*/
{
   uint16_t Sec_Checksum;
   uint16_t Sec_Compatibility;
   uint32_t Sec_Size;
} Dspace_Logging_Hdr_T;

typedef struct Virtual_TrackObject_Tag /*Offset Start byte of the Structure TrackObject is 8 bytes*/
{
   uint32_t id;
   uint8_t status;
   uint8_t age;
   uint8_t stage_age;
   uint8_t K_Unused8_1;
   float32_t vcs_long_posn;
   float32_t vcs_long_vel;
   float32_t vcs_long_accel;
   float32_t vcs_lat_posn;
   float32_t vcs_lat_vel;
   float32_t vcs_lat_accel;
   float32_t vcs_long_vel_rel;
   float32_t vcs_lat_vel_rel;
   float32_t speed;
   float32_t tangential_accel;
   float32_t heading;
   float32_t heading_rate;
   float32_t length;
   float32_t width;
   uint8_t object_class;
   uint8_t K_Unused8_2;
   uint16_t K_Unused16_2;
} Virtual_TrackObject_T;

typedef struct Detections_Info_Logging_Tag /*Offset Start byte of the Structure Detections_Info_Logging is 76 bytes*/
{
   float32_t AutoAlignAzimuth;
   float32_t AutoAlignElevation;
   float32_t timestamp;
   uint32_t Count;
   uint32_t ScanIndex;
   uint8_t AutoAlignAzimuthQF;
   uint8_t AutoAlignElevationQF;
   uint8_t timestamp_consistency;
   uint8_t LookID;
   uint8_t LookType;
   uint8_t K_Unused8_1;
   uint16_t radar_data_valid;
} Detections_Info_Logging_T;

typedef struct Detections_Tag /*Offset Start byte of the Structure Detections is 104 bytes*/
{
   float32_t elevation;
   float32_t azimuth;
   float32_t range_rate;
   float32_t range;
   float32_t amplitude;
   float32_t snr;
   float32_t std_elevation;
   float32_t std_azimuth;
   float32_t std_range_rate;
   float32_t std_range;
   float32_t std_rcs;
   float32_t multi_target_probability;
   float32_t existence_probability;
   uint8_t azimuth_confidence;
   uint8_t elevation_confidence;
   uint8_t valid;
   bitfield8_t host_veh_clutter : 1;
   bitfield8_t super_res_target : 1;
   bitfield8_t nd_target : 1;
   bitfield8_t bistatic : 1;
   bitfield8_t k_unused_bits1 : 4;
} Detections_T;

typedef struct Detections_Logging_Tag /*Offset Start byte of the Structure Detections_Logging is 160 bytes*/
{
   Detections_T dets_float[NUMBER_OF_SELF_Detections];
   Detections_Info_Logging_T dets_info;
} Detections_Logging_T;

typedef struct Vehicle_Data_Input_Tag /*Offset Start byte of the Structure Vehicle_Data_Input is 28188 bytes*/
{
   float32_t abs_speed;
   float32_t yawrate;
   float32_t steering_angle;
   float32_t rear_axle_steering_angle;
   float32_t rear_axle_position;
   float32_t lane_width_external;
   float32_t lane_center_offset_external;
   float32_t host_vehicle_length;
   float32_t host_vehicle_width;
   float32_t curve_radius;
   float32_t vcs_long_acc;
   float32_t vcs_lat_acc;
   uint32_t vehicle_data_buff_timestamp;
   uint8_t prndl;
   uint8_t turn_signal;
   uint8_t f_reverse_gear;
   uint8_t f_trailer_present;
   uint8_t f_traffic_side;
   uint8_t K_Unused8_1;
   uint16_t K_Unused16_1;
} Vehicle_Data_Input_T;

typedef struct MOUNTING_POSITION_VALUES_Tag /*Offset Start byte of the Structure MOUNTING_POSITION_VALUES is 28248 bytes*/
{
   float32_t azimuth_polarity;
   float32_t boresight_angle;
   float32_t vcs_lat_position;
   float32_t vcs_lon_position;
   float32_t vcs_z_position;
} MOUNTING_POSITION_VALUES_T;

typedef struct Vehicle_Geometry_Tag /*Offset Start byte of the Structure Vehicle_Geometry is 28268 bytes*/
{
   float32_t vcs_lat_offset;
   float32_t vcs_long_offset;
   float32_t vehicle_width;
   float32_t vehicle_length;
   float32_t rear_axle_pos;
} Vehicle_Geometry_T;

typedef struct DSPACE_Common_Logging_Data_Tag /*Offset Start byte of the Structure DSPACE_Common_Logging_Data is 28288 bytes*/
{
   Dspace_Logging_Hdr_T Header;
   uint16_t running_counter;
   uint16_t K_Unused16_1;
   uint32_t utc_time;
   uint32_t time_stamp;
   uint8_t radar_position;
   uint8_t customer_id;
   uint16_t K_Unused16_2;
   Vehicle_Geometry_T Vehicle_Geometry;
   MOUNTING_POSITION_VALUES_T Mounting_Values_RL;
   MOUNTING_POSITION_VALUES_T Mounting_Values_RR;
   MOUNTING_POSITION_VALUES_T Mounting_Values_FL;
   MOUNTING_POSITION_VALUES_T Mounting_Values_FR;
   MOUNTING_POSITION_VALUES_T Mounting_Values_FC;
   MOUNTING_POSITION_VALUES_T Mounting_Values_BR;
   MOUNTING_POSITION_VALUES_T Mounting_Values_BL;
   Vehicle_Data_Input_T vehicle_input;
   Virtual_TrackObject_T virtual_track[DSPACE_SIMULATED_TRACKS];
   Detections_Logging_T front_right_detection;
   Detections_Logging_T front_left_detection;
   Detections_Logging_T rear_right_detection;
   Detections_Logging_T rear_left_detection;
   Detections_Logging_T front_center_detection;
   Detections_Logging_T bpil_left_detection;
   Detections_Logging_T bpil_right_detection;
} DSPACE_Common_Logging_Data_T;

#else

typedef struct Dspace_Logging_Hdr_Tag {
   unsigned32_t Sec_Size;
   unsigned16_t Sec_Compatibility;
   unsigned16_t Sec_Checksum;
} Dspace_Logging_Hdr_T;

typedef struct TrackObject_Tag {
   uint16_t K_Unused16_2;
   uint8_t K_Unused8_2;
   unsigned8_t object_class;
   float32_t width;
   float32_t length;
   float32_t heading_rate;
   float32_t heading;
   float32_t tangential_accel;
   float32_t speed;
   float32_t vcs_lat_vel_rel;
   float32_t vcs_long_vel_rel;
   float32_t vcs_lat_accel;
   float32_t vcs_lat_vel;
   float32_t vcs_lat_posn;
   float32_t vcs_long_accel;
   float32_t vcs_long_vel;
   float32_t vcs_long_posn;
   uint8_t K_Unused8_1;
   unsigned8_t stage_age;
   unsigned8_t age;
   unsigned8_t status;
   unsigned32_t id;
} TrackObject_T;

typedef struct Detections_Info_Logging_Tag {
   unsigned16_t radar_data_valid;
   uint8_t K_Unused8_1;
   unsigned8_t LookType;
   unsigned8_t LookID;
   unsigned8_t timestamp_consistency;
   unsigned8_t AutoAlignElevationQF;
   unsigned8_t AutoAlignAzimuthQF;
   unsigned32_t ScanIndex;
   unsigned32_t Count;
   float32_t timestamp;
   float32_t AutoAlignElevation;
   float32_t AutoAlignAzimuth;
} Detections_Info_Logging_T;

typedef struct Detections_Tag {
   bitfield8_t k_unused_bits1 : 4;
   bitfield8_t bistatic : 1;
   bitfield8_t nd_target : 1;
   bitfield8_t super_res_target : 1;
   bitfield8_t host_veh_clutter : 1;
   unsigned8_t valid;
   unsigned8_t elevation_confidence;
   unsigned8_t azimuth_confidence;
   float32_t existence_probability;
   float32_t multi_target_probability;
   float32_t std_rcs;
   float32_t std_range;
   float32_t std_range_rate;
   float32_t std_azimuth;
   float32_t std_elevation;
   float32_t snr;
   float32_t amplitude;
   float32_t range;
   float32_t range_rate;
   float32_t azimuth;
   float32_t elevation;
} Detections_T;

typedef struct Detections_Logging_Tag {
   Detections_Info_Logging_T dets_info;
   Detections_T dets_float[NUMBER_OF_SELF_Detections];
} Detections_Logging_T;

typedef struct Vehicle_Data_Input_Tag {
   uint16_t K_Unused16_1;
   uint8_t K_Unused8_1;
   unsigned8_t f_traffic_side;
   unsigned8_t f_trailer_present;
   unsigned8_t f_reverse_gear;
   unsigned8_t turn_signal;
   unsigned8_t prndl;
   unsigned32_t vehicle_data_buff_timestamp;
   float32_t vcs_lat_acc;
   float32_t vcs_long_acc;
   float32_t curve_radius;
   float32_t host_vehicle_width;
   float32_t host_vehicle_length;
   float32_t lane_center_offset_external;
   float32_t lane_width_external;
   float32_t rear_axle_position;
   float32_t rear_axle_steering_angle;
   float32_t steering_angle;
   float32_t yawrate;
   float32_t abs_speed;
} Vehicle_Data_Input_T;

typedef struct MOUNTING_POSITION_VALUES_Tag {
   float32_t vcs_z_position;
   float32_t vcs_lon_position;
   float32_t vcs_lat_position;
   float32_t boresight_angle;
   float32_t azimuth_polarity;
} MOUNTING_POSITION_VALUES_T;

typedef struct Vehicle_Geometry_Tag {
   float32_t rear_axle_pos;
   float32_t vehicle_length;
   float32_t vehicle_width;
   float32_t vcs_long_offset;
   float32_t vcs_lat_offset;
} Vehicle_Geometry_T;

typedef struct DSPACE_Common_Logging_Data_Tag {
   Detections_Logging_T bpil_right_detection;
   Detections_Logging_T bpil_left_detection;
   Detections_Logging_T front_center_detection;
   Detections_Logging_T rear_left_detection;
   Detections_Logging_T rear_right_detection;
   Detections_Logging_T front_left_detection;
   Detections_Logging_T front_right_detection;
   TrackObject_T virtual_track[SIMULATED_TRACKS];
   Vehicle_Data_Input_T vehicle_input;
   MOUNTING_POSITION_VALUES_T Mounting_Values_BL;
   MOUNTING_POSITION_VALUES_T Mounting_Values_BR;
   MOUNTING_POSITION_VALUES_T Mounting_Values_FC;
   MOUNTING_POSITION_VALUES_T Mounting_Values_FR;
   MOUNTING_POSITION_VALUES_T Mounting_Values_FL;
   MOUNTING_POSITION_VALUES_T Mounting_Values_RR;
   MOUNTING_POSITION_VALUES_T Mounting_Values_RL;
   Vehicle_Geometry_T Vehicle_Geometry;
   uint16_t K_Unused16_2;
   unsigned8_t customer_id;
   unsigned8_t radar_position;
   unsigned32_t time_stamp;
   unsigned32_t utc_time;
   uint16_t K_Unused16_1;
   unsigned16_t running_counter;
   Dspace_Logging_Hdr_T Header;
} DSPACE_Common_Logging_Data_T;

extern void Print_DSPACE_COMMON_INPUT_STRUCTURE_Traces_Header(FILE *CfilePtr[], DSPACE_Common_Logging_Data_T *debug);
extern void Print_DSPACE_COMMON_INPUT_STRUCTURE_Traces_Data(FILE *CfilePtr[], DSPACE_Common_Logging_Data_T *debug, unsigned int Scan_Index_Self);
extern void Print_DSPACE_COMMON_INPUT_STRUCTURE_Xml_Traces(FILE *CfilePtr, DSPACE_Common_Logging_Data_T *debug);
extern void Reverse_Array_DSPACE_COMMON_INPUT_STRUCTURE(DSPACE_Common_Logging_Data_T *debug);
extern int Get_DSPACE_COMMON_INPUT_STRUCTURE_CSV_Split_Files_Num_Count();
#endif /*PC_Resim*/

#pragma pack(pop, save_pack)
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 09-05-2023     10:59:15    jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/

#endif /*DSPACE_COMMON_INPUT_STRUCTURE_H*/
