#ifndef OSI_INPUT_STRUCTURE_H
#define OSI_INPUT_STRUCTURE_H

/********************************************************************************************
 * Copyright 2007 Delphi Technologies, Inc., All Rights Reserved
 * XML uses version 2 of the base file.
 * File Name: OSI_INPUT_STRUCTURE
 * Created:	 04-06-2020 	 09:05:59
 * From XML file: OSI_INPUT_STRUCTURE.xml
 * Set Description:        Logging Structure/Interface structure
 * Tool Version: Major Version : 4,Minor Version 1
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

// This is added to convert the structures in this file to 4 byte padding
#pragma pack(push, save_pack)
#pragma pack(push, 4)

/*Macros For ARRAY Sizes*/
#define SIMULATED_TRACKS (64)
/*Macro For Structure Version*/
#define OSI_INPUT_STRUCTURE_VERSION (2)
/*Macro for Stream id,This is dummy ID for testing */
#define OSI_LOGGING_DATA_ID (67)
/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_OSI_INPUT_STRUCTURE (3080)

/*Macro for size of Sub structures*/
#define SIZE_OF_Ref_TrackObject  (48)
#define SIZE_OF_Ref_Logging_Hdr  (8)
#define SIZE_OF_Ref_Logging_Data (3080)

#ifndef PC_RESIM
typedef struct Ref_TrackObject_Tag /*Offset Start byte of the Structure Ref_TrackObject is 0 bytes*/
{
   float32_T vcs_long_posn;
   float32_T vcs_long_vel;
   float32_T vcs_long_accel;
   float32_T vcs_lat_posn;
   float32_T vcs_lat_vel;
   float32_T vcs_lat_accel;
   float32_T vcs_long_vel_rel;
   float32_T vcs_lat_vel_rel;
   float32_T speed;
   float32_T heading;
   float32_T length;
   float32_T width;
} Ref_TrackObject_T;
typedef struct Ref_Logging_Hdr_Tag /*Offset Start byte of the Structure Ref_Logging_Hdr is 48 bytes*/
{
   unsigned16_T Sec_Checksum;
   unsigned16_T Sec_Compatibility;
   unsigned32_T Sec_Size;
} Ref_Logging_Hdr_T;
typedef struct Ref_Logging_Data_Tag /*Offset Start byte of the Structure Ref_Logging_Data is 56 bytes*/
{
   Ref_TrackObject_T object[SIMULATED_TRACKS];
   Ref_Logging_Hdr_T Header;
} Ref_Logging_Data_T;
#else
typedef struct Ref_TrackObject_Tag {
   float32_T width;
   float32_T length;
   float32_T heading;
   float32_T speed;
   float32_T vcs_lat_vel_rel;
   float32_T vcs_long_vel_rel;
   float32_T vcs_lat_accel;
   float32_T vcs_lat_vel;
   float32_T vcs_lat_posn;
   float32_T vcs_long_accel;
   float32_T vcs_long_vel;
   float32_T vcs_long_posn;
} Ref_TrackObject_T;
typedef struct Ref_Logging_Hdr_Tag {
   unsigned32_T Sec_Size;
   unsigned16_T Sec_Compatibility;
   unsigned16_T Sec_Checksum;
} Ref_Logging_Hdr_T;
typedef struct Ref_Logging_Data_Tag {
   Ref_Logging_Hdr_T Header;
   Ref_TrackObject_T object[SIMULATED_TRACKS];
} Ref_Logging_Data_T;
extern void Print_OSI_INPUT_STRUCTURE_Traces_Header(FILE *CfilePtr, Ref_Logging_Data_T *debug);
extern void Print_OSI_INPUT_STRUCTURE_Traces_Data(FILE *CfilePtr, Ref_Logging_Data_T *debug);
extern void Print_OSI_INPUT_STRUCTURE_Xml_Traces(FILE *CfilePtr, Ref_Logging_Data_T *debug);
extern void Reverse_Array_OSI_INPUT_STRUCTURE(Ref_Logging_Data_T *debug);
#endif /*PC_Resim*/

#pragma pack(pop, save_pack)
#endif /*OSI_INPUT_STRUCTURE_H*/
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 04-06-2020 	 09:05:59	 jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/
