#ifndef RADAR_ECU_INTERNAL_CORE1_H
#define RADAR_ECU_INTERNAL_CORE1_H

/********************************************************************************************
 * Copyright 2007 Delphi Technologies, Inc., All Rights Reserved
 * XML uses version 2 of the base file.
 * File Name: RADAR_ECU_INTERNAL_CORE1
 * Created:	 04-09-2020 	 13:45:28
 * From XML file: RADAR_ECU_INTERNAL_CORE1.xml
 * Set Description:        Logging Structure/Interface structure
 * Tool Version: Major Version : 4,Minor Version 3
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

/*Macros For ARRAY Sizes*/
#define RADAR_ECU__INTERNAL_CORE1_ID (95)
#define DATA_SIZE                    (1424)
/*Macro For Structure Version*/
#define RADAR_ECU_INTERNAL_CORE1_VERSION (2)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_RADAR_ECU_INTERNAL_CORE1 (1424)

/*Macro for size of Sub structures*/
#define SIZE_OF_Radar_ECU_Internal_CORE1 (1424)

#ifndef UDP_LITTLE_ENDIAN_BYTE_ORDER_STRUCTURE
typedef struct Radar_ECU_Internal_CORE1_Tag /*Offset Start byte of the Structure Radar_ECU_Internal_CORE1 is 0 bytes*/
{
   unsigned8_T Tracker_Internal_Data[DATA_SIZE];
} Radar_ECU_Internal_CORE1_T;
#else
typedef struct Radar_ECU_Internal_CORE1_Tag {
   unsigned8_T Tracker_Internal_Data[DATA_SIZE];
} Radar_ECU_Internal_CORE1_T;
extern void Print_RADAR_ECU_INTERNAL_CORE1_Traces_Header(FILE *CfilePtr, Radar_ECU_Internal_CORE1_T *debug);
extern void Print_RADAR_ECU_INTERNAL_CORE1_Traces_Data(FILE *CfilePtr, Radar_ECU_Internal_CORE1_T *debug);
extern void Print_RADAR_ECU_INTERNAL_CORE1_Xml_Traces(FILE *CfilePtr, Radar_ECU_Internal_CORE1_T *debug);
extern void Reverse_Array_RADAR_ECU_INTERNAL_CORE1(Radar_ECU_Internal_CORE1_T *debug);
#endif /*PC_Resim*/

#endif /*RADAR_ECU_INTERNAL_CORE1_H*/
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 04-09-2020 	 13:45:28	 jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/
