#ifndef RADAR_ECU_CALIBRATION_H
#define RADAR_ECU_CALIBRATION_H

/********************************************************************************************
 * Copyright 2007 Delphi Technologies, Inc., All Rights Reserved
 * XML uses version 7 of the base file.
 * File Name: RADAR_ECU_CALIBRATION
 * Created:	 04-09-2020 	 13:50:51
 * From XML file: RADAR_ECU_CALIBRATION.xml
 * Set Description:        Logging Structure/Interface structure
 * Tool Version: Major Version : 4,Minor Version 3
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

/*Macros For ARRAY Sizes*/
#define RADAR_ECU_CALIBRATION_ID         (94)
#define MAX_NUMBER_OF_SENSORS_CALS_LOG   (4)
#define ANT_SENS_SCS_AZIM_DEG_ARRAY_SIZE (18)
#define ANT_SENS_SEC_RNG_90_ARRAY_SIZE   (18)
#define ANT_SENS_SEC_RNG_50_ARRAY_SIZE   (18)
/*Macro For Structure Version*/
#define RADAR_ECU_CALIBRATION_VERSION (8)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_RADAR_ECU_CALIBRATION (312)

/*Macro for size of Sub structures*/
#define SIZE_OF_Calibration_Hdr       (12)
#define SIZE_OF_CAF_Data              (0)
#define SIZE_OF_F360_calib            (0)
#define SIZE_OF_radar_sensor          (0)
#define SIZE_OF_Antenna_Sensor        (216)
#define SIZE_OF_Radar_ECU_calibration (312)

/*Temporary fix - By Revanth*/
typedef struct
{
   uint32_t Section_Size;
   uint16_t version;
   uint16_t Section_Compatibility;
   uint16_t Cal_Chk_Sum;
   uint8_t Chk_sum_Version;
   uint8_t Cal_Type;
} H3_Hdr_T;

typedef struct
{
   /*Float variables 4 bytes aligned refers to sensor boresight angle*/
   float32_T Sensor_FL_offset_angle;
   float32_T Sensor_FR_offset_angle;
   float32_T Sensor_RL_offset_angle;
   float32_T Sensor_RR_offset_angle;

   float32_T Sensor_L_offset_angle;
   float32_T Sensor_R_offset_angle;
   float32_T PFGS_warning_yawrate_max_tu;
   float32_T PFGS_braking_yawrate_min_tu;
   float32_T PFGS_warning_yawrate_min_tu;
   float32_T PFGS_braking_yawrate_max_tu;
   float32_T Sensor_FL_offset_elevation;
   float32_T Sensor_FR_offset_elevation;
   float32_T Sensor_L_offset_elevation;
   float32_T Sensor_RL_offset_elevation;
   float32_T Sensor_RR_offset_elevation;
   float32_T Sensor_R_offset_elevation;
   float32_T SCT_MaxTimeWithoutTimeSync;
   float32_T SCT_TimeSyncDeviationThreshold;
   float32_T SFE_acute_warning_zone;
   float32_T SFE_acute_TTC;
   float32_T SFE_warning_TTC;
   /*Unsigned32 variables 4 bytes aligned*/
   unsigned32_T CDC_Client_max_transmission_rate;
   unsigned32_T CDC_Client_max_transmission_size;
   unsigned32_T PFGS_brake_forecast_max_time;
   unsigned32_T PFGS_brake_forecast_min_time;
   unsigned32_T PFGS_braking_max_time;
   unsigned32_T PFGS_braking_min_time;
   unsigned32_T PFGS_dbc_threshold_adaptation_max_time;
   unsigned32_T PFGS_dbc_threshold_adaptation_min_time;
   unsigned32_T PFGS_warning_hold_time;
   unsigned32_T PFGS_warning_max_time;
   unsigned32_T PFGS_warning_min_time;
   unsigned32_T Dummy_Byte_11;
   unsigned32_T PFGS_warning_hold_time_after_braking;
   /*Sensor positions in ego vehicle*/
   float32_T Sensor_FL_offset_lat;
   float32_T Sensor_FL_offset_long;
   float32_T Sensor_FR_offset_lat;
   float32_T Sensor_FR_offset_long;
   float32_T Sensor_RL_offset_lat;
   float32_T Sensor_RL_offset_long;
   float32_T Sensor_RR_offset_lat;
   float32_T Sensor_RR_offset_long;

   signed16_T Sensor_L_offset_lat;
   signed16_T Sensor_L_offset_long;
   signed16_T Sensor_R_offset_lat;
   signed16_T Sensor_R_offset_long;
   signed16_T VCS_offset_lat;
   signed16_T VCS_offset_long;
   /*Z-position of sensor in ego vehicle*/
   float32_T Sensor_FL_offset_vert;
   float32_T Sensor_FR_offset_vert;
   float32_T Sensor_RL_offset_vert;
   float32_T Sensor_RR_offset_vert;
   signed16_T Sensor_L_offset_vert;
   signed16_T Sensor_R_offset_vert;

   uint16_t LCW_max_vel_hysteresis_lower_limit;
   uint16_t LCW_max_vel_hysteresis_upper_limit;
   uint16_t SCW_fs_max_vel_hysteresis_lower_limit;
   uint16_t SCW_fs_max_vel_hysteresis_upper_limit;
   uint16_t SCW_obj_max_vel_hysteresis_lower_limit;
   uint16_t SCW_obj_max_vel_hysteresis_upper_limit;
   float32_T VEH_Length;
   float32_T VEH_Width;
   uint16_t VEH_Width_EXMI;
   uint16_t SFE_deactivation_time_exit_intention;
   uint16_t Client_transmission_cycle_time;
   uint16_t VEH_Axis_Distance;
   // uint16_t Dummy_Byte_10;/*commenting to padd the bytes*/
   /*unsigned8/signed8 variables 4 bytes aligned*/
   uint8_t DIAG_FAULT_ENABLE_TABLE[64];
   uint8_t Sensor_FL_angle_correction_array[40];
   uint8_t Sensor_FR_angle_correction_array[40];
   uint8_t Sensor_L_angle_correction_array[40];
   uint8_t Sensor_RL_angle_correction_array[40];
   uint8_t Sensor_RR_angle_correction_array[40];
   uint8_t Sensor_R_angle_correction_array[40];
   /*Polarity of sensors*/
   float32_T Sensor_FL_polarity;
   float32_T Sensor_FR_polarity;
   float32_T Sensor_RL_polarity;
   float32_T Sensor_RR_polarity;
   boolean_T FASTA_Active;
   boolean_T LCW_Enabled;
   uint8_t LCW_min_vel_hysteresis_lower_limit;
   uint8_t LCW_min_vel_hysteresis_upper_limit;
   boolean_T GetC_PFGS_Enabled;
   boolean_T RECW_Enabled;
   boolean_T SCW_Enabled;
   boolean_T LTB_Enabled;
   boolean_T ESA_Enabled;
   uint8_t SCW_fs_min_vel_hysteresis_lower_limit;
   uint8_t SCW_fs_min_vel_hysteresis_upper_limit;
   uint8_t SCW_obj_min_vel_hysteresis_lower_limit;
   uint8_t SCW_obj_min_vel_hysteresis_upper_limit;
   boolean_T SFE_Enabled;
   uint8_t SFE_activation_hysteresis_lower_limit;
   uint8_t SFE_activation_hysteresis_upper_limit;
   uint8_t SFE_delay_door_opening;
   uint8_t SFE_minimum_warning_output_time;
   uint8_t SFE_minimum_warning_time;
   signed8_T Sensor_L_polarity;
   signed8_T Sensor_R_polarity;
   boolean_T TAP_Enabled;
   uint8_t Variant;
   boolean_T CTA_enable_braking_front;
   boolean_T CTA_enable_braking_rear;
   uint8_t CTA_speedthreshold_hysteresis_kph;
   uint8_t CTA_speedthreshold_hysteresis_mph;
   uint8_t CTA_speedthreshold_kph;
   uint8_t CTA_speedthreshold_mph;
   boolean_T FCTA_Enabled;
   boolean_T RCTA_Enabled;
   boolean_T LCW_enable_dropback_handler;
   boolean_T LCW_enable_plausibility_check_environment;
   boolean_T LCW_enable_subfunction_blind_spot_area;
   boolean_T LCW_enable_subfunction_dynamic_area;
   boolean_T LCW_enable_subfunction_simultaneous_lane_change;
   uint8_t PFGS_braking_ped_vmax_ego_tu_all;
   uint8_t PFGS_country;
   boolean_T PFGS_enable_coll_crit_obj_pfgs;
   boolean_T PFGS_enable_dbc_threshold_adaption_tu_all;
   boolean_T PFGS_enable_debug_signals;
   boolean_T PFGS_enable_error_ccm;
   boolean_T PFGS_enable_hapt_warning_tu_all;
   uint8_t PFGS_enable_pfgs_2_haf;
   boolean_T PFGS_enable_pfgs_forced_switch_on;
   boolean_T PFGS_enable_warning_x_tu_all;
   signed8_T PFGS_max_braking;
   uint8_t PFGS_preponed_warning_vmin_ego_bic;
   uint8_t PFGS_preponed_warning_vmin_ego_ped;
   uint8_t PFGS_prewarning_vmin_ego_tu_all;
   uint8_t PFGS_steering_angle_fro_axle_eff_max_left;
   uint8_t PFGS_steering_angle_fro_axle_eff_max_right;
   uint8_t PFGS_warning_vmax_ego_tu_all;
   uint8_t PFGS_warning_vmin_ego_tu_all;
   boolean_T RECW_enable_m_drive;
   uint8_t RECW_type;
   boolean_T SCW_enable_dynamic_objects;
   boolean_T SCW_enable_guardrail;
   boolean_T SFE_enable_lock_door;
   boolean_T SFE_enable_output_signals;
   boolean_T TAP_enable_plausibility_check_environment;
   boolean_T TAP_enable_subfunction_dynamic_area;
   boolean_T TAP_enable_subfunction_turning_area;
   boolean_T VAR_adcam_available;
   uint8_t VAR_steering;
   boolean_T VAR_trailer_available;
   //	uint8_t  Dummy_Byte_01;
   // uint8_t  Dummy_Byte_02;
   uint8_t Dummy_Byte_03;
   uint8_t C_el_deg_con_speed_threshold;
   uint8_t C_el_deg_con_number_objects;
   boolean_T DEV_enable_udp_logging;
   uint8_t PFGS_warning_max_sec_turnsignal_status;
   uint8_t SFE_variant;
   uint8_t PFGS_preponed_warning_vmax_ego_tu_all;
   uint8_t PFGS_braking_ped_vmax_ego_st_all;
   boolean_T PFGS_enable_dbc_threshold_adaption_st_all;
   boolean_T PFGS_enable_srr_visibility_ccm;
   boolean_T PFGS_enable_brake_forecast_tu_all;
   uint8_t PFGS_warning_vmin_ego_st_all;
   boolean_T PFGS_ignore_e2e_errors;
   uint8_t PFGS_preponed_warning_vmin_ego_tu_all;
   boolean_T PFGS_enable_brake_forecast_st_all;
   boolean_T PFGS_enable_hapt_warning_st_all;
   uint8_t PFGS_preponed_warning_vmin_ego_st_all;
   uint8_t PFGS_enable_braking_tu_all;
   uint8_t PFGS_braking_ped_vmin_ego_tu_all;
   boolean_T PFGS_ignore_radar_blindness;
   boolean_T PFGS_enable_warning_tu_all;
   boolean_T PFGS_enable_preponed_warning_st_all;
   boolean_T PFGS_enable_preponed_warning_tu_all;
   boolean_T PFGS_enable_warning_x_st_all;
   uint8_t PFGS_warning_vmax_ego_st_all;
   uint8_t PFGS_preponed_warning_vmax_ego_st_all;
   uint8_t PFGS_enable_braking_st_all;
   uint8_t PFGS_braking_ped_vmin_ego_st_all;
   boolean_T PFGS_enable_warning_st_all;
   boolean_T CDC_Client_enabled;
   uint8_t PFGS_Enabled_CRC;
   uint8_t PFGS_brake_forecast_max_time_CRC;
   uint8_t PFGS_brake_forecast_min_time_CRC;
   uint8_t PFGS_braking_max_time_CRC;
   uint8_t PFGS_braking_min_time_CRC;
   uint8_t PFGS_braking_vmax_ego_st_all;
   uint8_t PFGS_braking_vmax_ego_st_all_CRC;
   uint8_t PFGS_braking_vmax_ego_tu_all;
   uint8_t PFGS_braking_vmax_ego_tu_all_CRC;
   uint8_t PFGS_braking_vmin_ego_st_all;
   uint8_t PFGS_braking_vmin_ego_st_all_CRC;
   uint8_t PFGS_braking_vmin_ego_tu_all;
   uint8_t PFGS_braking_vmin_ego_tu_all_CRC;
   uint8_t PFGS_braking_yawrate_max_tu_CRC;
   uint8_t PFGS_braking_yawrate_min_tu_CRC;
   uint8_t PFGS_country_CRC;
   uint8_t PFGS_dbc_threshold_adaptation_max_time_CRC;
   uint8_t PFGS_dbc_threshold_adaptation_min_time_CRC;
   uint8_t PFGS_enable_brake_forecast_st_all_CRC;
   uint8_t PFGS_enable_brake_forecast_tu_all_CRC;
   uint8_t PFGS_enable_braking_st_all_CRC;
   uint8_t PFGS_enable_braking_tu_all_CRC;
   uint8_t PFGS_enable_coll_crit_obj_pfgs_CRC;
   uint8_t PFGS_enable_dbc_threshold_adaption_st_all_CRC;
   uint8_t PFGS_enable_dbc_threshold_adaption_tu_all_CRC;
   uint8_t PFGS_enable_debug_signals_CRC;
   uint8_t PFGS_enable_error_ccm_CRC;
   uint8_t PFGS_enable_hapt_warning_st_all_CRC;
   uint8_t PFGS_enable_hapt_warning_tu_all_CRC;
   uint8_t PFGS_enable_hysteresis_vmax_ego;
   uint8_t PFGS_enable_hysteresis_vmax_ego_CRC;
   uint8_t PFGS_enable_hysteresis_vmin_ego;
   uint8_t PFGS_enable_hysteresis_vmin_ego_CRC;
   uint8_t PFGS_enable_pfgs_2_haf_CRC;
   uint8_t PFGS_enable_pfgs_forced_switch_on_CRC;
   uint8_t PFGS_enable_preponed_warning_st_all_CRC;
   uint8_t PFGS_enable_preponed_warning_tu_all_CRC;
   uint8_t PFGS_enable_srr_visibility_ccm_CRC;
   uint8_t PFGS_enable_warning_st_all_CRC;
   uint8_t PFGS_enable_warning_tu_all_CRC;
   uint8_t PFGS_enable_warning_x_st_all_CRC;
   uint8_t PFGS_enable_warning_x_tu_all_CRC;
   uint8_t PFGS_ignore_e2e_errors_CRC;
   uint8_t PFGS_ignore_radar_blindness_CRC;
   uint8_t PFGS_max_braking_CRC;
   uint8_t PFGS_preponed_warning_driver_attention_st_all;
   uint8_t PFGS_preponed_warning_driver_attention_st_all_CRC;
   uint8_t PFGS_preponed_warning_driver_attention_tu_all;
   uint8_t PFGS_preponed_warning_driver_attention_tu_all_CRC;
   uint8_t PFGS_preponed_warning_vmax_ego_st_all_CRC;
   uint8_t PFGS_preponed_warning_vmax_ego_tu_all_CRC;
   uint8_t PFGS_preponed_warning_vmin_ego_st_all_CRC;
   uint8_t PFGS_preponed_warning_vmin_ego_tu_all_CRC;
   uint8_t PFGS_steering_angle_fro_axle_eff_max_left_CRC;
   uint8_t PFGS_steering_angle_fro_axle_eff_max_right_CRC;
   uint8_t PFGS_warning_hold_time_CRC;
   uint8_t PFGS_warning_max_sec_turnsignal_status_CRC;
   uint8_t PFGS_warning_max_time_CRC;
   uint8_t PFGS_warning_min_time_CRC;
   uint8_t PFGS_warning_vmax_ego_st_all_CRC;
   uint8_t PFGS_warning_vmax_ego_tu_all_CRC;
   uint8_t PFGS_warning_vmin_ego_st_all_CRC;
   uint8_t PFGS_warning_vmin_ego_tu_all_CRC;
   uint8_t PFGS_warning_yawrate_max_tu_CRC;
   uint8_t PFGS_warning_yawrate_min_tu_CRC;
   uint8_t Sensor_FL_offset_angle_CRC;
   uint8_t Sensor_FL_offset_elevation_CRC;
   uint8_t Sensor_FL_offset_lat_CRC;
   uint8_t Sensor_FL_offset_long_CRC;
   uint8_t Sensor_FL_offset_vert_CRC;
   uint8_t Sensor_FL_polarity_CRC;
   uint8_t Sensor_FR_offset_angle_CRC;
   uint8_t Sensor_FR_offset_elevation_CRC;
   uint8_t Sensor_FR_offset_lat_CRC;
   uint8_t Sensor_FR_offset_long_CRC;
   uint8_t Sensor_FR_offset_vert_CRC;
   uint8_t Sensor_FR_polarity_CRC;
   uint8_t Sensor_L_offset_angle_CRC;
   uint8_t Sensor_L_offset_elevation_CRC;
   uint8_t Sensor_L_offset_lat_CRC;
   uint8_t Sensor_L_offset_long_CRC;
   uint8_t Sensor_L_offset_vert_CRC;
   uint8_t Sensor_L_polarity_CRC;
   uint8_t Sensor_RL_offset_angle_CRC;
   uint8_t Sensor_RL_offset_elevation_CRC;
   uint8_t Sensor_RL_offset_lat_CRC;
   uint8_t Sensor_RL_offset_long_CRC;
   uint8_t Sensor_RL_offset_vert_CRC;
   uint8_t Sensor_RL_polarity_CRC;
   uint8_t Sensor_RR_offset_angle_CRC;
   uint8_t Sensor_RR_offset_elevation_CRC;
   uint8_t Sensor_RR_offset_lat_CRC;
   uint8_t Sensor_RR_offset_long_CRC;
   uint8_t Sensor_RR_offset_vert_CRC;
   uint8_t Sensor_RR_polarity_CRC;
   uint8_t Sensor_R_offset_angle_CRC;
   uint8_t Sensor_R_offset_elevation_CRC;
   uint8_t Sensor_R_offset_lat_CRC;
   uint8_t Sensor_R_offset_long_CRC;
   uint8_t Sensor_R_offset_vert_CRC;
   uint8_t Sensor_R_polarity_CRC;
   uint8_t VAR_steering_CRC;
   uint8_t VAR_trailer_available_CRC;
   uint8_t VCS_offset_lat_CRC;
   uint8_t VCS_offset_long_CRC;
   uint8_t VEH_Axis_Distance_CRC;
   uint8_t VEH_Length_CRC;
   uint8_t VEH_Width_CRC;
   uint8_t VEH_Width_EXMI_CRC;
   uint8_t Variant_CRC;
   uint8_t CountryType_ASIL_CRC;
   uint8_t CountryType_ASIL_PDU[1];
   uint8_t T_OAV;
   uint8_t T_OAV_CRC;
   uint8_t Steering_ASIL_CRC;
   uint8_t Steering_ASIL_PDU[1];
   uint8_t Vehicle_ASIL_CRC;
   uint8_t Vehicle_ASIL_PDU;
   boolean_T DBG_SDaT_PCAN_FL;
   boolean_T DBG_SDaT_PCAN_FR;
   boolean_T DBG_SDaT_PCAN_RL;
   boolean_T DBG_SDaT_PCAN_RR;
   boolean_T LCW_enable_basic_lane_model;
   boolean_T LCW_enable_extended_lane_model;
   boolean_T LCW_enable_subfunction_AWA;
   boolean_T CTA_acute_warning_same_time_with_advance_warning;
   uint8_t SCT_MaxTimeWithoutTimeSync_CRC;
   uint8_t SCT_TimeSyncDeviationThreshold_CRC;
   uint8_t C_LCW_trailer_mode;
   uint8_t C_Internal_Reflections_Enable_Function;
   uint8_t C_el_deg_con_range;
   uint8_t C_el_deg_con_angle_elevation;
   uint8_t Dummy_Byte_08;
   uint8_t Dummy_Byte_09;
   uint8_t PFGS_warning_silent_time;
   uint8_t PFGS_braking_silent_time;
   uint8_t C_LCW_enable_fallback_handle;
   uint8_T Dummy_Byte_12;
   uint8_T Dummy_Byte_13;
   uint8_T Dummy_Byte_14;
   uint8_T Dummy_Byte_15;
   uint8_T Dummy_Byte_16;
   uint8_T Dummy_Byte_17;
   uint16_T Dummy_Byte_18;
   uint8_t Dummy_Byte_25;
   uint16_T Dummy_Byte_26;
   uint16_T Dummy_Byte_27;
   uint8_T C_CVW_enable_limit_zone;
   uint8_T C_CVW_limit_zone_range;
   uint8_T LCW_enable_subfunction_GBT_blind_spot;
   uint8_T RCTA_extended_pre_alert_zone;
   uint8_T SFE_minimum_gong_time;
   uint8_T C_Snow_Blockage_Enabled;
   uint8_T LCW_trailer_mode_speed_lower_limit;
   uint8_T LCW_trailer_mode_speed_upper_limit;
   boolean_T SFE_enabled_acute_warning;
   boolean_T SFE_enabled_warning_mirror;
} CAF_Param_log;

#ifndef UDP_LITTLE_ENDIAN_BYTE_ORDER_STRUCTURE
typedef struct Calibration_Hdr_Tag /*Offset Start byte of the Structure Calibration_Hdr is 0 bytes*/
{
   unsigned32_T Sec_Size;
   unsigned16_T Sec_Compatibility;
   unsigned16_T Sec_Checksum;
   unsigned16_T run_counter;
   unsigned16_T version_number;
} Calibration_Hdr_T;
typedef struct CAF_Data_Tag /*Offset Start byte of the Structure CAF_Data is 12 bytes*/
{
   H3_Hdr_T Header;
   CAF_Param_log CAF_Parameter;
} CAF_Data_T;
typedef struct F360_calib_Tag /*Offset Start byte of the Structure F360_calib is 12 bytes*/
{
   H3_Hdr_T Header;
} F360_calib_T;
typedef struct radar_sensor_Tag /*Offset Start byte of the Structure radar_sensor is 12 bytes*/
{
   H3_Hdr_T Header;
} radar_sensor_T;
typedef struct Radar_ECU_calibration_Tag /*Offset Start byte of the Structure Radar_ECU_calibration is 0 bytes*/
{
   Calibration_Hdr_T calibration_Hdr;
   CAF_Data_T CAF_data;
   F360_calib_T f360_Calib;
   radar_sensor_T Radar_Sensor;
} Radar_ECU_calibration_T;
#else
typedef struct Calibration_Hdr_Tag {
   unsigned16_T version_number;
   unsigned16_T run_counter;
   unsigned16_T Sec_Checksum;
   unsigned16_T Sec_Compatibility;
   unsigned32_T Sec_Size;
} Calibration_Hdr_T;
typedef struct CAF_Data_Tag {
   CAF_Param_log CAF_Parameter;
   H3_Hdr_T Header;
} CAF_Data_T;
typedef struct F360_calib_Tag {
   F360_Calibrations_T f360_calibrations;
   H3_Hdr_T Header;
} F360_calib_T;
typedef struct radar_sensor_Tag {
   F360_Radar_Sensor_Calib_T sensors[MAX_NUMBER_OF_SENSORS_CALS_LOG];
   H3_Hdr_T Header;
} radar_sensor_T;
typedef struct Radar_ECU_calibration_Tag {
   Calibration_Freespace_T calibration_freespace;
   radar_sensor_T Radar_Sensor;
   F360_calib_T f360_Calib;
   CAF_Data_T CAF_data;
   Scw_Calibration_T calibration_SCW;
   TA_CALIBRATION_T calibration_TA;
   Path_Tracking_Calibrations_T Path_Tracking_Calibrations;
   Ced_Calibration_T calibration_ced;
   Lcda_Calibration_T calibration_lcda;
   Recw_Calibration_T recw_calibrations;
   Cta_Calibration_T cta_calibration;
   Calibration_Hdr_T calibration_Hdr;
} Radar_ECU_calibration_T;
extern void Print_RADAR_ECU_CALIBRATION_Traces_Header(FILE *CfilePtr, Radar_ECU_calibration_T *debug);
extern void Print_RADAR_ECU_CALIBRATION_Traces_Data(FILE *CfilePtr, Radar_ECU_calibration_T *debug);
extern void Print_RADAR_ECU_CALIBRATION_Xml_Traces(FILE *CfilePtr, Radar_ECU_calibration_T *debug);
extern void Reverse_Array_RADAR_ECU_CALIBRATION(Radar_ECU_calibration_T *debug);
#endif /*PC_Resim*/

#endif /*RADAR_ECU_CALIBRATION_H*/
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 04-09-2020 	 13:50:51	 jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/
