#ifndef RADAR_ECU_CORE1_H
#define RADAR_ECU_CORE1_H

/********************************************************************************************
 * Copyright 2007 Delphi Technologies, Inc., All Rights Reserved
 * XML uses version 27 of the base file.
 * File Name: RADAR_ECU_CORE1
 * Created:	 27-01-2022 	 14:14:53
 * From XML file: RADAR_ECU_CORE1.xml
 * Set Description:        Logging Structure/Interface structure
 * Tool Version: Major Version : 4,Minor Version 3
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

// This is added to convert the structures in this file to 4 byte padding
#pragma pack(push, save_pack)
#pragma pack(push, 4)

/*Macros For ARRAY Sizes*/
#define RADAR_ECU_CORE1_ID                       (91)
#define MAX_F360_OBJECTS_LOG                     (128)
#define MAX_REDUCED_OBJECTS_LOG                  (50)
#define NUM_TOTAL_RADAR_SENSORS_LOG              (4)
#define MAX_ALL_RADAR_DETS_LOG                   (800)
#define STATE_VARIANCE_ARRAY_SIZE                (6)
#define SUPPLEMENTAL_STATE_COVARIANCE_ARRAY_SIZE (3)
#define USEFUL_FOV_ARRAY_SIZE                    (2)
#define HOST_PROPS_ARRAY_1                       (2)
#define HOST_PROPS_ARRAY_2                       (2)
#define SCL_OUT_LOG_UNUSED                       (3)
#define F360_NUM_OF_STATIC_ENV_POLYS_LOG         (6)
/*Macro For Structure Version*/
#define RADAR_ECU_CORE1_VERSION (28)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_RADAR_ECU_CORE1 (52084)

/*Macro for size of Sub structures*/
#define SIZE_OF_Radar_ECU_CORE1_Hdr           (12)
#define SIZE_OF_TimeStamp_Rader_CORE1         (8)
#define SIZE_OF_Core_1_Timing_Info            (32)
#define SIZE_OF_Tracker_Error_Info            (28)
#define SIZE_OF_Sensor_Info_Log               (68)
#define SIZE_OF_Detection_Log                 (27204)
#define SIZE_OF_Process_Detections_Log        (27476)
#define SIZE_OF_Object_Log_Extended           (172)
#define SIZE_OF_All_Objects_Log               (22028)
#define SIZE_OF_Tracker_Info_Log              (896)
#define SIZE_OF_Vehicle_Info_Log              (132)
#define SIZE_OF_ItemizedExecutionTiming_Log   (220)
#define SIZE_OF_OverallTiming_Log             (80)
#define SIZE_OF_Timing_Info_Log               (312)
#define SIZE_OF_Core_Info_Faults_Log          (4)
#define SIZE_OF_Radar_Sensor_Calib_Faults_Log (4)
#define SIZE_OF_Radar_Sensor_Faults_Log       (4)
#define SIZE_OF_Host_Info_Faults_Log          (8)
#define SIZE_OF_Input_Faults_Log              (44)
#define SIZE_OF_Output_Faults_Log             (4)
#define SIZE_OF_SCL_Output_Log                (16)
#define SIZE_OF_Functional_Safety_Faults_Log  (64)
#define SIZE_OF_F360_Adaptation_Output        (364)
#define SIZE_OF_VSE_Output_Log                (128)
#define SIZE_OF_Host_Raw_Data_Log             (48)
#define SIZE_OF_F360_Host_Props_Log           (96)
#define SIZE_OF_Tracker_Version_Info_Log      (4)
#define SIZE_OF_Partial_Blockage_Header       (16)
#define SIZE_OF_SB_BLKG_OUTPUT                (32)
#define SIZE_OF_Partial_Blockage_Log          (52)
#define SIZE_OF_F360_Static_Env_Poly_Data_Log (28)
#define SIZE_OF_F360_Static_Env_Poly_Log      (180)
#define SIZE_OF_Quick_Check_Algo_Log          (16)
#define SIZE_OF_F360_Host_Calib_Log           (52)
#define SIZE_OF_Radar_ECU_CORE1               (52084)

#ifndef UDP_LITTLE_ENDIAN_BYTE_ORDER_STRUCTURE
typedef struct Radar_ECU_CORE1_Hdr_Tag /*Offset Start byte of the Structure Radar_ECU_CORE1_Hdr is 0 bytes*/
{
   unsigned32_T Sec_Size;
   unsigned16_T Sec_Compatibility;
   unsigned16_T Sec_Checksum;
   unsigned16_T run_counter;
   unsigned16_T version_number;
} Radar_ECU_CORE1_Hdr_T;
typedef struct RECU_TimeStamp_Rader_CORE1_Tag /*Offset Start byte of the Structure TimeStamp_Rader_CORE1 is 12 bytes*/
{
   unsigned32_T time_seconds;
   unsigned32_T time_fraction;
} TimeStamp_Rader_CORE1_T;
typedef struct RECU_Core_1_Timing_Info_Tag /*Offset Start byte of the Structure Core_1_Timing_Info is 20 bytes*/
{
   TimeStamp_Rader_CORE1_T core_starttime;
   TimeStamp_Rader_CORE1_T core_endtime;
   TimeStamp_Rader_CORE1_T tracker_starttime;
   TimeStamp_Rader_CORE1_T tracker_endtime;
} Core_1_Timing_Info_T;
typedef struct RECU_Tracker_Error_Info_Tag /*Offset Start byte of the Structure Tracker_Error_Info is 52 bytes*/
{
   unsigned32_T tracker_overrun_cnt;
   unsigned32_T scan_index_FR;
   unsigned32_T scan_index_FL;
   unsigned32_T scan_index_RR;
   unsigned32_T scan_index_RL;
   unsigned32_T reserved;
   unsigned8_T tracker_overrun_flag;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_Tracker_Error_Info_T;
typedef struct RECU_Sensor_Info_Log_Tag /*Offset Start byte of the Structure Sensor_Info_Log is 80 bytes*/
{
   unsigned64_T timestamp_us;
   float32_T vcs_long_posn;
   float32_T vcs_lat_posn;
   float32_T vcs_long_vel;
   float32_T vcs_lat_vel;
   float32_T vcs_height_offset_m;
   float32_T vcs_boresight_az_angle;
   float32_T vcs_boresight_elev_angle;
   float32_T range_rate_interval_width;
   float32_T align_angle_az_rad;
   float32_T align_angle_el_rad;
   float32_T useful_fov[USEFUL_FOV_ARRAY_SIZE];
   unsigned16_T look_index;
   unsigned8_T sensorID;
   unsigned8_T f_sens_valid;
   unsigned8_T new_measurement_update;
   signed8_T mount_location;
   signed8_T sensor_type;
   signed8_T look_id;
   signed8_T radar_polarity;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_Sensor_Info_Log_T;
typedef struct RECU_Detection_Log_Tag /*Offset Start byte of the Structure Detection_Log is 148 bytes*/
{
   float32_T vcs_x[MAX_ALL_RADAR_DETS_LOG];
   float32_T vcs_y[MAX_ALL_RADAR_DETS_LOG];
   float32_T rngrate_dealiased[MAX_ALL_RADAR_DETS_LOG];
   float32_T rngrate_comp[MAX_ALL_RADAR_DETS_LOG];
   unsigned16_T num_dets;
   unsigned16_T raw_det_id[MAX_ALL_RADAR_DETS_LOG];
   unsigned16_T objTrkID[MAX_ALL_RADAR_DETS_LOG];
   unsigned16_T clusterID[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T sensorID[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T motion_status[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T wheel_spin[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_azimuth_error[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_dealiased[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_double_bounce[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_FOV_edge[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_selected_by_trk[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_close_target[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_inside_gate[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_ok_to_use[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_on_guardrail[MAX_ALL_RADAR_DETS_LOG];
   u16p0_T K_Unused16_1;
} RECU_Detection_Log_T;
typedef struct RECU_Process_Detections_Log_Tag /*Offset Start byte of the Structure Process_Detections_Log is 27352 bytes*/
{
   RECU_Sensor_Info_Log_T sensorInfoLog[NUM_TOTAL_RADAR_SENSORS_LOG];
   RECU_Detection_Log_T detsLog;
} RECU_Process_Detections_Log_T;
typedef struct RECU_Object_Log_Extended_Tag /*Offset Start byte of the Structure Object_Log_Extended is 54828 bytes*/
{
   float32_T vcs_xposn;
   float32_T vcs_yposn;
   float32_T vcs_xvel;
   float32_T vcs_yvel;
   float32_T vcs_xaccel;
   float32_T vcs_yaccel;
   float32_T vcs_heading;
   float32_T vcs_pointing;
   float32_T speed;
   float32_T curvature;
   float32_T tang_accel;
   float32_T state_variance[STATE_VARIANCE_ARRAY_SIZE];
   float32_T supplemental_state_covariance[SUPPLEMENTAL_STATE_COVARIANCE_ARRAY_SIZE];
   float32_T time_since_measurement;
   float32_T time_since_cluster_created;
   float32_T time_since_track_updated;
   float32_T len1;
   float32_T len2;
   float32_T wid1;
   float32_T wid2;
   float32_T confidenceLevel;
   float32_T time_since_stage_start;
   float32_T existence_probability;
   float32_T accuracy_length;
   float32_T accuracy_width;
   float32_T probability_pedestrian;
   float32_T probability_car;
   float32_T probability_motorcycle;
   float32_T probability_bicycle;
   float32_T probability_truck;
   float32_T probability_undet;
   unsigned16_T trkID;
   unsigned16_T ndets;
   unsigned16_T num_reduced_dets;
   unsigned8_T reducedID;
   unsigned8_T trk_fltr_type;
   unsigned8_T status;
   unsigned8_T reducedStatus;
   unsigned8_T init_scheme;
   unsigned8_T object_class;
   unsigned8_T f_crossing;
   unsigned8_T f_moving;
   unsigned8_T f_moveable;
   unsigned8_T f_oncoming;
   unsigned8_T f_vehicular_trk;
   unsigned8_T f_onguardrail;
   unsigned8_T f_fast_moving;
   unsigned8_T underdrivable_status;
} RECU_Object_Log_Extended_T;
typedef struct RECU_All_Objects_Log_Tag /*Offset Start byte of the Structure All_Objects_Log is 55000 bytes*/
{
   unsigned64_T object_list_timestamp;
   unsigned32_T tracker_index;
   RECU_Object_Log_Extended_T obj[MAX_F360_OBJECTS_LOG];
} RECU_All_Objects_Log_T;
typedef struct RECU_Tracker_Info_Log_Tag /*Offset Start byte of the Structure Tracker_Info_Log is 77028 bytes*/
{
   unsigned64_T timestamp_us;
   unsigned64_T object_list_timestamp;
   unsigned64_T sensor_timestamp_us[NUM_TOTAL_RADAR_SENSORS_LOG];
   float32_T elapsed_time_s;
   unsigned32_T sw_version_buildID;
   unsigned32_T tracker_index;
   unsigned32_T vehicle_index;
   unsigned16_T active_obj_ids[MAX_F360_OBJECTS_LOG];
   unsigned16_T inactive_obj_ids[MAX_F360_OBJECTS_LOG];
   unsigned16_T num_active_objs;
   unsigned16_T reduced_active_obj_ids[MAX_REDUCED_OBJECTS_LOG];
   unsigned16_T reduced_inactive_obj_ids[MAX_REDUCED_OBJECTS_LOG];
   unsigned16_T reduced_obj_ids[MAX_REDUCED_OBJECTS_LOG];
   unsigned16_T reduced_num_active_objs;
   unsigned16_T sensor_look_index[NUM_TOTAL_RADAR_SENSORS_LOG];
   unsigned16_T num_active_clusters;
   unsigned16_T number_of_historic_detections;
   unsigned8_T sw_version_major;
   unsigned8_T sw_version_minor;
   unsigned8_T sw_version_patch;
   u8p0_T K_Unused8_1;
} RECU_Tracker_Info_Log_T;
typedef struct RECU_Vehicle_Info_Log_Tag /*Offset Start byte of the Structure Vehicle_Info_Log is 77924 bytes*/
{
   double64_T global_time_sync_s;
   double64_T timestamp_s;
   float32_T align_angle_az_rad[NUM_TOTAL_RADAR_SENSORS_LOG];
   float32_T align_angle_el_rad[NUM_TOTAL_RADAR_SENSORS_LOG];
   float32_T world_x;
   float32_T world_y;
   float32_T rear_cornering_compliance;
   float32_T raw_speed;
   float32_T steering_angle_rad;
   float32_T raw_yaw_rate_rad;
   float32_T dist_rear_axle_to_vcs_m;
   float32_T speed_correction_factor;
   float32_T speed;
   float32_T acceleration;
   float32_T vcs_speed;
   float32_T vcs_lat_acceleration;
   float32_T vcs_long_acceleration;
   float32_T heading;
   float32_T delta_pointing;
   float32_T delta_position_x;
   float32_T delta_position_y;
   float32_T vcs_sideslip;
   float32_T curvature_rear;
   signed32_T vehicle_index;
   unsigned8_T prndl;
   unsigned8_T f_reverse_gear;
   boolean_T f_trailer_present;
   u8p0_T K_Unused8_1;
} RECU_Vehicle_Info_Log_T;
typedef struct RECU_ItemizedExecutionTiming_Log_Tag /*Offset Start byte of the Structure ItemizedExecutionTiming_Log is 78056 bytes*/
{
   float32_T host_state_update;
   float32_T calc_mov_stat_thresh;
   float32_T calc_obj_mov_stat_thresh;
   float32_T update_sensor_valid_info;
   float32_T configure_rdot_interval_compability;
   float32_T sensor_motion;
   float32_T update_det_hist;
   float32_T update_det_posn_hist;
   float32_T ego_motion_compensate_dets;
   float32_T detect_wheelspin;
   float32_T check_az_el_conf;
   float32_T mark_out_det_pairs;
   float32_T detect_azimuth_errors;
   float32_T sensor_capability_module;
   float32_T double_bounce_detection_countermeasure;
   float32_T time_update_obj_trks_cca;
   float32_T time_update_obj_trks_ctca;
   float32_T split_tracks;
   float32_T kill_coasted_tracks;
   float32_T assoc_dets_with_obj_trks;
   float32_T assoc_countermeasure;
   float32_T store_det_data;
   float32_T det_downselect;
   float32_T cluster_moving_detections;
   float32_T cluster_leftover_detections;
   float32_T initialize_clusters;
   float32_T assoc_unconf_obj_trks;
   float32_T merge_tracks;
   float32_T pseudo_estimations;
   float32_T initialize_tracked_objects;
   float32_T obj_trk_status_bookkeeping;
   float32_T adjust_fltr_type_dependent_params;
   float32_T obj_trk_properties;
   float32_T cancel_new_updated_trk_overlapping_confirmed_trks;
   float32_T adjust_overlapping_confirmed_trks;
   float32_T det_mean_var;
   float32_T underdrivability_classification;
   float32_T mark_object_tracks_next_to_sensors;
   float32_T sanity_check;
   float32_T reserve1;
   float32_T reserve2;
   float32_T reserve3;
   float32_T reserve4;
   float32_T reserve5;
   float32_T msmt_update_obj_trks_ctca;
   float32_T get_pseudo_hdg_msmt_from_associated_dets_sum;
   float32_T get_pseudo_hdg_msmt_from_associated_dets_mean;
   float32_T assoc_unconf_obj_trks_sub_time_1;
   float32_T assoc_unconf_obj_trks_sub_time_2;
   float32_T assoc_unconf_obj_trks_sub_time_3;
   float32_T assoc_unconf_obj_trks_sub_time_4;
   float32_T assoc_unconf_obj_trks_sub_time_5;
   float32_T assoc_unconf_obj_trks_sub_time_6;
   float32_T time_update_obj_trks_ccv;
   float32_T msmt_update_obj_trks_ccv;
} RECU_ItemizedExecutionTiming_Log_T;
typedef struct RECU_OverallTiming_Log_Tag /*Offset Start byte of the Structure OverallTiming_Log is 78276 bytes*/
{
   float32_T time_taken_core_tracker;
   float32_T time_taken_core_and_udp_packing;
   float32_T time_taken_full_tracker_DLL_func;
   float32_T sensor_preprocessing;
   float32_T time_update_tracks;
   float32_T pre_association_track_management;
   float32_T detection_to_track_association;
   float32_T clustering;
   float32_T cluster_grouping;
   float32_T track_grouping;
   float32_T measurement_update_tracks;
   float32_T initialize_tracks;
   float32_T post_update_track_adjustments;
   float32_T track_classification;
   float32_T track_validity;
   float32_T track_downselection;
   float32_T e2e_protection;
   float32_T occlusion;
   float32_T lsc_module;
   float32_T concrete_wall_detector;
} RECU_OverallTiming_Log_T;
typedef struct RECU_Timing_Info_Log_Tag /*Offset Start byte of the Structure Timing_Info_Log is 78356 bytes*/
{
   float32_T timestamp;
   float32_T prev_timestamp;
   RECU_ItemizedExecutionTiming_Log_T itemized_execution_times;
   RECU_OverallTiming_Log_T overall_execution_times;
   unsigned32_T tracker_index;
} RECU_Timing_Info_Log_T;
typedef struct RECU_Core_Info_Faults_Log_Tag /*Offset Start byte of the Structure Core_Info_Faults_Log is 78668 bytes*/
{
   unsigned8_T time_us_no_increase;
   unsigned8_T cnt_loops_no_increase;
   unsigned8_T elapsed_time_below_lower_limit;
   unsigned8_T elapsed_time_above_upper_limit;
} RECU_Core_Info_Faults_Log_T;
typedef struct RECU_Radar_Sensor_Calib_Faults_Log_Tag /*Offset Start byte of the Structure Radar_Sensor_Calib_Faults_Log is 78672 bytes*/
{
   unsigned8_T mounting_pos_is_invalid;
   unsigned8_T polarity_is_invalid;
   unsigned8_T boresight_angle_is_invalid;
   u8p0_T K_Unused8_1;
} RECU_Radar_Sensor_Calib_Faults_Log_T;
typedef struct RECU_Radar_Sensor_Faults_Log_Tag /*Offset Start byte of the Structure Radar_Sensor_Faults_Log is 78676 bytes*/
{
   unsigned8_T look_index_no_increase;
   unsigned8_T sensor_vs_tracker_timestamp_divergence;
   u16p0_T K_Unused16_1;
} RECU_Radar_Sensor_Faults_Log_T;
typedef struct RECU_Host_Info_Faults_Log_Tag /*Offset Start byte of the Structure Host_Info_Faults_Log is 78680 bytes*/
{
   unsigned8_T vehicle_index_no_increase;
   unsigned8_T host_speed_invalid;
   unsigned8_T host_yawrate_invalid;
   unsigned8_T host_longitudinal_acceleration_invalid;
   unsigned8_T host_lateral_acceleration_invalid;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_Host_Info_Faults_Log_T;
typedef struct RECU_Input_Faults_Log_Tag /*Offset Start byte of the Structure Input_Faults_Log is 78688 bytes*/
{
   RECU_Core_Info_Faults_Log_T core_info;
   RECU_Radar_Sensor_Calib_Faults_Log_T sensors_calibs[NUM_TOTAL_RADAR_SENSORS_LOG];
   RECU_Radar_Sensor_Faults_Log_T sensors[NUM_TOTAL_RADAR_SENSORS_LOG];
   RECU_Host_Info_Faults_Log_T host_info;
} RECU_Input_Faults_Log_T;
typedef struct RECU_Output_Faults_Log_Tag /*Offset Start byte of the Structure Output_Faults_Log is 78732 bytes*/
{
   unsigned8_T f_track_positions_faulty;
   unsigned8_T f_track_velocities_faulty;
   unsigned8_T f_track_accelerations_faulty;
   u8p0_T K_Unused8_1;
} RECU_Output_Faults_Log_T;
typedef struct RECU_SCL_Output_Log_Tag /*Offset Start byte of the Structure SCL_Output_Log is 78736 bytes*/
{
   unsigned8_T sensors_calibs_fault_status[NUM_TOTAL_RADAR_SENSORS_LOG];
   unsigned8_T sensors_fault_status[NUM_TOTAL_RADAR_SENSORS_LOG];
   unsigned8_T object_track_fault_status;
   unsigned8_T should_reset;
   unsigned8_T core_info_fault_status;
   unsigned8_T host_info_fault_status;
   unsigned8_T overall_fault_status;
   unsigned8_T UNUSED[SCL_OUT_LOG_UNUSED];
} RECU_SCL_Output_Log_T;
typedef struct RECU_Functional_Safety_Faults_Log_Tag /*Offset Start byte of the Structure Functional_Safety_Faults_Log is 78752 bytes*/
{
   RECU_Input_Faults_Log_T input_faults;
   RECU_Output_Faults_Log_T output_faults;
   RECU_SCL_Output_Log_T scl_output_faults;
} RECU_Functional_Safety_Faults_Log_T;
typedef struct RECU_F360_Adaptation_Output_Tag /*Offset Start byte of the Structure F360_Adaptation_Output is 78816 bytes*/
{
   unsigned16_T prev_bmw_active_obj_ids[MAX_F360_OBJECTS_LOG];
   unsigned16_T time_since_downselected_array[MAX_REDUCED_OBJECTS_LOG];
   unsigned64_T previous_timestamp;
} RECU_F360_Adaptation_Output_T;
typedef struct RECU_VSE_Output_Log_Tag /*Offset Start byte of the Structure VSE_Output_Log is 79180 bytes*/
{
   unsigned64_T timestamp_us;
   float32_T raw_speed_mps;
   float32_T speed_compensation_factor;
   float32_T filt_veh_speed_over_ground;
   float32_T raw_lat_accel;
   float32_T raw_long_accel;
   float32_T raw_yaw_rate_rps;
   float32_T raw_steering_angle_deg;
   float32_T road_wheel_angle_deg;
   float32_T yaw_rate_sa;
   float32_T yaw_rate_raw_bias;
   float32_T comp_yaw_rate_unfiltered;
   float32_T comp_yaw_rate_filtered;
   float32_T curvature_rear_axle;
   float32_T sideslip_rear_axle;
   float32_T vcs_sideslip;
   float32_T vcs_long_velocity;
   float32_T vcs_lat_velocity;
   float32_T sensor_sideslip;
   float32_T sensor_long_velocity;
   float32_T sensor_lat_velocity;
   float32_T k_dist_rear_axle_to_vcs;
   float32_T vcs_lat_accel;
   float32_T vcs_long_accel;
   float32_T accel_rear_axle;
   float32_T signed_filt_veh_speed_over_ground;
   unsigned32_T veh_index;
   unsigned8_T raw_speed_qf;
   unsigned8_T speed_compensation_factor_qf;
   unsigned8_T filt_veh_speed_over_ground_qf;
   unsigned8_T raw_lat_accel_qf;
   unsigned8_T raw_long_accel_qf;
   unsigned8_T raw_yaw_rate_qf;
   unsigned8_T raw_steering_angle_qf;
   unsigned8_T road_wheel_angle_qf;
   unsigned8_T yaw_rate_sa_qf;
   unsigned8_T yaw_rate_bias_qf;
   unsigned8_T comp_yaw_rate_qf;
   unsigned8_T stationary;
   unsigned8_T vcs_lat_accel_qf;
   unsigned8_T vcs_long_accel_qf;
   u16p0_T K_Unused16_1;
} RECU_VSE_Output_Log_T;
typedef struct RECU_Host_Raw_Data_Log_Tag /*Offset Start byte of the Structure Host_Raw_Data_Log is 79308 bytes*/
{
   float32_T global_time_sync_s;
   float32_T timestamp_s;
   float32_T raw_speed;
   float32_T steering_wheel_angle_rad;
   float32_T raw_yaw_rate_rad;
   float32_T lat_accel;
   float32_T long_accel;
   float32_T speed_correction_factor;
   float32_T road_wheel_angle_rad;
   unsigned8_T reverse_gear;
   unsigned8_T prndl;
   unsigned8_T speed_qf;
   unsigned8_T yaw_rate_qf;
   unsigned8_T steering_wheel_angle_qf;
   unsigned8_T lat_accel_qf;
   unsigned8_T long_accel_qf;
   unsigned8_T speed_correction_factor_qf;
   unsigned8_T road_wheel_angle_qf;
   boolean_T f_trailer_present;
   u16p0_T K_Unused16_1;
} RECU_Host_Raw_Data_Log_T;
typedef struct RECU_F360_Host_Props_Log_Tag /*Offset Start byte of the Structure F360_Host_Props_Log is 79356 bytes*/
{
   float32_T position_x;
   float32_T position_y;
   float32_T heading;
   float32_T delta_pointing;
   float32_T delta_position_x;
   float32_T delta_position_y;
   float32_T std_speed_scm;
   float32_T std_yaw_rate_scm;
   float32_T vel_cov_scm[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
   float32_T vel_cov[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
   float32_T position_inc_cov_scm[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
   float32_T position_inc_cov[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
} RECU_F360_Host_Props_Log_T;
typedef struct RECU_Tracker_Version_Info_Log_Tag /*Offset Start byte of the Structure Tracker_Version_Info_Log is 79452 bytes*/
{
   unsigned8_T sw_version_major;
   unsigned8_T sw_version_minor;
   unsigned8_T dll_version_major;
   unsigned8_T dll_version_minor;
} RECU_Tracker_Version_Info_Log_T;
typedef struct RECU_Partial_Blockage_Header_Tag /*Offset Start byte of the Structure Partial_Blockage_Header is 79456 bytes*/
{
   float32_T timestamp;
   float32_T prev_timestamp;
   unsigned32_T tracker_index;
   signed32_T sensorID;
} RECU_Partial_Blockage_Header_T;
typedef struct RECU_SB_BLKG_OUTPUT_Tag /*Offset Start byte of the Structure SB_BLKG_OUTPUT is 79472 bytes*/
{
   float32_T filtered_det_cnt;
   float32_T filtered_moving_azConf_0_percent;
   float32_T filtered_moving_azConf_3_percent;
   signed32_T SB_sidelobeFlag_SetCounter;
   signed32_T SB_sidelobeFlag_ResetCounter;
   signed32_T SB_blockage_ResetCounter;
   signed32_T valid_cnt_dets_MR;
   unsigned8_T f_SB_Blockage;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_SB_BLKG_OUTPUT_T;
typedef struct RECU_Partial_Blockage_Log_Tag /*Offset Start byte of the Structure Partial_Blockage_Log is 79504 bytes*/
{
   RECU_Partial_Blockage_Header_T header_info;
   RECU_Tracker_Version_Info_Log_T tracker_version;
   RECU_SB_BLKG_OUTPUT_T sb_blockage_state;
} RECU_Partial_Blockage_Log_T;
typedef struct RECU_F360_Static_Env_Poly_Data_Log_Tag /*Offset Start byte of the Structure F360_Static_Env_Poly_Data_Log is 79556 bytes*/
{
   float32_T confidence;
   float32_T lower_limit;
   float32_T upper_limit;
   float32_T p0;
   float32_T p1;
   float32_T p2;
   unsigned8_T age;
   unsigned8_T poly_type;
   unsigned8_T status;
   u8p0_T K_Unused8_1;
} RECU_F360_Static_Env_Poly_Data_Log_T;
typedef struct RECU_F360_Static_Env_Poly_Log_Tag /*Offset Start byte of the Structure F360_Static_Env_Poly_Log is 79584 bytes*/
{
   RECU_F360_Static_Env_Poly_Data_Log_T static_env_polys[F360_NUM_OF_STATIC_ENV_POLYS_LOG];
   unsigned64_T timestamp_us;
   unsigned32_T tracker_index;
} RECU_F360_Static_Env_Poly_Log_T;
typedef struct RECU_Quick_Check_Algo_Log_Tag /*Offset Start byte of the Structure Quick_Check_Algo_Log is 79764 bytes*/
{
   float32_T FL_Yaw_sd;
   float32_T FR_Yaw_sd;
   float32_T RL_Yaw_sd;
   float32_T RR_Yaw_sd;
} RECU_Quick_Check_Algo_Log_T;
typedef struct RECU_F360_Host_Calib_Log_Tag /*Offset Start byte of the Structure F360_Host_Calib_Log is 79780 bytes*/
{
   float32_T dist_rear_axle_to_vcs_m;
   float32_T rear_cornering_compliance;
   float32_T steer_gear_ratio;
   float32_T wheelbase_m;
   float32_T understeer_coefficient;
   float32_T vehicle_width_m;
   float32_T vehicle_length_m;
   float32_T cog_x;
   float32_T cog_y;
   float32_T front_wheel_radius_m;
   float32_T front_track_width_m;
   unsigned32_T raw_host_signal_latency_ms;
   boolean_T f_enable_internal_reflections_func;
   boolean_T f_enable_internal_reflections_func_trailer;
   u16p0_T K_Unused16_1;
} RECU_F360_Host_Calib_Log_T;
typedef struct Radar_ECU_CORE1_Tag /*Offset Start byte of the Structure Radar_ECU_CORE1 is 79832 bytes*/
{
   Radar_ECU_CORE1_Hdr_T radar_ecu_CORE1_Hdr;
   Core_1_Timing_Info_T timing_info;
   RECU_Tracker_Error_Info_T tracker_error_info;
   RECU_Process_Detections_Log_T processed_detections;
   RECU_All_Objects_Log_T all_objects;
   RECU_Tracker_Info_Log_T tracker_info;
   RECU_Vehicle_Info_Log_T vehicle_info;
   RECU_Timing_Info_Log_T timing_log;
   RECU_VSE_Output_Log_T vse_output_log;
   RECU_Host_Raw_Data_Log_T host_raw_data_log;
   RECU_Functional_Safety_Faults_Log_T fs_faults_log;
   RECU_F360_Adaptation_Output_T f360_adapt_output;
   RECU_F360_Host_Props_Log_T f360_host_props_info;
   RECU_Partial_Blockage_Log_T partial_blkg_log[NUM_TOTAL_RADAR_SENSORS_LOG];
   RECU_F360_Static_Env_Poly_Log_T Log_Static_Env_Polys;
   unsigned64_T tracker_oal_timestamp_us;
   unsigned32_T tracker_index;
   RECU_Quick_Check_Algo_Log_T quick_check_algo_log;
   RECU_F360_Host_Calib_Log_T host_calib_log;
} Radar_ECU_CORE1_T;
#else
typedef struct RECU_Radar_ECU_CORE1_Hdr_Tag {
   unsigned16_T version_number;
   unsigned16_T run_counter;
   unsigned16_T Sec_Checksum;
   unsigned16_T Sec_Compatibility;
   unsigned32_T Sec_Size;
} RECU_Radar_ECU_CORE1_Hdr_T;
typedef struct RECU_TimeStamp_Rader_CORE1_Tag {
   unsigned32_T time_fraction;
   unsigned32_T time_seconds;
} RECU_TimeStamp_Rader_CORE1_T;
typedef struct RECU_Core_1_Timing_Info_Tag {
   TimeStamp_Rader_CORE1_T tracker_endtime;
   TimeStamp_Rader_CORE1_T tracker_starttime;
   TimeStamp_Rader_CORE1_T core_endtime;
   TimeStamp_Rader_CORE1_T core_starttime;
} RECU_Core_1_Timing_Info_T;
typedef struct RECU_Tracker_Error_Info_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T tracker_overrun_flag;
   unsigned32_T reserved;
   unsigned32_T scan_index_RL;
   unsigned32_T scan_index_RR;
   unsigned32_T scan_index_FL;
   unsigned32_T scan_index_FR;
   unsigned32_T tracker_overrun_cnt;
} RECU_Tracker_Error_Info_T;
typedef struct RECU_Sensor_Info_Log_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   signed8_T radar_polarity;
   signed8_T look_id;
   signed8_T sensor_type;
   signed8_T mount_location;
   unsigned8_T new_measurement_update;
   unsigned8_T f_sens_valid;
   unsigned8_T sensorID;
   unsigned16_T look_index;
   float32_T useful_fov[USEFUL_FOV_ARRAY_SIZE];
   float32_T align_angle_el_rad;
   float32_T align_angle_az_rad;
   float32_T range_rate_interval_width;
   float32_T vcs_boresight_elev_angle;
   float32_T vcs_boresight_az_angle;
   float32_T vcs_height_offset_m;
   float32_T vcs_lat_vel;
   float32_T vcs_long_vel;
   float32_T vcs_lat_posn;
   float32_T vcs_long_posn;
   unsigned64_T timestamp_us;
} RECU_Sensor_Info_Log_T;
typedef struct RECU_Detection_Log_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T f_on_guardrail[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_ok_to_use[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_inside_gate[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_close_target[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_selected_by_trk[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_FOV_edge[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_double_bounce[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_dealiased[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T f_azimuth_error[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T wheel_spin[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T motion_status[MAX_ALL_RADAR_DETS_LOG];
   unsigned8_T sensorID[MAX_ALL_RADAR_DETS_LOG];
   unsigned16_T clusterID[MAX_ALL_RADAR_DETS_LOG];
   unsigned16_T objTrkID[MAX_ALL_RADAR_DETS_LOG];
   unsigned16_T raw_det_id[MAX_ALL_RADAR_DETS_LOG];
   unsigned16_T num_dets;
   float32_T rngrate_comp[MAX_ALL_RADAR_DETS_LOG];
   float32_T rngrate_dealiased[MAX_ALL_RADAR_DETS_LOG];
   float32_T vcs_y[MAX_ALL_RADAR_DETS_LOG];
   float32_T vcs_x[MAX_ALL_RADAR_DETS_LOG];
} RECU_Detection_Log_T;
typedef struct RECU_Process_Detections_Log_Tag {
   RECU_Detection_Log_T detsLog;
   RECU_Sensor_Info_Log_T sensorInfoLog[NUM_TOTAL_RADAR_SENSORS_LOG];
} RECU_Process_Detections_Log_T;
typedef struct RECU_Object_Log_Extended_Tag {
   unsigned8_T underdrivable_status;
   unsigned8_T f_fast_moving;
   unsigned8_T f_onguardrail;
   unsigned8_T f_vehicular_trk;
   unsigned8_T f_oncoming;
   unsigned8_T f_moveable;
   unsigned8_T f_moving;
   unsigned8_T f_crossing;
   unsigned8_T object_class;
   unsigned8_T init_scheme;
   unsigned8_T reducedStatus;
   unsigned8_T status;
   unsigned8_T trk_fltr_type;
   unsigned8_T reducedID;
   unsigned16_T num_reduced_dets;
   unsigned16_T ndets;
   unsigned16_T trkID;
   float32_T probability_undet;
   float32_T probability_truck;
   float32_T probability_bicycle;
   float32_T probability_motorcycle;
   float32_T probability_car;
   float32_T probability_pedestrian;
   float32_T accuracy_width;
   float32_T accuracy_length;
   float32_T existence_probability;
   float32_T time_since_stage_start;
   float32_T confidenceLevel;
   float32_T wid2;
   float32_T wid1;
   float32_T len2;
   float32_T len1;
   float32_T time_since_track_updated;
   float32_T time_since_cluster_created;
   float32_T time_since_measurement;
   float32_T supplemental_state_covariance[SUPPLEMENTAL_STATE_COVARIANCE_ARRAY_SIZE];
   float32_T state_variance[STATE_VARIANCE_ARRAY_SIZE];
   float32_T tang_accel;
   float32_T curvature;
   float32_T speed;
   float32_T vcs_pointing;
   float32_T vcs_heading;
   float32_T vcs_yaccel;
   float32_T vcs_xaccel;
   float32_T vcs_yvel;
   float32_T vcs_xvel;
   float32_T vcs_yposn;
   float32_T vcs_xposn;
} RECU_Object_Log_Extended_T;
typedef struct RECU_All_Objects_Log_Tag {
   RECU_Object_Log_Extended_T obj[MAX_F360_OBJECTS_LOG];
   unsigned32_T tracker_index;
   unsigned64_T object_list_timestamp;
} RECU_All_Objects_Log_T;
typedef struct RECU_Tracker_Info_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T sw_version_patch;
   unsigned8_T sw_version_minor;
   unsigned8_T sw_version_major;
   unsigned16_T number_of_historic_detections;
   unsigned16_T num_active_clusters;
   unsigned16_T sensor_look_index[NUM_TOTAL_RADAR_SENSORS_LOG];
   unsigned16_T reduced_num_active_objs;
   unsigned16_T reduced_obj_ids[MAX_REDUCED_OBJECTS_LOG];
   unsigned16_T reduced_inactive_obj_ids[MAX_REDUCED_OBJECTS_LOG];
   unsigned16_T reduced_active_obj_ids[MAX_REDUCED_OBJECTS_LOG];
   unsigned16_T num_active_objs;
   unsigned16_T inactive_obj_ids[MAX_F360_OBJECTS_LOG];
   unsigned16_T active_obj_ids[MAX_F360_OBJECTS_LOG];
   unsigned32_T vehicle_index;
   unsigned32_T tracker_index;
   unsigned32_T sw_version_buildID;
   float32_T elapsed_time_s;
   unsigned64_T sensor_timestamp_us[NUM_TOTAL_RADAR_SENSORS_LOG];
   unsigned64_T object_list_timestamp;
   unsigned64_T timestamp_us;
} RECU_Tracker_Info_Log_T;
typedef struct RECU_Vehicle_Info_Log_Tag {
   u8p0_T K_Unused8_1;
   boolean_T f_trailer_present;
   unsigned8_T f_reverse_gear;
   unsigned8_T prndl;
   signed32_T vehicle_index;
   float32_T curvature_rear;
   float32_T vcs_sideslip;
   float32_T delta_position_y;
   float32_T delta_position_x;
   float32_T delta_pointing;
   float32_T heading;
   float32_T vcs_long_acceleration;
   float32_T vcs_lat_acceleration;
   float32_T vcs_speed;
   float32_T acceleration;
   float32_T speed;
   float32_T speed_correction_factor;
   float32_T dist_rear_axle_to_vcs_m;
   float32_T raw_yaw_rate_rad;
   float32_T steering_angle_rad;
   float32_T raw_speed;
   float32_T rear_cornering_compliance;
   float32_T world_y;
   float32_T world_x;
   float32_T align_angle_el_rad[NUM_TOTAL_RADAR_SENSORS_LOG];
   float32_T align_angle_az_rad[NUM_TOTAL_RADAR_SENSORS_LOG];
   double64_T timestamp_s;
   double64_T global_time_sync_s;
} RECU_Vehicle_Info_Log_T;
typedef struct RECU_ItemizedExecutionTiming_Log_Tag {
   float32_T msmt_update_obj_trks_ccv;
   float32_T time_update_obj_trks_ccv;
   float32_T assoc_unconf_obj_trks_sub_time_6;
   float32_T assoc_unconf_obj_trks_sub_time_5;
   float32_T assoc_unconf_obj_trks_sub_time_4;
   float32_T assoc_unconf_obj_trks_sub_time_3;
   float32_T assoc_unconf_obj_trks_sub_time_2;
   float32_T assoc_unconf_obj_trks_sub_time_1;
   float32_T get_pseudo_hdg_msmt_from_associated_dets_mean;
   float32_T get_pseudo_hdg_msmt_from_associated_dets_sum;
   float32_T msmt_update_obj_trks_ctca;
   float32_T reserve5;
   float32_T reserve4;
   float32_T reserve3;
   float32_T reserve2;
   float32_T reserve1;
   float32_T sanity_check;
   float32_T mark_object_tracks_next_to_sensors;
   float32_T underdrivability_classification;
   float32_T det_mean_var;
   float32_T adjust_overlapping_confirmed_trks;
   float32_T cancel_new_updated_trk_overlapping_confirmed_trks;
   float32_T obj_trk_properties;
   float32_T adjust_fltr_type_dependent_params;
   float32_T obj_trk_status_bookkeeping;
   float32_T initialize_tracked_objects;
   float32_T pseudo_estimations;
   float32_T merge_tracks;
   float32_T assoc_unconf_obj_trks;
   float32_T initialize_clusters;
   float32_T cluster_leftover_detections;
   float32_T cluster_moving_detections;
   float32_T det_downselect;
   float32_T store_det_data;
   float32_T assoc_countermeasure;
   float32_T assoc_dets_with_obj_trks;
   float32_T kill_coasted_tracks;
   float32_T split_tracks;
   float32_T time_update_obj_trks_ctca;
   float32_T time_update_obj_trks_cca;
   float32_T double_bounce_detection_countermeasure;
   float32_T sensor_capability_module;
   float32_T detect_azimuth_errors;
   float32_T mark_out_det_pairs;
   float32_T check_az_el_conf;
   float32_T detect_wheelspin;
   float32_T ego_motion_compensate_dets;
   float32_T update_det_posn_hist;
   float32_T update_det_hist;
   float32_T sensor_motion;
   float32_T configure_rdot_interval_compability;
   float32_T update_sensor_valid_info;
   float32_T calc_obj_mov_stat_thresh;
   float32_T calc_mov_stat_thresh;
   float32_T host_state_update;
} RECU_ItemizedExecutionTiming_Log_T;
typedef struct RECU_OverallTiming_Log_Tag {
   float32_T concrete_wall_detector;
   float32_T lsc_module;
   float32_T occlusion;
   float32_T e2e_protection;
   float32_T track_downselection;
   float32_T track_validity;
   float32_T track_classification;
   float32_T post_update_track_adjustments;
   float32_T initialize_tracks;
   float32_T measurement_update_tracks;
   float32_T track_grouping;
   float32_T cluster_grouping;
   float32_T clustering;
   float32_T detection_to_track_association;
   float32_T pre_association_track_management;
   float32_T time_update_tracks;
   float32_T sensor_preprocessing;
   float32_T time_taken_full_tracker_DLL_func;
   float32_T time_taken_core_and_udp_packing;
   float32_T time_taken_core_tracker;
} RECU_OverallTiming_Log_T;
typedef struct RECU_Timing_Info_Log_Tag {
   unsigned32_T tracker_index;
   RECU_OverallTiming_Log_T overall_execution_times;
   RECU_ItemizedExecutionTiming_Log_T itemized_execution_times;
   float32_T prev_timestamp;
   float32_T timestamp;
} RECU_Timing_Info_Log_T;
typedef struct RECU_Core_Info_Faults_Log_Tag {
   unsigned8_T elapsed_time_above_upper_limit;
   unsigned8_T elapsed_time_below_lower_limit;
   unsigned8_T cnt_loops_no_increase;
   unsigned8_T time_us_no_increase;
} RECU_Core_Info_Faults_Log_T;
typedef struct RECU_Radar_Sensor_Calib_Faults_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T boresight_angle_is_invalid;
   unsigned8_T polarity_is_invalid;
   unsigned8_T mounting_pos_is_invalid;
} RECU_Radar_Sensor_Calib_Faults_Log_T;
typedef struct RECU_Radar_Sensor_Faults_Log_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T sensor_vs_tracker_timestamp_divergence;
   unsigned8_T look_index_no_increase;
} RECU_Radar_Sensor_Faults_Log_T;
typedef struct RECU_Host_Info_Faults_Log_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T host_lateral_acceleration_invalid;
   unsigned8_T host_longitudinal_acceleration_invalid;
   unsigned8_T host_yawrate_invalid;
   unsigned8_T host_speed_invalid;
   unsigned8_T vehicle_index_no_increase;
} RECU_Host_Info_Faults_Log_T;
typedef struct RECU_Input_Faults_Log_Tag {
   RECU_Host_Info_Faults_Log_T host_info;
   RECU_Radar_Sensor_Faults_Log_T sensors[NUM_TOTAL_RADAR_SENSORS_LOG];
   RECU_Radar_Sensor_Calib_Faults_Log_T sensors_calibs[NUM_TOTAL_RADAR_SENSORS_LOG];
   RECU_Core_Info_Faults_Log_T core_info;
} RECU_Input_Faults_Log_T;
typedef struct RECU_Output_Faults_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T f_track_accelerations_faulty;
   unsigned8_T f_track_velocities_faulty;
   unsigned8_T f_track_positions_faulty;
} RECU_Output_Faults_Log_T;
typedef struct RECU_SCL_Output_Log_Tag {
   unsigned8_T UNUSED[SCL_OUT_LOG_UNUSED];
   unsigned8_T overall_fault_status;
   unsigned8_T host_info_fault_status;
   unsigned8_T core_info_fault_status;
   unsigned8_T should_reset;
   unsigned8_T object_track_fault_status;
   unsigned8_T sensors_fault_status[NUM_TOTAL_RADAR_SENSORS_LOG];
   unsigned8_T sensors_calibs_fault_status[NUM_TOTAL_RADAR_SENSORS_LOG];
} RECU_SCL_Output_Log_T;
typedef struct RECU_Functional_Safety_Faults_Log_Tag {
   RECU_SCL_Output_Log_T scl_output_faults;
   RECU_Output_Faults_Log_T output_faults;
   RECU_Input_Faults_Log_T input_faults;
} RECU_Functional_Safety_Faults_Log_T;
typedef struct RECU_F360_Adaptation_Output_Tag {
   unsigned64_T previous_timestamp;
   unsigned16_T time_since_downselected_array[MAX_REDUCED_OBJECTS_LOG];
   unsigned16_T prev_bmw_active_obj_ids[MAX_F360_OBJECTS_LOG];
} RECU_F360_Adaptation_Output_T;
typedef struct RECU_VSE_Output_Log_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T vcs_long_accel_qf;
   unsigned8_T vcs_lat_accel_qf;
   unsigned8_T stationary;
   unsigned8_T comp_yaw_rate_qf;
   unsigned8_T yaw_rate_bias_qf;
   unsigned8_T yaw_rate_sa_qf;
   unsigned8_T road_wheel_angle_qf;
   unsigned8_T raw_steering_angle_qf;
   unsigned8_T raw_yaw_rate_qf;
   unsigned8_T raw_long_accel_qf;
   unsigned8_T raw_lat_accel_qf;
   unsigned8_T filt_veh_speed_over_ground_qf;
   unsigned8_T speed_compensation_factor_qf;
   unsigned8_T raw_speed_qf;
   unsigned32_T veh_index;
   float32_T signed_filt_veh_speed_over_ground;
   float32_T accel_rear_axle;
   float32_T vcs_long_accel;
   float32_T vcs_lat_accel;
   float32_T k_dist_rear_axle_to_vcs;
   float32_T sensor_lat_velocity;
   float32_T sensor_long_velocity;
   float32_T sensor_sideslip;
   float32_T vcs_lat_velocity;
   float32_T vcs_long_velocity;
   float32_T vcs_sideslip;
   float32_T sideslip_rear_axle;
   float32_T curvature_rear_axle;
   float32_T comp_yaw_rate_filtered;
   float32_T comp_yaw_rate_unfiltered;
   float32_T yaw_rate_raw_bias;
   float32_T yaw_rate_sa;
   float32_T road_wheel_angle_deg;
   float32_T raw_steering_angle_deg;
   float32_T raw_yaw_rate_rps;
   float32_T raw_long_accel;
   float32_T raw_lat_accel;
   float32_T filt_veh_speed_over_ground;
   float32_T speed_compensation_factor;
   float32_T raw_speed_mps;
   unsigned64_T timestamp_us;
} RECU_VSE_Output_Log_T;
typedef struct RECU_Host_Raw_Data_Log_Tag {
   u16p0_T K_Unused16_1;
   boolean_T f_trailer_present;
   unsigned8_T road_wheel_angle_qf;
   unsigned8_T speed_correction_factor_qf;
   unsigned8_T long_accel_qf;
   unsigned8_T lat_accel_qf;
   unsigned8_T steering_wheel_angle_qf;
   unsigned8_T yaw_rate_qf;
   unsigned8_T speed_qf;
   unsigned8_T prndl;
   unsigned8_T reverse_gear;
   float32_T road_wheel_angle_rad;
   float32_T speed_correction_factor;
   float32_T long_accel;
   float32_T lat_accel;
   float32_T raw_yaw_rate_rad;
   float32_T steering_wheel_angle_rad;
   float32_T raw_speed;
   float32_T timestamp_s;
   float32_T global_time_sync_s;
} RECU_Host_Raw_Data_Log_T;
typedef struct RECU_F360_Host_Props_Log_Tag {
   float32_T position_inc_cov[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
   float32_T position_inc_cov_scm[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
   float32_T vel_cov[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
   float32_T vel_cov_scm[HOST_PROPS_ARRAY_1][HOST_PROPS_ARRAY_2];
   float32_T std_yaw_rate_scm;
   float32_T std_speed_scm;
   float32_T delta_position_y;
   float32_T delta_position_x;
   float32_T delta_pointing;
   float32_T heading;
   float32_T position_y;
   float32_T position_x;
} RECU_F360_Host_Props_Log_T;
typedef struct RECU_Tracker_Version_Info_Log_Tag {
   unsigned8_T dll_version_minor;
   unsigned8_T dll_version_major;
   unsigned8_T sw_version_minor;
   unsigned8_T sw_version_major;
} RECU_Tracker_Version_Info_Log_T;
typedef struct RECU_Partial_Blockage_Header_Tag {
   signed32_T sensorID;
   unsigned32_T tracker_index;
   float32_T prev_timestamp;
   float32_T timestamp;
} RECU_Partial_Blockage_Header_T;
typedef struct RECU_SB_BLKG_OUTPUT_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T f_SB_Blockage;
   signed32_T valid_cnt_dets_MR;
   signed32_T SB_blockage_ResetCounter;
   signed32_T SB_sidelobeFlag_ResetCounter;
   signed32_T SB_sidelobeFlag_SetCounter;
   float32_T filtered_moving_azConf_3_percent;
   float32_T filtered_moving_azConf_0_percent;
   float32_T filtered_det_cnt;
} RECU_SB_BLKG_OUTPUT_T;
typedef struct RECU_Partial_Blockage_Log_Tag {
   RECU_SB_BLKG_OUTPUT_T sb_blockage_state;
   RECU_Tracker_Version_Info_Log_T tracker_version;
   RECU_Partial_Blockage_Header_T header_info;
} RECU_Partial_Blockage_Log_T;
typedef struct RECU_F360_Static_Env_Poly_Data_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T status;
   unsigned8_T poly_type;
   unsigned8_T age;
   float32_T p2;
   float32_T p1;
   float32_T p0;
   float32_T upper_limit;
   float32_T lower_limit;
   float32_T confidence;
} RECU_F360_Static_Env_Poly_Data_Log_T;
typedef struct RECU_F360_Static_Env_Poly_Log_Tag {
   unsigned32_T tracker_index;
   unsigned64_T timestamp_us;
   RECU_F360_Static_Env_Poly_Data_Log_T static_env_polys[F360_NUM_OF_STATIC_ENV_POLYS_LOG];
} RECU_F360_Static_Env_Poly_Log_T;
typedef struct RECU_Quick_Check_Algo_Log_Tag {
   float32_T RR_Yaw_sd;
   float32_T RL_Yaw_sd;
   float32_T FR_Yaw_sd;
   float32_T FL_Yaw_sd;
} RECU_Quick_Check_Algo_Log_T;
typedef struct RECU_F360_Host_Calib_Log_Tag {
   u16p0_T K_Unused16_1;
   boolean_T f_enable_internal_reflections_func_trailer;
   boolean_T f_enable_internal_reflections_func;
   unsigned32_T raw_host_signal_latency_ms;
   float32_T front_track_width_m;
   float32_T front_wheel_radius_m;
   float32_T cog_y;
   float32_T cog_x;
   float32_T vehicle_length_m;
   float32_T vehicle_width_m;
   float32_T understeer_coefficient;
   float32_T wheelbase_m;
   float32_T steer_gear_ratio;
   float32_T rear_cornering_compliance;
   float32_T dist_rear_axle_to_vcs_m;
} RECU_F360_Host_Calib_Log_T;
typedef struct Radar_ECU_CORE1_Tag {
   RECU_F360_Host_Calib_Log_T host_calib_log;
   RECU_Quick_Check_Algo_Log_T quick_check_algo_log;
   unsigned32_T tracker_index;
   unsigned64_T tracker_oal_timestamp_us;
   RECU_F360_Static_Env_Poly_Log_T Log_Static_Env_Polys;
   RECU_Partial_Blockage_Log_T partial_blkg_log[NUM_TOTAL_RADAR_SENSORS_LOG];
   RECU_F360_Host_Props_Log_T f360_host_props_info;
   RECU_F360_Adaptation_Output_T f360_adapt_output;
   RECU_Functional_Safety_Faults_Log_T fs_faults_log;
   RECU_Host_Raw_Data_Log_T host_raw_data_log;
   RECU_VSE_Output_Log_T vse_output_log;
   RECU_Timing_Info_Log_T timing_log;
   RECU_Vehicle_Info_Log_T vehicle_info;
   RECU_Tracker_Info_Log_T tracker_info;
   RECU_All_Objects_Log_T all_objects;
   RECU_Process_Detections_Log_T processed_detections;
   RECU_Tracker_Error_Info_T tracker_error_info;
   Core_1_Timing_Info_T timing_info;
   Radar_ECU_CORE1_Hdr_T radar_ecu_CORE1_Hdr;
} Radar_ECU_CORE1_T;
extern void Print_RADAR_ECU_CORE1_Traces_Header(FILE *CfilePtr, Radar_ECU_CORE1_T *debug);
extern void Print_RADAR_ECU_CORE1_Traces_Data(FILE *CfilePtr, Radar_ECU_CORE1_T *debug);
extern void Print_RADAR_ECU_CORE1_Xml_Traces(FILE *CfilePtr, Radar_ECU_CORE1_T *debug);
extern void Reverse_Array_RADAR_ECU_CORE1(Radar_ECU_CORE1_T *debug);
#endif /*PC_Resim*/

#pragma pack(pop, save_pack)
#endif /*RADAR_ECU_CORE1_H*/
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 27-01-2022 	 14:14:54	 jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/
