#ifndef RADAR_ECU_VRU_CLASSIFIER_H
#define RADAR_ECU_VRU_CLASSIFIER_H

/********************************************************************************************
 * Copyright 2007 Delphi Technologies, Inc., All Rights Reserved
 * XML uses version 9 of the base file.
 * File Name: RADAR_ECU_VRU_CLASSIFIER
 * Created:	 27-03-2021 	 13:25:03
 * From XML file: RADAR_ECU_VRU_CLASSIFIER.xml
 * Set Description:        Logging Structure/Interface structure
 * Tool Version: Major Version : 4,Minor Version 3
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

// This is added to convert the structures in this file to 4 byte padding
#pragma pack(push, save_pack)
#pragma pack(push, 4)

/*Macros For ARRAY Sizes*/
#define DC_VRU_CLASSIFIER_STREAM_ID        (96)
#define NUMBER_OF_LOGGED_TRACKS_LOG        (35)
#define NUMBER_OF_LOGGED_TRACKS_FUSION_LOG (70)
#define NUM_VRU_FUSION_CLASSES_LOG         (6)
#define NUM_VRU_CLASSIFIER_CLASSES_LOG     (4)
/*Macro For Structure Version*/
#define RADAR_ECU_VRU_CLASSIFIER_VERSION (10)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_RADAR_ECU_VRU_CLASSIFIER (2764)

/*Macro for size of Sub structures*/
#define SIZE_OF_VRU_Classifier_Hdr (12)
#define SIZE_OF_VRU_Classifier_Log (832)
#define SIZE_OF_VRU_Fusion_Log     (1920)
#define SIZE_OF_Radar_ECU_VRU      (2764)

#ifndef UDP_LITTLE_ENDIAN_BYTE_ORDER_STRUCTURE
typedef struct VRU_Classifier_Hdr_Tag /*Offset Start byte of the Structure VRU_Classifier_Hdr is 0 bytes*/
{
   unsigned32_T Sec_Size;
   unsigned16_T Sec_Compatibility;
   unsigned16_T Sec_Checksum;
   unsigned16_T run_counter;
   unsigned16_T version_number;
} VRU_Classifier_Hdr_T;
typedef struct VRU_Classifier_Log_Tag /*Offset Start byte of the Structure VRU_Classifier_Log is 12 bytes*/
{
   unsigned64_T timestamp_us;
   unsigned64_T prev_timestamp_us;
   float32_T class_probabilities[NUMBER_OF_LOGGED_TRACKS_LOG][NUM_VRU_CLASSIFIER_CLASSES_LOG];
   float32_T confidence[NUMBER_OF_LOGGED_TRACKS_LOG];
   unsigned16_T track_id[NUMBER_OF_LOGGED_TRACKS_LOG];
   unsigned16_T num_active_objs;
   unsigned16_T tracker_index;
   unsigned8_T lifetime_counter[NUMBER_OF_LOGGED_TRACKS_LOG];
   unsigned8_T version_major;
   unsigned8_T version_minor;
   unsigned8_T version_patch;
   unsigned8_T integrity_decreased;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} VRU_Classifier_Log_T;
typedef struct VRU_Fusion_Log_Tag /*Offset Start byte of the Structure VRU_Fusion_Log is 844 bytes*/
{
   unsigned64_T timestamp_us;
   unsigned64_T prev_timestamp_us;
   float32_T class_probabilities[NUMBER_OF_LOGGED_TRACKS_FUSION_LOG][NUM_VRU_FUSION_CLASSES_LOG];
   unsigned32_T padding4_0;
   unsigned16_T track_id[NUMBER_OF_LOGGED_TRACKS_FUSION_LOG];
   unsigned16_T num_active_objs;
   unsigned16_T tracker_index;
   unsigned16_T padding2_0;
   unsigned8_T integrity_decreased;
   unsigned8_T object_class[NUMBER_OF_LOGGED_TRACKS_FUSION_LOG];
   unsigned8_T version_major;
   unsigned8_T version_minor;
   unsigned8_T version_patch;
} VRU_Fusion_Log_T;
typedef struct Radar_ECU_VRU_Tag /*Offset Start byte of the Structure Radar_ECU_VRU is 2764 bytes*/
{
   VRU_Classifier_Hdr_T radar_ecu_vru_Hdr;
   VRU_Classifier_Log_T vru_classifier_log;
   VRU_Fusion_Log_T vru_fusion_log;
} Radar_ECU_VRU_T;
#else
typedef struct VRU_Classifier_Hdr_Tag {
   unsigned16_T version_number;
   unsigned16_T run_counter;
   unsigned16_T Sec_Checksum;
   unsigned16_T Sec_Compatibility;
   unsigned32_T Sec_Size;
} VRU_Classifier_Hdr_T;
typedef struct VRU_Classifier_Log_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T integrity_decreased;
   unsigned8_T version_patch;
   unsigned8_T version_minor;
   unsigned8_T version_major;
   unsigned8_T lifetime_counter[NUMBER_OF_LOGGED_TRACKS_LOG];
   unsigned16_T tracker_index;
   unsigned16_T num_active_objs;
   unsigned16_T track_id[NUMBER_OF_LOGGED_TRACKS_LOG];
   float32_T confidence[NUMBER_OF_LOGGED_TRACKS_LOG];
   float32_T class_probabilities[NUMBER_OF_LOGGED_TRACKS_LOG][NUM_VRU_CLASSIFIER_CLASSES_LOG];
   unsigned64_T prev_timestamp_us;
   unsigned64_T timestamp_us;
} VRU_Classifier_Log_T;
typedef struct VRU_Fusion_Log_Tag {
   unsigned8_T version_patch;
   unsigned8_T version_minor;
   unsigned8_T version_major;
   unsigned8_T object_class[NUMBER_OF_LOGGED_TRACKS_FUSION_LOG];
   unsigned8_T integrity_decreased;
   unsigned16_T padding2_0;
   unsigned16_T tracker_index;
   unsigned16_T num_active_objs;
   unsigned16_T track_id[NUMBER_OF_LOGGED_TRACKS_FUSION_LOG];
   unsigned32_T padding4_0;
   float32_T class_probabilities[NUMBER_OF_LOGGED_TRACKS_FUSION_LOG][NUM_VRU_FUSION_CLASSES_LOG];
   unsigned64_T prev_timestamp_us;
   unsigned64_T timestamp_us;
} VRU_Fusion_Log_T;
typedef struct Radar_ECU_VRU_Tag {
   VRU_Fusion_Log_T vru_fusion_log;
   VRU_Classifier_Log_T vru_classifier_log;
   VRU_Classifier_Hdr_T radar_ecu_vru_Hdr;
} Radar_ECU_VRU_T;
extern void Print_RADAR_ECU_VRU_CLASSIFIER_Traces_Header(FILE *CfilePtr, Radar_ECU_VRU_T *debug);
extern void Print_RADAR_ECU_VRU_CLASSIFIER_Traces_Data(FILE *CfilePtr, Radar_ECU_VRU_T *debug);
extern void Print_RADAR_ECU_VRU_CLASSIFIER_Xml_Traces(FILE *CfilePtr, Radar_ECU_VRU_T *debug);
extern void Reverse_Array_RADAR_ECU_VRU_CLASSIFIER(Radar_ECU_VRU_T *debug);
#endif /*PC_Resim*/

#ifdef PC_RESIM
extern void Print_RADAR_ECU_VRU_CLASSIFIER_Traces_Header(FILE *CfilePtr, Radar_ECU_VRU_T *debug);
extern void Print_RADAR_ECU_VRU_CLASSIFIER_Traces_Data(FILE *CfilePtr, Radar_ECU_VRU_T *debug);
extern void Print_RADAR_ECU_VRU_CLASSIFIER_Xml_Traces(FILE *CfilePtr, Radar_ECU_VRU_T *debug);
extern void Reverse_Array_RADAR_ECU_VRU_CLASSIFIER(Radar_ECU_VRU_T *debug);
#endif // PC_RESIM

#pragma pack(pop, save_pack)
#endif /*RADAR_ECU_VRU_CLASSIFIER_H*/
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 27-03-2021 	 13:25:03	 jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/
