#ifndef RADAR_ECU_CORE3_H
#define RADAR_ECU_CORE3_H

/********************************************************************************************
 * Copyright 2007 Delphi Technologies, Inc., All Rights Reserved
 * XML uses version 37 of the base file.
 * File Name: RADAR_ECU_CORE3
 * Created:	 02-09-2021 	 15:55:35
 * From XML file: RADAR_ECU_CORE3.xml
 * Set Description:        Logging Structure/Interface structure
 * Tool Version: Major Version : 4,Minor Version 3
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

// This is added to convert the structures in this file to 4 byte padding
#pragma pack(push, save_pack)
#pragma pack(push, 4)

/*Macros For ARRAY Sizes*/
#define RADAR_ECU_CORE3_ID               (92)
#define NUMBER_OF_SIDES_UDP_LOG          (2)
#define NUMBER_OF_OBJECTS_UDP_LOG        (50)
#define PA_OBJ_NUMBER_OF_OBJECTS_UDP_LOG (50)
#define N_OBJECTS_UDP_LOG                (8)
/*Macro For Structure Version*/
#define RADAR_ECU_CORE3_VERSION (38)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_RADAR_ECU_CORE3 (8092)

/*Macro for size of Sub structures*/
#define SIZE_OF_Radar_ECU_CORE3_Hdr                (12)
#define SIZE_OF_TimeStamp_Rader_CORE3              (8)
#define SIZE_OF_Core_3_Timing_Info                 (128)
#define SIZE_OF_FF_Error_Info                      (20)
#define SIZE_OF_SW_version_number_Core3            (8)
#define SIZE_OF_FF_version                         (48)
#define SIZE_OF_Camera_Data_Udp_Log                (124)
#define SIZE_OF_RECW_INPUT_LOG                     (12)
#define SIZE_OF_Recw_Output_Udp_Log                (52)
#define SIZE_OF_RECW_LOG                           (64)
#define SIZE_OF_LCDA_INPUT_LOG                     (20)
#define SIZE_OF_Lcda_Output_Udp_Log                (120)
#define SIZE_OF_LCDA_LOG                           (140)
#define SIZE_OF_CTA_INPUT_LOG                      (8)
#define SIZE_OF_CTA_ERRORS                         (4)
#define SIZE_OF_Cta_Output_Udp_Log                 (64)
#define SIZE_OF_Path_Tracking_Nearest_Path_Udp_Log (12)
#define SIZE_OF_Path_Object_Pair_Output_Udp_Log    (28)
#define SIZE_OF_Path_Tracking_Output_Udp_Log       (2004)
#define SIZE_OF_CTA_LOG                            (72)
#define SIZE_OF_Ta_BMW_Boardnet_Udp_Log            (128)
#define SIZE_OF_TA_INPUT_LOG                       (152)
#define SIZE_OF_FTA_Object_List_Udp_Log            (124)
#define SIZE_OF_Ta_Output_Udp_Log                  (1124)
#define SIZE_OF_TA_LOG                             (1276)
#define SIZE_OF_CED_INPUT_LOG                      (4)
#define SIZE_OF_Ced_Output_Udp_Log                 (96)
#define SIZE_OF_CED_LOG                            (100)
#define SIZE_OF_PATH_TRACKING_LOG                  (2004)
#define SIZE_OF_SCW_INPUT_LOG                      (4)
#define SIZE_OF_Scw_Output_Udp_Log                 (96)
#define SIZE_OF_SCW_LOG                            (100)
#define SIZE_OF_FF_OUTPUT_Logging_Data             (3756)
#define SIZE_OF_GDSR_TRACKER_LOG_OUTPUT            (2152)
#define SIZE_OF_LCDA_SM_INPUT                      (12)
#define SIZE_OF_LCDA_SM_Output                     (144)
#define SIZE_OF_SCW_SM_Input                       (4)
#define SIZE_OF_SCW_State_Machine_Output           (108)
#define SIZE_OF_CED_SM_Input                       (72)
#define SIZE_OF_CED_SM_Output                      (44)
#define SIZE_OF_CTA_App_Params                     (40)
#define SIZE_OF_CTA_SM_Input                       (32)
#define SIZE_OF_Warning_Acoustic                   (12)
#define SIZE_OF_CTA_SM_Output                      (40)
#define SIZE_OF_RECW_App_Params                    (64)
#define SIZE_OF_RECW_SM_Input                      (16)
#define SIZE_OF_RECW_SM_Output                     (48)
#define SIZE_OF_TAP_SM_Input                       (12)
#define SIZE_OF_TA_SM_Output                       (1136)
#define SIZE_OF_PFGS_SM_Input                      (36)
#define SIZE_OF_PFGS_SM_Output                     (36)
#define SIZE_OF_FreeSpace_State_Machine_Input      (4)
#define SIZE_OF_FF_SM_LOG                          (1848)
#define SIZE_OF_Radar_ECU_CORE3                    (8092)

#ifndef UDP_LITTLE_ENDIAN_BYTE_ORDER_STRUCTURE
typedef struct RECU_Radar_ECU_CORE3_Hdr_Tag /*Offset Start byte of the Structure Radar_ECU_CORE3_Hdr is 0 bytes*/
{
   unsigned32_T Sec_Size;
   unsigned16_T Sec_Compatibility;
   unsigned16_T Sec_Checksum;
   unsigned16_T run_counter;
   unsigned16_T version_number;
} RECU_Radar_ECU_CORE3_Hdr_T;
typedef struct RECU_TimeStamp_Rader_CORE3_Tag /*Offset Start byte of the Structure TimeStamp_Rader_CORE3 is 12 bytes*/
{
   unsigned32_T time_seconds;
   unsigned32_T time_fraction;
} RECU_TimeStamp_Rader_CORE3_T;
typedef struct RECU_Core_3_Timing_Info_Tag /*Offset Start byte of the Structure Core_3_Timing_Info is 20 bytes*/
{
   RECU_TimeStamp_Rader_CORE3_T core_starttime;
   RECU_TimeStamp_Rader_CORE3_T core_endtime;
   RECU_TimeStamp_Rader_CORE3_T RECW_starttime;
   RECU_TimeStamp_Rader_CORE3_T RECW_endtime;
   RECU_TimeStamp_Rader_CORE3_T CTA_starttime;
   RECU_TimeStamp_Rader_CORE3_T CTA_endtime;
   RECU_TimeStamp_Rader_CORE3_T LCDA_starttime;
   RECU_TimeStamp_Rader_CORE3_T LCDA_endtime;
   RECU_TimeStamp_Rader_CORE3_T TA_starttime;
   RECU_TimeStamp_Rader_CORE3_T TA_endtime;
   RECU_TimeStamp_Rader_CORE3_T SFE_starttime;
   RECU_TimeStamp_Rader_CORE3_T SFE_endtime;
   RECU_TimeStamp_Rader_CORE3_T SCW_starttime;
   RECU_TimeStamp_Rader_CORE3_T SCW_endtime;
   RECU_TimeStamp_Rader_CORE3_T CED_starttime;
   RECU_TimeStamp_Rader_CORE3_T CED_endtime;
} RECU_Core_3_Timing_Info_T;
typedef struct RECU_FF_Error_Info_Tag /*Offset Start byte of the Structure FF_Error_Info is 148 bytes*/
{
   unsigned32_T FF_overrun_cnt;
   unsigned32_T tracker_index_skipped;
   unsigned32_T FF_Skip_Index;
   unsigned32_T reserved;
   unsigned8_T ff_overrun_flag;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_FF_Error_Info_T;
typedef struct RECU_SW_version_number_Core3_Tag /*Offset Start byte of the Structure SW_version_number_Core3 is 168 bytes*/
{
   unsigned16_T major_version;
   unsigned16_T minor_version;
   unsigned16_T revision;
   u16p0_T K_Unused16_1;
} RECU_SW_version_number_Core3_T;
typedef struct RECU_FF_version_Tag /*Offset Start byte of the Structure FF_version is 176 bytes*/
{
   RECU_SW_version_number_Core3_T RECW_Version;
   RECU_SW_version_number_Core3_T LCDA_Version;
   RECU_SW_version_number_Core3_T CTA_Version;
   RECU_SW_version_number_Core3_T Ta_Version;
   RECU_SW_version_number_Core3_T CED_Version;
   RECU_SW_version_number_Core3_T PATH_TRACKING_Version;
} RECU_FF_version_T;
typedef struct RECU_Camera_Data_Udp_Log_Tag /*Offset Start byte of the Structure Camera_Data_Udp_Log is 224 bytes*/
{
   float32_T lane_width_ego;
   float32_T lane_width_left;
   float32_T lane_width_right;
   float32_T lane_center_offset;
   float32_T quality_lane_width_ego;
   float32_T quality_lane_width_left;
   float32_T quality_lane_width_right;
   float32_T quality_lane_center_offset;
   float32_T lane_distance_first_left;
   float32_T lane_distance_first_right;
   float32_T lane_distance_second_left;
   float32_T lane_distance_second_right;
   float32_T lane_angle_first_left;
   float32_T lane_angle_first_right;
   float32_T lane_angle_second_left;
   float32_T lane_angle_second_right;
   float32_T lane_curvature_first_left;
   float32_T lane_curvature_first_right;
   float32_T lane_curvature_second_left;
   float32_T lane_curvature_second_right;
   float32_T lane_curvature_change_first_left;
   float32_T lane_curvature_change_first_right;
   float32_T lane_curvature_change_second_left;
   float32_T lane_curvature_change_second_right;
   float32_T lane_existance_probability_first_left;
   float32_T lane_existance_probability_first_right;
   float32_T lane_existance_probability_second_left;
   float32_T lane_existance_probability_second_right;
   unsigned8_T lane_border_status_first_left;
   unsigned8_T lane_border_status_first_right;
   unsigned8_T lane_border_status_second_left;
   unsigned8_T lane_border_status_second_right;
   unsigned8_T lane_type_first_left;
   unsigned8_T lane_type_first_right;
   unsigned8_T lane_type_second_left;
   unsigned8_T lane_type_second_right;
   unsigned8_T lane_color_first_left;
   unsigned8_T lane_color_first_right;
   u16p0_T K_Unused16_1;
} RECU_Camera_Data_Udp_Log_T;
typedef struct RECU_RECW_INPUT_LOG_Tag /*Offset Start byte of the Structure RECW_INPUT_LOG is 348 bytes*/
{
   unsigned8_T f_recw_switch;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
   float32_T accelerator_pedal_gradient;
   unsigned8_T unused;
   u8p0_T K_Unused8_2;
   u16p0_T K_Unused16_2;
} RECU_RECW_INPUT_LOG_T;
typedef struct RECU_Recw_Output_Udp_Log_Tag /*Offset Start byte of the Structure Recw_Output_Udp_Log is 360 bytes*/
{
   float32_T recw_ttc;
   float32_T recw_obj_distance;
   float32_T recw_obj_speed;
   float32_T recw_obj_lat_pos;
   float32_T recw_obj_long_pos;
   float32_T recw_obj_heading;
   float32_T recw_crash_probability;
   float32_T recw_overlap;
   float32_T recw_ttc_warning_threshold;
   float32_T recb_nominal_acceleration_applied;
   unsigned8_T recw_status;
   unsigned8_T recw_alert_signal;
   unsigned8_T recw_acute_alert_signal;
   unsigned8_T recw_obj_id;
   unsigned8_T recw_obj_class;
   unsigned8_T recw_obj_class_cdc;
   unsigned8_T unused;
   unsigned8_T recb_braking_signal;
   unsigned8_T recb_qualifier_nominal_acceleration;
   unsigned8_T recb_SSM;
   unsigned8_T recb_integrity;
   u8p0_T K_Unused8_1;
} RECU_Recw_Output_Udp_Log_T;
typedef struct RECU_RECW_LOG_Tag /*Offset Start byte of the Structure RECW_LOG is 412 bytes*/
{
   RECU_RECW_INPUT_LOG_T recw_input_log;
   RECU_Recw_Output_Udp_Log_T recw_output;
} RECU_RECW_LOG_T;
typedef struct RECU_LCDA_INPUT_LOG_Tag /*Offset Start byte of the Structure LCDA_INPUT_LOG is 476 bytes*/
{
   unsigned8_T f_lcda_enable;
   unsigned8_T f_lcda_enable_bsw;
   unsigned8_T f_lcda_enable_cvw;
   unsigned8_T f_lcda_enable_slc;
   unsigned8_T f_lcda_enable_awa;
   unsigned8_T f_lcda_enable_dropback;
   unsigned8_T f_lcda_enable_fallback;
   unsigned8_T f_lcda_enable_environment_plausibilization;
   unsigned8_T f_lcda_trailer_mode;
   unsigned8_T f_lcda_trailer_connected;
   unsigned8_T lcda_warntrigger_hmi;
   unsigned8_T navigation_data_road_type;
   unsigned8_T navigation_data_number_of_lanes;
   unsigned8_T f_lcda_enable_basic_lane_model;
   unsigned8_T f_lcda_enable_extended_lane_model;
   unsigned8_T driver_side;
   unsigned8_T country_type;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_LCDA_INPUT_LOG_T;
typedef struct RECU_Lcda_Output_Udp_Log_Tag /*Offset Start byte of the Structure Lcda_Output_Udp_Log is 496 bytes*/
{
   float32_T cvw_ttc[NUMBER_OF_SIDES_UDP_LOG];
   float32_T slc_ttc[NUMBER_OF_SIDES_UDP_LOG];
   float32_T slc_lane_change_probability[NUMBER_OF_SIDES_UDP_LOG];
   float32_T awa_ttc[NUMBER_OF_SIDES_UDP_LOG];
   float32_T awa_dec[NUMBER_OF_SIDES_UDP_LOG];
   float32_T lane_width;
   float32_T lane_center_offset;
   float32_T lcda_object_px_left;
   float32_T lcda_object_py_left;
   float32_T lcda_object_ttc_left;
   float32_T lcda_object_vx_left;
   float32_T lcda_object_vy_left;
   float32_T lcda_object_px_right;
   float32_T lcda_object_py_right;
   float32_T lcda_object_ttc_right;
   float32_T lcda_object_vx_right;
   float32_T lcda_object_vy_right;
   unsigned16_T lcda_object_existance_probability_left;
   unsigned16_T lcda_object_existance_probability_right;
   unsigned8_T bsw_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T cvw_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T slc_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T awa_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T bsw_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T cvw_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T slc_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T awa_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T f_awa_enabled;
   unsigned8_T f_lcda_enabled;
   unsigned8_T f_bsw_enabled;
   unsigned8_T f_cvw_enabled;
   unsigned8_T f_slc_enabled;
   unsigned8_T lcda_object_type_left;
   unsigned8_T lcda_object_type_right;
   unsigned8_T lcda_object_id_left;
   unsigned8_T lcda_object_lane_change_probability_left;
   unsigned8_T lcda_object_id_right;
   unsigned8_T lcda_object_lane_change_probability_right;
   u8p0_T K_Unused8_1;
} RECU_Lcda_Output_Udp_Log_T;
typedef struct RECU_LCDA_LOG_Tag /*Offset Start byte of the Structure LCDA_LOG is 616 bytes*/
{
   RECU_LCDA_INPUT_LOG_T lcda_input_log;
   RECU_Lcda_Output_Udp_Log_T lcda_output;
} RECU_LCDA_LOG_T;
typedef struct RECU_CTA_INPUT_LOG_Tag /*Offset Start byte of the Structure CTA_INPUT_LOG is 756 bytes*/
{
   unsigned32_T cta_radar_position;
   boolean_T f_cta_switch;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_CTA_INPUT_LOG_T;
typedef struct RECU_CTA_ERRORS_Tag /*Offset Start byte of the Structure CTA_ERRORS is 764 bytes*/
{
   bitfield32_T f_input_ptr_null : 1;
   bitfield32_T f_tracker_ptr_null : 1;
   bitfield32_T f_vehicle_ptr_null : 1;
   bitfield32_T f_cals_ptr_null : 1;
   bitfield32_T f_persistant_ptr_null : 1;
   bitfield32_T f_error_flag_unused : 27;
} RECU_CTA_ERRORS_T;
typedef struct RECU_Cta_Output_Udp_Log_Tag /*Offset Start byte of the Structure Cta_Output_Udp_Log is 768 bytes*/
{
   RECU_CTA_ERRORS_T error_flags;
   float32_T cta_ttc_left;
   float32_T RCTB_brake_request;
   float32_T cta_ttc_right;
   float32_T crash_prob_left;
   float32_T crash_prob_right;
   float32_T Dist_rel_object_left;
   float32_T Vel_rel_object_left;
   float32_T Acc_rel_object_left;
   float32_T Dist_rel_object_right;
   float32_T Vel_rel_object_right;
   float32_T Acc_rel_object_right;
   signed32_T cta_id_left;
   signed32_T cta_id_right;
   unsigned8_T f_cta_enabled;
   unsigned8_T f_cta_alert_left;
   unsigned8_T f_cta_warn_left;
   unsigned8_T cta_radarposition;
   unsigned8_T f_cta_alert_right;
   unsigned8_T f_cta_warn_right;
   unsigned8_T RCTB_qualifier;
   unsigned8_T dummy1;
} RECU_Cta_Output_Udp_Log_T;
typedef struct RECU_Path_Tracking_Nearest_Path_Udp_Log_Tag /*Offset Start byte of the Structure Path_Tracking_Nearest_Path_Udp_Log is 832 bytes*/
{
   float32_T range_vcs_proj_to_path_segment;
   float32_T segment_heading_diff;
   signed8_T track_idx_nearest_path;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_Path_Tracking_Nearest_Path_Udp_Log_T;
typedef struct RECU_Path_Object_Pair_Output_Udp_Log_Tag /*Offset Start byte of the Structure Path_Object_Pair_Output_Udp_Log is 844 bytes*/
{
   float32_T range_at_zero;
   float32_T range_to_current_path_part;
   float32_T path_heading;
   float32_T range_at_host_edge;
   float32_T length_of_trajectory;
   unsigned32_T path_direction;
   unsigned8_T track_match_age;
   signed8_T track_match;
   signed8_T track_match_last_cycle;
   u8p0_T K_Unused8_1;
} RECU_Path_Object_Pair_Output_Udp_Log_T;
typedef struct RECU_Path_Tracking_Output_Udp_Log_Tag /*Offset Start byte of the Structure Path_Tracking_Output_Udp_Log is 872 bytes*/
{
   RECU_Path_Tracking_Nearest_Path_Udp_Log_T nearest_path_output[PA_OBJ_NUMBER_OF_OBJECTS_UDP_LOG];
   RECU_Path_Object_Pair_Output_Udp_Log_T path_obj_pair_output[PA_OBJ_NUMBER_OF_OBJECTS_UDP_LOG];
   boolean_T f_pt_operational;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_Path_Tracking_Output_Udp_Log_T;
typedef struct RECU_CTA_LOG_Tag /*Offset Start byte of the Structure CTA_LOG is 2876 bytes*/
{
   RECU_CTA_INPUT_LOG_T cta_input_log;
   RECU_Cta_Output_Udp_Log_T cta_output_log;
} RECU_CTA_LOG_T;
typedef struct RECU_Ta_BMW_Boardnet_Udp_Log_Tag /*Offset Start byte of the Structure Ta_BMW_Boardnet_Udp_Log is 2948 bytes*/
{
   float32_T acceleration_longitudinal_cog;
   float32_T acceleration_longitudinal_cog_qualifier;
   float32_T acceleration_lateral_cog;
   float32_T acceleration_lateral_cog_qualifier;
   float32_T acceleration_driving_direction;
   float32_T status_braking_driver;
   float32_T accelerator_pedal_angle;
   float32_T accelerator_pedal_angle_gradient;
   float32_T accelerator_pedal_angle_qualifier;
   float32_T ego_trajectory_curvature;
   float32_T ego_trajectory_curvature_qualifier;
   float32_T control_prewarning;
   float32_T control_active_safety;
   float32_T control_move_off_prevention;
   float32_T driving_direction_vehicle_confirmed;
   float32_T status_warn_brake_coordinator;
   float32_T qualifier_function_brake_chain;
   float32_T qualifier_function_warning_chain;
   float32_T steering_angle_driver;
   float32_T steering_angle_driver_qualifier;
   float32_T steering_angle_front_axle;
   float32_T steering_angle_front_axle_qualifier;
   float32_T steering_angle_front_axle_condition;
   float32_T status_condition_vehicle;
   float32_T status_condition_vehicle_qualifier;
   float32_T velocity_vehicle_longitudinal;
   float32_T velocity_vehicle_longitudinal_qualifier;
   float32_T yawrate;
   float32_T yawrate_qualifier;
   float32_T status_control_longitudinal_guidance;
   float32_T status_interface_driverassistance_limit;
   unsigned8_T lcda_warntrigger_hmi;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_Ta_BMW_Boardnet_Udp_Log_T;
typedef struct RECU_TA_INPUT_LOG_Tag /*Offset Start byte of the Structure TA_INPUT_LOG is 3076 bytes*/
{
   RECU_Ta_BMW_Boardnet_Udp_Log_T ta_bmw_boardnet_signals;
   float32_T fta_obj_offset_x_positive;
   float32_T fta_obj_offset_x_negative;
   float32_T fta_obj_offset_y_positive;
   float32_T fta_obj_offset_y_negative;
   unsigned8_T f_fta_enable;
   unsigned8_T f_rta_enable;
   unsigned8_T f_rta_enable_turning_area;
   unsigned8_T f_rta_enable_dynamic_area;
   unsigned8_T fta_steering_angle_max_left;
   unsigned8_T fta_steering_angle_max_right;
   u16p0_T K_Unused16_1;
} RECU_TA_INPUT_LOG_T;
typedef struct RECU_FTA_Object_List_Udp_Log_Tag /*Offset Start byte of the Structure FTA_Object_List_Udp_Log is 3228 bytes*/
{
   float32_T fta_obj_list_rcs;
   float32_T fta_obj_list_id;
   float32_T fta_obj_list_age;
   float32_T fta_obj_list_meas_status;
   float32_T fta_obj_list_move_status;
   float32_T fta_obj_list_exist_prob;
   float32_T fta_obj_list_ref_point;
   float32_T fta_obj_list_ref_pnt_long_posn;
   float32_T fta_obj_list_ref_pnt_long_posn_std_dev;
   float32_T fta_obj_list_ref_pnt_lat_posn;
   float32_T fta_obj_list_ref_pnt_lat_posn_std_dev;
   float32_T fta_obj_list_covariance_posn;
   float32_T fta_obj_list_yaw_angle;
   float32_T fta_obj_list_yaw_angle_std_dev;
   float32_T fta_obj_list_long_vel;
   float32_T fta_obj_list_long_vel_std_dev;
   float32_T fta_obj_list_lat_vel;
   float32_T fta_obj_list_lat_vel_std_dev;
   float32_T fta_obj_list_covariance_vel;
   float32_T fta_obj_list_long_accel;
   float32_T fta_obj_list_long_accel_std_dev;
   float32_T fta_obj_list_lat_accel;
   float32_T fta_obj_list_lat_accel_std_dev;
   float32_T fta_obj_list_covariance_accel;
   float32_T fta_obj_list_yawrate;
   float32_T fta_obj_list_yawrate_std_dev;
   float32_T fta_obj_list_length;
   float32_T fta_obj_list_length_std_dev;
   float32_T fta_obj_list_width;
   float32_T fta_obj_list_width_std_dev;
   float32_T fta_obj_list_object_class;
} RECU_FTA_Object_List_Udp_Log_T;
typedef struct RECU_Ta_Output_Udp_Log_Tag /*Offset Start byte of the Structure Ta_Output_Udp_Log is 3352 bytes*/
{
   float32_T fta_brake_deceleration_request;
   float32_T ta_ttp_left;
   float32_T ta_ttp_right;
   float32_T fta_target_gap;
   float32_T fta_ttc;
   float32_T rta_long_posn_left;
   float32_T rta_lat_posn_left;
   float32_T rta_long_posn_right;
   float32_T rta_lat_posn_right;
   float32_T rta_ttc_left;
   float32_T rta_ttc_right;
   float32_T rta_long_vel_left;
   float32_T rta_lat_vel_left;
   float32_T rta_long_vel_right;
   float32_T rta_lat_vel_right;
   float32_T rta_existence_probability_left;
   float32_T rta_existence_probability_right;
   float32_T ta_ttc_left;
   float32_T ta_collision_probability_left;
   float32_T ta_ttc_right;
   float32_T ta_collision_probability_right;
   float32_T ta_current_deceleration_estimate;
   float32_T fta_target_age;
   float32_T fta_target_vel_long;
   float32_T fta_target_vel_lat;
   float32_T fta_target_exist_prob;
   unsigned16_T unused2;
   unsigned8_T fta_alert_level;
   unsigned8_T fta_symbol_request;
   unsigned8_T fta_brake_threshold_reduction;
   unsigned8_T fta_brake_conditioning;
   unsigned8_T f_fta_enable;
   unsigned8_T f_rta_enable;
   unsigned8_T f_rta_enable_turning_area;
   unsigned8_T f_rta_enable_dynamic_area;
   unsigned8_T fta_target_id;
   unsigned8_T fta_maneuver_direction;
   unsigned8_T rta_dynamic_area_status;
   unsigned8_T rta_turning_area_status;
   unsigned8_T rta_alert_left;
   unsigned8_T rta_alert_right;
   unsigned8_T rta_id_left;
   unsigned8_T rta_id_right;
   unsigned8_T ta_alert_left;
   unsigned8_T ta_id_left;
   unsigned8_T ta_alert_right;
   unsigned8_T ta_id_right;
   unsigned8_T ta_turn_maneuver;
   unsigned8_T unused1;
   unsigned8_T lcda_warntrigger_hmi;
   boolean_T f_diagnostic_mode;
   u16p0_T K_Unused16_1;
   RECU_FTA_Object_List_Udp_Log_T fta_relevant_object[N_OBJECTS_UDP_LOG];
} RECU_Ta_Output_Udp_Log_T;
typedef struct RECU_TA_LOG_Tag /*Offset Start byte of the Structure TA_LOG is 4476 bytes*/
{
   RECU_TA_INPUT_LOG_T ta_input_log;
   RECU_Ta_Output_Udp_Log_T ta_output;
} RECU_TA_LOG_T;
typedef struct RECU_CED_INPUT_LOG_Tag /*Offset Start byte of the Structure CED_INPUT_LOG is 5752 bytes*/
{
   boolean_T f_ced_enable;
   boolean_T f_ced_front_mode;
   boolean_T f_ced_rear_mode;
   u8p0_T K_Unused8_1;
} RECU_CED_INPUT_LOG_T;
typedef struct RECU_Ced_Output_Udp_Log_Tag /*Offset Start byte of the Structure Ced_Output_Udp_Log is 5756 bytes*/
{
   float32_T SFE_CED_ttc_left;
   float32_T SFE_CED_ttc_right;
   float32_T SFE_CED_rear_ttc_right;
   float32_T SFE_CED_rear_ttc_left;
   float32_T SFE_CED_rear_lat_right;
   float32_T SFE_CED_rear_lat_left;
   float32_T SFE_CED_front_ttc_right;
   float32_T SFE_CED_front_ttc_left;
   float32_T SFE_CED_front_lat_right;
   float32_T SFE_CED_front_lat_left;
   float32_T SFE_CED_obj_speed_right;
   float32_T SFE_CED_obj_speed_left;
   float32_T SFE_CED_obj_heading_right;
   float32_T SFE_CED_obj_lateral_pos_right;
   float32_T SFE_CED_obj_lateral_pos_left;
   float32_T SFE_CED_obj_long_pos_right;
   float32_T SFE_CED_obj_long_pos_left;
   float32_T SFE_CED_obj_heading_left;
   unsigned8_T SFE_CED_Status;
   unsigned8_T SFE_CED_alert_right;
   unsigned8_T SFE_CED_alert_left;
   unsigned8_T SFE_CED_dir_right;
   unsigned8_T SFE_CED_dir_left;
   unsigned8_T unused_1;
   unsigned8_T SFE_CED_id_right;
   unsigned8_T SFE_CED_id_left;
   unsigned8_T SFE_CED_rear_status;
   unsigned8_T SFE_CED_rear_alert_right;
   unsigned8_T SFE_CED_rear_alert_left;
   unsigned8_T SFE_CED_rear_id_right;
   unsigned8_T SFE_CED_rear_id_left;
   unsigned8_T SFE_CED_rear_path_match_right;
   unsigned8_T SFE_CED_rear_path_match_left;
   unsigned8_T SFE_CED_front_status;
   unsigned8_T SFE_CED_front_alert_right;
   unsigned8_T SFE_CED_front_alert_left;
   unsigned8_T SFE_CED_front_id_right;
   unsigned8_T SFE_CED_front_id_left;
   unsigned8_T SFE_CED_front_path_match_right;
   unsigned8_T SFE_CED_front_path_match_left;
   unsigned8_T SFE_CED_obj_type_right;
   unsigned8_T SFE_CED_obj_type_left;
} RECU_Ced_Output_Udp_Log_T;
typedef struct RECU_CED_LOG_Tag /*Offset Start byte of the Structure CED_LOG is 5852 bytes*/
{
   RECU_CED_INPUT_LOG_T ced_input_log;
   RECU_Ced_Output_Udp_Log_T ced_output;
} RECU_CED_LOG_T;
typedef struct RECU_PATH_TRACKING_LOG_Tag /*Offset Start byte of the Structure PATH_TRACKING_LOG is 5952 bytes*/
{
   RECU_Path_Tracking_Output_Udp_Log_T Path_Tracking_Output_Udp_Log;
} RECU_PATH_TRACKING_LOG_T;
typedef struct RECU_SCW_INPUT_LOG_Tag /*Offset Start byte of the Structure SCW_INPUT_LOG is 7956 bytes*/
{
   unsigned8_T f_scw_enable;
   unsigned8_T f_scw_enable_dynamic;
   unsigned8_T f_scw_enable_guardrail;
   u8p0_T K_Unused8_1;
} RECU_SCW_INPUT_LOG_T;
typedef struct RECU_Scw_Output_Udp_Log_Tag /*Offset Start byte of the Structure Scw_Output_Udp_Log is 7960 bytes*/
{
   float32_T scw_object_px_left;
   float32_T scw_object_py_left;
   float32_T scw_object_width_left;
   float32_T scw_object_length_left;
   float32_T scw_object_heading_left;
   float32_T scw_object_ttc_left;
   float32_T scw_object_vx_left;
   float32_T scw_object_vy_left;
   float32_T scw_object_ax_left;
   float32_T scw_object_ay_left;
   float32_T scw_object_px_right;
   float32_T scw_object_py_right;
   float32_T scw_object_width_right;
   float32_T scw_object_length_right;
   float32_T scw_object_heading_right;
   float32_T scw_object_ttc_right;
   float32_T scw_object_vx_right;
   float32_T scw_object_vy_right;
   float32_T scw_object_ax_right;
   float32_T scw_object_ay_right;
   unsigned16_T scw_object_existance_probability_left;
   unsigned16_T scw_object_age_left;
   unsigned16_T scw_object_existance_probability_right;
   unsigned16_T scw_object_age_right;
   unsigned8_T f_scw_enabled;
   unsigned8_T f_scw_dyn_enabled;
   unsigned8_T f_scw_guardrail_enabled;
   unsigned8_T scw_object_type_left;
   unsigned8_T scw_object_id_left;
   unsigned8_T scw_object_type_right;
   unsigned8_T scw_object_id_right;
   u8p0_T K_Unused8_1;
} RECU_Scw_Output_Udp_Log_T;
typedef struct RECU_SCW_LOG_Tag /*Offset Start byte of the Structure SCW_LOG is 8056 bytes*/
{
   RECU_SCW_INPUT_LOG_T scw_input_log;
   RECU_Scw_Output_Udp_Log_T scw_output;
} RECU_SCW_LOG_T;
typedef struct RECU_FF_OUTPUT_Logging_Data_Tag /*Offset Start byte of the Structure FF_OUTPUT_Logging_Data is 8156 bytes*/
{
   RECU_RECW_LOG_T recw_Log;
   RECU_LCDA_LOG_T lcda_log;
   RECU_CTA_LOG_T cta_log;
   RECU_TA_LOG_T ta_log;
   RECU_CED_LOG_T ced_log;
   RECU_PATH_TRACKING_LOG_T path_tracking_log;
   RECU_SCW_LOG_T scw_log;
} RECU_FF_OUTPUT_Logging_Data_T;
typedef struct RECU_GDSR_TRACKER_LOG_OUTPUT_Tag /*Offset Start byte of the Structure GDSR_TRACKER_LOG_OUTPUT is 11912 bytes*/
{
   float32_T vcs_long_posn[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T vcs_long_vel[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T vcs_lat_posn[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T vcs_lat_vel[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T heading[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T length[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T width[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T age[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned32_T status[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned32_T object_class[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned8_T object_id[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned8_T f_stationary[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned8_T f_moveable[NUMBER_OF_OBJECTS_UDP_LOG];
   u16p0_T K_Unused16_1;
} RECU_GDSR_TRACKER_LOG_OUTPUT_T;
typedef struct RECU_LCDA_SM_INPUT_Tag /*Offset Start byte of the Structure LCDA_SM_INPUT is 14064 bytes*/
{
   float32_T Veh_Speed;
   unsigned32_T Direction_of_travel;
   unsigned8_T Status_trailer;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_LCDA_SM_INPUT_T;
typedef struct RECU_LCDA_SM_Output_Tag /*Offset Start byte of the Structure LCDA_SM_Output is 14076 bytes*/
{
   unsigned32_T Status_Blind_Spot_Area;
   unsigned32_T Status_Dynamic_Area;
   unsigned32_T Status_Simultaneous_Lane_Change;
   unsigned32_T event_data_qualifier;
   unsigned32_T Extended_Qualifier;
   unsigned16_T lcw_sm_resim_flag;
   u16p0_T K_Unused16_1;
   RECU_Lcda_Output_Udp_Log_T p_lcda_SM_output;
} RECU_LCDA_SM_Output_T;
typedef struct RECU_SCW_SM_Input_Tag /*Offset Start byte of the Structure SCW_SM_Input is 14220 bytes*/
{
   unsigned32_T Unused_1;
} RECU_SCW_SM_Input_T;
typedef struct RECU_SCW_State_Machine_Output_Tag /*Offset Start byte of the Structure SCW_State_Machine_Output is 14224 bytes*/
{
   unsigned32_T event_data_qualifier;
   unsigned32_T extended_qualifier;
   unsigned16_T scw_sm_resim_flag;
   unsigned8_T state_scw;
   unsigned8_T status_guardrail;
   RECU_Scw_Output_Udp_Log_T scw_output;
} RECU_SCW_State_Machine_Output_T;
typedef struct RECU_CED_SM_Input_Tag /*Offset Start byte of the Structure CED_SM_Input is 14332 bytes*/
{
   float32_T Veh_Speed;
   float32_T sfe_ced_obj_speed_driver;
   float32_T sfe_ced_obj_speed_passenger;
   float32_T sfe_ced_ttc_driver;
   float32_T sfe_ced_ttc_passenger;
   unsigned32_T Time_Sec_Counter;
   unsigned16_T Time_Day_Counter;
   unsigned8_T Direction_of_travel;
   unsigned8_T Status_trailer;
   unsigned8_T control_safe_exit;
   unsigned8_T control_safer_exit_sound;
   unsigned8_T status_seat_occupying_DR;
   unsigned8_T status_seat_occupying_PS;
   unsigned8_T status_seat_occupying_RDR;
   unsigned8_T status_seat_occupying_RPS;
   unsigned8_T status_belt_switch_DR;
   unsigned8_T status_belt_switch_PS;
   unsigned8_T status_belt_switch_RDR;
   unsigned8_T status_belt_switch_RPS;
   unsigned8_T status_door_lock_DR;
   unsigned8_T status_door_lock_PS;
   unsigned8_T status_door_lock_RDR;
   unsigned8_T status_door_lock_RPS;
   unsigned8_T status_inside_pushbutton_DR;
   unsigned8_T status_inside_pushbutton_PS;
   unsigned8_T status_inside_pushbutton_RDR;
   unsigned8_T status_inside_pushbutton_RPS;
   unsigned8_T alert_driver;
   unsigned8_T alert_passenger;
   unsigned8_T sfe_ced_id_driver;
   unsigned8_T sfe_ced_id_passenger;
   unsigned8_T sfe_ced_obj_type_driver;
   unsigned8_T sfe_ced_obj_type_passenger;
   unsigned8_T status_automatic_doors_DR;
   unsigned8_T status_automatic_doors_PS;
   unsigned8_T status_automatic_doors_RDR;
   unsigned8_T status_automatic_doors_RPS;
   unsigned8_T st_chisl;
   unsigned8_T operation_open_lock_request_DR;
   unsigned8_T operation_open_lock_request_PS;
   unsigned8_T operation_open_lock_request_RDR;
   unsigned8_T operation_open_lock_request_RPS;
   boolean_T FL_SFE_CED_Degraded;
   boolean_T FR_SFE_CED_Degraded;
   boolean_T RL_SFE_CED_Degraded;
   boolean_T RR_SFE_CED_Degraded;
   boolean_T FL_SFE_CED_Error;
   boolean_T FR_SFE_CED_Error;
   boolean_T RL_SFE_CED_Error;
   boolean_T RR_SFE_CED_Error;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_CED_SM_Input_T;
typedef struct RECU_CED_SM_Output_Tag /*Offset Start byte of the Structure CED_SM_Output is 14404 bytes*/
{
   float32_T EdrDrasyStaticVelocity;
   unsigned32_T EdrDrasyStaticTimestampMsec;
   unsigned32_T EdrDrasyStaticTimestampSec;
   unsigned32_T request_interier_display_doors;
   unsigned16_T sfe_sm_resim_flag;
   unsigned8_T request_automatic_door_stop;
   unsigned8_T request_door_lock;
   unsigned8_T requestExteriorMirrorDisplayWarningDriverSFE;
   unsigned8_T requestExteriorMirrorDisplayWarningPassengerSFE;
   unsigned8_T display_SafeExit_Warning_Front_Left;
   unsigned8_T display_SafeExit_Warning_Front_Right;
   unsigned8_T display_SafeExit_Warning_Rear_Left;
   unsigned8_T display_SafeExit_Warning_Rear_Right;
   unsigned8_T Request_Gong_FAO;
   unsigned8_T Request_Gong_DUR;
   unsigned8_T Request_Gong_LCN;
   unsigned8_T Request_Gong_TYP;
   unsigned8_T Request_Gong_ANG;
   unsigned8_T Request_Gong_DIST;
   unsigned8_T Request_Gong_HND;
   unsigned8_T Request_Gong_ID;
   unsigned8_T stop_gong_ID;
   unsigned8_T stop_gong_handle;
   unsigned8_T EdrDrasyEventID62ASafeExitOrientation;
   unsigned8_T EdrDrasyEventID62AGongType;
   unsigned8_T EdrDrasyEventID62AGongLocalisation;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchDRD;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchPSD;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchDVDR;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchPSDR;
   unsigned8_T EdrDrasyEventID62AStatusSafeExit;
} RECU_CED_SM_Output_T;
typedef struct RECU_CTA_App_Params_Tag /*Offset Start byte of the Structure CTA_App_Params is 14448 bytes*/
{
   unsigned16_T A_CTA_speedThreshold_hysteresis_kmh;
   unsigned16_T A_CTA_speedThreshold_hysteresis_mph;
   unsigned16_T A_CTA_timeDelay_warning_acoustic;
   unsigned16_T A_CTA_timeDelay_warning_visual;
   unsigned16_T A_CTA_timeDelay_warning_mirror_LED;
   unsigned16_T A_CTB_distance_thirdPartyVehicle;
   unsigned16_T A_CTB_Sollbeschleunigung_Ziel_Bremsen_Verzoegerung;
   unsigned16_T A_CTB_targetAcceleration_target_braking_time;
   unsigned16_T A_CTB_targetAcceleration_target_release_deceleration;
   unsigned16_T A_CTB_targetAcceleration_target_release_time;
   unsigned16_T A_CTB_max_TTC;
   unsigned16_T A_CTB_min_TTC;
   unsigned16_T A_CTB_responseTime_brakeActuation;
   unsigned16_T A_CTB_deadTime;
   unsigned16_T A_CTB_max_number_brakingOperations_per_parkingManeuver;
   unsigned16_T A_CTB_gradient_actuation_acceleratorPedal_override;
   unsigned16_T A_CTB_gradient_actuation_acceleratorPedal_sporty_driveOff;
   unsigned16_T A_CTB_integrity;
   unsigned8_T A_CTB_target_status_longitudinalGuidance;
   unsigned8_T A_CTB_qualifier_targetAccel_target_limit;
   u16p0_T K_Unused16_1;
} RECU_CTA_App_Params_T;
typedef struct RECU_CTA_SM_Input_Tag /*Offset Start byte of the Structure CTA_SM_Input is 14488 bytes*/
{
   float32_T speed_speedometer;
   float32_T speed_vehicle;
   unsigned32_T Time_Sec_Counter;
   unsigned16_T Time_Day_Counter;
   signed16_T gradient_actuation_acceleratorPedal;
   signed16_T drivingTorque_driverRequest;
   unsigned8_T control_cross_traffic_brake;
   unsigned8_T st_drvdir_dvch;
   unsigned8_T drvdir_veh_cfd;
   unsigned8_T st_tria;
   unsigned8_T status_rollerDynamometerMode;
   unsigned8_T qualifier_speed_vehicle;
   unsigned8_T drivingDirection_vehicle;
   unsigned8_T request_dimming_warning_laneChange;
   unsigned8_T qualifier_gradient_actuation_acceleratorPedal;
   unsigned8_T qualifier_v_veh_cog;
   boolean_T status_endOfLineMode;
   boolean_T status_activation_function_parking;
   boolean_T request_states_function_parking;
   u8p0_T K_Unused8_1;
} RECU_CTA_SM_Input_T;
typedef struct RECU_Warning_Acoustic_Tag /*Offset Start byte of the Structure Warning_Acoustic is 14520 bytes*/
{
   unsigned8_T GO_ID;
   unsigned8_T GO_HND;
   unsigned8_T GO_DIST;
   unsigned8_T GO_ANG;
   unsigned8_T GO_TYP;
   unsigned8_T GO_LCN;
   unsigned8_T GO_FAO;
   unsigned8_T GO_DUR;
   unsigned8_T IGP_updated;
   unsigned8_T stop_GO_HND;
   unsigned8_T stop_GO_ID;
   u8p0_T K_Unused8_1;
} RECU_Warning_Acoustic_T;
typedef struct RECU_CTA_SM_Output_Tag /*Offset Start byte of the Structure CTA_SM_Output is 14532 bytes*/
{
   float32_T target_state_longitudinalGuidance;
   float32_T targetAcceleration_target;
   unsigned32_T qualifier_function_ctb;
   RECU_Warning_Acoustic_T warning_acoustic;
   unsigned16_T cta_sm_resim_flag;
   unsigned8_T CounterRequestCTB;
   unsigned8_T status_brakeRequest;
   unsigned8_T display_warning_graphic;
   unsigned8_T request_warning_displayElement_left;
   unsigned8_T request_warning_displayElement_right;
   unsigned8_T request_warning_dimming;
   unsigned8_T qualifier_targetAccel_limit;
   unsigned8_T request_brake_integrity;
   unsigned8_T EdrDrasyEventID62CTBStatus;
   unsigned8_T EdrDrasyEventID62CTBOrientation;
   unsigned8_T EdrDrasyEventID62CTBBraking;
   unsigned8_T EdrDrasyEventID62GongType;
   unsigned8_T EdrDrasyEventID62GongLocalisation;
   u8p0_T K_Unused8_1;
} RECU_CTA_SM_Output_T;
typedef struct RECU_RECW_App_Params_Tag /*Offset Start byte of the Structure RECW_App_Params is 14572 bytes*/
{
   float32_T A_RECW_V_rel_min;
   float32_T A_RECW_V_rel_max;
   float32_T A_PCSH_V_rel_max;
   float32_T A_PCSH_V_rel_min;
   float32_T A_RECW_V_ego_min;
   float32_T A_RECW_V_ego_max;
   float32_T A_PCSH_V_ego_min;
   float32_T A_PCSH_V_ego_max;
   float32_T A_RECB_V_ego_max;
   float32_T A_RECB_V_0_time;
   float32_T A_RECB_V_rel_min;
   float32_T A_RECB_TTC_max;
   float32_T A_RECB_Ruecknahmezeit;
   float32_T A_RECB_Gradient_Gaspedal;
   float32_T A_RECB_Sollbeschleunigung;
   unsigned8_T A_RECB_Qualifier_Sollbeschleunigung_Ziel_Limit;
   unsigned8_T A_RECB_Integritaet;
   unsigned8_T A_RECB_SSM;
   u8p0_T K_Unused8_1;
} RECU_RECW_App_Params_T;
typedef struct RECU_RECW_SM_Input_Tag /*Offset Start byte of the Structure RECW_SM_Input is 14636 bytes*/
{
   float32_T speed;
   unsigned32_T Time_Sec_Counter;
   unsigned16_T Time_Day_Counter;
   unsigned8_T Direction_of_travel;
   unsigned8_T Status_trailer;
   unsigned8_T dynamometerMode;
   unsigned8_T ControlSetting2RECWMDrive;
   boolean_T status_endOfLineMode;
   u8p0_T K_Unused8_1;
} RECU_RECW_SM_Input_T;
typedef struct RECU_RECW_SM_Output_Tag /*Offset Start byte of the Structure RECW_SM_Output is 14652 bytes*/
{
   float32_T Sollbeschleunigung_Ziel;
   float32_T DistanceToObstacleSideRadarRear;
   float32_T CollisionAngleSideRadarRear;
   float32_T CollisionOverlap_PreCrash_RearRadar;
   unsigned32_T recw_state_PCAN;
   unsigned32_T Status_PreCrash_Heckradar;
   unsigned32_T Status_Auffahrwarnung_Heck;
   float32_T Annaeherungsgeschwindigkeit_PreCrash_Heckradar;
   float32_T Aufprallzeit_PreCrash_Heckradar;
   unsigned16_T recw_sm_resim_flag;
   unsigned8_T Anforderung_Bremse_Qualifier;
   unsigned8_T Qualifier_Sollbeschleunigung_Ziel_Limit;
   unsigned8_T Soll_Zustand_Laengsfuehrung;
   unsigned8_T Anforderung_Bremse_Integritaet;
   unsigned8_T EdrDrasyEventID62AStatusCollisionWarningSideRadarRear;
   unsigned8_T EdrDrasyEventID62AStatusPreCrashSideRadarRear;
   unsigned8_T ObstacleTypeSideRadarRear;
   unsigned8_T EdrDrasyEventID62ATrigger;
   u16p0_T K_Unused16_1;
} RECU_RECW_SM_Output_T;
typedef struct RECU_TAP_SM_Input_Tag /*Offset Start byte of the Structure TAP_SM_Input is 14700 bytes*/
{
   float32_T Ego_Speed;
   unsigned32_T Direction_Of_Travel_TAP;
   unsigned16_T ta_sm_resim_flag;
   unsigned8_T Status_Turning_Area_TAP;
   unsigned8_T Status_Dynamic_Area_TAP;
} RECU_TAP_SM_Input_T;
typedef struct RECU_TA_SM_Output_Tag /*Offset Start byte of the Structure TA_SM_Output is 14712 bytes*/
{
   unsigned32_T Status_Event_Data_Qualifier;
   unsigned32_T Status_Extended_Qualifier;
   unsigned8_T Status_Critical_Object;
   unsigned8_T Status_Non_Critical_Object;
   u16p0_T K_Unused16_1;
   RECU_Ta_Output_Udp_Log_T p_tap_SM_output;
} RECU_TA_SM_Output_T;
typedef struct RECU_PFGS_SM_Input_Tag /*Offset Start byte of the Structure PFGS_SM_Input is 15848 bytes*/
{
   float32_T v_veh_cog;
   float32_T Steering_angle;
   float32_T yaw_rate;
   unsigned32_T Driven_distance;
   unsigned32_T t_sec_cou;
   unsigned8_T controlActiveSafety;
   unsigned8_T ST_DYNOMOD;
   unsigned8_T ST_EOLMOD;
   unsigned8_T StDrivDirVeh;
   unsigned8_T driving_direction_choice;
   unsigned8_T ST_CON_STEA_2;
   unsigned8_T qualifier_function_brakeChain;
   unsigned8_T qualifier_function_WarnChain;
   unsigned8_T ST_CON_VEH;
   boolean_T FL_PFGS_Degraded_Flag;
   boolean_T FR_PFGS_Degraded_Flag;
   boolean_T FL_PFGS_Error_Flag;
   boolean_T FR_PFGS_Error_Flag;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_PFGS_SM_Input_T;
typedef struct RECU_PFGS_SM_Output_Tag /*Offset Start byte of the Structure PFGS_SM_Output is 15884 bytes*/
{
   float32_T gapTargetObjectPPPSide;
   float32_T targetDecelerationPPPSide;
   unsigned32_T crc_HeadwayobservationPPPSide;
   unsigned32_T alive_HeadwayobservationPPPSide;
   unsigned32_T chl_HeadwayobservationPPPSide;
   unsigned16_T pfgs_sm_resim_flag;
   unsigned8_T qualifierFunctionPPPSide;
   unsigned8_T reductionThValueBrakeAssistPPPSide;
   unsigned8_T forecastSafetyBrakePPPSide;
   unsigned8_T warningPPPSide;
   unsigned8_T requestSymbolPPPSide;
   unsigned8_T integrityBrakeRequestPPPSide;
   unsigned8_T NOT_AVAILABLE1;
   unsigned8_T NOT_AVAILABLE2;
   unsigned8_T NOT_AVAILABLE3;
   unsigned8_T NOT_AVAILABLE4;
   unsigned8_T idTargetObjectPPPSide;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_PFGS_SM_Output_T;
typedef struct RECU_FreeSpace_State_Machine_Input_Tag /*Offset Start byte of the Structure FreeSpace_State_Machine_Input is 15920 bytes*/
{
   unsigned8_T drive_direction;
   boolean_T f_function_freespace_error;
   u16p0_T K_Unused16_1;
} RECU_FreeSpace_State_Machine_Input_T;
typedef struct RECU_FF_SM_LOG_Tag /*Offset Start byte of the Structure FF_SM_LOG is 15924 bytes*/
{
   RECU_LCDA_SM_INPUT_T lcda_sm_input;
   RECU_LCDA_SM_Output_T lcda_sm_output;
   RECU_SCW_SM_Input_T scw_sm_input;
   RECU_SCW_State_Machine_Output_T scw_sm_output;
   RECU_CED_SM_Input_T ced_sm_input;
   RECU_CED_SM_Output_T ced_sm_output;
   RECU_CTA_App_Params_T cta_app_parameters;
   RECU_CTA_SM_Input_T cta_sm_input;
   RECU_CTA_SM_Output_T cta_sm_output;
   RECU_RECW_App_Params_T RECW_App_Params;
   RECU_RECW_SM_Input_T recw_sm_input;
   RECU_RECW_SM_Output_T recw_sm_output;
   RECU_TAP_SM_Input_T ta_sm_input;
   RECU_TA_SM_Output_T ta_sm_output;
   RECU_PFGS_SM_Input_T pfgs_sm_input;
   RECU_PFGS_SM_Output_T pfgs_sm_output;
   RECU_FreeSpace_State_Machine_Input_T freespace_sm_input;
} RECU_FF_SM_LOG_T;
typedef struct Radar_ECU_CORE3_Tag /*Offset Start byte of the Structure Radar_ECU_CORE3 is 17772 bytes*/
{
   RECU_Radar_ECU_CORE3_Hdr_T radar_ecu_CORE3_Hdr;
   RECU_Core_3_Timing_Info_T timing_info;
   RECU_FF_Error_Info_T ff_error_info;
   RECU_FF_version_T ff_version;
   RECU_Camera_Data_Udp_Log_T camera_data;
   RECU_FF_OUTPUT_Logging_Data_T FF_OUTPUT_Logging_Data;
   RECU_GDSR_TRACKER_LOG_OUTPUT_T gdsr_tracker_log_output;
   RECU_FF_SM_LOG_T ff_sm_log;
   boolean_T data_valid;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} Radar_ECU_CORE3_T;
#else
typedef struct RECU_Radar_ECU_CORE3_Hdr_Tag {
   unsigned16_T version_number;
   unsigned16_T run_counter;
   unsigned16_T Sec_Checksum;
   unsigned16_T Sec_Compatibility;
   unsigned32_T Sec_Size;
} RECU_Radar_ECU_CORE3_Hdr_T;
typedef struct RECU_TimeStamp_Rader_CORE3_Tag {
   unsigned32_T time_fraction;
   unsigned32_T time_seconds;
} RECU_TimeStamp_Rader_CORE3_Tag;
typedef struct RECU_Core_3_Timing_Info_Tag {
   RECU_TimeStamp_Rader_CORE3_Tag CED_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag CED_starttime;
   RECU_TimeStamp_Rader_CORE3_Tag SCW_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag SCW_starttime;
   RECU_TimeStamp_Rader_CORE3_Tag SFE_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag SFE_starttime;
   RECU_TimeStamp_Rader_CORE3_Tag TA_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag TA_starttime;
   RECU_TimeStamp_Rader_CORE3_Tag LCDA_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag LCDA_starttime;
   RECU_TimeStamp_Rader_CORE3_Tag CTA_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag CTA_starttime;
   RECU_TimeStamp_Rader_CORE3_Tag RECW_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag RECW_starttime;
   RECU_TimeStamp_Rader_CORE3_Tag core_endtime;
   RECU_TimeStamp_Rader_CORE3_Tag core_starttime;
} RECU_Core_3_Timing_Info_T;
typedef struct RECU_FF_Error_Info_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T ff_overrun_flag;
   unsigned32_T reserved;
   unsigned32_T FF_Skip_Index;
   unsigned32_T tracker_index_skipped;
   unsigned32_T FF_overrun_cnt;
} RECU_FF_Error_Info_T;
typedef struct RECU_SW_version_number_Core3_Tag {
   u16p0_T K_Unused16_1;
   unsigned16_T revision;
   unsigned16_T minor_version;
   unsigned16_T major_version;
} RECU_SW_version_number_Core3_T;
typedef struct RECU_FF_version_Tag {
   RECU_SW_version_number_Core3_T PATH_TRACKING_Version;
   RECU_SW_version_number_Core3_T CED_Version;
   RECU_SW_version_number_Core3_T Ta_Version;
   RECU_SW_version_number_Core3_T CTA_Version;
   RECU_SW_version_number_Core3_T LCDA_Version;
   RECU_SW_version_number_Core3_T RECW_Version;
} RECU_FF_version_T;
typedef struct RECU_Camera_Data_Udp_Log_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T lane_color_first_right;
   unsigned8_T lane_color_first_left;
   unsigned8_T lane_type_second_right;
   unsigned8_T lane_type_second_left;
   unsigned8_T lane_type_first_right;
   unsigned8_T lane_type_first_left;
   unsigned8_T lane_border_status_second_right;
   unsigned8_T lane_border_status_second_left;
   unsigned8_T lane_border_status_first_right;
   unsigned8_T lane_border_status_first_left;
   float32_T lane_existance_probability_second_right;
   float32_T lane_existance_probability_second_left;
   float32_T lane_existance_probability_first_right;
   float32_T lane_existance_probability_first_left;
   float32_T lane_curvature_change_second_right;
   float32_T lane_curvature_change_second_left;
   float32_T lane_curvature_change_first_right;
   float32_T lane_curvature_change_first_left;
   float32_T lane_curvature_second_right;
   float32_T lane_curvature_second_left;
   float32_T lane_curvature_first_right;
   float32_T lane_curvature_first_left;
   float32_T lane_angle_second_right;
   float32_T lane_angle_second_left;
   float32_T lane_angle_first_right;
   float32_T lane_angle_first_left;
   float32_T lane_distance_second_right;
   float32_T lane_distance_second_left;
   float32_T lane_distance_first_right;
   float32_T lane_distance_first_left;
   float32_T quality_lane_center_offset;
   float32_T quality_lane_width_right;
   float32_T quality_lane_width_left;
   float32_T quality_lane_width_ego;
   float32_T lane_center_offset;
   float32_T lane_width_right;
   float32_T lane_width_left;
   float32_T lane_width_ego;
} RECU_Camera_Data_Udp_Log_T;
typedef struct RECU_RECW_INPUT_LOG_Tag {
   u16p0_T K_Unused16_2;
   u8p0_T K_Unused8_2;
   unsigned8_T unused;
   float32_T accelerator_pedal_gradient;
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T f_recw_switch;
} RECU_RECW_INPUT_LOG_T;
typedef struct RECU_Recw_Output_Udp_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T recb_integrity;
   unsigned8_T recb_SSM;
   unsigned8_T recb_qualifier_nominal_acceleration;
   unsigned8_T recb_braking_signal;
   unsigned8_T unused;
   unsigned8_T recw_obj_class_cdc;
   unsigned8_T recw_obj_class;
   unsigned8_T recw_obj_id;
   unsigned8_T recw_acute_alert_signal;
   unsigned8_T recw_alert_signal;
   unsigned8_T recw_status;
   float32_T recb_nominal_acceleration_applied;
   float32_T recw_ttc_warning_threshold;
   float32_T recw_overlap;
   float32_T recw_crash_probability;
   float32_T recw_obj_heading;
   float32_T recw_obj_long_pos;
   float32_T recw_obj_lat_pos;
   float32_T recw_obj_speed;
   float32_T recw_obj_distance;
   float32_T recw_ttc;
} RECU_Recw_Output_Udp_Log_T;
typedef struct RECU_RECW_LOG_Tag {
   RECU_Recw_Output_Udp_Log_T recw_output;
   RECU_RECW_INPUT_LOG_T recw_input_log;
} RECU_RECW_LOG_T;
typedef struct RECU_LCDA_INPUT_LOG_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T country_type;
   unsigned8_T driver_side;
   unsigned8_T f_lcda_enable_extended_lane_model;
   unsigned8_T f_lcda_enable_basic_lane_model;
   unsigned8_T navigation_data_number_of_lanes;
   unsigned8_T navigation_data_road_type;
   unsigned8_T lcda_warntrigger_hmi;
   unsigned8_T f_lcda_trailer_connected;
   unsigned8_T f_lcda_trailer_mode;
   unsigned8_T f_lcda_enable_environment_plausibilization;
   unsigned8_T f_lcda_enable_fallback;
   unsigned8_T f_lcda_enable_dropback;
   unsigned8_T f_lcda_enable_awa;
   unsigned8_T f_lcda_enable_slc;
   unsigned8_T f_lcda_enable_cvw;
   unsigned8_T f_lcda_enable_bsw;
   unsigned8_T f_lcda_enable;
} RECU_LCDA_INPUT_LOG_T;
typedef struct RECU_Lcda_Output_Udp_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T lcda_object_lane_change_probability_right;
   unsigned8_T lcda_object_id_right;
   unsigned8_T lcda_object_lane_change_probability_left;
   unsigned8_T lcda_object_id_left;
   unsigned8_T lcda_object_type_right;
   unsigned8_T lcda_object_type_left;
   unsigned8_T f_slc_enabled;
   unsigned8_T f_cvw_enabled;
   unsigned8_T f_bsw_enabled;
   unsigned8_T f_lcda_enabled;
   unsigned8_T f_awa_enabled;
   unsigned8_T awa_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T slc_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T cvw_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T bsw_alert[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T awa_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T slc_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T cvw_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned8_T bsw_id[NUMBER_OF_SIDES_UDP_LOG];
   unsigned16_T lcda_object_existance_probability_right;
   unsigned16_T lcda_object_existance_probability_left;
   float32_T lcda_object_vy_right;
   float32_T lcda_object_vx_right;
   float32_T lcda_object_ttc_right;
   float32_T lcda_object_py_right;
   float32_T lcda_object_px_right;
   float32_T lcda_object_vy_left;
   float32_T lcda_object_vx_left;
   float32_T lcda_object_ttc_left;
   float32_T lcda_object_py_left;
   float32_T lcda_object_px_left;
   float32_T lane_center_offset;
   float32_T lane_width;
   float32_T awa_dec[NUMBER_OF_SIDES_UDP_LOG];
   float32_T awa_ttc[NUMBER_OF_SIDES_UDP_LOG];
   float32_T slc_lane_change_probability[NUMBER_OF_SIDES_UDP_LOG];
   float32_T slc_ttc[NUMBER_OF_SIDES_UDP_LOG];
   float32_T cvw_ttc[NUMBER_OF_SIDES_UDP_LOG];
} RECU_Lcda_Output_Udp_Log_T;
typedef struct RECU_LCDA_LOG_Tag {
   RECU_Lcda_Output_Udp_Log_T lcda_output;
   RECU_LCDA_INPUT_LOG_T lcda_input_log;
} RECU_LCDA_LOG_T;
typedef struct RECU_CTA_INPUT_LOG_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   boolean_T f_cta_switch;
   unsigned32_T cta_radar_position;
} RECU_CTA_INPUT_LOG_T;
typedef struct RECU_CTA_ERRORS_Tag {
   bitfield32_T f_error_flag_unused : 27;
   bitfield32_T f_persistant_ptr_null : 1;
   bitfield32_T f_cals_ptr_null : 1;
   bitfield32_T f_vehicle_ptr_null : 1;
   bitfield32_T f_tracker_ptr_null : 1;
   bitfield32_T f_input_ptr_null : 1;
} RECU_CTA_ERRORS_T;
typedef struct RECU_Cta_Output_Udp_Log_Tag {
   unsigned8_T dummy1;
   unsigned8_T RCTB_qualifier;
   unsigned8_T f_cta_warn_right;
   unsigned8_T f_cta_alert_right;
   unsigned8_T cta_radarposition;
   unsigned8_T f_cta_warn_left;
   unsigned8_T f_cta_alert_left;
   unsigned8_T f_cta_enabled;
   signed32_T cta_id_right;
   signed32_T cta_id_left;
   float32_T Acc_rel_object_right;
   float32_T Vel_rel_object_right;
   float32_T Dist_rel_object_right;
   float32_T Acc_rel_object_left;
   float32_T Vel_rel_object_left;
   float32_T Dist_rel_object_left;
   float32_T crash_prob_right;
   float32_T crash_prob_left;
   float32_T cta_ttc_right;
   float32_T RCTB_brake_request;
   float32_T cta_ttc_left;
   RECU_CTA_ERRORS_T error_flags;
} RECU_Cta_Output_Udp_Log_T;
typedef struct RECU_Path_Tracking_Nearest_Path_Udp_Log_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   signed8_T track_idx_nearest_path;
   float32_T segment_heading_diff;
   float32_T range_vcs_proj_to_path_segment;
} RECU_Path_Tracking_Nearest_Path_Udp_Log_T;
typedef struct RECU_Path_Object_Pair_Output_Udp_Log_Tag {
   u8p0_T K_Unused8_1;
   signed8_T track_match_last_cycle;
   signed8_T track_match;
   unsigned8_T track_match_age;
   unsigned32_T path_direction;
   float32_T length_of_trajectory;
   float32_T range_at_host_edge;
   float32_T path_heading;
   float32_T range_to_current_path_part;
   float32_T range_at_zero;
} RECU_Path_Object_Pair_Output_Udp_Log_T;
typedef struct RECU_Path_Tracking_Output_Udp_Log_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   boolean_T f_pt_operational;
   RECU_Path_Object_Pair_Output_Udp_Log_T path_obj_pair_output[PA_OBJ_NUMBER_OF_OBJECTS_UDP_LOG];
   RECU_Path_Tracking_Nearest_Path_Udp_Log_T nearest_path_output[PA_OBJ_NUMBER_OF_OBJECTS_UDP_LOG];
} RECU_Path_Tracking_Output_Udp_Log_T;
typedef struct RECU_CTA_LOG_Tag {
   RECU_Cta_Output_Udp_Log_T cta_output_log;
   RECU_CTA_INPUT_LOG_T cta_input_log;
} RECU_CTA_LOG_T;
typedef struct RECU_Ta_BMW_Boardnet_Udp_Log_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T lcda_warntrigger_hmi;
   float32_T status_interface_driverassistance_limit;
   float32_T status_control_longitudinal_guidance;
   float32_T yawrate_qualifier;
   float32_T yawrate;
   float32_T velocity_vehicle_longitudinal_qualifier;
   float32_T velocity_vehicle_longitudinal;
   float32_T status_condition_vehicle_qualifier;
   float32_T status_condition_vehicle;
   float32_T steering_angle_front_axle_condition;
   float32_T steering_angle_front_axle_qualifier;
   float32_T steering_angle_front_axle;
   float32_T steering_angle_driver_qualifier;
   float32_T steering_angle_driver;
   float32_T qualifier_function_warning_chain;
   float32_T qualifier_function_brake_chain;
   float32_T status_warn_brake_coordinator;
   float32_T driving_direction_vehicle_confirmed;
   float32_T control_move_off_prevention;
   float32_T control_active_safety;
   float32_T control_prewarning;
   float32_T ego_trajectory_curvature_qualifier;
   float32_T ego_trajectory_curvature;
   float32_T accelerator_pedal_angle_qualifier;
   float32_T accelerator_pedal_angle_gradient;
   float32_T accelerator_pedal_angle;
   float32_T status_braking_driver;
   float32_T acceleration_driving_direction;
   float32_T acceleration_lateral_cog_qualifier;
   float32_T acceleration_lateral_cog;
   float32_T acceleration_longitudinal_cog_qualifier;
   float32_T acceleration_longitudinal_cog;
} RECU_Ta_BMW_Boardnet_Udp_Log_T;
typedef struct RECU_TA_INPUT_LOG_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T fta_steering_angle_max_right;
   unsigned8_T fta_steering_angle_max_left;
   unsigned8_T f_rta_enable_dynamic_area;
   unsigned8_T f_rta_enable_turning_area;
   unsigned8_T f_rta_enable;
   unsigned8_T f_fta_enable;
   float32_T fta_obj_offset_y_negative;
   float32_T fta_obj_offset_y_positive;
   float32_T fta_obj_offset_x_negative;
   float32_T fta_obj_offset_x_positive;
   RECU_Ta_BMW_Boardnet_Udp_Log_T ta_bmw_boardnet_signals;
} RECU_TA_INPUT_LOG_T;
typedef struct RECU_TA_Object_List_Udp_Log_Tag {
   float32_T fta_obj_list_object_class;
   float32_T fta_obj_list_width_std_dev;
   float32_T fta_obj_list_width;
   float32_T fta_obj_list_length_std_dev;
   float32_T fta_obj_list_length;
   float32_T fta_obj_list_yawrate_std_dev;
   float32_T fta_obj_list_yawrate;
   float32_T fta_obj_list_covariance_accel;
   float32_T fta_obj_list_lat_accel_std_dev;
   float32_T fta_obj_list_lat_accel;
   float32_T fta_obj_list_long_accel_std_dev;
   float32_T fta_obj_list_long_accel;
   float32_T fta_obj_list_covariance_vel;
   float32_T fta_obj_list_lat_vel_std_dev;
   float32_T fta_obj_list_lat_vel;
   float32_T fta_obj_list_long_vel_std_dev;
   float32_T fta_obj_list_long_vel;
   float32_T fta_obj_list_yaw_angle_std_dev;
   float32_T fta_obj_list_yaw_angle;
   float32_T fta_obj_list_covariance_posn;
   float32_T fta_obj_list_ref_pnt_lat_posn_std_dev;
   float32_T fta_obj_list_ref_pnt_lat_posn;
   float32_T fta_obj_list_ref_pnt_long_posn_std_dev;
   float32_T fta_obj_list_ref_pnt_long_posn;
   float32_T fta_obj_list_ref_point;
   float32_T fta_obj_list_exist_prob;
   float32_T fta_obj_list_move_status;
   float32_T fta_obj_list_meas_status;
   float32_T fta_obj_list_age;
   float32_T fta_obj_list_id;
   float32_T fta_obj_list_rcs;
} RECU_FTA_Object_List_Udp_Log_T;
typedef struct RECU_Ta_Output_Udp_Log_Tag {
   RECU_FTA_Object_List_Udp_Log_T
       fta_relevant_object[N_OBJECTS_UDP_LOG];
   u16p0_T K_Unused16_1;
   boolean_T f_diagnostic_mode;
   unsigned8_T lcda_warntrigger_hmi;
   unsigned8_T unused1;
   unsigned8_T ta_turn_maneuver;
   unsigned8_T ta_id_right;
   unsigned8_T ta_alert_right;
   unsigned8_T ta_id_left;
   unsigned8_T ta_alert_left;
   unsigned8_T rta_id_right;
   unsigned8_T rta_id_left;
   unsigned8_T rta_alert_right;
   unsigned8_T rta_alert_left;
   unsigned8_T rta_turning_area_status;
   unsigned8_T rta_dynamic_area_status;
   unsigned8_T fta_maneuver_direction;
   unsigned8_T fta_target_id;
   unsigned8_T f_rta_enable_dynamic_area;
   unsigned8_T f_rta_enable_turning_area;
   unsigned8_T f_rta_enable;
   unsigned8_T f_fta_enable;
   unsigned8_T fta_brake_conditioning;
   unsigned8_T fta_brake_threshold_reduction;
   unsigned8_T fta_symbol_request;
   unsigned8_T fta_alert_level;
   unsigned16_T unused2;
   float32_T fta_target_exist_prob;
   float32_T fta_target_vel_lat;
   float32_T fta_target_vel_long;
   float32_T fta_target_age;
   float32_T ta_current_deceleration_estimate;
   float32_T ta_collision_probability_right;
   float32_T ta_ttc_right;
   float32_T ta_collision_probability_left;
   float32_T ta_ttc_left;
   float32_T rta_existence_probability_right;
   float32_T rta_existence_probability_left;
   float32_T rta_lat_vel_right;
   float32_T rta_long_vel_right;
   float32_T rta_lat_vel_left;
   float32_T rta_long_vel_left;
   float32_T rta_ttc_right;
   float32_T rta_ttc_left;
   float32_T rta_lat_posn_right;
   float32_T rta_long_posn_right;
   float32_T rta_lat_posn_left;
   float32_T rta_long_posn_left;
   float32_T fta_ttc;
   float32_T fta_target_gap;
   float32_T ta_ttp_right;
   float32_T ta_ttp_left;
   float32_T fta_brake_deceleration_request;
} RECU_Ta_Output_Udp_Log_T;
typedef struct RECU_TA_LOG_Tag {
   RECU_Ta_Output_Udp_Log_T
       ta_output;
   RECU_TA_INPUT_LOG_T ta_input_log;
} RECU_TA_LOG_T;
typedef struct RECU_CED_INPUT_LOG_Tag {
   u8p0_T K_Unused8_1;
   boolean_T f_ced_rear_mode;
   boolean_T f_ced_front_mode;
   boolean_T f_ced_enable;
} RECU_CED_INPUT_LOG_T;
typedef struct RECU_Ced_Output_Udp_Log_Tag {
   unsigned8_T SFE_CED_obj_type_left;
   unsigned8_T SFE_CED_obj_type_right;
   unsigned8_T SFE_CED_front_path_match_left;
   unsigned8_T SFE_CED_front_path_match_right;
   unsigned8_T SFE_CED_front_id_left;
   unsigned8_T SFE_CED_front_id_right;
   unsigned8_T SFE_CED_front_alert_left;
   unsigned8_T SFE_CED_front_alert_right;
   unsigned8_T SFE_CED_front_status;
   unsigned8_T SFE_CED_rear_path_match_left;
   unsigned8_T SFE_CED_rear_path_match_right;
   unsigned8_T SFE_CED_rear_id_left;
   unsigned8_T SFE_CED_rear_id_right;
   unsigned8_T SFE_CED_rear_alert_left;
   unsigned8_T SFE_CED_rear_alert_right;
   unsigned8_T SFE_CED_rear_status;
   unsigned8_T SFE_CED_id_left;
   unsigned8_T SFE_CED_id_right;
   unsigned8_T unused_1;
   unsigned8_T SFE_CED_dir_left;
   unsigned8_T SFE_CED_dir_right;
   unsigned8_T SFE_CED_alert_left;
   unsigned8_T SFE_CED_alert_right;
   unsigned8_T SFE_CED_Status;
   float32_T SFE_CED_obj_heading_left;
   float32_T SFE_CED_obj_long_pos_left;
   float32_T SFE_CED_obj_long_pos_right;
   float32_T SFE_CED_obj_lateral_pos_left;
   float32_T SFE_CED_obj_lateral_pos_right;
   float32_T SFE_CED_obj_heading_right;
   float32_T SFE_CED_obj_speed_left;
   float32_T SFE_CED_obj_speed_right;
   float32_T SFE_CED_front_lat_left;
   float32_T SFE_CED_front_lat_right;
   float32_T SFE_CED_front_ttc_left;
   float32_T SFE_CED_front_ttc_right;
   float32_T SFE_CED_rear_lat_left;
   float32_T SFE_CED_rear_lat_right;
   float32_T SFE_CED_rear_ttc_left;
   float32_T SFE_CED_rear_ttc_right;
   float32_T SFE_CED_ttc_right;
   float32_T SFE_CED_ttc_left;
} RECU_Ced_Output_Udp_Log_T;
typedef struct RECU_CED_LOG_Tag {
   RECU_Ced_Output_Udp_Log_T
       ced_output;
   RECU_CED_INPUT_LOG_T ced_input_log;
} RECU_CED_LOG_T;
typedef struct RECU_PATH_TRACKING_LOG_Tag {
   RECU_Path_Tracking_Output_Udp_Log_T Path_Tracking_Output_Udp_Log;
} RECU_PATH_TRACKING_LOG_T;
typedef struct RECU_SCW_INPUT_LOG_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T f_scw_enable_guardrail;
   unsigned8_T f_scw_enable_dynamic;
   unsigned8_T f_scw_enable;
} RECU_SCW_INPUT_LOG_T;
typedef struct RECU_Scw_Output_Udp_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T scw_object_id_right;
   unsigned8_T scw_object_type_right;
   unsigned8_T scw_object_id_left;
   unsigned8_T scw_object_type_left;
   unsigned8_T f_scw_guardrail_enabled;
   unsigned8_T f_scw_dyn_enabled;
   unsigned8_T f_scw_enabled;
   unsigned16_T scw_object_age_right;
   unsigned16_T scw_object_existance_probability_right;
   unsigned16_T scw_object_age_left;
   unsigned16_T scw_object_existance_probability_left;
   float32_T scw_object_ay_right;
   float32_T scw_object_ax_right;
   float32_T scw_object_vy_right;
   float32_T scw_object_vx_right;
   float32_T scw_object_ttc_right;
   float32_T scw_object_heading_right;
   float32_T scw_object_length_right;
   float32_T scw_object_width_right;
   float32_T scw_object_py_right;
   float32_T scw_object_px_right;
   float32_T scw_object_ay_left;
   float32_T scw_object_ax_left;
   float32_T scw_object_vy_left;
   float32_T scw_object_vx_left;
   float32_T scw_object_ttc_left;
   float32_T scw_object_heading_left;
   float32_T scw_object_length_left;
   float32_T scw_object_width_left;
   float32_T scw_object_py_left;
   float32_T scw_object_px_left;
} RECU_Scw_Output_Udp_Log_T;
typedef struct RECU_SCW_LOG_Tag {
   RECU_Scw_Output_Udp_Log_T scw_output;
   RECU_SCW_INPUT_LOG_T scw_input_log;
} RECU_SCW_LOG_T;
typedef struct RECU_FF_OUTPUT_Logging_Data_Tag {
   RECU_SCW_LOG_T scw_log;
   RECU_PATH_TRACKING_LOG_T path_tracking_log;
   RECU_CED_LOG_T ced_log;
   RECU_TA_LOG_T ta_log;
   RECU_CTA_LOG_T cta_log;
   RECU_LCDA_LOG_T lcda_log;
   RECU_RECW_LOG_T recw_Log;
} RECU_FF_OUTPUT_Logging_Data_T;
typedef struct RECU_GDSR_TRACKER_LOG_OUTPUT_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T f_moveable[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned8_T f_stationary[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned8_T object_id[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned32_T object_class[NUMBER_OF_OBJECTS_UDP_LOG];
   unsigned32_T status[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T age[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T width[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T length[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T heading[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T vcs_lat_vel[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T vcs_lat_posn[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T vcs_long_vel[NUMBER_OF_OBJECTS_UDP_LOG];
   float32_T vcs_long_posn[NUMBER_OF_OBJECTS_UDP_LOG];
} RECU_GDSR_TRACKER_LOG_OUTPUT_T;
typedef struct RECU_LCDA_SM_INPUT_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T Status_trailer;
   unsigned32_T Direction_of_travel;
   float32_T Veh_Speed;
} RECU_LCDA_SM_INPUT_T;
typedef struct RECU_LCDA_SM_Output_Tag {
   RECU_Lcda_Output_Udp_Log_T p_lcda_SM_output;
   u16p0_T K_Unused16_1;
   unsigned16_T lcw_sm_resim_flag;
   unsigned32_T Extended_Qualifier;
   unsigned32_T event_data_qualifier;
   unsigned32_T Status_Simultaneous_Lane_Change;
   unsigned32_T Status_Dynamic_Area;
   unsigned32_T Status_Blind_Spot_Area;
} RECU_LCDA_SM_Output_T;
typedef struct RECU_SCW_SM_Input_Tag {
   unsigned32_T Unused_1;
} RECU_SCW_SM_Input_T;
typedef struct RECU_SCW_State_Machine_Output_Tag {
   RECU_Scw_Output_Udp_Log_T scw_output;
   unsigned8_T status_guardrail;
   unsigned8_T state_scw;
   unsigned16_T scw_sm_resim_flag;
   unsigned32_T extended_qualifier;
   unsigned32_T event_data_qualifier;
} RECU_SCW_State_Machine_Output_T;
typedef struct RECU_CED_SM_Input_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   boolean_T RR_SFE_CED_Error;
   boolean_T RL_SFE_CED_Error;
   boolean_T FR_SFE_CED_Error;
   boolean_T FL_SFE_CED_Error;
   boolean_T RR_SFE_CED_Degraded;
   boolean_T RL_SFE_CED_Degraded;
   boolean_T FR_SFE_CED_Degraded;
   boolean_T FL_SFE_CED_Degraded;
   unsigned8_T operation_open_lock_request_RPS;
   unsigned8_T operation_open_lock_request_RDR;
   unsigned8_T operation_open_lock_request_PS;
   unsigned8_T operation_open_lock_request_DR;
   unsigned8_T st_chisl;
   unsigned8_T status_automatic_doors_RPS;
   unsigned8_T status_automatic_doors_RDR;
   unsigned8_T status_automatic_doors_PS;
   unsigned8_T status_automatic_doors_DR;
   unsigned8_T sfe_ced_obj_type_passenger;
   unsigned8_T sfe_ced_obj_type_driver;
   unsigned8_T sfe_ced_id_passenger;
   unsigned8_T sfe_ced_id_driver;
   unsigned8_T alert_passenger;
   unsigned8_T alert_driver;
   unsigned8_T status_inside_pushbutton_RPS;
   unsigned8_T status_inside_pushbutton_RDR;
   unsigned8_T status_inside_pushbutton_PS;
   unsigned8_T status_inside_pushbutton_DR;
   unsigned8_T status_door_lock_RPS;
   unsigned8_T status_door_lock_RDR;
   unsigned8_T status_door_lock_PS;
   unsigned8_T status_door_lock_DR;
   unsigned8_T status_belt_switch_RPS;
   unsigned8_T status_belt_switch_RDR;
   unsigned8_T status_belt_switch_PS;
   unsigned8_T status_belt_switch_DR;
   unsigned8_T status_seat_occupying_RPS;
   unsigned8_T status_seat_occupying_RDR;
   unsigned8_T status_seat_occupying_PS;
   unsigned8_T status_seat_occupying_DR;
   unsigned8_T control_safer_exit_sound;
   unsigned8_T control_safe_exit;
   unsigned8_T Status_trailer;
   unsigned8_T Direction_of_travel;
   unsigned16_T Time_Day_Counter;
   unsigned32_T Time_Sec_Counter;
   float32_T sfe_ced_ttc_passenger;
   float32_T sfe_ced_ttc_driver;
   float32_T sfe_ced_obj_speed_passenger;
   float32_T sfe_ced_obj_speed_driver;
   float32_T Veh_Speed;
} RECU_CED_SM_Input_T;
typedef struct RECU_CED_SM_Output_Tag {
   unsigned8_T EdrDrasyEventID62AStatusSafeExit;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchPSDR;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchDVDR;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchPSD;
   unsigned8_T EdrDrasyEventID62AStatusDoorSwitchDRD;
   unsigned8_T EdrDrasyEventID62AGongLocalisation;
   unsigned8_T EdrDrasyEventID62AGongType;
   unsigned8_T EdrDrasyEventID62ASafeExitOrientation;
   unsigned8_T stop_gong_handle;
   unsigned8_T stop_gong_ID;
   unsigned8_T Request_Gong_ID;
   unsigned8_T Request_Gong_HND;
   unsigned8_T Request_Gong_DIST;
   unsigned8_T Request_Gong_ANG;
   unsigned8_T Request_Gong_TYP;
   unsigned8_T Request_Gong_LCN;
   unsigned8_T Request_Gong_DUR;
   unsigned8_T Request_Gong_FAO;
   unsigned8_T display_SafeExit_Warning_Rear_Right;
   unsigned8_T display_SafeExit_Warning_Rear_Left;
   unsigned8_T display_SafeExit_Warning_Front_Right;
   unsigned8_T display_SafeExit_Warning_Front_Left;
   unsigned8_T requestExteriorMirrorDisplayWarningPassengerSFE;
   unsigned8_T requestExteriorMirrorDisplayWarningDriverSFE;
   unsigned8_T request_door_lock;
   unsigned8_T request_automatic_door_stop;
   unsigned16_T sfe_sm_resim_flag;
   unsigned32_T request_interier_display_doors;
   unsigned32_T EdrDrasyStaticTimestampSec;
   unsigned32_T EdrDrasyStaticTimestampMsec;
   float32_T EdrDrasyStaticVelocity;
} RECU_CED_SM_Output_T;
typedef struct RECU_CTA_App_Params_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T A_CTB_qualifier_targetAccel_target_limit;
   unsigned8_T A_CTB_target_status_longitudinalGuidance;
   unsigned16_T A_CTB_integrity;
   unsigned16_T A_CTB_gradient_actuation_acceleratorPedal_sporty_driveOff;
   unsigned16_T A_CTB_gradient_actuation_acceleratorPedal_override;
   unsigned16_T A_CTB_max_number_brakingOperations_per_parkingManeuver;
   unsigned16_T A_CTB_deadTime;
   unsigned16_T A_CTB_responseTime_brakeActuation;
   unsigned16_T A_CTB_min_TTC;
   unsigned16_T A_CTB_max_TTC;
   unsigned16_T A_CTB_targetAcceleration_target_release_time;
   unsigned16_T A_CTB_targetAcceleration_target_release_deceleration;
   unsigned16_T A_CTB_targetAcceleration_target_braking_time;
   unsigned16_T A_CTB_Sollbeschleunigung_Ziel_Bremsen_Verzoegerung;
   unsigned16_T A_CTB_distance_thirdPartyVehicle;
   unsigned16_T A_CTA_timeDelay_warning_mirror_LED;
   unsigned16_T A_CTA_timeDelay_warning_visual;
   unsigned16_T A_CTA_timeDelay_warning_acoustic;
   unsigned16_T A_CTA_speedThreshold_hysteresis_mph;
   unsigned16_T A_CTA_speedThreshold_hysteresis_kmh;
} RECU_CTA_App_Params_T;
typedef struct RECU_CTA_SM_Input_Tag {
   u8p0_T K_Unused8_1;
   boolean_T request_states_function_parking;
   boolean_T status_activation_function_parking;
   boolean_T status_endOfLineMode;
   unsigned8_T qualifier_v_veh_cog;
   unsigned8_T qualifier_gradient_actuation_acceleratorPedal;
   unsigned8_T request_dimming_warning_laneChange;
   unsigned8_T drivingDirection_vehicle;
   unsigned8_T qualifier_speed_vehicle;
   unsigned8_T status_rollerDynamometerMode;
   unsigned8_T st_tria;
   unsigned8_T drvdir_veh_cfd;
   unsigned8_T st_drvdir_dvch;
   unsigned8_T control_cross_traffic_brake;
   signed16_T drivingTorque_driverRequest;
   signed16_T gradient_actuation_acceleratorPedal;
   unsigned16_T Time_Day_Counter;
   unsigned32_T Time_Sec_Counter;
   float32_T speed_vehicle;
   float32_T speed_speedometer;
} RECU_CTA_SM_Input_T;
typedef struct RECU_Warning_Acoustic_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T stop_GO_ID;
   unsigned8_T stop_GO_HND;
   unsigned8_T IGP_updated;
   unsigned8_T GO_DUR;
   unsigned8_T GO_FAO;
   unsigned8_T GO_LCN;
   unsigned8_T GO_TYP;
   unsigned8_T GO_ANG;
   unsigned8_T GO_DIST;
   unsigned8_T GO_HND;
   unsigned8_T GO_ID;
} RECU_Warning_Acoustic_T;
typedef struct RECU_CTA_SM_Output_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T EdrDrasyEventID62GongLocalisation;
   unsigned8_T EdrDrasyEventID62GongType;
   unsigned8_T EdrDrasyEventID62CTBBraking;
   unsigned8_T EdrDrasyEventID62CTBOrientation;
   unsigned8_T EdrDrasyEventID62CTBStatus;
   unsigned8_T request_brake_integrity;
   unsigned8_T qualifier_targetAccel_limit;
   unsigned8_T request_warning_dimming;
   unsigned8_T request_warning_displayElement_right;
   unsigned8_T request_warning_displayElement_left;
   unsigned8_T display_warning_graphic;
   unsigned8_T status_brakeRequest;
   unsigned8_T CounterRequestCTB;
   unsigned16_T cta_sm_resim_flag;
   RECU_Warning_Acoustic_T warning_acoustic;
   unsigned32_T qualifier_function_ctb;
   float32_T targetAcceleration_target;
   float32_T target_state_longitudinalGuidance;
} RECU_CTA_SM_Output_T;
typedef struct RECU_RECW_App_Params_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T A_RECB_SSM;
   unsigned8_T A_RECB_Integritaet;
   unsigned8_T A_RECB_Qualifier_Sollbeschleunigung_Ziel_Limit;
   float32_T A_RECB_Sollbeschleunigung;
   float32_T A_RECB_Gradient_Gaspedal;
   float32_T A_RECB_Ruecknahmezeit;
   float32_T A_RECB_TTC_max;
   float32_T A_RECB_V_rel_min;
   float32_T A_RECB_V_0_time;
   float32_T A_RECB_V_ego_max;
   float32_T A_PCSH_V_ego_max;
   float32_T A_PCSH_V_ego_min;
   float32_T A_RECW_V_ego_max;
   float32_T A_RECW_V_ego_min;
   float32_T A_PCSH_V_rel_min;
   float32_T A_PCSH_V_rel_max;
   float32_T A_RECW_V_rel_max;
   float32_T A_RECW_V_rel_min;
} RECU_RECW_App_Params_T;
typedef struct RECU_RECW_SM_Input_Tag {
   u8p0_T K_Unused8_1;
   boolean_T status_endOfLineMode;
   unsigned8_T ControlSetting2RECWMDrive;
   unsigned8_T dynamometerMode;
   unsigned8_T Status_trailer;
   unsigned8_T Direction_of_travel;
   unsigned16_T Time_Day_Counter;
   unsigned32_T Time_Sec_Counter;
   float32_T speed;
} RECU_RECW_SM_Input_T;
typedef struct RECU_RECW_SM_Output_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T EdrDrasyEventID62ATrigger;
   unsigned8_T ObstacleTypeSideRadarRear;
   unsigned8_T EdrDrasyEventID62AStatusPreCrashSideRadarRear;
   unsigned8_T EdrDrasyEventID62AStatusCollisionWarningSideRadarRear;
   unsigned8_T Anforderung_Bremse_Integritaet;
   unsigned8_T Soll_Zustand_Laengsfuehrung;
   unsigned8_T Qualifier_Sollbeschleunigung_Ziel_Limit;
   unsigned8_T Anforderung_Bremse_Qualifier;
   unsigned16_T recw_sm_resim_flag;
   float32_T Aufprallzeit_PreCrash_Heckradar;
   float32_T Annaeherungsgeschwindigkeit_PreCrash_Heckradar;
   unsigned32_T Status_Auffahrwarnung_Heck;
   unsigned32_T Status_PreCrash_Heckradar;
   unsigned32_T recw_state_PCAN;
   float32_T CollisionOverlap_PreCrash_RearRadar;
   float32_T CollisionAngleSideRadarRear;
   float32_T DistanceToObstacleSideRadarRear;
   float32_T Sollbeschleunigung_Ziel;
} RECU_RECW_SM_Output_T;
typedef struct RECU_TAP_SM_Input_Tag {
   unsigned8_T Status_Dynamic_Area_TAP;
   unsigned8_T Status_Turning_Area_TAP;
   unsigned16_T ta_sm_resim_flag;
   unsigned32_T Direction_Of_Travel_TAP;
   float32_T Ego_Speed;
} RECU_TAP_SM_Input_T;
typedef struct TA_SM_Output_Tag {
   RECU_Ta_Output_Udp_Log_T
       p_tap_SM_output;
   u16p0_T K_Unused16_1;
   unsigned8_T Status_Non_Critical_Object;
   unsigned8_T Status_Critical_Object;
   unsigned32_T Status_Extended_Qualifier;
   unsigned32_T Status_Event_Data_Qualifier;
} RECU_TA_SM_Output_T;
typedef struct RECU_PFGS_SM_Input_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   boolean_T FR_PFGS_Error_Flag;
   boolean_T FL_PFGS_Error_Flag;
   boolean_T FR_PFGS_Degraded_Flag;
   boolean_T FL_PFGS_Degraded_Flag;
   unsigned8_T ST_CON_VEH;
   unsigned8_T qualifier_function_WarnChain;
   unsigned8_T qualifier_function_brakeChain;
   unsigned8_T ST_CON_STEA_2;
   unsigned8_T driving_direction_choice;
   unsigned8_T StDrivDirVeh;
   unsigned8_T ST_EOLMOD;
   unsigned8_T ST_DYNOMOD;
   unsigned8_T controlActiveSafety;
   unsigned32_T t_sec_cou;
   unsigned32_T Driven_distance;
   float32_T yaw_rate;
   float32_T Steering_angle;
   float32_T v_veh_cog;
} RECU_PFGS_SM_Input_T;
typedef struct RECU_PFGS_SM_Output_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T idTargetObjectPPPSide;
   unsigned8_T NOT_AVAILABLE4;
   unsigned8_T NOT_AVAILABLE3;
   unsigned8_T NOT_AVAILABLE2;
   unsigned8_T NOT_AVAILABLE1;
   unsigned8_T integrityBrakeRequestPPPSide;
   unsigned8_T requestSymbolPPPSide;
   unsigned8_T warningPPPSide;
   unsigned8_T forecastSafetyBrakePPPSide;
   unsigned8_T reductionThValueBrakeAssistPPPSide;
   unsigned8_T qualifierFunctionPPPSide;
   unsigned16_T pfgs_sm_resim_flag;
   unsigned32_T chl_HeadwayobservationPPPSide;
   unsigned32_T alive_HeadwayobservationPPPSide;
   unsigned32_T crc_HeadwayobservationPPPSide;
   float32_T targetDecelerationPPPSide;
   float32_T gapTargetObjectPPPSide;
} RECU_PFGS_SM_Output_T;
typedef struct RECU_FreeSpace_State_Machine_Input_Tag {
   u16p0_T K_Unused16_1;
   boolean_T f_function_freespace_error;
   unsigned8_T drive_direction;
} RECU_FreeSpace_State_Machine_Input_T;
typedef struct RECU_FF_SM_LOG_Tag {
   RECU_FreeSpace_State_Machine_Input_T freespace_sm_input;
   RECU_PFGS_SM_Output_T pfgs_sm_output;
   RECU_PFGS_SM_Input_T pfgs_sm_input;
   RECU_TA_SM_Output_T ta_sm_output;
   RECU_TAP_SM_Input_T ta_sm_input;
   RECU_RECW_SM_Output_T recw_sm_output;
   RECU_RECW_SM_Input_T recw_sm_input;
   RECU_RECW_App_Params_T RECW_App_Params;
   RECU_CTA_SM_Output_T cta_sm_output;
   RECU_CTA_SM_Input_T cta_sm_input;
   RECU_CTA_App_Params_T cta_app_parameters;
   RECU_CED_SM_Output_T ced_sm_output;
   RECU_CED_SM_Input_T ced_sm_input;
   RECU_SCW_State_Machine_Output_T scw_sm_output;
   RECU_SCW_SM_Input_T scw_sm_input;
   RECU_LCDA_SM_Output_T lcda_sm_output;
   RECU_LCDA_SM_INPUT_T lcda_sm_input;
} RECU_FF_SM_LOG_T;
typedef struct Radar_ECU_CORE3_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   boolean_T data_valid;
   RECU_FF_SM_LOG_T ff_sm_log;
   RECU_GDSR_TRACKER_LOG_OUTPUT_T gdsr_tracker_log_output;
   RECU_FF_OUTPUT_Logging_Data_T FF_OUTPUT_Logging_Data;
   RECU_Camera_Data_Udp_Log_T camera_data;
   RECU_FF_version_T ff_version;
   RECU_FF_Error_Info_T ff_error_info;
   RECU_Core_3_Timing_Info_T timing_info;
   RECU_Radar_ECU_CORE3_Hdr_T radar_ecu_CORE3_Hdr;
} Radar_ECU_CORE3_T;
extern void Print_RADAR_ECU_CORE3_Traces_Header(FILE *CfilePtr, Radar_ECU_CORE3_T *debug);
extern void Print_RADAR_ECU_CORE3_Traces_Data(FILE *CfilePtr, Radar_ECU_CORE3_T *debug);
extern void Print_RADAR_ECU_CORE3_Xml_Traces(FILE *CfilePtr, Radar_ECU_CORE3_T *debug);
extern void Reverse_Array_RADAR_ECU_CORE3(Radar_ECU_CORE3_T *debug);
#endif /*PC_Resim*/

#pragma pack(pop, save_pack)
#endif /*RADAR_ECU_CORE3_H*/
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 02-09-2021 	 15:55:37	 jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/
