#ifndef RADAR_ECU_CORE0_H
#define RADAR_ECU_CORE0_H

/********************************************************************************************
 * Copyright 2007 Delphi Technologies, Inc., All Rights Reserved
 * XML uses version 17 of the base file.
 * File Name: RADAR_ECU_CORE0
 * Created:	 22-01-2022 	 12:48:42
 * From XML file: RADAR_ECU_CORE0.xml
 * Set Description:        Logging Structure/Interface structure
 * Tool Version: Major Version : 4,Minor Version 3
 * Do not edit this file Manually, This file is Auto Generated from Calibration tool only
 ********************************************************************************************/
#include "fixmac.h"

// This is added to convert the structures in this file to 4 byte padding
#pragma pack(push, save_pack)
#pragma pack(push, 4)

/*Macros For ARRAY Sizes*/
#define RADAR_ECU_CORE0_ID            (90)
#define KALMAN_STATE_ARRAY_SIZE       (2)
#define MAX_NUMBER_OF_SRR_SENSORS_LOG (4)
#define NUM_OF_INTERNAL_FAULTS        (16)
#define NUM_OF_EXTERNAL_FAULTS        (23)
#define NUMBER_OF_SRR_DETECTIONS_LOG  (500)
/*Macro For Structure Version*/
#define RADAR_ECU_CORE0_VERSION (17)

/*Macro for size of Main structure*/
#define SIZE_OF_RESIM_RADAR_ECU_CORE0 (26436)

/*Macro for size of Sub structures*/
#define SIZE_OF_Radar_ECU_CORE0_Hdr                    (12)
#define SIZE_OF_TimeStamp_Rader_CORE0                  (8)
#define SIZE_OF_Core_0_Timing_Info                     (16)
#define SIZE_OF_Tracker_Error_Info_Core0               (28)
#define SIZE_OF_FF_Error_Info_Core0                    (20)
#define SIZE_OF_OG_Error_Info_Core0                    (20)
#define SIZE_OF_SW_version_number                      (8)
#define SIZE_OF_Vector_2d_Core0                        (8)
#define SIZE_OF_Angle_Core0                            (12)
#define SIZE_OF_CURV_STATE_Core0                       (24)
#define SIZE_OF_Ego_Vehicle_Info_Core0                 (192)
#define SIZE_OF_TrackerIn_Raw_Detections               (32)
#define SIZE_OF_TrackerIn_Sensor_Det                   (6432)
#define SIZE_OF_FAULT_SIGNALS                          (36)
#define SIZE_OF_Faults_Internal_External_Faults_DC_Log (40)
#define SIZE_OF_DTC_Internal_External_Faults           (200)
#define SIZE_OF_FL_SIGNAL_GROUP                        (40)
#define SIZE_OF_FR_SIGNAL_GROUP                        (40)
#define SIZE_OF_RL_SIGNAL_GROUP                        (40)
#define SIZE_OF_RR_SIGNAL_GROUP                        (40)
#define SIZE_OF_SENSOR_SIGNAL_GROUP                    (160)
#define SIZE_OF_Radar_ECU_CORE0                        (26436)

#ifndef UDP_LITTLE_ENDIAN_BYTE_ORDER_STRUCTURE
typedef struct Radar_ECU_CORE0_Hdr_Tag /*Offset Start byte of the Structure Radar_ECU_CORE0_Hdr is 0 bytes*/
{
   unsigned32_T Sec_Size;
   unsigned16_T Sec_Compatibility;
   unsigned16_T Sec_Checksum;
   unsigned16_T run_counter;
   unsigned16_T version_number;
} Radar_ECU_CORE0_Hdr_T;
typedef struct RECU_TimeStamp_Rader_CORE0_Tag /*Offset Start byte of the Structure TimeStamp_Rader_CORE0 is 12 bytes*/
{
   unsigned32_T time_seconds;
   unsigned32_T time_fraction;
} RECU_TimeStamp_Rader_CORE0_T;
typedef struct RECU_Core_0_Timing_Info_Tag /*Offset Start byte of the Structure Core_0_Timing_Info is 20 bytes*/
{
   RECU_TimeStamp_Rader_CORE0_T core_starttime;
   RECU_TimeStamp_Rader_CORE0_T core_endtime;
} RECU_Core_0_Timing_Info_T;
typedef struct RECU_Tracker_Error_Info_Core0_Tag /*Offset Start byte of the Structure Tracker_Error_Info_Core0 is 36 bytes*/
{
   unsigned32_T tracker_overrun_cnt;
   unsigned32_T scan_index_FR;
   unsigned32_T scan_index_FL;
   unsigned32_T scan_index_RR;
   unsigned32_T scan_index_RL;
   unsigned32_T reserved;
   unsigned8_T tracker_overrun_flag;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_Tracker_Error_Info_Core0_T;
typedef struct RECU_FF_Error_Info_Core0_Tag /*Offset Start byte of the Structure FF_Error_Info_Core0 is 64 bytes*/
{
   unsigned32_T ff_overrun_cnt;
   unsigned32_T tracker_index_skipped;
   unsigned32_T ff_Skip_Index;
   unsigned32_T reserved;
   unsigned8_T ff_overrun_flag;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_FF_Error_Info_Core0_T;
typedef struct RECU_OG_Error_Info_Core0_Tag /*Offset Start byte of the Structure OG_Error_Info_Core0 is 84 bytes*/
{
   unsigned32_T og_overrun_cnt;
   unsigned32_T tracker_index_skipped;
   unsigned32_T OG_Skip_Index;
   unsigned32_T reserved;
   unsigned8_T og_overrun_flag;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_OG_Error_Info_Core0_T;
typedef struct RECU_SW_version_number_Tag /*Offset Start byte of the Structure SW_version_number is 104 bytes*/
{
   unsigned16_T major_version;
   unsigned16_T minor_version;
   unsigned16_T revision;
   u16p0_T K_Unused16_1;
} RECU_SW_version_number_T;
typedef struct RECU_Vector_2d_Core0_Tag /*Offset Start byte of the Structure Vector_2d_Core0 is 112 bytes*/
{
   float32_T x;
   float32_T y;
} RECU_Vector_2d_Core0_T;
typedef struct RECU_Angle_Core0_Tag /*Offset Start byte of the Structure Angle_Core0 is 120 bytes*/
{
   float32_T angle;
   float32_T sin;
   float32_T cos;
} RECU_Angle_Core0_T;
typedef struct RECU_CURV_STATE_Core0_Tag /*Offset Start byte of the Structure CURV_STATE_Core0 is 132 bytes*/
{
   float32_T dist_est;
   float32_T yaw_est;
   float32_T variance;
   float32_T kalman_state[KALMAN_STATE_ARRAY_SIZE];
   unsigned8_T f_kalman_initialized;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
} RECU_CURV_STATE_Core0_T;
typedef struct RECU_Ego_Vehicle_Info_Core0_Tag /*Offset Start byte of the Structure Ego_Vehicle_Info_Core0 is 156 bytes*/
{
   float32_T yaw_rate;
   float32_T steering_angle;
   float32_T rear_axle_steering_angle;
   float32_T dist_rear_axle_to_vcs;
   float32_T wheelbase;
   float32_T lane_width_external;
   float32_T lane_center_offset_external;
   float32_T host_vehicle_length;
   float32_T host_vehicle_width;
   float32_T curve_radius;
   float32_T abs_speed;
   float32_T vcs_long_vel;
   float32_T vcs_lat_vel;
   float32_T vcs_long_acc;
   float32_T vcs_lat_acc;
   float32_T speed;
   float32_T raw_speed;
   float32_T speed_estimated;
   float32_T speed_correction_factor;
   float32_T acceleration;
   float32_T rear_axle_sideslip;
   float32_T vcs_sideslip;
   float32_T cos_vcs_sideslip;
   float32_T sin_vcs_sideslip;
   float32_T host_curvature_fast;
   float32_T host_curvature_slow;
   float32_T raw_long_accel;
   float32_T raw_lat_accel;
   unsigned32_T vehicle_data_timestamp;
   unsigned32_T prndl;
   unsigned32_T max_value_mastertime;
   unsigned32_T tracker_mode;
   unsigned32_T speed_mode;
   unsigned8_T turn_signal;
   unsigned8_T reverse_gear;
   unsigned8_T f_trailer_present;
   unsigned8_T f_traffic_side;
   unsigned8_T f_speed_corrected;
   unsigned8_T f_speed_estimated;
   unsigned8_T f_mastertime_consistent;
   unsigned8_T rolling_count_vehicle_data;
   unsigned8_T f_reverse;
   unsigned8_T f_abs_curvature_LT_cal;
   unsigned8_T raw_speed_qf;
   unsigned8_T raw_long_accel_qf;
   unsigned8_T raw_lat_accel_qf;
   unsigned8_T raw_steering_angle_qf;
   unsigned8_T raw_yaw_rate_qf;
   unsigned8_T trailer_connected;
   RECU_Vector_2d_Core0_T vcs_time_update;
   RECU_Angle_Core0_T yaw_per_cycle;
   RECU_CURV_STATE_Core0_T tractor_curvature;
} RECU_Ego_Vehicle_Info_Core0_T;
typedef struct RECU_TrackerIn_Raw_Detections_Tag /*Offset Start byte of the Structure TrackerIn_Raw_Detections is 348 bytes*/
{
   float32_T azimuth;
   float32_T range;
   float32_T range_rate;
   float32_T elevation;
   float32_T amplitude;
   float32_T snr;
   unsigned8_T confid_azimuth;
   unsigned8_T confid_elevation;
   boolean_T valid;
   boolean_T host_clutter;
   boolean_T super_res_target;
   boolean_T nd_target;
   boolean_T bistatic;
   u8p0_T K_Unused8_1;
} RECU_TrackerIn_Raw_Detections_T;
typedef struct RECU_TrackerIn_Sensor_Det_Tag /*Offset Start byte of the Structure TrackerIn_Sensor_Det is 380 bytes*/
{
   double64_T timestamp;
   float32_T vcs_boresight_az_align_angle;
   float32_T vcs_boresight_el_align_angle;
   float32_T veh_speed_comp_factor;
   unsigned16_T look_index;
   unsigned8_T sensor_id;
   unsigned8_T look_id;
   unsigned8_T look_type;
   unsigned8_T range_type;
   unsigned8_T num_dets;
   boolean_T f_az_align_applied;
   boolean_T f_full_blockage;
   u8p0_T K_Unused8_1;
   u16p0_T K_Unused16_1;
   RECU_TrackerIn_Raw_Detections_T raw_dets[NUMBER_OF_SRR_DETECTIONS_LOG];
} RECU_TrackerIn_Sensor_Det_T;
typedef struct RECU_FAULT_SIGNALS_Tag /*Offset Start byte of the Structure FAULT_SIGNALS is 6812 bytes*/
{
   unsigned8_T Function_SCW_Qualifier;
   unsigned8_T Function_LCW_Qualifier;
   unsigned8_T Function_TAP_Qualifier;
   unsigned8_T Function_OL_Qualifier;
   unsigned8_T Function_FOV_Qualifier;
   unsigned8_T Function_DL_RR_Qualifier;
   unsigned8_T Function_DL_RL_Qualifier;
   unsigned8_T Function_DL_FL_Qualifier;
   unsigned8_T Function_DL_FR_Qualifier;
   unsigned8_T Function_SFE_Active;
   unsigned8_T Function_RCTA_Active;
   unsigned8_T Function_FCTA_Active;
   unsigned8_T Function_SCW_Active;
   unsigned8_T Function_RECW_Active;
   unsigned8_T Function_LCW_Active;
   unsigned8_T Function_TAP_Active;
   unsigned8_T Function_PFGS_Active;
   boolean_T Function_SFE_Degraded_Front;
   boolean_T Function_SFE_Degraded_Rear;
   boolean_T Function_RCTA_Degraded;
   boolean_T Function_FCTA_Degraded;
   boolean_T Function_SCW_Degraded;
   boolean_T Function_RECW_Degraded;
   boolean_T Function_LCW_Degraded;
   boolean_T Function_TAP_Degraded;
   boolean_T Function_PFGS_Degraded;
   boolean_T Function_SFE_Error;
   boolean_T Function_RCTA_Error;
   boolean_T Function_FCTA_Error;
   boolean_T Function_SCW_Error;
   boolean_T Function_RECW_Error;
   boolean_T Function_LCW_Error;
   boolean_T Function_TAP_Error;
   boolean_T Function_PFGS_Error;
   u16p0_T K_Unused16_1;
} RECU_FAULT_SIGNALS_T;
typedef struct RECU_Faults_Internal_External_Faults_DC_Log_Tag /*Offset Start byte of the Structure Faults_Internal_External_Faults_DC_Log is 6848 bytes*/
{
   unsigned8_T internal_faults_0_to_15_bytes[NUM_OF_INTERNAL_FAULTS];
   unsigned8_T external_faults_16_to_38_bytes[NUM_OF_EXTERNAL_FAULTS];
   u8p0_T K_Unused8_1;
} RECU_Faults_Internal_External_Faults_DC_Log_T;
typedef struct RECU_DTC_Internal_External_Faults_Tag /*Offset Start byte of the Structure DTC_Internal_External_Faults is 6888 bytes*/
{
   RECU_Faults_Internal_External_Faults_DC_Log_T Active_Fault_V;
   RECU_Faults_Internal_External_Faults_DC_Log_T History_Fault_V;
   RECU_Faults_Internal_External_Faults_DC_Log_T Active_Fault_Latched_V;
   RECU_Faults_Internal_External_Faults_DC_Log_T Fault_Test_Completed_V;
   RECU_Faults_Internal_External_Faults_DC_Log_T Fault_Enable_Table;
} RECU_DTC_Internal_External_Faults_T;
typedef struct RECU_FL_SIGNAL_GROUP_Tag /*Offset Start byte of the Structure FL_SIGNAL_GROUP is 7088 bytes*/
{
   unsigned32_T FL_PFGS_DTC;
   unsigned32_T FL_FCTA_DTC;
   unsigned32_T FL_RCTA_DTC;
   unsigned32_T FL_SFE_DTC;
   boolean_T FL_SCW_Degraded;
   boolean_T FL_TAP_Degraded;
   unsigned8_T FL_TAP_Qualifier;
   boolean_T FL_SFE_Error;
   boolean_T FL_RECW_Degraded;
   boolean_T FL_TAP_Error;
   unsigned8_T FL_OL_Qualifier;
   unsigned8_T CAN_TX_FL_SW_Variant;
   boolean_T FL_SCW_Error;
   unsigned8_T FL_SCW_Qualifier;
   unsigned8_T CAN_TX_FL_Info_ALV_CNTR;
   unsigned8_T FL_LCW_Qualifier;
   boolean_T FL_FCTA_Error;
   boolean_T FL_LCW_Degraded;
   boolean_T FL_RCTA_Degraded;
   boolean_T FL_RCTA_Error;
   boolean_T FL_SFE_Degraded;
   unsigned8_T FL_FOV_Qualifier;
   boolean_T FL_LCW_Error;
   boolean_T FL_PFGS_Degraded;
   unsigned8_T FL_DL_Qualifier;
   boolean_T FL_PFGS_Error;
   boolean_T FL_RECW_Error;
   boolean_T FL_FCTA_Degraded;
} RECU_FL_SIGNAL_GROUP_T;
typedef struct RECU_FR_SIGNAL_GROUP_Tag /*Offset Start byte of the Structure FR_SIGNAL_GROUP is 7128 bytes*/
{
   unsigned32_T FR_FCTA_DTC;
   unsigned32_T FR_SFE_DTC;
   unsigned32_T FR_PFGS_DTC;
   unsigned32_T FR_RCTA_DTC;
   boolean_T FR_FCTA_Degraded;
   boolean_T FR_LCW_Degraded;
   unsigned8_T FR_DL_Qualifier;
   boolean_T FR_LCW_Error;
   unsigned8_T FR_FOV_Qualifier;
   boolean_T FR_PFGS_Degraded;
   boolean_T FR_TAP_Error;
   boolean_T FR_RECW_Degraded;
   boolean_T FR_RECW_Error;
   boolean_T FR_RCTA_Degraded;
   boolean_T FR_RCTA_Error;
   boolean_T FR_SCW_Degraded;
   boolean_T FR_SFE_Degraded;
   unsigned8_T CAN_TX_FR_Info_ALV_CNTR;
   unsigned8_T CAN_TX_FR_SW_Variant;
   boolean_T FR_SCW_Error;
   boolean_T FR_PFGS_Error;
   unsigned8_T FR_SCW_Qualifier;
   boolean_T FR_TAP_Degraded;
   unsigned8_T FR_OL_Qualifier;
   boolean_T FR_FCTA_Error;
   unsigned8_T FR_TAP_Qualifier;
   boolean_T FR_SFE_Error;
   unsigned8_T FR_LCW_Qualifier;
} RECU_FR_SIGNAL_GROUP_T;
typedef struct RECU_RL_SIGNAL_GROUP_Tag /*Offset Start byte of the Structure RL_SIGNAL_GROUP is 7168 bytes*/
{
   unsigned32_T RL_SFE_DTC;
   unsigned32_T RL_PFGS_DTC;
   unsigned32_T RL_RCTA_DTC;
   unsigned32_T RL_FCTA_DTC;
   unsigned8_T RL_TAP_Qualifier;
   unsigned8_T CAN_TX_RL_SW_Variant;
   unsigned8_T RL_FOV_Qualifier;
   boolean_T RL_LCW_Degraded;
   boolean_T RL_RECW_Degraded;
   boolean_T RL_SCW_Error;
   boolean_T RL_LCW_Error;
   boolean_T RL_PFGS_Error;
   unsigned8_T RL_OL_Qualifier;
   unsigned8_T RL_DL_Qualifier;
   boolean_T RL_RECW_Error;
   boolean_T RL_FCTA_Error;
   boolean_T RL_PFGS_Degraded;
   boolean_T RL_FCTA_Degraded;
   boolean_T RL_RCTA_Degraded;
   boolean_T RL_SCW_Degraded;
   unsigned8_T CAN_TX_RL_Info_ALV_CNTR;
   boolean_T RL_TAP_Degraded;
   boolean_T RL_SFE_Degraded;
   boolean_T RL_TAP_Error;
   unsigned8_T RL_SCW_Qualifier;
   boolean_T RL_SFE_Error;
   unsigned8_T RL_LCW_Qualifier;
   boolean_T RL_RCTA_Error;
} RECU_RL_SIGNAL_GROUP_T;
typedef struct RECU_RR_SIGNAL_GROUP_Tag /*Offset Start byte of the Structure RR_SIGNAL_GROUP is 7208 bytes*/
{
   unsigned32_T RR_RCTA_DTC;
   unsigned32_T RR_PFGS_DTC;
   unsigned32_T RR_FCTA_DTC;
   unsigned32_T RR_SFE_DTC;
   boolean_T RR_RCTA_Error;
   boolean_T RR_RECW_Error;
   unsigned8_T RR_OL_Qualifier;
   boolean_T RR_TAP_Degraded;
   boolean_T RR_FCTA_Degraded;
   unsigned8_T CAN_TX_RR_SW_Variant;
   unsigned8_T RR_LCW_Qualifier;
   boolean_T RR_SCW_Error;
   boolean_T RR_PFGS_Degraded;
   boolean_T RR_FCTA_Error;
   unsigned8_T RR_SCW_Qualifier;
   unsigned8_T RR_TAP_Qualifier;
   boolean_T RR_SFE_Degraded;
   unsigned8_T RR_FOV_Qualifier;
   boolean_T RR_RECW_Degraded;
   boolean_T RR_LCW_Error;
   boolean_T RR_SCW_Degraded;
   boolean_T RR_TAP_Error;
   unsigned8_T RR_DL_Qualifier;
   unsigned8_T CAN_TX_RR_Info_ALV_CNTR;
   boolean_T RR_SFE_Error;
   boolean_T RR_LCW_Degraded;
   boolean_T RR_PFGS_Error;
   boolean_T RR_RCTA_Degraded;
} RECU_RR_SIGNAL_GROUP_T;
typedef struct RECU_SENSOR_SIGNAL_GROUP_Tag /*Offset Start byte of the Structure SENSOR_SIGNAL_GROUP is 7248 bytes*/
{
   RECU_FL_SIGNAL_GROUP_T FL_SignalGroup;
   RECU_FR_SIGNAL_GROUP_T FR_SignalGroup;
   RECU_RL_SIGNAL_GROUP_T RL_SignalGroup;
   RECU_RR_SIGNAL_GROUP_T RR_SignalGroup;
} RECU_SENSOR_SIGNAL_GROUP_T;
typedef struct Radar_ECU_CORE0_Tag /*Offset Start byte of the Structure Radar_ECU_CORE0 is 7408 bytes*/
{
   Radar_ECU_CORE0_Hdr_T radar_ecu_CORE0_Hdr;
   RECU_Core_0_Timing_Info_T timing_info;
   RECU_Tracker_Error_Info_Core0_T tracker_error_info_Core0;
   RECU_FF_Error_Info_Core0_T ff_error_info_Core0;
   RECU_OG_Error_Info_Core0_T og_error_info_Core0;
   RECU_SW_version_number_T core0_version;
   RECU_Ego_Vehicle_Info_Core0_T ego_vehicle_info_Core0;
   RECU_FAULT_SIGNALS_T fault_signals;
   RECU_DTC_Internal_External_Faults_T dtc_internal_external_faults;
   RECU_SENSOR_SIGNAL_GROUP_T sensor_signal_group;
   RECU_TrackerIn_Sensor_Det_T raw_srr_dets[MAX_NUMBER_OF_SRR_SENSORS_LOG];
   unsigned64_T tracker_timestamp_us;
   unsigned32_T recu_index;
   unsigned8_T pcan_major_version;
   unsigned8_T pcan_minor_version;
   u16p0_T K_Unused16_1;
} Radar_ECU_CORE0_T;
#else
typedef struct Radar_ECU_CORE0_Hdr_Tag {
   unsigned16_T version_number;
   unsigned16_T run_counter;
   unsigned16_T Sec_Checksum;
   unsigned16_T Sec_Compatibility;
   unsigned32_T Sec_Size;
} Radar_ECU_CORE0_Hdr_T;
typedef struct RECU_TimeStamp_Rader_CORE0_Tag {
   unsigned32_T time_fraction;
   unsigned32_T time_seconds;
} RECU_TimeStamp_Rader_CORE0_T;
typedef struct RECU_Core_0_Timing_Info_Tag {
   TimeStamp_Rader_CORE0_T core_endtime;
   TimeStamp_Rader_CORE0_T core_starttime;
} RECU_Core_0_Timing_Info_T;
typedef struct RECU_Tracker_Error_Info_Core0_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T tracker_overrun_flag;
   unsigned32_T reserved;
   unsigned32_T scan_index_RL;
   unsigned32_T scan_index_RR;
   unsigned32_T scan_index_FL;
   unsigned32_T scan_index_FR;
   unsigned32_T tracker_overrun_cnt;
} RECU_Tracker_Error_Info_Core0_T;
typedef struct RECU_FF_Error_Info_Core0_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T ff_overrun_flag;
   unsigned32_T reserved;
   unsigned32_T ff_Skip_Index;
   unsigned32_T tracker_index_skipped;
   unsigned32_T ff_overrun_cnt;
} RECU_FF_Error_Info_Core0_T;
typedef struct RECU_OG_Error_Info_Core0_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T og_overrun_flag;
   unsigned32_T reserved;
   unsigned32_T OG_Skip_Index;
   unsigned32_T tracker_index_skipped;
   unsigned32_T og_overrun_cnt;
} RECU_OG_Error_Info_Core0_T;
typedef struct RECU_SW_version_number_Tag {
   u16p0_T K_Unused16_1;
   unsigned16_T revision;
   unsigned16_T minor_version;
   unsigned16_T major_version;
} RECU_SW_version_number_T;
typedef struct RECU_Vector_2d_Core0_Tag {
   float32_T y;
   float32_T x;
} RECU_Vector_2d_Core0_T;
typedef struct RECU_Angle_Core0_Tag {
   float32_T cos;
   float32_T sin;
   float32_T angle;
} RECU_Angle_Core0_T;
typedef struct RECU_CURV_STATE_Core0_Tag {
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   unsigned8_T f_kalman_initialized;
   float32_T kalman_state[KALMAN_STATE_ARRAY_SIZE];
   float32_T variance;
   float32_T yaw_est;
   float32_T dist_est;
} RECU_CURV_STATE_Core0_T;
typedef struct RECU_Ego_Vehicle_Info_Core0_Tag {
   CURV_STATE_Core0_T tractor_curvature;
   Angle_Core0_T yaw_per_cycle;
   Vector_2d_Core0_T vcs_time_update;
   unsigned8_T trailer_connected;
   unsigned8_T raw_yaw_rate_qf;
   unsigned8_T raw_steering_angle_qf;
   unsigned8_T raw_lat_accel_qf;
   unsigned8_T raw_long_accel_qf;
   unsigned8_T raw_speed_qf;
   unsigned8_T f_abs_curvature_LT_cal;
   unsigned8_T f_reverse;
   unsigned8_T rolling_count_vehicle_data;
   unsigned8_T f_mastertime_consistent;
   unsigned8_T f_speed_estimated;
   unsigned8_T f_speed_corrected;
   unsigned8_T f_traffic_side;
   unsigned8_T f_trailer_present;
   unsigned8_T reverse_gear;
   unsigned8_T turn_signal;
   unsigned32_T speed_mode;
   unsigned32_T tracker_mode;
   unsigned32_T max_value_mastertime;
   unsigned32_T prndl;
   unsigned32_T vehicle_data_timestamp;
   float32_T raw_lat_accel;
   float32_T raw_long_accel;
   float32_T host_curvature_slow;
   float32_T host_curvature_fast;
   float32_T sin_vcs_sideslip;
   float32_T cos_vcs_sideslip;
   float32_T vcs_sideslip;
   float32_T rear_axle_sideslip;
   float32_T acceleration;
   float32_T speed_correction_factor;
   float32_T speed_estimated;
   float32_T raw_speed;
   float32_T speed;
   float32_T vcs_lat_acc;
   float32_T vcs_long_acc;
   float32_T vcs_lat_vel;
   float32_T vcs_long_vel;
   float32_T abs_speed;
   float32_T curve_radius;
   float32_T host_vehicle_width;
   float32_T host_vehicle_length;
   float32_T lane_center_offset_external;
   float32_T lane_width_external;
   float32_T wheelbase;
   float32_T dist_rear_axle_to_vcs;
   float32_T rear_axle_steering_angle;
   float32_T steering_angle;
   float32_T yaw_rate;
} RECU_Ego_Vehicle_Info_Core0_T;
typedef struct RECU_TrackerIn_Raw_Detections_Tag {
   u8p0_T K_Unused8_1;
   boolean_T bistatic;
   boolean_T nd_target;
   boolean_T super_res_target;
   boolean_T host_clutter;
   boolean_T valid;
   unsigned8_T confid_elevation;
   unsigned8_T confid_azimuth;
   float32_T snr;
   float32_T amplitude;
   float32_T elevation;
   float32_T range_rate;
   float32_T range;
   float32_T azimuth;
} RECU_TrackerIn_Raw_Detections_T;
typedef struct RECU_TrackerIn_Sensor_Det_Tag {
   TrackerIn_Raw_Detections_T raw_dets[NUMBER_OF_SRR_DETECTIONS_LOG];
   u16p0_T K_Unused16_1;
   u8p0_T K_Unused8_1;
   boolean_T f_full_blockage;
   boolean_T f_az_align_applied;
   unsigned8_T num_dets;
   unsigned8_T range_type;
   unsigned8_T look_type;
   unsigned8_T look_id;
   unsigned8_T sensor_id;
   unsigned16_T look_index;
   float32_T veh_speed_comp_factor;
   float32_T vcs_boresight_el_align_angle;
   float32_T vcs_boresight_az_align_angle;
   double64_T timestamp;
} RECU_TrackerIn_Sensor_Det_T;
typedef struct RECU_FAULT_SIGNALS_Tag {
   u16p0_T K_Unused16_1;
   boolean_T Function_PFGS_Error;
   boolean_T Function_TAP_Error;
   boolean_T Function_LCW_Error;
   boolean_T Function_RECW_Error;
   boolean_T Function_SCW_Error;
   boolean_T Function_FCTA_Error;
   boolean_T Function_RCTA_Error;
   boolean_T Function_SFE_Error;
   boolean_T Function_PFGS_Degraded;
   boolean_T Function_TAP_Degraded;
   boolean_T Function_LCW_Degraded;
   boolean_T Function_RECW_Degraded;
   boolean_T Function_SCW_Degraded;
   boolean_T Function_FCTA_Degraded;
   boolean_T Function_RCTA_Degraded;
   boolean_T Function_SFE_Degraded_Rear;
   boolean_T Function_SFE_Degraded_Front;
   unsigned8_T Function_PFGS_Active;
   unsigned8_T Function_TAP_Active;
   unsigned8_T Function_LCW_Active;
   unsigned8_T Function_RECW_Active;
   unsigned8_T Function_SCW_Active;
   unsigned8_T Function_FCTA_Active;
   unsigned8_T Function_RCTA_Active;
   unsigned8_T Function_SFE_Active;
   unsigned8_T Function_DL_FR_Qualifier;
   unsigned8_T Function_DL_FL_Qualifier;
   unsigned8_T Function_DL_RL_Qualifier;
   unsigned8_T Function_DL_RR_Qualifier;
   unsigned8_T Function_FOV_Qualifier;
   unsigned8_T Function_OL_Qualifier;
   unsigned8_T Function_TAP_Qualifier;
   unsigned8_T Function_LCW_Qualifier;
   unsigned8_T Function_SCW_Qualifier;
} RECU_FAULT_SIGNALS_T;
typedef struct RECU_Faults_Internal_External_Faults_DC_Log_Tag {
   u8p0_T K_Unused8_1;
   unsigned8_T external_faults_16_to_38_bytes[NUM_OF_EXTERNAL_FAULTS];
   unsigned8_T internal_faults_0_to_15_bytes[NUM_OF_INTERNAL_FAULTS];
} RECU_Faults_Internal_External_Faults_DC_Log_T;
typedef struct RECU_DTC_Internal_External_Faults_Tag {
   Faults_Internal_External_Faults_DC_Log_T Fault_Enable_Table;
   Faults_Internal_External_Faults_DC_Log_T Fault_Test_Completed_V;
   Faults_Internal_External_Faults_DC_Log_T Active_Fault_Latched_V;
   Faults_Internal_External_Faults_DC_Log_T History_Fault_V;
   Faults_Internal_External_Faults_DC_Log_T Active_Fault_V;
} RECU_DTC_Internal_External_Faults_T;
typedef struct RECU_FL_SIGNAL_GROUP_Tag {
   boolean_T FL_FCTA_Degraded;
   boolean_T FL_RECW_Error;
   boolean_T FL_PFGS_Error;
   unsigned8_T FL_DL_Qualifier;
   boolean_T FL_PFGS_Degraded;
   boolean_T FL_LCW_Error;
   unsigned8_T FL_FOV_Qualifier;
   boolean_T FL_SFE_Degraded;
   boolean_T FL_RCTA_Error;
   boolean_T FL_RCTA_Degraded;
   boolean_T FL_LCW_Degraded;
   boolean_T FL_FCTA_Error;
   unsigned8_T FL_LCW_Qualifier;
   unsigned8_T CAN_TX_FL_Info_ALV_CNTR;
   unsigned8_T FL_SCW_Qualifier;
   boolean_T FL_SCW_Error;
   unsigned8_T CAN_TX_FL_SW_Variant;
   unsigned8_T FL_OL_Qualifier;
   boolean_T FL_TAP_Error;
   boolean_T FL_RECW_Degraded;
   boolean_T FL_SFE_Error;
   unsigned8_T FL_TAP_Qualifier;
   boolean_T FL_TAP_Degraded;
   boolean_T FL_SCW_Degraded;
   unsigned32_T FL_SFE_DTC;
   unsigned32_T FL_RCTA_DTC;
   unsigned32_T FL_FCTA_DTC;
   unsigned32_T FL_PFGS_DTC;
} RECU_FL_SIGNAL_GROUP_T;
typedef struct RECU_FR_SIGNAL_GROUP_Tag {
   unsigned8_T FR_LCW_Qualifier;
   boolean_T FR_SFE_Error;
   unsigned8_T FR_TAP_Qualifier;
   boolean_T FR_FCTA_Error;
   unsigned8_T FR_OL_Qualifier;
   boolean_T FR_TAP_Degraded;
   unsigned8_T FR_SCW_Qualifier;
   boolean_T FR_PFGS_Error;
   boolean_T FR_SCW_Error;
   unsigned8_T CAN_TX_FR_SW_Variant;
   unsigned8_T CAN_TX_FR_Info_ALV_CNTR;
   boolean_T FR_SFE_Degraded;
   boolean_T FR_SCW_Degraded;
   boolean_T FR_RCTA_Error;
   boolean_T FR_RCTA_Degraded;
   boolean_T FR_RECW_Error;
   boolean_T FR_RECW_Degraded;
   boolean_T FR_TAP_Error;
   boolean_T FR_PFGS_Degraded;
   unsigned8_T FR_FOV_Qualifier;
   boolean_T FR_LCW_Error;
   unsigned8_T FR_DL_Qualifier;
   boolean_T FR_LCW_Degraded;
   boolean_T FR_FCTA_Degraded;
   unsigned32_T FR_RCTA_DTC;
   unsigned32_T FR_PFGS_DTC;
   unsigned32_T FR_SFE_DTC;
   unsigned32_T FR_FCTA_DTC;
} RECU_FR_SIGNAL_GROUP_T;
typedef struct RECU_RL_SIGNAL_GROUP_Tag {
   boolean_T RL_RCTA_Error;
   unsigned8_T RL_LCW_Qualifier;
   boolean_T RL_SFE_Error;
   unsigned8_T RL_SCW_Qualifier;
   boolean_T RL_TAP_Error;
   boolean_T RL_SFE_Degraded;
   boolean_T RL_TAP_Degraded;
   unsigned8_T CAN_TX_RL_Info_ALV_CNTR;
   boolean_T RL_SCW_Degraded;
   boolean_T RL_RCTA_Degraded;
   boolean_T RL_FCTA_Degraded;
   boolean_T RL_PFGS_Degraded;
   boolean_T RL_FCTA_Error;
   boolean_T RL_RECW_Error;
   unsigned8_T RL_DL_Qualifier;
   unsigned8_T RL_OL_Qualifier;
   boolean_T RL_PFGS_Error;
   boolean_T RL_LCW_Error;
   boolean_T RL_SCW_Error;
   boolean_T RL_RECW_Degraded;
   boolean_T RL_LCW_Degraded;
   unsigned8_T RL_FOV_Qualifier;
   unsigned8_T CAN_TX_RL_SW_Variant;
   unsigned8_T RL_TAP_Qualifier;
   unsigned32_T RL_FCTA_DTC;
   unsigned32_T RL_RCTA_DTC;
   unsigned32_T RL_PFGS_DTC;
   unsigned32_T RL_SFE_DTC;
} RECU_RL_SIGNAL_GROUP_T;
typedef struct RECU_RR_SIGNAL_GROUP_Tag {
   boolean_T RR_RCTA_Degraded;
   boolean_T RR_PFGS_Error;
   boolean_T RR_LCW_Degraded;
   boolean_T RR_SFE_Error;
   unsigned8_T CAN_TX_RR_Info_ALV_CNTR;
   unsigned8_T RR_DL_Qualifier;
   boolean_T RR_TAP_Error;
   boolean_T RR_SCW_Degraded;
   boolean_T RR_LCW_Error;
   boolean_T RR_RECW_Degraded;
   unsigned8_T RR_FOV_Qualifier;
   boolean_T RR_SFE_Degraded;
   unsigned8_T RR_TAP_Qualifier;
   unsigned8_T RR_SCW_Qualifier;
   boolean_T RR_FCTA_Error;
   boolean_T RR_PFGS_Degraded;
   boolean_T RR_SCW_Error;
   unsigned8_T RR_LCW_Qualifier;
   unsigned8_T CAN_TX_RR_SW_Variant;
   boolean_T RR_FCTA_Degraded;
   boolean_T RR_TAP_Degraded;
   unsigned8_T RR_OL_Qualifier;
   boolean_T RR_RECW_Error;
   boolean_T RR_RCTA_Error;
   unsigned32_T RR_SFE_DTC;
   unsigned32_T RR_FCTA_DTC;
   unsigned32_T RR_PFGS_DTC;
   unsigned32_T RR_RCTA_DTC;
} RECU_RR_SIGNAL_GROUP_T;
typedef struct RECU_SENSOR_SIGNAL_GROUP_Tag {
   RR_SIGNAL_GROUP_T RR_SignalGroup;
   RL_SIGNAL_GROUP_T RL_SignalGroup;
   FR_SIGNAL_GROUP_T FR_SignalGroup;
   FL_SIGNAL_GROUP_T FL_SignalGroup;
} RECU_SENSOR_SIGNAL_GROUP_T;
typedef struct Radar_ECU_CORE0_Tag {
   u16p0_T K_Unused16_1;
   unsigned8_T pcan_minor_version;
   unsigned8_T pcan_major_version;
   unsigned32_T recu_index;
   unsigned64_T tracker_timestamp_us;
   TrackerIn_Sensor_Det_T raw_srr_dets[MAX_NUMBER_OF_SRR_SENSORS_LOG];
   SENSOR_SIGNAL_GROUP_T sensor_signal_group;
   DTC_Internal_External_Faults_T dtc_internal_external_faults;
   FAULT_SIGNALS_T fault_signals;
   Ego_Vehicle_Info_Core0_T ego_vehicle_info_Core0;
   SW_version_number_T core0_version;
   OG_Error_Info_Core0_T og_error_info_Core0;
   FF_Error_Info_Core0_T ff_error_info_Core0;
   Tracker_Error_Info_Core0_T tracker_error_info_Core0;
   Core_0_Timing_Info_T timing_info;
   Radar_ECU_CORE0_Hdr_T radar_ecu_CORE0_Hdr;
} Radar_ECU_CORE0_T;
extern void Print_RADAR_ECU_CORE0_Traces_Header(FILE *CfilePtr, Radar_ECU_CORE0_T *debug);
extern void Print_RADAR_ECU_CORE0_Traces_Data(FILE *CfilePtr, Radar_ECU_CORE0_T *debug);
extern void Print_RADAR_ECU_CORE0_Xml_Traces(FILE *CfilePtr, Radar_ECU_CORE0_T *debug);
extern void Reverse_Array_RADAR_ECU_CORE0(Radar_ECU_CORE0_T *debug);
#endif /*PC_Resim*/

#pragma pack(pop, save_pack)
#endif /*RADAR_ECU_CORE0_H*/
/*=========================================================================================*
 * File Revision History (top to bottom: first revision to last revision)
 *==========================================================================================
 *
 * Date           time        userid    (Description on following lines: SCR #, etc.)
 * ----------- -------- --------------------------------------------------------------------
 * 22-01-2022 	 12:48:42	 jjyr0p    Do not make any changes it's an auto generated file
 *
 *=========================================================================================*/
