SensorSimulator:
  SimulationDescription: "\n        Configuration file for LiME - Template FMU with\
    \ ZMQ Sender/Receiver for OSI\n    "
  Configuration:
    UseCase: SIL
    RunMode: auto
    Defaults:
      LogLevel: InfoAndWarnings
      PerfLogVersion: v1
    PerformanceLogging:
      - Report: FullPipeline
        Start:
          Element: Receiver
          Id: 0
          LogPoint: Entry
        End:
          Element: Sender
          Id: 0
          LogPoint: Exit
      - Report: SM2CalculationTime
        Start:
          Element: Model
          Id: 0
          LogPoint: Entry
        End:
          Element: Model
          Id: 0
          LogPoint: Exit
      - Report: LM2CalculationTime
        Start:
          Element: Model
          Id: 2
          LogPoint: Entry
        End:
          Element: Model
          Id: 2
          LogPoint: Exit
    Remote:
      Control:
        Enabled: false
        Ip: 127.0.0.1
        Port: 6363
  ReceiverList:
    - Receiver: 0
      DataType: SensorView
      CommunicationType: zmq
      CommunicationOptions:
        Ip: 127.0.0.1
        Port: 5564
        Pattern: Pub-Sub      
        Protocol: TCP
        EpgmLocalIpOrInterface: 127.0.0.1
        EpgmRate: 1000000
      ConnectTo:
        - Element: Model
          Id: 0
          InputPort: 0
  SenderList:
    - Sender: 0
      DataType: SensorData
      CommunicationType: zmq
      CommunicationOptions:
        Ip: 127.0.0.1
        Port: 5563
        Pattern: Pub-Sub      
        Protocol: TCP
        EpgmLocalIpOrInterface: 127.0.0.1
        EpgmRate: 1000000
    - Sender: 1
      DataType: SensorData
      CommunicationType: zmq
      CommunicationOptions:
        Ip: 127.0.0.1
        Port: 5562
        Pattern: Pub-Sub      
        Protocol: TCP
        EpgmLocalIpOrInterface: 127.0.0.1
        EpgmRate: 1000000
    - Sender: 2
      DataType: SensorData
      CommunicationType: zmq
      CommunicationOptions:
        Ip: 127.0.0.1
        Port: 5561
        Pattern: Pub-Sub      
        Protocol: TCP
        EpgmLocalIpOrInterface: 127.0.0.1
        EpgmRate: 1000000
    - Sender: 3
      DataType: SensorData
      CommunicationType: zmq
      CommunicationOptions:
        Ip: 127.0.0.1
        Port: 5560
        Pattern: Pub-Sub      
        Protocol: TCP
        EpgmLocalIpOrInterface: 127.0.0.1
        EpgmRate: 1000000
    - Sender: 4
      DataType: SensorData
      CommunicationType: zmq
      CommunicationOptions:
        Ip: 127.0.0.1
        Port: 5560
        Pattern: Pub-Sub      
        Protocol: TCP
        EpgmLocalIpOrInterface: 127.0.0.1
        EpgmRate: 1000000
  ModelList:
    - Model: 0
      ModelType: Sensor
      Scheduler:
        Enabled: true
        StartupDelay:
          Unit: sec
          Value: 0
        Interval:
          Unit: ms
          Value: 50
      FmuArchive:
        Path: 02_SENSOR_MODEL/FMU/Ultrasonic_SM2_OSI3.5.0_v0.1.13.6.0/Windows/Ultrasonic_SensorModel2.fmu #Ultrasonic SM2
        Origin: config
      FmuLogLevel: Warn
      InputPortList:
        - Port: 0
          DataType: SensorView
          InputVariableName: SensorViewIn
      OutputPortList:
        - Port: 0
          DataType: SensorData
          ConnectTo:
            - Element: Model
              Id: 13
              InputPort: 0
          OutputVariableName: SensorDataOut
      ModelVariables:
        - {Name: SRR.SM2.Customer_enum, Type: Integer, Start: 12}
        - {Name: SRR.SM2.SensorType_enum, Type: Integer, Start: 8}
        - {Name: SRR.SM2.MaxNumberOfDetections, Type: Integer, Start: 500}
        - {Name: SRR.SM2.SensorMountingPosition.Position.X_m, Type: Real, Start: 2.39427}
        - {Name: SRR.SM2.SensorMountingPosition.Position.Y_m, Type: Real, Start: 0.33782}
        - {Name: SRR.SM2.SensorMountingPosition.Position.Z_m, Type: Real, Start: -0.39576}
        - {Name: SRR.SM2.SensorMountingPosition.Orientation.Roll_rad, Type: Real, Start: 0.0}
        - {Name: SRR.SM2.SensorMountingPosition.Orientation.Pitch_rad, Type: Real, Start: 0.06981}
        - {Name: SRR.SM2.SensorMountingPosition.Orientation.Yaw_rad, Type: Real, Start: 0.1159}
        - {Name: SRR.SM2.Traffic.BbCenterToRearXFactor, Type: Real, Start: 0.7}
        - {Name: SRR.SM2.Traffic.BbCenterToFrontXFactor, Type: Real, Start: 0.8}
        - {Name: SRR.SM2.Traffic.GroundClearance_m, Type: Real, Start: 0.2}
        - {Name: SRR.SM2.Traffic.WheelRadius_m, Type: Real, Start: 0.2}
        - {Name: SRR.SM2.Host.Length_m, Type: Real, Start: 5.245}
        - {Name: SRR.SM2.Host.Width_m, Type: Real, Start: 2.10208}
        - {Name: SRR.SM2.Host.Height_m, Type: Real, Start: 1.42}
        - {Name: SRR.SM2.Host.BbCenterToRear.X_m, Type: Real, Start: -1.4}
        - {Name: SRR.SM2.Host.BbCenterToRear.Y_m, Type: Real, Start: 0.0}
        - {Name: SRR.SM2.Host.BbCenterToRear.Z_m, Type: Real, Start: -0.5}
        - {Name: SRR.SM2.Host.BbCenterToFront.X_m, Type: Real, Start: 1.6}
        - {Name: SRR.SM2.Host.BbCenterToFront.Y_m, Type: Real, Start: 0.0}
        - {Name: SRR.SM2.Host.BbCenterToFront.Z_m, Type: Real, Start: -0.5}
        - {Name: SRR.SM2.SensorName, Type: String, Start: FRONT_LEFT_MIDDLE}
        - {Name: SRR.SM2.Custom, Type: String ,Start: Disable}
        - {Name: SRR.SM2.FoV.BlockageMaskAzimuth, Type: String, Start: 111111111111111111111111111111}
    - Model: 1
      ModelType: Viz
      Scheduler:
        Enabled: true
        StartupDelay:
          Unit: sec
          Value: 0
        Interval:
          Unit: sec
          Value: 0
      FmuArchive:
      FmuLogLevel: Warn
      InputPortList:
        - Port: 0
          DataType: SensorData
          InputVariableName: SensorDataIn_DFT0
      OutputPortList:
      ModelVariables:
