module(
    name = "build_config",
)

# these bazel_dep versions are essentially meaningless since they are expected
# to be overriden in the root module
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "bbe_windows", version = "2025.5")
bazel_dep(name = "bbe_linux", version = "2025.5")  # Should be able to get this transitively from bbe_linux_luna
bazel_dep(name = "bbe_linux_luna", version = "2025.5.asic.B0")
bazel_dep(name = "bbe_windows_luna", version = "2025.5.asic.B0")
bazel_dep(name = "rapid_build_platform", repo_name = "bazel_platform", version = "2.3.0")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "iND13400_sdk",
    integrity = "sha256-op3gt+39an9saQBukpi0qtoAXUVagyB89rYjZyIbsKg=",
    urls = ["https://jfrog.asux.aptiv.com/artifactory/core_radar-aptiv-00000000-building_blocks-local/Core_Radar_Gen8_iND13400_SDK/v3/Core_Radar_Gen8_iND13400_SDK_v3.52.45.zip"],
)
