sync: false
log:
  vehicle: 61829d79905130001fb19655
  structure:
    pcap: log.pcap

#logging:
#  ethernet:
#    interfaces:
#      - interface: enx8cae4ce9789f
#        udp:
#          - 2050
#          - 10000
#        tcp:
#          - ip: 192.168.50.50
#            port: 9870
#            timeout: 10
#      - interface: enp0s31f6
#        udp:
#          - 5555
#  chunk-options:
#    duration: 60
#    out-directory: mylogging

sensors:
  ethernet:
    MachEPandoraLidar:
      port: 2050
      remote: 192.168.50.50:10000
      type: pandora
      # [TODO] we should get the correct calib
      calibration: ./config/atcity/lidarCalib.csv
      extrinsics:
        position: { x: 1.31488, y: 0, z: -1.64098 }
        # [TODO] Is this the correct rotation??
        rotation: {w: -0.0017373879672959447, x: 0.7184227108955383, y: -0.6956017017364502, z: -0.002018760424107313}
    MachEPandoraCamera:
      remote: 192.168.50.50:9870
      type: pandora-camera
      names:
        0: MachEFrontCameraRGB
        1: MachEFrontCamera
        2: MachERightCamera
        3: MachERearCamera
        4: MachELeftCamera
      #fix-front-camera-image: true
    MachERadarRearLeft:
      port: 5555
      remote: 192.168.1.81:5555
      type: radar-sensor
      radar-type: MRR360
      extrinsics:
        position: { x: -0.66736, y: -0.75889, z: -0.78538 }
        rotation: { w: 0, x: 0.491663844071007, y: -0.870785085100406, z: 0 }
      antenna-angle-min: -75.0
      antenna-angle-max: 75.
      look-types:
        LRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.13941717147827148
          rangeResolution: 0.41156005859375
          vua: 35.690853118896484
        LRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.11685514450073242
          rangeResolution: 0.4282989501953125
          vua: 29.914928913116455
        MRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.14387226104736328
          rangeResolution: 0.41156005859375
          vua: 36.831350326538086
        MRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.12129974365234375
          rangeResolution: 0.4282989501953125
          vua: 31.052739143371582
      emit-host-data: true

    MachERadarRearRight:
      port: 5555
      remote: 192.168.1.82:5555
      type: radar-sensor
      radar-type: MRR360
      extrinsics:
        position: { x: -0.68, y: 0.75159, z: -0.78519 }
        rotation: { w: 0.492347605365765, x: 0, y: 0, z: 0.870398664687967 }
      antenna-angle-min: -75.0
      antenna-angle-max: 75.0
      look-types:
        LRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.13941717147827148
          rangeResolution: 0.41156005859375
          vua: 35.690853118896484
        LRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.11685514450073242
          rangeResolution: 0.4282989501953125
          vua: 29.914928913116455
        MRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.14387226104736328
          rangeResolution: 0.41156005859375
          vua: 36.831350326538086
        MRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.12129974365234375
          rangeResolution: 0.4282989501953125
          vua: 31.052739143371582
      emit-host-data: true

    MachERadarFrontRight:
      port: 5555
      remote: 192.168.1.83:5555
      type: radar-sensor
      radar-type: MRR360
      extrinsics:
        position: { x: 3.5919, y: 0.78277, z: -0.5515 }
        rotation: { w: 0, x: 0.91636272956224, y: 0.400349032556895, z: 0 }
      antenna-angle-min: -75.0
      antenna-angle-max: 75.0
      look-types:
        LRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.13941717147827148
          rangeResolution: 0.41156005859375
          vua: 35.690853118896484
        LRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.11685514450073242
          rangeResolution: 0.4282989501953125
          vua: 29.914928913116455
        MRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.14387226104736328
          rangeResolution: 0.41156005859375
          vua: 36.831350326538086
        MRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.12129974365234375
          rangeResolution: 0.4282989501953125
          vua: 31.052739143371582
      emit-host-data: true

    MachERadarFrontLeft:
      port: 5555
      remote: 192.168.1.84:5555
      type: radar-sensor
      radar-type: MRR360
      antenna-angle-min: -75.0
      antenna-angle-max: 75.0
      extrinsics:
        position: { x: 3.5919, y: -0.78277, z: -0.5515 }
        rotation: { w: 0.911223632870061, x: 0, y: 0, z: -0.411911994118996 }
      look-types:
        LRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.13941717147827148
          rangeResolution: 0.41156005859375
          vua: 35.690853118896484
        LRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.11685514450073242
          rangeResolution: 0.4282989501953125
          vua: 29.914928913116455
        MRLL:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.14387226104736328
          rangeResolution: 0.41156005859375
          vua: 36.831350326538086
        MRML:
          minRangeRate: -23
          minRange: 0
          rangeRateResolution: 0.12129974365234375
          rangeResolution: 0.4282989501953125
          vua: 31.052739143371582
      emit-host-data: true

  can: {}

network-kind: at-city-bmw-mrr360
network:
  preprocessing:
    batch-logic: Pivot
    pivot-indices: [0, 1]
    normalization: normalized
    egomotion-method: Interpolated
    sensor-map:
      - identifier: MachERadarFrontLeft
        rtype: mrr360
        range-box:
          forward: 80.0
          backward: 60.0
          left: 40.0
          right: 40.0
      - identifier: MachERadarRearRight
        rtype: mrr360
        range-box:
          forward: 80.0
          backward: 60.0
          left: 40.0
          right: 40.0
      - identifier: MachERadarFrontRight
        rtype: mrr360
        range-box:
          forward: 80.0
          backward: 60.0
          left: 40.0
          right: 40.0
      - identifier: MachERadarRearLeft
        rtype: mrr360
        range-box:
          forward: 80.0
          backward: 60.0
          left: 40.0
          right: 40.0


  python-tensorflow:
    path: ./runtime_data/network.py
    class: Network
    model: config/mach_e/detection/network.pb
    interface: config/mach_e/detection/interface.json
  postprocessing:
    score-threshold: 0.2
    nms-threshold: 0.1
    nms-method: overlap-classwise
    classwise:
      0:
        name: Bike
        score-threshold: 0.2
        height: 1.5
      1:
        name: Large_Moving
        score-threshold: 0.2
        height: 2.5
      2:
        name: Large_Stationary
        score-threshold: 0.2
        height: 2.5
      3:
        name: Other
        score-threshold: 2.0
        height: 5.0
      4:
        name: Pedestrian
        score-threshold: 0.2
        height: 1.8
      5:
        name: Vehicle_Moving
        score-threshold: 0.2
        height: 1.5
      6:
        name: Vehicle_Stationary
        score-threshold: 0.2
        height: 1.5

tracker: config/mach_e/detection/tracker_params.json

xviz:
  port: 9000
  message-format: BINARY
