set(tmp_cmake_folder ${CMAKE_FOLDER})

set(CMAKE_FOLDER ${tmp_cmake_folder}/modules/support)
add_subdirectory(host)
add_subdirectory(math)

if(SG_DC_ENABLED)
    set(CMAKE_FOLDER ${tmp_cmake_folder}/modules/drivability_classification)
    add_subdirectory(drivability_classification)
    if (SG_DRIVABILITY_CLASSIFICATION_TOOLING_WRAPPER)
       add_subdirectory(drivability_classification_wrapper)
    endif()
endif()

set(CMAKE_FOLDER ${tmp_cmake_folder}/modules/kernel)
add_subdirectory(calibrations)
add_subdirectory(common)
add_subdirectory(contour_downselection)
add_subdirectory(contour_initialization)
add_subdirectory(critical_region)
add_subdirectory(detection_clustering)
add_subdirectory(detection_processing)
add_subdirectory(measurement_association)
add_subdirectory(measurement_update)
add_subdirectory(postprocessing)
add_subdirectory(time_update)
add_subdirectory(rspp)
add_subdirectory(entry_data_processing)

set(CMAKE_FOLDER ${tmp_cmake_folder})
