cc_library(
    name = "OLP_Core_h",
    srcs = [],
    hdrs = [
        "olp.h",
        "olp_compute_cog.h",
        "olp_compute_curvi_data.h",
        "olp_core_types.h",
        "olp_distance_based_curvature.h",
        "olp_iface.h",
        "olp_ml_math.h",
        "olp_snail_trail_computation.h",
        "olp_calibration.h",
    ],
    defines = [],
    deps = [],
    strip_include_prefix = "//OLP_Core/includes",
    visibility = ["//visibility:public"],
)
