#!/usr/bin/env python3
"""Update E2E CAPL buffer length constants from E2EXf_LCfg.c.

update_e2e_capl_buffer_lengths.py
-----------------------------------
Automatically synchronises the E2E transformation buffer-length constants in a
CANoe CAPL validation script with the values generated by DaVinci / AUTOSAR RTE
in E2EXf_LCfg.c.

File locations (both files live together in this folder):
  SOURCE  : software/m7/autosar/config/Appl/GenData/E2EXf_LCfg.c
              ^ Generated by DaVinci after every DBC update + RTE regeneration.
                Contains the authoritative E2E Profile 5 DataLength values.

  TARGET  : tools/util_scripts/OSPAS_E2E_Validation_Script.can
              ^ CANoe CAPL script used for E2E CRC/Counter validation on the bench.
                This script reads the CAPL file and patches the BUFFER_LEN_* constants.

After any DBC update + RTE re-generation run this script once:

    python tools/util_scripts/e2e_can_validation/update_e2e_capl_buffer_lengths.py

The script will:
  1. Parse E2EXf_LCfg.c and extract the E2E Profile 5 DataLength (bits) for the
     four CAN message types: RadarHeader, AlignmentStatus1, AlignmentStatus2,
     RadarCapability.
  2. Convert bits -> bytes  (bufferLength = DataLength / 8).
  3. Patch the BUFFER_LEN_* constants in the CAPL script.
  4. Report what changed (or confirm nothing changed).

Usage
-----
  # Default paths (run from repo root):
  python tools/util_scripts/e2e_can_validation/update_e2e_capl_buffer_lengths.py

  # Preview changes without writing:
  python tools/util_scripts/e2e_can_validation/update_e2e_capl_buffer_lengths.py --dry-run

  # Override CAPL script path (if you keep it elsewhere):
  python tools/util_scripts/e2e_can_validation/update_e2e_capl_buffer_lengths.py --capl "C:/path/to/script.can"
"""

import re
import sys
import argparse
import os

# ---------------------------------------------------------------------------
# Default paths (relative to repo root, adjust if the files move)
# ---------------------------------------------------------------------------
REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))

DEFAULT_E2EXF_LCFG = os.path.join(
    REPO_ROOT,
    "software",
    "m7",
    "autosar",
    "config",
    "Appl",
    "GenData",
    "E2EXf_LCfg.c",
)

DEFAULT_CAPL_SCRIPT = os.path.join(
    os.path.dirname(__file__),
    "OSPAS_E2E_Validation_Script.can",
)

# ---------------------------------------------------------------------------
# Mapping: CAPL constant name  ->  substring that identifies the E2E P05
#          config struct in E2EXf_LCfg.c (first occurrence is used because
#          all RDR01-08 instances of the same message have identical DataLength)
# ---------------------------------------------------------------------------
BUFFER_CONSTANTS = {
    "BUFFER_LEN_HEADER": "Pp_SG_RadarHeader_",
    "BUFFER_LEN_ALIGN_001": "Pp_SG_AlignmentStatus1_",
    "BUFFER_LEN_ALIGN_002": "Pp_SG_AlignmentStatus2_",
    "BUFFER_LEN_CAPABILITY": "Pp_SG_RadarCapability_",
}


def extract_data_lengths(e2exf_path: str) -> dict[str, int]:
    """Parse E2EXf_LCfg.c and return {identifier_substring: DataLength_in_bits}.

    Only E2E_P05ConfigType structs are considered (CAN messages use Profile 5).
    """
    with open(e2exf_path, "r", encoding="utf-8", errors="replace") as fh:
        content = fh.read()

    # Match every P05 config block:
    #   CONST(E2E_P05ConfigType, ...) <name> = { ... DataLength ... };
    block_re = re.compile(
        r"E2E_P05ConfigType[^)]*\)\s+(\w+)\s*=\s*\{([^}]+)\}",
        re.DOTALL,
    )
    data_length_re = re.compile(r"(\d+)U\s*/\*\s*DataLength\s*\*/")

    results: dict[str, int] = {}
    for match in block_re.finditer(content):
        struct_name = match.group(1)
        body = match.group(2)
        dl_match = data_length_re.search(body)
        if dl_match:
            results[struct_name] = int(dl_match.group(1))

    return results


def resolve_buffer_lengths(data_lengths: dict[str, int]) -> dict[str, int]:
    """Resolve buffer lengths for each CAPL constant.

    For each CAPL constant, find the first P05 struct whose name contains the
    identifying substring and return bufferLength = DataLength / 8.
    """
    resolved: dict[str, int] = {}
    missing: list[str] = []

    for constant, needle in BUFFER_CONSTANTS.items():
        found = None
        for struct_name, bits in data_lengths.items():
            if needle in struct_name:
                found = bits
                break
        if found is None:
            missing.append(f"  {constant} (looking for '{needle}')")
        else:
            if found % 8 != 0:
                print(
                    f"WARNING: DataLength {found} bits for '{constant}' is not "
                    f"divisible by 8 — check the AUTOSAR configuration."
                )
            resolved[constant] = found // 8

    if missing:
        print("ERROR: Could not find DataLength for the following constants:")
        print("\n".join(missing))
        print(
            "Check that E2EXf_LCfg.c is up-to-date and the struct name "
            "substrings in BUFFER_CONSTANTS still match."
        )
        sys.exit(1)

    return resolved


def patch_capl_script(
    capl_path: str,
    new_values: dict[str, int],
    dry_run: bool = False,
) -> bool:
    """Replace BUFFER_LEN_* constant values in the CAPL script.

    Returns True if any change was made (or would be made in dry-run mode).
    """
    with open(capl_path, "r", encoding="latin-1") as fh:
        original = fh.read()

    patched = original
    changes: list[tuple[str, int, int]] = []

    for constant, new_bytes in new_values.items():
        # Match lines like:  const byte BUFFER_LEN_HEADER      = 54;  // ...
        pattern = re.compile(r"(const\s+byte\s+" + re.escape(constant) + r"\s*=\s*)(\d+)(;.*)")
        match = pattern.search(patched)
        if not match:
            print(f"WARNING: '{constant}' not found in CAPL script — skipped.")
            continue

        old_bytes = int(match.group(2))
        if old_bytes == new_bytes:
            print(f"  {constant}: {old_bytes} bytes  [unchanged]")
            continue

        # Rebuild the comment to reflect the new bit count
        bits = new_bytes * 8
        new_comment = f"  // {bits} bits / 8 = {new_bytes} bytes"
        new_line = match.group(1) + str(new_bytes) + ";" + new_comment
        patched = pattern.sub(new_line, patched, count=1)
        changes.append((constant, old_bytes, new_bytes))
        arrow = ">>>" if not dry_run else "(dry-run)"
        print(f"  {constant}: {old_bytes} -> {new_bytes} bytes  {arrow}")

    if changes and not dry_run:
        with open(capl_path, "w", encoding="latin-1") as fh:
            fh.write(patched)
        print(f"\nPatched {len(changes)} constant(s) in:\n  {capl_path}")
    elif changes and dry_run:
        print(f"\nDry-run: {len(changes)} constant(s) would be updated.")
    else:
        print("\nNo changes required — CAPL script is already up-to-date.")

    return bool(changes)


def main() -> None:
    """Sync E2E buffer-length constants in a CAPL script from E2EXf_LCfg.c."""
    parser = argparse.ArgumentParser(
        description="Sync E2E buffer-length constants in a CAPL script from E2EXf_LCfg.c"
    )
    parser.add_argument(
        "--e2exf",
        default=DEFAULT_E2EXF_LCFG,
        help=f"Path to E2EXf_LCfg.c  (default: {DEFAULT_E2EXF_LCFG})",
    )
    parser.add_argument(
        "--capl",
        default=DEFAULT_CAPL_SCRIPT,
        help=f"Path to the CAPL .can script  (default: {DEFAULT_CAPL_SCRIPT})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without writing to disk",
    )
    args = parser.parse_args()

    # --- Validate input files -----------------------------------------------
    for label, path in [("E2EXf_LCfg.c", args.e2exf), ("CAPL script", args.capl)]:
        if not os.path.isfile(path):
            print(f"ERROR: {label} not found:\n  {path}")
            sys.exit(1)

    print(f"Source : {args.e2exf}")
    print(f"Target : {args.capl}")
    print(f"Mode   : {'DRY-RUN' if args.dry_run else 'UPDATE'}")
    print("-" * 60)

    # --- Extract DataLength values from E2EXf_LCfg.c ------------------------
    data_lengths = extract_data_lengths(args.e2exf)
    if not data_lengths:
        print("ERROR: No E2E_P05ConfigType structs found in E2EXf_LCfg.c.")
        sys.exit(1)
    print(f"Found {len(data_lengths)} E2E P05 config struct(s) in E2EXf_LCfg.c")

    # --- Resolve per-constant buffer lengths ---------------------------------
    new_values = resolve_buffer_lengths(data_lengths)
    print("\nResolved buffer lengths (bytes):")
    for const, val in new_values.items():
        print(f"  {const:<25} = {val}  ({val * 8} bits)")

    # --- Patch the CAPL script -----------------------------------------------
    print("\nPatching CAPL script:")
    patch_capl_script(args.capl, new_values, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
