##########################
### Project definition ###
##########################
cmake_minimum_required(VERSION 4.0)

set(project_name  "Common_Structures")
project(${project_name})

set(COMMON_STRUCTURE_PROJECT_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}/..")

set(SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/Common_Structures.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/SOMEIPCommonHeader.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI250.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI290.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_Common.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_HeaderI290.h")

list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI330.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_HeaderI330.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_IPFFAR_SOMEIP_HeaderI290.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_IPFFAR_SOMEIP_HeaderI330.h")

list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI360.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_HeaderI360.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_IPFFAR_SOMEIP_HeaderI360.h")

list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI380.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_HeaderI380.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_IPFFAR_SOMEIP_HeaderI380.h")

list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI390.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_HeaderI390.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_IPFFAR_SOMEIP_HeaderI390.h")

list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI420.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_HeaderI420.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_IPFFAR_SOMEIP_HeaderI420.h")

list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_SRR7P_SOMEIP_HeaderI430.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_FLR7_SOMEIP_HeaderI430.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/BMWL2_IPFFAR_SOMEIP_HeaderI430.h")

list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/DLTCommonHeader.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_log_types.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_detection_log.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_internal_cluster.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_internal_cwd.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_internal_detection_history.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_internal_object.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_internal_reflection_buffer.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_internal_underdrivability.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_log_data.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_log_types.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_object_log.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_rot_object_log.h")
list(APPEND SOURCES "${COMMON_STRUCTURE_PROJECT_ROOT_PATH}/DLTHeaders/f360_sensor_calib_log.h")

add_library(${project_name} STATIC "")
set_target_properties(${project_name} PROPERTIES LINKER_LANGUAGE CXX)
target_sources(${project_name} PUBLIC ${SOURCES})


