; ********************************************************************************
; NOTE: All paths should be absolute from a specific folder INSIDE the repository
; ********************************************************************************
; For PATH_CHECK_RESULT, the options are to cause the script to fail (Error),
; print a warning (Warning), or skip (Ignore) the path existence check
; ********************************************************************************
[PATH_CHECK_RESULT]
TOOLS                 = Ignore

# Make this a folder inside the repository! All other paths are relative to one level up from this directory
[ROOT]
repo_root = software

[TOOLS]
ptp = tools/ptp/ptp
ptpDir = tools/ptp
buildifier = tools/python/runBuildifier/buildifier
