#!/bin/bash

newarr[0]=$1
newarr[1]=$2
TEMP_PATH=$3
input_file=$4
CUST_NAME=$5
SESSION_BASE=$6
BUS_TAG=${7:-b04}
RM_ZERO=${8:-false}
#echo "Running ReSim for ${newarr[0]}"
#echo "Running ReSim for ${newarr[1]}"
#echo "Running ReSim for $TEMP_PATH"
#echo "Running ReSim for $input_file"

# Explicitly (re)initialize all accumulator arrays. This guards against duplicate
# log entries in the generated JSON if this script's body ever runs more than once
# in the same shell (e.g. sourced/re-entered) instead of a single fresh process -
# without this, bash's "+=" would keep appending onto arrays left over from a
# previous run instead of starting from empty.
deb_files=(); bus_files=(); ref_files=(); vid_files=()
deb_logs=(); bus_logs=(); ref_logs=(); vid_logs=()

echo "Running ReSim for $CUST_NAME"
echo "[Splitter_Execution] : bus log tag requested - $BUS_TAG"
echo "[Splitter_Execution] : rm_zero requested - $RM_ZERO"

echo "[Splitter_Execution] : execution requested for - ${newarr[0]}, ${newarr[1]}"

# Excludes the 0th log segment (e.g. "..._0000_b05.MF4") and its corresponding
# b04/b02/bus/ref logs when RM_ZERO=true, so segment 0 is removed entirely from
# the picture (mirrors the same '_0000_' filter applied in resim_splitter.py).
filter_zero() {
    if [[ "$RM_ZERO" == "true" ]]; then
        grep -v '_0000_'
    else
        cat
    fi
}
#echo "[DEBUG]:$CUST_NAME"

############# function to capture file if FS is UPU #############
CREATE_UPU(){
    bus_files=()
    deb_files=()
    for path in "$1"/*; do
        #echo "UPU-path : $path"
        for file in "$path"/*; do
            #echo "UPU-File : $file"
            if [[ $file = *"_${BUS_TAG}.MF4" || "$file" == *'BUS'* ]]; then
                bus_files+=($file)
            elif [[ $file = *'_b05.MF4' || "$file" == *'SDVRADAR'* || "$file" == *'SDV_RADAR'* || "$file" == *'DEBUG'* ]]; then
                deb_files+=($file)
            fi
        done
    done  
#echo "deb files : ${deb_files[@]}"   
}

############# function to capture file based on customer #############
if [[ $CUST_NAME == *'STLA-SMALL'* ]]; then
    IFS="/" read -r -a path <<< "${newarr[0]}" 
    INPUT_DIR=${newarr[0]%%"/${path[-2]}"*}
    if [[ -n "$SESSION_BASE" && -d "$SESSION_BASE" ]]; then
        SEARCH_ROOT="$SESSION_BASE"
    else
        SEARCH_ROOT="$INPUT_DIR"
    fi

    # Current LABCAR3 naming: flat _b05 (debug) / _${BUS_TAG} (bus) MF4 files nested under
    # per-segment subfolders (e.g. SESSION/STLASMALL_..._0000/*_b05.MF4) - no RADAR_DEBUG/RADAR_DATA
    # split, and NOT a single flat level, so this must recurse (no -maxdepth) under SEARCH_ROOT.
    while IFS= read -r file; do
        deb_files+=("$file")
    done < <(find -L "$SEARCH_ROOT" -type f \( -iname "*_b05*.MF4" -o -iname "*_b05*.mf4" \) | sort | filter_zero)
    while IFS= read -r file; do
        bus_files+=("$file")
    done < <(find -L "$SEARCH_ROOT" -type f \( -iname "*_${BUS_TAG}*.MF4" -o -iname "*_${BUS_TAG}*.mf4" \) | sort | filter_zero)
    echo "[Splitter_STLA-SMALL] : found ${#deb_files[@]} b05 files and ${#bus_files[@]} $BUS_TAG (bus) files under $SEARCH_ROOT"

    # Fall back to legacy RADAR_DEBUG/RADAR_DATA folder convention if the flat naming yielded nothing
    if [[ ${#deb_files[@]} -eq 0 || ${#bus_files[@]} -eq 0 ]]; then
        echo "[Splitter_STLA-SMALL] : no flat _b05/_${BUS_TAG} files found, falling back to RADAR_DEBUG/RADAR_DATA folders"
        deb_files=(); bus_files=()
        for path in "$INPUT_DIR"/*; do
            if [[ $path = *'RADAR_DEBUG'* ]]; then
                for file in "$path"/*; do
                    #echo "[DEBUG]:file : $file"
                    [[ "$RM_ZERO" == "true" && "$file" == *'_0000_'* ]] && continue
                    if [[ $file = *'.MF4'* ]]; then
                        deb_files+=($file)
                    fi
                done

           elif [[ $path = *'RADAR_DATA'* ]]; then
               for file in "$path"/*; do
                   [[ "$RM_ZERO" == "true" && "$file" == *'_0000_'* ]] && continue
                   if [[ $file = *'.MF4'* ]]; then
                       bus_files+=($file)
                   fi
               done
           fi
        done
    fi
    echo "[Splitter_STLA-SMALL] : deb_files count=${#deb_files[@]}, bus_files count=${#bus_files[@]}"

elif [[ $CUST_NAME == *'MCIP'* ]]; then
    IFS="/" read -r -a path <<< "${newarr[0]}"
    INPUT_DIR=${newarr[0]%%"/${path[-2]}"*}
    # Read b05 and bus (b04/b02) files from precached lists (generated by resim_splitter.py).
    # A single batch can span multiple nested session folders, so read the full
    # recursive set from the cache instead of scanning only this file's own folder.
    JOBOUT_DIR=$(dirname "$input_file")
    B05_CACHE="$JOBOUT_DIR/mcip_b05_cache.txt"
    BUS_CACHE="$JOBOUT_DIR/mcip_bus_cache.txt"

    if [[ -f "$B05_CACHE" && -f "$BUS_CACHE" ]]; then
        while IFS= read -r file; do
            [[ -n "$file" ]] && deb_files+=("$file")
        done < <(awk '!seen[$0]++' "$B05_CACHE")
        while IFS= read -r file; do
            [[ -n "$file" ]] && bus_files+=("$file")
        done < <(awk '!seen[$0]++' "$BUS_CACHE")
        echo "[Splitter_MCIP] : loaded ${#deb_files[@]} b05 files and ${#bus_files[@]} $BUS_TAG (bus) files from cache"
    else
        # Fallback: if cache files don't exist, do a recursive find (for backwards compatibility)
        echo "[Splitter_MCIP] : cache files not found, falling back to find operation"
        if [[ -n "$SESSION_BASE" && -d "$SESSION_BASE" ]]; then
            SEARCH_ROOT="$SESSION_BASE"
        else
            SEARCH_ROOT="$INPUT_DIR"
        fi
        while IFS= read -r file; do
            if [[ "$file" == *"_${BUS_TAG}.MF4" || "$file" == *"_${BUS_TAG}.mf4" ]]; then
                bus_files+=("$file")
            elif [[ "$file" == *'_b05'* ]]; then
                deb_files+=("$file")
            fi
        done < <(find -L "$SEARCH_ROOT" -type f \( -iname "*.MF4" -o -iname "*.mf4" \) | sort | filter_zero)
    fi
    echo "[Splitter_MCIP] : deb_files count=${#deb_files[@]}, bus_files count=${#bus_files[@]}"

elif [[ $CUST_NAME == *'GPO-V2'* ]]; then
    IFS="/" read -r -a path <<< "${newarr[0]}" 
    INPUT_DIR=${newarr[0]%%"/${path[-1]}"*}
    UPU_DIR=${newarr[0]%%"/${path[-2]}"*}
    echo "[Splitter_GPO-V2] : INPUT_DIR=$INPUT_DIR"
    # Read b05 and bus (b04/b02) files from precached lists (generated by resim_splitter.py)
    JOBOUT_DIR=$(dirname "$input_file")
    B05_CACHE="$JOBOUT_DIR/gpo_v2_b05_cache.txt"
    BUS_CACHE="$JOBOUT_DIR/gpo_v2_bus_cache.txt"
    
    if [[ -f "$B05_CACHE" && -f "$BUS_CACHE" ]]; then
        # De-duplicate while reading: guards against duplicate lines that may have
        # been written into the shared cache (e.g. this session's files scanned/
        # appended more than once), which would otherwise duplicate log entries
        # in the final JSON for jobs whose log count spans the duplicated indices.
        while IFS= read -r file; do
            [[ -n "$file" ]] && deb_files+=("$file")
        done < <(awk '!seen[$0]++' "$B05_CACHE")
        while IFS= read -r file; do
            [[ -n "$file" ]] && bus_files+=("$file")
        done < <(awk '!seen[$0]++' "$BUS_CACHE")
        echo "[Splitter_GPO-V2] : loaded ${#deb_files[@]} b05 files and ${#bus_files[@]} $BUS_TAG (bus) files from cache"
    else
        # Fallback: if cache files don't exist, do a recursive find (for backwards compatibility)
        echo "[Splitter_GPO-V2] : cache files not found, falling back to find operation"
        if [[ -n "$SESSION_BASE" && -d "$SESSION_BASE" ]]; then
            SEARCH_ROOT="$SESSION_BASE"
        else
            SEARCH_ROOT="$UPU_DIR"
        fi
        while IFS= read -r file; do
            if [[ "$file" == *"_${BUS_TAG}.MF4" || "$file" == *"_${BUS_TAG}.mf4" || "$file" == *'BUS'* ]]; then
                bus_files+=("$file")
            elif [[ "$file" == *'_b05'* || "$file" == *'SDVRADAR'* || "$file" == *'SDV_RADAR'* || "$file" == *'DEBUG'* ]]; then
                deb_files+=("$file")
            fi
        done < <(find -L "$SEARCH_ROOT" -type f \( -iname "*.MF4" -o -iname "*.mf4" \) | sort | filter_zero)
    fi
    echo "[Splitter_GPO-V2] : deb_files count=${#deb_files[@]}, bus_files count=${#bus_files[@]}"
    if [ ${#bus_files[@]} -eq 0 ]; then
        bus_files=("${deb_files[@]}")
    elif [ ${#deb_files[@]} -eq 0 ]; then
	deb_files=("${bus_files[@]}")
    fi

elif [[ $CUST_NAME == *'DC'* ]]; then

    IFS="/" read -r -a path <<< "${newarr[0]}" 
    INPUT_DIR=${newarr[0]%%"/${path[-1]}"*}
    UPU_DIR=${newarr[0]%%"/${path[-2]}"*}
    while IFS= read -r file; do
        if [[ "$file" == *"_${BUS_TAG}.MF4" || "$file" == *"_${BUS_TAG}.mf4" || "$file" == *'BUS'* ]]; then
            bus_files+=("$file")
        elif [[ "$file" == *'_b05'* || "$file" == *'SDVRADAR'* || "$file" == *'SDV_RADAR'* || "$file" == *'DEBUG'* || "$file" == *'CCA'* ]]; then
            deb_files+=("$file")
        fi
    done < <(find "$UPU_DIR" -type f \( -iname "*.MF4" -o -iname "*.mf4" \) | sort | filter_zero)

elif [[ $CUST_NAME == *'DGPS'* ]]; then
    IFS="/" read -r -a path_arr <<< "${newarr[0]}"
    INPUT_DIR=${newarr[0]%%"/${path_arr[-1]}"*}
    echo "[Splitter_DGPS] : INPUT_DIR=$INPUT_DIR"
    # Use SESSION_BASE as search root to find all b05 across nested subfolders
    if [[ -n "$SESSION_BASE" && -d "$SESSION_BASE" ]]; then
        DGPS_SEARCH_ROOT="$SESSION_BASE"
    else
        DGPS_SEARCH_ROOT="$INPUT_DIR"
    fi
    echo "[Splitter_DGPS] : DGPS_SEARCH_ROOT=$DGPS_SEARCH_ROOT"
    while IFS= read -r file; do
        deb_files+=("$file")
    done < <(find -L "$DGPS_SEARCH_ROOT" -type f \( -iname "*_b05*.MF4" -o -iname "*_b05*.mf4" \) | sort | filter_zero)
    echo "[Splitter_DGPS] : found ${#deb_files[@]} b05 files"
    # Read g03/g02 from pre-cached lists (generated by resim_splitter.py)
    JOBOUT_DIR=$(dirname "$input_file")
    G03_CACHE="$JOBOUT_DIR/dgps_g03_cache.txt"
    G02_CACHE="$JOBOUT_DIR/dgps_g02_cache.txt"
    if [[ -f "$G03_CACHE" ]]; then
        while IFS= read -r file; do
            [[ -n "$file" ]] && ref_files+=("$file")
        done < "$G03_CACHE"
        echo "[Splitter_DGPS] : loaded ${#ref_files[@]} g03 files from cache"
    else
        echo "[Splitter_DGPS] : WARNING - g03 cache not found, falling back to find"
        if [[ -n "$SESSION_BASE" && -d "$SESSION_BASE" ]]; then SEARCH_ROOT="$SESSION_BASE"; else SEARCH_ROOT="$INPUT_DIR"; fi
        while IFS= read -r file; do
            ref_files+=("$file")
        done < <(find "$SEARCH_ROOT" -type f \( -iname "*_g03*.MF4" -o -iname "*_g03*.mf4" \) | sort | filter_zero)
    fi
    if [[ -f "$G02_CACHE" ]]; then
        while IFS= read -r file; do
            [[ -n "$file" ]] && vid_files+=("$file")
        done < "$G02_CACHE"
        echo "[Splitter_DGPS] : loaded ${#vid_files[@]} g02 files from cache"
    else
        echo "[Splitter_DGPS] : WARNING - g02 cache not found, falling back to find"
        if [[ -n "$SESSION_BASE" && -d "$SESSION_BASE" ]]; then SEARCH_ROOT="$SESSION_BASE"; else SEARCH_ROOT="$INPUT_DIR"; fi
        while IFS= read -r file; do
            vid_files+=("$file")
        done < <(find "$SEARCH_ROOT" -type f \( -iname "*_g02*.MF4" -o -iname "*_g02*.mf4" \) | sort | filter_zero)
    fi
    echo "[Splitter_DGPS] : b05 files=${#deb_files[@]}, g03 files=${#ref_files[@]}, g02 files=${#vid_files[@]}"

elif [[ $CUST_NAME == *'ADCAM'* ]]; then
    # ADCAM docker (ifv600_*.simg): only p01 MF4 files are collected; there is
    # no separate bus/ref stream for this docker type.
    IFS="/" read -r -a path_arr <<< "${newarr[0]}"
    INPUT_DIR=${newarr[0]%%"/${path_arr[-1]}"*}
    UPU_DIR=${newarr[0]%%"/${path_arr[-2]}"*}
    echo "[Splitter_ADCAM] : INPUT_DIR=$INPUT_DIR"
    if [[ -n "$SESSION_BASE" && -d "$SESSION_BASE" ]]; then
        SEARCH_ROOT="$SESSION_BASE"
    else
        SEARCH_ROOT="$UPU_DIR"
    fi
    echo "[Splitter_ADCAM] : SEARCH_ROOT=$SEARCH_ROOT"
    while IFS= read -r file; do
        deb_files+=("$file")
    done < <(find -L "$SEARCH_ROOT" -type f \( -iname "*_p01*.MF4" -o -iname "*_p01*.mf4" \) | sort | filter_zero)
    echo "[Splitter_ADCAM] : found ${#deb_files[@]} p01 files"

else
    # DEFAULT: generic file collection for vehicle/unknown docker types
    IFS="/" read -r -a path_arr <<< "${newarr[0]}"
    INPUT_DIR=${newarr[0]%%"/${path_arr[-1]}"*}
    UPU_DIR=${newarr[0]%%"/${path_arr[-2]}"*}
    echo "[Splitter_DEFAULT] : INPUT_DIR=$INPUT_DIR"
    echo "[Splitter_DEFAULT] : UPU_DIR=$UPU_DIR"
    # Recursive scan for all MF4 debug/bus files
    while IFS= read -r file; do
        if [[ "$file" == *'_b05'* || "$file" == *'SDVRADAR'* || "$file" == *'SDV_RADAR'* || "$file" == *'_DEBUG_'* || "$file" == *'DEBUG'* ]]; then
            deb_files+=("$file")
        elif [[ "$file" == *"_${BUS_TAG}"* || "$file" == *'_BUS_'* || "$file" == *'BUS'* ]]; then
            bus_files+=("$file")
        fi
    done < <(find "$UPU_DIR" -type f \( -iname "*.MF4" -o -iname "*.mf4" \) ! -iname "*ORCAS*" ! -iname "*CANoe*" | sort | filter_zero)
    echo "[Splitter_DEFAULT] : deb_files count=${#deb_files[@]}"
    echo "[Splitter_DEFAULT] : bus_files count=${#bus_files[@]}"
    if [ ${#bus_files[@]} -eq 0 ]; then
        bus_files=("${deb_files[@]}")
    fi
    if [ ${#deb_files[@]} -eq 0 ]; then
        deb_files=("${bus_files[@]}")
    fi
fi

log_name=${newarr[0]}
log_basename=$(basename "$log_name")


for i in "${!deb_files[@]}"; do
   if [[ "${deb_files[$i]}" = "${log_name}" ]]; then
       start_log=${i};
       end_log=$(( $start_log + ${newarr[1]} - 1 ));
       echo "[Splitter_DEBUG] : Full path match found at index $i"
       break;
   fi
done

# Fallback: match by basename if full-path match failed (handles nested subfolder differences)
if [[ -z "$start_log" ]]; then
    echo "[Splitter_DEBUG] : Full path match failed for: $log_name"
    echo "[Splitter_DEBUG] : Searching by basename: $log_basename"
    echo "[Splitter_DEBUG] : First 3 deb_files: ${deb_files[0]} | ${deb_files[1]} | ${deb_files[2]}"
    for i in "${!deb_files[@]}"; do
        deb_basename=$(basename "${deb_files[$i]}")
        if [[ "$deb_basename" == "$log_basename" ]]; then
            start_log=${i};
            end_log=$(( $start_log + ${newarr[1]} - 1 ));
            echo "[Splitter_Fallback] : matched by basename at index $i"
            break;
        fi
    done
fi

if [[ -z "$start_log" ]]; then
    echo "[Splitter_ERROR] : Could not find start log '${log_name}' in deb_files (count=${#deb_files[@]})"
    echo "[Splitter_ERROR] : First few deb_files: ${deb_files[0]} | ${deb_files[1]} | ${deb_files[2]}"
    echo "[Splitter_ERROR] : Aborting splitter"
    # Write empty JSON so downstream doesn't crash on missing file
    echo '{"reprocessingInputFileStreams":[{"key":"BN_CALIFR","files":[]},{"key":"BN_FASETH","files":[]},{"key":"SRR_DEBUG","files":[]},{"key":"SRR_REFERENCE","files":[]}]}' > $input_file
    exit 1
fi

mkdir -p $TEMP_PATH/LOGS
#mkdir -p $TEMP_PATH/RESIM-RESULTS

echo "[Splitter_Execution] : start log index is $start_log (${deb_files[$start_log]})"
echo "[Splitter_Execution] : end log index is $end_log (${deb_files[$end_log]})"
echo "[Splitter_DEBUG] : Processing ${newarr[1]} files from index $start_log to $end_log"

# Cap end_log to array bounds
if [[ $end_log -ge ${#deb_files[@]} ]]; then
    end_log=$(( ${#deb_files[@]} - 1 ))
    echo "[Splitter_Execution] : capped end_log to $end_log (array size=${#deb_files[@]})"
fi

############# function to copy data to tmp location #############
echo "[Splitter_DEBUG] : Starting copy loop: for (( i=$start_log; i<=$end_log; i++ ))"
for (( i=$start_log; i<=$end_log; i++ )); do
    echo "[Splitter_DEBUG] : Copying file $i: ${deb_files[$i]}"

    if [[ $CUST_NAME == *'STLA-SMALL'* ]]; then
        cp ${deb_files[$i]} $TEMP_PATH/LOGS
        deb_logs+=($(basename "${deb_files[$i]}"))
        cp ${bus_files[$i]} $TEMP_PATH/LOGS
        bus_logs+=($(basename "${bus_files[$i]}"))

    elif [[ $CUST_NAME == *'MCIP'* ]]; then
        cp ${deb_files[$i]} $TEMP_PATH/LOGS
        deb_logs+=($(basename "${deb_files[$i]}"))
        cp ${bus_files[$i]} $TEMP_PATH/LOGS
        bus_logs+=($(basename "${bus_files[$i]}"))


    elif [[ $CUST_NAME == *'GPO-V2'* ]]; then
        cp ${deb_files[$i]} $TEMP_PATH/LOGS
        deb_logs+=($(basename "${deb_files[$i]}"))
        # Stem-based match: strip _b05/bus-tag suffix AND any Radar/Can modality
        # infix (some sessions name debug/bus files "..._Radar_..._b05.MF4" /
        # "..._Can_..._b02.MF4" instead of sharing an identical base name).
        # Also normalize the literal "_DEBUG_"/"_BUS_" tag (used by sessions that
        # name files "..._DEBUG_<ts>_NNNN.MF4"/"..._BUS_<ts>_NNNN.MF4" instead of
        # the "_b05"/"_{BUS_TAG}" suffix convention) so both naming schemes
        # produce a matching stem.
        deb_bname=$(basename "${deb_files[$i]}")
        deb_stem=$(echo "${deb_bname}" | sed -E "s/_(Radar|Can)_/_/I; s/_(DEBUG|BUS)_/_/I; s/(_b05|_${BUS_TAG}).*//I" | tr '[:upper:]' '[:lower:]')
        found_bus=""
        for bf in "${bus_files[@]}"; do
            bf_bname=$(basename "$bf")
            bf_stem=$(echo "${bf_bname}" | sed -E "s/_(Radar|Can)_/_/I; s/_(DEBUG|BUS)_/_/I; s/(_${BUS_TAG}).*//I" | tr '[:upper:]' '[:lower:]')
            if [[ "$bf_stem" == "$deb_stem" ]]; then
                found_bus="$bf"
                break
            fi
        done
        if [[ -n "$found_bus" ]]; then
            cp "$found_bus" $TEMP_PATH/LOGS
            bus_logs+=($(basename "$found_bus"))
        else
            echo "[Splitter_GPO-V2] : WARNING - no matching bus file for ${deb_files[$i]}, using deb as fallback"
            bus_logs+=($(basename "${deb_files[$i]}"))
        fi

    elif [[ $CUST_NAME == *'DC'* ]]; then
        cp ${deb_files[$i]} $TEMP_PATH/LOGS 
        deb_logs+=($(basename "${deb_files[$i]}"))
        cp ${bus_files[$i]} $TEMP_PATH/LOGS
        bus_logs+=($(basename "${bus_files[$i]}"))

    elif [[ $CUST_NAME == *'DGPS'* ]]; then
        # Extract stem: everything before _b05 (case-insensitive)
        deb_basename=$(basename "${deb_files[$i]}")
        deb_stem="${deb_basename%%_b05*}"
        deb_stem_lower=$(echo "$deb_stem" | tr '[:upper:]' '[:lower:]')
        
        # Find corresponding g03 (ref) file in cache
        found_rf=""
        for rf in "${ref_files[@]}"; do
            rf_basename=$(basename "$rf")
            rf_stem="${rf_basename%%_g03*}"
            rf_stem_lower=$(echo "$rf_stem" | tr '[:upper:]' '[:lower:]')
            if [[ "$rf_stem_lower" == "$deb_stem_lower" ]]; then
                found_rf="$rf"
                break
            fi
        done

        if [[ -n "$found_rf" ]]; then
            cp "${deb_files[$i]}" $TEMP_PATH/LOGS
            deb_logs+=("$deb_basename")
            
            cp "$found_rf" $TEMP_PATH/LOGS
            ref_logs+=("$rf_basename")
            
            # Find and copy corresponding g02 (vid) file
            for vf in "${vid_files[@]}"; do
                vf_basename=$(basename "$vf")
                vf_stem="${vf_basename%%_g02*}"
                vf_stem_lower=$(echo "$vf_stem" | tr '[:upper:]' '[:lower:]')
                if [[ "$vf_stem_lower" == "$deb_stem_lower" ]]; then
                    cp "$vf" $TEMP_PATH/LOGS
                    vid_logs+=("$vf_basename")
                    break
                fi
            done
        else
            echo "[Splitter_DGPS] : Skipping ${deb_files[$i]} - no matching g03 found in cache"
        fi

    elif [[ $CUST_NAME == *'ADCAM'* ]]; then
        # ADCAM: only p01 files, no matching bus/ref stream to copy
        cp "${deb_files[$i]}" $TEMP_PATH/LOGS
        deb_logs+=($(basename "${deb_files[$i]}"))

    else
        # DEFAULT: copy debug files
        cp "${deb_files[$i]}" $TEMP_PATH/LOGS
        deb_logs+=($(basename "${deb_files[$i]}"))
        if [ ${#bus_files[@]} -gt $i ] && [ -n "${bus_files[$i]}" ]; then
            cp "${bus_files[$i]}" $TEMP_PATH/LOGS
            bus_logs+=($(basename "${bus_files[$i]}"))
        fi

    fi
done

echo "[Splitter_DEBUG] : Copy loop completed"
echo "[Splitter_DEBUG] : Total deb_logs copied: ${#deb_logs[@]}"
echo "[Splitter_DEBUG] : Total bus_logs copied: ${#bus_logs[@]}"
echo "[Splitter_DEBUG] : Sample deb_logs: ${deb_logs[0]} | ${deb_logs[1]} | ${deb_logs[2]}"

# DGPS ref/vid files are already copied with stem-matching inside the loop above

############# function to write data in json files #############
POPULATE_FILES(){
    local total_entries=$(( ${#} - 1 ))
    echo "		{"  >> $input_file
    echo "  		\"key\": \"$1\"," >> $input_file
    echo '"files": [ ' >> $input_file
    count=1	

    for file in "${@:2}"; do
        if [[ "$count" -lt "$total_entries" ]]; then
            echo "		                    \"$TEMP_PATH/LOGS/$file\"," >> $input_file    
        else
            echo "		                    \"$TEMP_PATH/LOGS/$file\" " >> $input_file    
       fi
       count=$((count + 1))
    done

    echo "			]" >> $input_file
    if [[ $1 != "SRR_REFERENCE" ]]; then
	echo "		},"  >> $input_file
    else
	echo "		}"  >> $input_file
	#echo "" >> $input_file
    fi
}
#POPULATE_FILES() function closes here



############# function to create json files #############
echo "{" > $input_file
echo '  "reprocessingInputFileStreams": ' >> $input_file
echo "	["  >> $input_file

if [[ $CUST_NAME == *'STLA-SMALL'* ]]; then
    POPULATE_FILES "BN_CALIFR" "${bus_logs[@]}" 
    POPULATE_FILES "BN_FASETH" "${bus_logs[@]}" 
    POPULATE_FILES "SRR_DEBUG" "${deb_logs[@]}"
    POPULATE_FILES "SRR_REFERENCE"

elif [[ $CUST_NAME == *'MCIP'* ]]; then
    POPULATE_FILES "BN_CALIFR" "${bus_logs[@]}" 
    POPULATE_FILES "BN_FASETH" "${bus_logs[@]}" 
    POPULATE_FILES "SRR_DEBUG" "${deb_logs[@]}"
    POPULATE_FILES "SRR_REFERENCE"

elif [[ $CUST_NAME == *'DC'* ]]; then
    POPULATE_FILES "BN_CALIFR" "${bus_logs[@]}" 
    POPULATE_FILES "BN_FASETH" "${bus_logs[@]}" 
    POPULATE_FILES "SRR_DEBUG" "${deb_logs[@]}"
    POPULATE_FILES "SRR_REFERENCE"  

elif [[ $CUST_NAME == *'GPO-V2'* ]]; then
    POPULATE_FILES "BN_CALIFR" "${bus_logs[@]}" 
    POPULATE_FILES "BN_FASETH" "${bus_logs[@]}" 
    POPULATE_FILES "SRR_DEBUG" "${deb_logs[@]}"
    POPULATE_FILES "SRR_REFERENCE"

elif [[ $CUST_NAME == *'DGPS'* ]]; then
    POPULATE_FILES "BN_CALIFR" "${deb_logs[@]}"
    POPULATE_FILES "BN_FASETH" "${deb_logs[@]}"
    POPULATE_FILES "SRR_DEBUG" "${deb_logs[@]}"
    POPULATE_FILES "SRR_REFERENCE" "${ref_logs[@]}"

elif [[ $CUST_NAME == *'ADCAM'* ]]; then
    # ADCAM: only p01 files go into SRR_DEBUG; all other tags stay empty.
    POPULATE_FILES "BN_CALIFR"
    POPULATE_FILES "BN_FASETH"
    POPULATE_FILES "SRR_DEBUG" "${deb_logs[@]}"
    POPULATE_FILES "SRR_REFERENCE"

else
    POPULATE_FILES "BN_CALIFR" "${bus_logs[@]}" 
    POPULATE_FILES "BN_FASETH" "${bus_logs[@]}" 
    POPULATE_FILES "SRR_DEBUG" "${deb_logs[@]}"  
    POPULATE_FILES "SRR_REFERENCE"
fi 

echo "	]"  >> $input_file
echo "}"  >> $input_file
