target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_FILE})

target_include_directories(CTA PUBLIC ${CMAKE_CURRENT_LIST_DIR})

target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_braking_logic.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_criticality_level_calculation.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_counters.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_debug_writer.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_debug_interface.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_factory.h)
target_sources(CTA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/cta_persistent_t.h)
target_sources(CTA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/cta_types.h)
target_sources(CTA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/cta_core_input_t.h)
target_sources(CTA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/cta_core_output_t.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_struct_initializer.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_object_validator.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_conflict_zone_adapter.h)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_common_functions.h)
target_sources(CTA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/cta_iface.h)
target_sources(CTA PUBLIC ${CMAKE_CURRENT_LIST_DIR}/cta_instance.h)

target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_braking_logic.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_criticality_level_calculation.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_counters.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_debug_writer.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_debug_interface.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_factory.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_struct_initializer.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_iface.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_object_validator.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_conflict_zone_adapter.c)
target_sources(CTA PRIVATE ${CMAKE_CURRENT_LIST_DIR}/cta_common_functions.c)
