[config]
# optional (default main): define the toplevel entry point
entry_point = main

# optional: list of category 1 interrupts (hardware/non-rtos interrupts that
# can occur at any time and use whatever stack is currently active)
# multiline entries are supported as long as they are indented
cat1_interrupts:
  DSP_Exception_Handler
  Timer0_Isr
  Ext_Write_Err_Isr
  Ipc_Trigger_Irq

# optional (default 1 GB): specify a maximum stack size target
# if this is exceeded, the script will exit with an error code
# 14746 = 24kB * 60%
max_stack = 14746

# optional (default 0): specify a fixed amount to add to the final computed
# stack size
# this can help if there is some stack already used before your main entry
# point or if you want to include some additional buffer
# extra_stack = 0

# required: specify the toolchain executable to use to perform the analysis
# currently only supported value is 'xt-stack-usage'
tool = xt-stack-usage

# specify the toolchain path where the tool can be found
# this will be relative to the execroot
tool_path_prefix_linux = external/bbe_linux
tool_path_prefix_win32 = external/bbe_windows
tool_path_linux = ${tool_path_prefix_linux}/tools/RI-2021.7-linux/XtensaTools/bin
tool_path_win32 = ${tool_path_prefix_win32}/tools/RI-2021.7-win32/XtensaTools/bin
tool_path_cygwin = ${tool_path_win32}

# these options are specific to xt-stack-usage
xtensa_core = spt_bbe32_vfpu_gold_r1p3
xtensa_system_linux = ${tool_path_prefix_linux}/builds/RI-2021.7-linux/${xtensa_core}/config
xtensa_system_win32 = ${tool_path_prefix_win32}/builds/RI-2021.7-win32/${xtensa_core}/config
xtensa_system_cygwin = ${xtensa_system_win32}

# the entry point and each indirect branch target can have their own section
[main]
# additional stack can be specified just for this subtree
# extra_stack = 0

# specify any additional indirect branches (function pointers or longjmp targets)
# entries are separated by whitespace
# multiline entries are supported as long as they are indented
indirect_calls:
    Init_Handler
    Idle_Handler
    Wait_For_Rfft_Complete_Handler
    Doppler_Handler
    Anglefinding_Handler
    SP_Post_Proc_Complete_Handler
