#Name of module - needs to be changed.
set(MODULE_NAME
   "internal_preprocessing"
)
#Path where module folder is - needs to be changed.
set(MODULE_PATH
    "sw/F360TrackerLib"
) 
#Path to module root - 
set(MODULE_ROOT 
   ${MODULE_PATH}/Fusion360/${MODULE_NAME}
)
#Path to Fusion root - 
set(FUSION_ROOT 
   ${MODULE_PATH}/Fusion360
)
#Path to stub files -
set(STUBS_ROOT 
   ${MODULE_ROOT}/unittest/stubs
)

#Add paths to include files needed
include_directories(
   ${MODULE_ROOT}
   ${FUSION_ROOT}/common/include
   ${FUSION_ROOT}/include
   ${MODULE_ROOT}/include
   ${FUSION_ROOT}/detection_to_track_association/include
   ${FUSION_ROOT}/cluster_grouping/include
   ${FUSION_ROOT}/clustering/include
   ${MODULE_ROOT}/Autogenerated
   ${FUSION_ROOT}/../Timing
   ${FUSION_ROOT}/clustering/unittest/utility_functions
   ${FUSION_ROOT}/unittest_common_data_generator
   ${FUSION_ROOT}/track_grouping/include
   ${FUSION_ROOT}/measurement_update_tracks/include
   ${FUSION_ROOT}/time_update_tracks/include
   ${FUSION_ROOT}/pre_association_track_management/include
   ${FUSION_ROOT}/track_classification/include
   ${FUSION_ROOT}/track_validity/include
   ${FUSION_ROOT}/post_update_track_adjustments/include
   ${FUSION_ROOT}/static_environment/include
   ${FUSION_ROOT}/initialize_tracks/include
   ${FUSION_ROOT}/internal_preprocessing/include
   ${FUSION_ROOT}/inputs_preprocessing/include
   ${FUSION_ROOT}/occlusion/include
   ${MODULE_PATH}/Diagnostics/InputDiagnostics/include
   ${MODULE_PATH}/Diagnostics/InternalDiagnostics/include
   ${MODULE_PATH}/include
   ${FUSION_ROOT}/unified_output/include
   ${FUSION_ROOT}/sensor_postprocessing/include  
   ${FUSION_ROOT}/internal_preprocessing/include
   ${FUSION_ROOT}/update_relative_timestamps/include
   ${FUSION_ROOT}/e2e_protection/include
   ${FUSION_ROOT}/autocode_reuse/include
   ${FUSION_ROOT}/unittest_stubs
)

message("Adding tests from " ${CMAKE_CURRENT_SOURCE_DIR})

#Add source files that shall be tested
set(SRC 
   ${MODULE_ROOT}/source/f360_calc_obj_mov_stat_thresh.cpp
   ${MODULE_ROOT}/source/f360_calc_probabilities_of_detections.cpp
   ${MODULE_ROOT}/source/f360_configure_rdot_interval_compatibility.cpp
   ${MODULE_ROOT}/source/f360_detect_stationary_bounce.cpp
   ${MODULE_ROOT}/source/f360_mark_out_det_pairs.cpp
   ${MODULE_ROOT}/source/f360_update_detection_property.cpp
   ${MODULE_ROOT}/source/f360_detection_double_bounce_detector.cpp  
   ${MODULE_ROOT}/source/f360_handle_host_vehicle_clutter.cpp
   ${MODULE_ROOT}/source/f360_handle_host_vehicle_clutter_helpers.cpp
   ${MODULE_ROOT}/source/f360_mark_object_tracks_next_to_sensors.cpp
   ${MODULE_ROOT}/source/f360_det_is_in_bistatic_fp_area.cpp
   ${MODULE_ROOT}/source/f360_det_is_seen_by_sensor.cpp
   ${MODULE_ROOT}/source/f360_handle_bistatic.cpp
   ${MODULE_ROOT}/source/f360_filter_out_low_quality_detections_on_or_behind_guardrail.cpp
)

#Add source files for including external references
file(GLOB EXTR_INC_SRC
   "${MODULE_ROOT}/source/*.cpp"
   "${FUSION_ROOT}/clustering/source/*.cpp"
   "${FUSION_ROOT}/track_grouping/source/*.cpp"
   "${FUSION_ROOT}/track_downselection/source/*.cpp"
   "${FUSION_ROOT}/track_classification/source/*.cpp"
   "${FUSION_ROOT}/track_validity/source/*.cpp"
   "${FUSION_ROOT}/multipath_detector/source/*.cpp"
   "${FUSION_ROOT}/measurement_update_tracks/source/*.cpp"
   "${FUSION_ROOT}/detection_to_track_association/source/*.cpp"
   "${FUSION_ROOT}/pre_association_track_management/source/*.cpp"
   "${FUSION_ROOT}/time_update_tracks/source/*.cpp"
   "${FUSION_ROOT}/post_update_track_adjustments/source/*.cpp"
   "${FUSION_ROOT}/static_environment/source/*.cpp"
   "${FUSION_ROOT}/cluster_grouping/source/*.cpp"
   "${FUSION_ROOT}/clustering/source/*.cpp"
   "${FUSION_ROOT}/initialize_tracks/source/*.cpp"
   "${FUSION_ROOT}/internal_preprocessing/source/*.cpp"
   "${FUSION_ROOT}/occlusion/source/*.cpp"
   "${MODULE_PATH}/Diagnostics/InputDiagnostics/source/*.cpp"
   "${MODULE_PATH}/*.cpp"
   "${FUSION_ROOT}/f360_calibrations.cpp"
   "${FUSION_ROOT}/unified_output/source/*.cpp"
   "${FUSION_ROOT}/internal_preprocessing/source/*.cpp"
   "${FUSION_ROOT}/sensor_postprocessing/source/*.cpp"
   "${FUSION_ROOT}/update_relative_timestamps/source/*.cpp"
   "${FUSION_ROOT}/e2e_protection/source/*.cpp"
   "${FUSION_ROOT}/common/source/*.cpp"
   "${MODULE_PATH}/Diagnostics/InternalDiagnostics/source/*.cpp"
   "${FUSION_ROOT}/autocode_reuse/source/*.cpp"
)

#Add additional stub files to be built if any.
set(STUB_SRC
   ${FUSION_ROOT}/common/source/f360_math_func.cpp
   ${FUSION_ROOT}/common/source/f360_try_to_dealiase_range_rate.cpp
   ${FUSION_ROOT}/common/source/f360_intersections.cpp
   ${FUSION_ROOT}/common/include/f360_find_interval_in_array.h
   ${FUSION_ROOT}/common/source/f360_norm_heading_angle.cpp
   ${FUSION_ROOT}/common/source/f360_uncertainty_propagation.cpp
   ${FUSION_ROOT}/common/source/f360_vcs_long_sorted_dets_support_functions.cpp
   ${FUSION_ROOT}/f360_calibrations.cpp
   ${FUSION_ROOT}/common/source/f360_statistical_tests.cpp
   ${FUSION_ROOT}/common/source/f360_clusters_preprocessing.cpp
   ${FUSION_ROOT}/common/source/f360_kill_cluster.cpp
   ${FUSION_ROOT}/common/source/f360_terminate_clusters.cpp
   ${FUSION_ROOT}/common/source/f360_sorted_clusters_mgmt.cpp
   ${FUSION_ROOT}/common/source/f360_clear_cluster.cpp
   ${FUSION_ROOT}/static_environment/unittest/stubs/f360_timing_stubs.cpp
   ${FUSION_ROOT}/common/source/f360_convert_tcs_posn_to_vcs_posn.cpp
   ${FUSION_ROOT}/common/source/f360_angle.cpp
   ${FUSION_ROOT}/common/source/f360_determine_cross_moving_obj.cpp
   ${FUSION_ROOT}/common/source/f360_object_track.cpp
   ${FUSION_ROOT}/common/source/f360_update_object_reference_point.cpp
   ${FUSION_ROOT}/unittest_stubs/f360_set_variant.cpp
)

unset(UTEST_SRC_LIST)

#
#Loop to generate corresponding template test file if not already there
#
#MESSAGE("Module=" ${MODULE_ROOT})
foreach(filename IN LISTS SRC)
#   MESSAGE("Working with file=" ${filename} )
   get_filename_component(name_without_extension ${filename} NAME_WE)
   set(utest_src ${name_without_extension}_unittest.cpp)
   set(testfile  ${CMAKE_CURRENT_SOURCE_DIR}/${MODULE_ROOT}/unittest/${utest_src})
   if(NOT EXISTS ${testfile})
       #Create a template unittest file
       MESSAGE("${testfile} doesn't exist.")
       add_unittest_template(${name_without_extension} ${MODULE_ROOT}/unittest)
   endif()
   set(UTEST_SRC_LIST
      ${UTEST_SRC_LIST}
      ${MODULE_ROOT}/unittest/${utest_src}
   )
endforeach(filename)


#List all qualification test source files
file(GLOB QTEST_SRC_LIST
  "${MODULE_ROOT}/qualification_testing/qualtest/*_qualtest.cpp"
)
file(GLOB QUTEST_SRC_LIST
  "${MODULE_ROOT}/unittest/*_qualtest_unittest.cpp"
)


add_cppu_test(${MODULE_NAME}_qualtest
   ${QTEST_SRC_LIST}
   ${QUTEST_SRC_LIST}   
   ${SRC}
   ${STUB_SRC}
   ${EXTR_INC_SRC}
)