"""
This test checks for skips and stuck scan indexes in the streams.

This script needs pcap file to process and a lua script from the same build in the Wireshark folder.
PATH environment variable needs to have the path to the wireshark directory

* expectation is that the .lua script generated by the build is in the wireshark plugin folder.
* the code in here to copy a given lua script to the plugins folder isnt able to save to that directory.

The following are the inputs:

[-p pcap]: pcap log file
[-i dest_ip]: Destination IP to help filter messages
[-w wiresharklua]: Wireshare lua script path to use durning testing (NOT WORKING, CANNOT WRITE TO THE PLUGIN FOLDER)

"""
import importlib
import subprocess
import shutil
import os
import sys
import pyshark  # v0.4.5
import argparse
from collections import OrderedDict

ignored_streams = [46]
variant_lookup = {71: "FLR7", 76: "SRR7e", 79: "SRR7p"}


def ReadLogFile(pcap_file_path, desired_destination_ip):
    """Read the given pcap log file."""
    # Create a capture object for reading from the pcap file
    cap = pyshark.FileCapture(pcap_file_path)
    # To store all scan indices for each stream for additional checks
    stream_data = {}
    print("Reading Log: " + pcap_file_path)
    for packet in cap:
        try:
            # Make sure this packet is part of the APTIVUDP protocol layer and the destination IP matches
            if packet.highest_layer == "APTIVUDP" and packet.ip.dst == desired_destination_ip:
                # Extract the necessary fields, if they exist
                source_info = (
                    int(packet["APTIVUDP"].sourceInfo)
                    if hasattr(packet["APTIVUDP"], "sourceInfo")
                    else None
                )
                sensor_id = (
                    int(packet["APTIVUDP"].sensorId)
                    if hasattr(packet["APTIVUDP"], "sensorId")
                    else None
                )
                stream_number = (
                    int(packet["APTIVUDP"].streamNumber)
                    if hasattr(packet["APTIVUDP"], "streamNumber")
                    else None
                )
                # Construct the dynamic field name for scan index
                stream_hdr_scan_index_field_name = f"s{stream_number}_stream_hdr_scan_index"

                scan_index = (
                    getattr(packet["APTIVUDP"], stream_hdr_scan_index_field_name)
                    if hasattr(packet["APTIVUDP"], stream_hdr_scan_index_field_name)
                    else None
                )
                if stream_number not in ignored_streams:
                    # Make sure all information is present
                    if (
                        source_info is not None
                        and sensor_id is not None
                        and stream_number is not None
                    ):
                        # Initialize nested dictionaries if they don't exist yet
                        if source_info not in stream_data:
                            stream_data[source_info] = {}
                        if sensor_id not in stream_data[source_info]:
                            stream_data[source_info][sensor_id] = {}
                        if stream_number not in stream_data[source_info][sensor_id]:
                            stream_data[source_info][sensor_id][stream_number] = []

                        # Append the scan index to the appropriate list
                        if scan_index is not None:
                            stream_data[source_info][sensor_id][stream_number].append(scan_index)

        except Exception as e:
            print(f"Error with packet: {e}")
    # Always close the capture file after processing
    cap.close()
    # Now sort the stream_data dictionary
    for source, sensors in stream_data.items():
        for sensor, streams in sensors.items():
            # Sort streams by their stream number
            sorted_streams = OrderedDict(sorted(streams.items()))
            # Update the dictionary with the sorted streams
            stream_data[source][sensor] = sorted_streams

    return stream_data


def calculate_percentage_of_skips_and_stucks(stream_data):
    """Take the given stream data and calculate skips and stucks."""
    GREEN = "\033[92m"
    RED = "\033[91m"
    ENDC = "\033[0m"  # Reset color
    for source_info, sensors in stream_data.items():
        for sensor_id, streams in sensors.items():
            for stream_number, scan_indices in streams.items():
                scan_indices = [int(index) for index in scan_indices if str(index).isdigit()]

                if len(set(scan_indices)) == 1:
                    uniform_value = scan_indices[0]
                    if uniform_value == 0:
                        print(
                            f"Stream {stream_number:<2} from sensor {sensor_id} (source {variant_lookup[source_info]}) "
                            f"has {RED}100.00%{ENDC} skips (all values are zero), 0 stuck values."
                        )
                    else:
                        print(
                            f"Stream {stream_number:<2} from sensor {sensor_id} (source {variant_lookup[source_info]}) "
                            "has uniform non-zero values, potential stuck value."
                        )
                else:
                    num_skips, num_stucks, total_checks = 0, 0, 0
                    last_index = None

                    for _i, index in enumerate(scan_indices):
                        if last_index is not None:
                            if index == last_index:
                                num_stucks += 1
                            elif index > last_index + 1:
                                num_skips += index - (last_index + 1)
                        last_index = index
                        total_checks += 1

                    percentage_skips = (num_skips / total_checks * 100) if total_checks > 0 else 0
                    percentage_stucks = (
                        (num_stucks / total_checks * 100) if total_checks > 0 else 0
                    )

                    summaryString = f"Stream {stream_number:<2} from sensor {sensor_id} (source {variant_lookup[source_info]}) "

                    if percentage_skips > 0:
                        summaryString += f"has {RED}{num_skips}{ENDC} skips out of {total_checks:<4} packets ({RED}{percentage_skips:.2f}%{ENDC}), "

                    else:
                        summaryString += f"has {GREEN}{num_skips}{ENDC} skips out of {total_checks:<4} packets ({GREEN}{percentage_skips:.2f}%{ENDC}), "

                    if percentage_stucks > 0:
                        summaryString += f"{RED}{num_stucks}{ENDC} stuck values out of {total_checks:<4} packets ({RED}{percentage_stucks:.2f}%{ENDC})."
                    else:
                        summaryString += f"{GREEN}{num_stucks}{ENDC} stuck values out of {total_checks:<4} packets ({GREEN}{percentage_stucks:.2f}%{ENDC})."

                    print(summaryString)


def copy_lua_to_wireshark_folder(source_file):
    """Copy the given Wireshark lua script to the plugins folder."""
    # Get the current user's appdata folder
    appdata_folder = os.getenv("APPDATA")

    source_file = os.path.realpath(source_file)

    # Destination folder for Wireshark plugins
    wireshark_plugins_folder = os.path.join(appdata_folder, "Wireshark", "plugins")

    # Ensure the destination folder exists, if not, create it
    os.makedirs(wireshark_plugins_folder, exist_ok=True)

    # Destination file path
    destination_file = os.path.join(wireshark_plugins_folder, os.path.basename(source_file))

    try:
        # Copy the source file to the Wireshark plugins folder, replacing existing files if any
        shutil.copy2(source_file, destination_file)
        print("Done")
    # eg. src and dest are the same file
    except shutil.Error as e:
        print("Error: %s" % e)
    # eg. source or destination doesn't exist
    except IOError as e:
        print("Error: %s" % e.strerror)


def pretty(d, indent=0):
    """Print out a given dictionary."""
    for key, value in d.items():
        print("\t" * indent + str(key))
        if isinstance(value, dict):
            pretty(value, indent + 1)
        else:
            print("\t" * (indent + 1) + str(value))


def setup():
    """Check that pyshark is installed."""
    # Usage example:
    library_name = "pyshark"  # Change this to the name of the library you want to check
    if not check_and_install_library(library_name):
        print(
            f"{library_name} has been installed. You may need to restart your Python interpreter."
        )


def check_and_install_library(library_name):
    """Install a given python library."""
    try:
        importlib.import_module(library_name)
        return True
    except ImportError:
        print(f"{library_name} is not installed. Installing...")
        subprocess.run(["pip", "install", library_name])
        print(f"{library_name} has been successfully installed.")
        return False


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="APTIV Gen7 Radar Skip Checker", epilog="APTIV Ltd, copyright 2024"
    )
    parser.add_argument("-p", "--pcap", metavar="pcap log file", type=str, required=True)
    parser.add_argument(
        "-i",
        "--dest_ip",
        metavar="Destinaton IP",
        type=str,
        required=False,
        default="192.168.1.40",
    )
    # parser.add_argument(
    #     "-w", "--wiresharklua", metavar="wireshark lua script", type=str, required=False
    # )
    args = parser.parse_args()

    # Check if the provided pcap file exists
    if not os.path.isfile(args.pcap):
        print(f"The specified pcap file does not exist: {args.pcap}")
        sys.exit(1)

    # # Check if the provided Lua script file exists
    # if args.wiresharklua:
    #     if not os.path.isfile(args.wiresharklua):
    #         print(f"The specified Wireshark Lua script file does not exist: {args.wiresharklua}")
    #         sys.exit(1)
    #     else:
    #         copy_lua_to_wireshark_folder(args.wiresharklua)

    setup()

    # Read the log file with the provided pcap file path
    stream_data = ReadLogFile(args.pcap, args.dest_ip)

    calculate_percentage_of_skips_and_stucks(stream_data)
