option(TRACKER_DEVELOPER_MODE "Create virtual targets in IDEs to be able to conveniently work on API files" OFF)

option(TRACKER_PROVIDE_HARMONIZED_INTERFACE "Provide a HarmonizedTrackerInterface target" OFF)
if(TRACKER_PROVIDE_HARMONIZED_INTERFACE)
add_subdirectory(harmonized_tracker_interface harmonized_tracker_interface)
endif()

if(NOT TARGET Tracker_api_constants)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/constants" "${CMAKE_CURRENT_BINARY_DIR}/constants")
endif()
if(NOT TARGET Tracker_api_object_output)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/object" "${CMAKE_CURRENT_BINARY_DIR}/object")
endif()
if(NOT TARGET Tracker_api_vehicle_output)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/vehicle" "${CMAKE_CURRENT_BINARY_DIR}/vehicle")
endif()
if(NOT TARGET Tracker_api_status_output)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/status" "${CMAKE_CURRENT_BINARY_DIR}/status")
endif()
if(NOT TARGET Tracker_api_guardrail_output)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/guardrail" "${CMAKE_CURRENT_BINARY_DIR}/guardrail")
endif()
if(NOT TARGET Tracker_api_detections_output)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/detections" "${CMAKE_CURRENT_BINARY_DIR}/detections")
endif()
if(NOT TARGET Tracker_api_radar_parameter_output)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/radar_parameter" "${CMAKE_CURRENT_BINARY_DIR}/radar_parameter")
endif()
if(NOT TARGET Tracker_api_object_legacy_output)
	add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/object_legacy" "${CMAKE_CURRENT_BINARY_DIR}/Tracker_api_object_legacy_output")
endif()