package(default_visibility = ["//visibility:public"])

cc_library(
    includes = ["."],
    name = "f360",
    srcs = [
        "types/AllObjectsLog.h",
        "types/T360_Types.h",
        "types/VehicleInfoLog.h",
        "types/f360_reuse.h",
        "types/f360_tracker_wrapper.h",
    ],
    hdrs = [
        "types/AllObjectsLog.h",
        "types/T360_Types.h",
        "types/VehicleInfoLog.h",
        "types/f360_reuse.h",
        "types/f360_tracker_wrapper.h",
    ],
    strip_include_prefix = "types",
    # deps = [
    #     "//Math_Library/development:dependencies",
    # ],
)
