import threading
from datetime import date
from os import system
import subprocess
import io
from Bordnet_Tool_spec_widgets import *


def Bordnet_XML(output_path_list, bordnet_json_list, Other_Options_List, Buschannel_Values_List, Execution_Info_values,
                Generate_File_Options_List, CSV_Options_List, XML_Options_List):
    with io.open('bordnet_config.xml', 'w+', encoding='cp1252') as file_pointer:
        file_pointer.write('\n<?xml version="1.0" encoding="UTF-8" ?>')
        file_pointer.write('\n<Configuration>')
        file_pointer.write('\n  <FILEVERSION>9.0</FILEVERSION>')
        file_pointer.write('\n')
        file_pointer.write('\n  <!-- Only JSON File is Supported -->')
        file_pointer.write('\n  <INPUTFILEPATH>' + str(bordnet_json_list[0]) + '</INPUTFILEPATH>')
        file_pointer.write('\n')
        file_pointer.write('\n  <!--XML files will be generated to the user specified Output path -->')
        file_pointer.write('\n  <OUTPUTPATH>' + str(output_path_list[0]) + '</OUTPUTPATH>')
        file_pointer.write('\n')
        file_pointer.write('\n  <!--To define the EXECUTION_TYPE for which Bordnet is executing.')
        file_pointer.write('\n          Options are : SEQUENTIAL, CONTINUOUS -->')
        file_pointer.write('\n  <EXECUTIONTYPE>' + str(Other_Options_List[0]) + '</EXECUTIONTYPE>')
        file_pointer.write('\n')
        file_pointer.write('\n  <!-- Options available are : BMW_SRR5 -->')
        file_pointer.write('\n  <CUSTOMER KEY="' + str(Other_Options_List[1]) + '">')
        file_pointer.write('\n    <INFO KEY="BMW_SRR5">')
        file_pointer.write(
            '\n      <!-- Options available are A_310, A_330, A_350, A_370, A_390, A_410, A_430, A_450, A_470, A_480 -->')
        file_pointer.write('\n      <VERSION>' + str(Other_Options_List[2]) + '</VERSION>')
        file_pointer.write('\n')
        file_pointer.write('\n      <!-- Options available are : BMW_LOW,BMW_MID,BMW_HIGH -->')
        file_pointer.write('\n      <VARIANT KEY="' + str(Other_Options_List[3]) + '">')
        if Other_Options_List[3] == 'BMW_LOW':
            file_pointer.write('\n        <INFO KEY="BMW_LOW">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write(
                '\n			            Options available for variant LOW  - RADAR_PCAN, RADAR_SCAN, RADAR_VCAN, ALL')
            file_pointer.write(
                '\n                  Option ALL to generate XML files for all CAN decoders in that variant -->')
            file_pointer.write('\n          <CANDECODER>' + str(Other_Options_List[4]) + '</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n        <INFO KEY="BMW_MID">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write(
                '\n			            Options available for variant MID  - RADAR_PCAN, ECU_VCAN, ECU_ETHERNET, ALL ')
            file_pointer.write(
                '\n							    Option ALL to generate XML files for all CAN decoders in that variant -->')
            file_pointer.write('\n          <CANDECODER>ECU_VCAN</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n        <INFO KEY="BMW_HIGH">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write('\n			           Options available for variant HIGH - RADAR_B_PIL -->')
            file_pointer.write('\n          <CANDECODER>RADAR_B_PIL</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n      </VARIANT>')
            file_pointer.write('\n    </INFO>')
        elif Other_Options_List[3] == 'BMW_MID':
            file_pointer.write('\n        <INFO KEY="BMW_LOW">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write(
                '\n			            Options available for variant LOW  - RADAR_PCAN, RADAR_SCAN, RADAR_VCAN, ALL')
            file_pointer.write(
                '\n                  Option ALL to generate XML files for all CAN decoders in that variant -->')
            file_pointer.write('\n          <CANDECODER>RADAR_SCAN</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n        <INFO KEY="BMW_MID">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write(
                '\n			            Options available for variant MID  - RADAR_PCAN, ECU_VCAN, ECU_ETHERNET, ALL ')
            file_pointer.write(
                '\n							    Option ALL to generate XML files for all CAN decoders in that variant -->')
            file_pointer.write('\n          <CANDECODER>' + str(Other_Options_List[4]) + '</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n        <INFO KEY="BMW_HIGH">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write('\n			           Options available for variant HIGH - RADAR_B_PIL -->')
            file_pointer.write('\n          <CANDECODER>RADAR_B_PIL</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n      </VARIANT>')
            file_pointer.write('\n    </INFO>')
        elif Other_Options_List[3] == 'BMW_HIGH':
            file_pointer.write('\n        <INFO KEY="BMW_LOW">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write(
                '\n			            Options available for variant LOW  - RADAR_PCAN, RADAR_SCAN, RADAR_VCAN, ALL')
            file_pointer.write(
                '\n                  Option ALL to generate XML files for all CAN decoders in that variant -->')
            file_pointer.write('\n          <CANDECODER>RADAR_SCAN</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n        <INFO KEY="BMW_MID">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write(
                '\n			            Options available for variant MID  - RADAR_PCAN, ECU_VCAN, ECU_ETHERNET, ALL ')
            file_pointer.write(
                '\n							    Option ALL to generate XML files for all CAN decoders in that variant -->')
            file_pointer.write('\n          <CANDECODER>ECU_VCAN</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n        <INFO KEY="BMW_HIGH">')
            file_pointer.write('\n          <!-- To define the CAN decoder for which the Bordnet is Executed. ')
            file_pointer.write('\n			           Options available for variant HIGH - RADAR_B_PIL -->')
            file_pointer.write('\n          <CANDECODER>' + str(Other_Options_List[4]) + '</CANDECODER>')
            file_pointer.write('\n        </INFO>')
            file_pointer.write('\n      </VARIANT>')
            file_pointer.write('\n    </INFO>')
        file_pointer.write('\n  </CUSTOMER>')
        file_pointer.write('\n')
        file_pointer.write('\n  <!-- To define the LOG_TYPE for which the Bordnet is Executed. ')
        file_pointer.write('\n			    Options available are : MAGNA_X2E, BMW_VIGEM ,BMW_CANOE -->')
        file_pointer.write('\n  <LOGTYPE KEY="' + str(Buschannel_Values_List[0]) + '">')
        if Buschannel_Values_List[0] == "BMW_CANOE":
            if Buschannel_Values_List[1] == "USER":
                file_pointer.write('\n    <INFO KEY="BMW_CANOE">')
                file_pointer.write('\n      <!--Options available are :')
                file_pointer.write(
                    '\n					  DEFAULT - Default channel value from attribte Default will be used')
                file_pointer.write('\n					  USER    - User defined channel value will be used -->')
                file_pointer.write('\n      <BUSCHANNEL TYPE="USER">')
                file_pointer.write('\n        <SCANLOW DEFAULT="4">' + str(Buschannel_Values_List[2]) + '</SCANLOW>')
                file_pointer.write('\n        <BPILLEFT DEFAULT="5">' + str(Buschannel_Values_List[3]) + '</BPILLEFT>')
                file_pointer.write(
                    '\n        <BPILRIGHT DEFAULT="6">' + str(Buschannel_Values_List[4]) + '</BPILRIGHT>')
                file_pointer.write(
                    '\n        <ECUETHERNET DEFAULT="12">' + str(Buschannel_Values_List[5]) + '</ECUETHERNET>')
                file_pointer.write(
                    '\n		<PCANLOWREAR DEFAULT="2">' + str(Buschannel_Values_List[6]) + '</PCANLOWREAR>')
                file_pointer.write(
                    '\n		<PCANLOWFRONT DEFAULT="2">' + str(Buschannel_Values_List[7]) + '</PCANLOWFRONT>')
                file_pointer.write(
                    '\n		<PCANMIDRL DEFAULT="2">' + str(Buschannel_Values_List[8]) + '</PCANMIDRL>')
                file_pointer.write(
                    '\n		<PCANMIDRR DEFAULT="2">' + str(Buschannel_Values_List[9]) + '</PCANMIDRR>')
                file_pointer.write(
                    '\n		<PCANMIDFR DEFAULT="2">' + str(Buschannel_Values_List[10]) + '</PCANMIDFR>')
                file_pointer.write(
                    '\n		<PCANMIDFL DEFAULT="2">' + str(Buschannel_Values_List[11]) + '</PCANMIDFL>')
                file_pointer.write('\n		<VCANLOW DEFAULT="2">' + str(Buschannel_Values_List[12]) + '</VCANLOW>')
                file_pointer.write('\n		<VCANECU DEFAULT="2">' + str(Buschannel_Values_List[13]) + '</VCANECU>')
                file_pointer.write('\n      </BUSCHANNEL>')
                file_pointer.write('\n    </INFO>')
                file_pointer.write('\n    <INFO KEY="MAGNA_X2E">')
                file_pointer.write('\n    </INFO>')
                file_pointer.write('\n    <INFO KEY="BMW_VIGEM">')
                file_pointer.write('\n    </INFO>')
                file_pointer.write('\n  </LOGTYPE>')
                file_pointer.write('\n')
            elif Buschannel_Values_List[1] == "DEFAULT":
                file_pointer.write('\n    <INFO KEY="BMW_CANOE">')
                file_pointer.write('\n      <!--Options available are :')
                file_pointer.write(
                    '\n					  DEFAULT - Default channel value from attribte Default will be used')
                file_pointer.write('\n					  USER    - User defined channel value will be used -->')
                file_pointer.write('\n      <BUSCHANNEL TYPE="DEFAULT">')
                file_pointer.write('\n        <SCANLOW DEFAULT="4">8</SCANLOW>')
                file_pointer.write('\n        <BPILLEFT DEFAULT="5">10</BPILLEFT>')
                file_pointer.write('\n        <BPILRIGHT DEFAULT="6">11</BPILRIGHT>')
                file_pointer.write('\n        <ECUETHERNET DEFAULT="12">1</ECUETHERNET>')
                file_pointer.write('\n		<PCANLOWREAR DEFAULT="2">2</PCANLOWREAR>')
                file_pointer.write('\n		<PCANLOWFRONT DEFAULT="2">1</PCANLOWFRONT>')
                file_pointer.write('\n		<PCANMIDRL DEFAULT="2">4</PCANMIDRL>')
                file_pointer.write('\n		<PCANMIDRR DEFAULT="2">5</PCANMIDRR>')
                file_pointer.write('\n		<PCANMIDFR DEFAULT="2">7</PCANMIDFR>')
                file_pointer.write('\n		<PCANMIDFL DEFAULT="2">6</PCANMIDFL>')
                file_pointer.write('\n		<VCANLOW DEFAULT="2">9</VCANLOW>')
                file_pointer.write('\n		<VCANECU DEFAULT="2">9</VCANECU>')
                file_pointer.write('\n      </BUSCHANNEL>')
                file_pointer.write('\n    </INFO>')
                file_pointer.write('\n    <INFO KEY="MAGNA_X2E">')
                file_pointer.write('\n    </INFO>')
                file_pointer.write('\n    <INFO KEY="BMW_VIGEM">')
                file_pointer.write('\n    </INFO>')
                file_pointer.write('\n  </LOGTYPE>')
                file_pointer.write('\n')
        elif Buschannel_Values_List[0] == "MAGNA_X2E" or "BMW_VIGEM":
            file_pointer.write('\n    <INFO KEY="BMW_CANOE">')
            file_pointer.write('\n      <!--Options available are :')
            file_pointer.write(
                '\n					  DEFAULT - Default channel value from attribte Default will be used')
            file_pointer.write('\n					  USER    - User defined channel value will be used -->')
            file_pointer.write('\n      <BUSCHANNEL TYPE="USER">')
            file_pointer.write('\n        <SCANLOW DEFAULT="4">8</SCANLOW>')
            file_pointer.write('\n        <BPILLEFT DEFAULT="5">10</BPILLEFT>')
            file_pointer.write('\n        <BPILRIGHT DEFAULT="6">11</BPILRIGHT>')
            file_pointer.write('\n        <ECUETHERNET DEFAULT="12">1</ECUETHERNET>')
            file_pointer.write('\n		<PCANLOWREAR DEFAULT="2">2</PCANLOWREAR>')
            file_pointer.write('\n		<PCANLOWFRONT DEFAULT="2">1</PCANLOWFRONT>')
            file_pointer.write('\n		<PCANMIDRL DEFAULT="2">4</PCANMIDRL>')
            file_pointer.write('\n		<PCANMIDRR DEFAULT="2">5</PCANMIDRR>')
            file_pointer.write('\n		<PCANMIDFR DEFAULT="2">7</PCANMIDFR>')
            file_pointer.write('\n		<PCANMIDFL DEFAULT="2">6</PCANMIDFL>')
            file_pointer.write('\n		<VCANLOW DEFAULT="2">9</VCANLOW>')
            file_pointer.write('\n		<VCANECU DEFAULT="2">9</VCANECU>')
            file_pointer.write('\n      </BUSCHANNEL>')
            file_pointer.write('\n    </INFO>')
            file_pointer.write('\n    <INFO KEY="MAGNA_X2E">')
            file_pointer.write('\n    </INFO>')
            file_pointer.write('\n    <INFO KEY="BMW_VIGEM">')
            file_pointer.write('\n    </INFO>')
            file_pointer.write('\n  </LOGTYPE>')
            file_pointer.write('\n')
        file_pointer.write('\n  <EXECUTIONINFO>')
        file_pointer.write('\n')
        file_pointer.write('\n    <!--Options available are :')
        file_pointer.write('\n          1 to Enable Old XML print')
        file_pointer.write('\n		      0 to Disable Old XML print-->')
        file_pointer.write('\n    <OLDXMLPRINT>' + str(Execution_Info_values[0]) + '</OLDXMLPRINT>')
        file_pointer.write('\n')
        file_pointer.write('\n    <!-- To Enable Timestamp Decoding in milisecond. ')
        file_pointer.write('\n			      1 - use Timestamp logic for Decoding')
        file_pointer.write('\n			      0 - Not to use Timestamp logic for Decoding-->')
        file_pointer.write('\n    <TIMESTAMPDECODING>')
        file_pointer.write('\n      <SCAN timestampinms="40">' + str(Execution_Info_values[1]) + '</SCAN>')
        file_pointer.write('\n      <SOMIP timestampinms="10">' + str(Execution_Info_values[2]) + '</SOMIP>')
        file_pointer.write('\n      <VCANBPIL timestampinms="15">' + str(Execution_Info_values[3]) + '</VCANBPIL>')
        file_pointer.write('\n      <VCANECU timestampinms="2000">' + str(Execution_Info_values[4]) + '</VCANECU>')
        file_pointer.write('\n      <VCANLOW timestampinms="14">' + str(Execution_Info_values[5]) + '</VCANLOW>')
        file_pointer.write('\n      <PCAN timestampinms="25">' + str(Execution_Info_values[6]) + '</PCAN>')
        file_pointer.write('\n    </TIMESTAMPDECODING>')
        file_pointer.write('\n')
        file_pointer.write('\n    <!--Options available are :')
        file_pointer.write('\n          1 to Enable BPIL sorting logic')
        file_pointer.write('\n		      0 to Disable BPIL sorting logic-->')
        file_pointer.write('\n    <SORT>')
        if Execution_Info_values[7] == "SCAN":
            file_pointer.write('\n      <SCAN>1</SCAN>')
            file_pointer.write('\n      <BPIL>0</BPIL>')
        elif Execution_Info_values[7] == "BPIL":
            file_pointer.write('\n      <SCAN>0</SCAN>')
            file_pointer.write('\n      <BPIL>1</BPIL>')
        else:
            file_pointer.write('\n      <SCAN>0</SCAN>')
            file_pointer.write('\n      <BPIL>0</BPIL>')

        file_pointer.write('\n    </SORT>')
        file_pointer.write('\n')
        file_pointer.write('\n    <GENERATEFILE>')
        file_pointer.write('\n')
        file_pointer.write('\n      <!-- XML Configuration Control for CAN ID and Timestamp CSV & TXT traces -   ')
        file_pointer.write('\n					    1 - GENERATE CSV & TXT Trace containing Diagnostic Information')
        file_pointer.write(
            '\n					    0 - SUPPRESS CSV & TXT Trace containing Diagnostic Information -->')
        file_pointer.write(
            '\n      <TIMESTAMPDIAGNOSTICS>' + str(Generate_File_Options_List[0]) + '</TIMESTAMPDIAGNOSTICS>')
        file_pointer.write('\n')
        file_pointer.write('\n      <!-- XML Configuration Control for CAN ID and Timestamp XML traces -   ')
        file_pointer.write('\n					    1 - GENERATE XML Trace containing only CAN Ids and Timestamps')
        file_pointer.write(
            '\n					    0 - SUPPRESS XML Trace containing only CAN Ids and Timestamps -->')
        file_pointer.write('\n      <CANIDTIMESTAMP>' + str(Generate_File_Options_List[1]) + '</CANIDTIMESTAMP>')
        file_pointer.write('\n')
        file_pointer.write('\n      <!-- XML Configuration Control for CAN ID and Timestamp XML traces -   ')
        file_pointer.write('\n					    1 - GENERATE XML Trace containing Diagnostic Information')
        file_pointer.write('\n					    0 - SUPPRESS XML Trace containing Diagnostic Information -->')
        file_pointer.write('\n      <DIAGNOSTICS>' + str(Generate_File_Options_List[2]) + '</DIAGNOSTICS>')
        file_pointer.write('\n')
        file_pointer.write('\n')
        file_pointer.write(
            '\n      <!-- Based on RESIM Framework JSON file, Timing Profile will be created. Options are :')
        file_pointer.write('\n              1 to Enable CSV file generation for timing profile')
        file_pointer.write('\n	            0 to Disable CSV file generation for timing profile -->')
        file_pointer.write(
            '\n      <FRAMEWORKTIMINGPROFILE>' + str(Generate_File_Options_List[3]) + '</FRAMEWORKTIMINGPROFILE>')
        file_pointer.write('\n')
        file_pointer.write('\n      <!-- This tag should be enabled to Create CSV -')
        file_pointer.write('\n			        1 to Enable CSV file to generate SOMEIP decoded messages')
        file_pointer.write('\n			        0 to Disable CSV file to generate SOMEIP decoded messages -->')
        file_pointer.write('\n')
        file_pointer.write('\n      <!--Only for SOMIP -->')
        file_pointer.write('\n      <CREATECSV>')
        file_pointer.write('\n        <OBJECTLIST>'+str(CSV_Options_List[0])+'</OBJECTLIST>')
        file_pointer.write('\n        <DETECTIONRR>'+str(CSV_Options_List[1])+'</DETECTIONRR>')
        file_pointer.write('\n        <DETECTIONRL>'+str(CSV_Options_List[2])+'</DETECTIONRL>')
        file_pointer.write('\n        <DETECTIONFR>'+str(CSV_Options_List[3])+'</DETECTIONFR>')
        file_pointer.write('\n        <DETECTIONFL>'+str(CSV_Options_List[4])+'</DETECTIONFL>')
        file_pointer.write('\n        <DETECTIONBPILLEFT>'+str(CSV_Options_List[5])+'</DETECTIONBPILLEFT>')
        file_pointer.write('\n        <DETECTIONBPILRIGHT>'+str(CSV_Options_List[6])+'</DETECTIONBPILRIGHT>')
        file_pointer.write('\n        <VCANALERTSHR>'+str(CSV_Options_List[7])+'</VCANALERTSHR>')
        file_pointer.write('\n        <VCANALERTSVL>'+str(CSV_Options_List[8])+'</VCANALERTSVL>')
        file_pointer.write('\n      </CREATECSV>')
        file_pointer.write('\n')
        file_pointer.write('\n      <!--Options available are :')
        file_pointer.write('\n              1 to Enable XML file to generate SOMEIP decoded messages')
        file_pointer.write('\n		          0 to Disable XML file to generate SOMEIP decoded messages -->')
        file_pointer.write('\n      <CREATEXML>')
        file_pointer.write('\n        <OBJECTLIST>'+str(XML_Options_List[0])+'</OBJECTLIST>')
        file_pointer.write('\n        <DETECTIONRR>'+str(XML_Options_List[1])+'</DETECTIONRR>')
        file_pointer.write('\n        <DETECTIONRL>'+str(XML_Options_List[2])+'</DETECTIONRL>')
        file_pointer.write('\n        <DETECTIONFR>'+str(XML_Options_List[3])+'</DETECTIONFR>')
        file_pointer.write('\n        <DETECTIONFL>'+str(XML_Options_List[4])+'</DETECTIONFL>')
        file_pointer.write('\n        <FREESPACE>'+str(XML_Options_List[5])+'</FREESPACE>')
        file_pointer.write('\n        <RESTMESSAGE>'+str(XML_Options_List[6])+'</RESTMESSAGE>')
        file_pointer.write('\n      </CREATEXML>')
        file_pointer.write('\n    </GENERATEFILE>')
        file_pointer.write('\n	')
        file_pointer.write('\n	<!--create CSV file for PCAN :')
        file_pointer.write('\n		 1 to Enable CSV file to generate PCAN decoded messages')
        file_pointer.write('\n		         0 to Disable CSV file to generate PCAN decoded messages -->')
        file_pointer.write('\n		')
        file_pointer.write('\n		<PCAN_CSV>' + str(Execution_Info_values[8]) + '</PCAN_CSV>')
        file_pointer.write('\n	')
        file_pointer.write('\n	')
        file_pointer.write("\n	<!-- To Decode SCAN Input and Output CANID's -->")
        file_pointer.write('\n	')
        file_pointer.write('\n	 <!-- A390 -> INPUTCANID  : 1914	')
        file_pointer.write('\n							    	')
        file_pointer.write('\n				  OUTPUTCANID :  	 	 ')
        file_pointer.write('\n							    	     ')
        file_pointer.write('\n						 ')
        file_pointer.write('\n	 <!-- A370 -> INPUTCANID  : 1914	')
        file_pointer.write('\n						           ')
        file_pointer.write('\n				  OUTPUTCANID :  ')
        file_pointer.write('\n						           ')
        file_pointer.write('\n						 ')
        file_pointer.write('\n	 <!-- A350 -> INPUTCANID  : 1914	')
        file_pointer.write('\n							       ')
        file_pointer.write('\n				  OUTPUTCANID :     ')
        file_pointer.write('\n						           ')
        file_pointer.write('\n						 ')
        file_pointer.write('\n	 <!-- A310 -> INPUTCANID  : 1900	')
        file_pointer.write('\n						           ')
        file_pointer.write('\n				  OUTPUTCANID : 1900    ')
        file_pointer.write('\n						           -->')
        file_pointer.write('\n	')
        file_pointer.write('\n	<DECODESCANCANID>')
        file_pointer.write('\n		<SCAN>')
        if Other_Options_List[2] == 'A_310' or "A_410" or "A_430" or "A_450" or "A_470" or "A_480":
            file_pointer.write('\n			<INPUTCANID>1900</INPUTCANID>')
            file_pointer.write('\n			<OUTPUTCANID>1900</OUTPUTCANID>')
        elif Other_Options_List[2] == 'A_350' or 'A_370' or 'A_390':
            file_pointer.write('\n			<INPUTCANID>1914</INPUTCANID>')
            file_pointer.write('\n			<OUTPUTCANID></OUTPUTCANID>')
        else:
            file_pointer.write('\n			<INPUTCANID>1900</INPUTCANID>')
            file_pointer.write('\n			<OUTPUTCANID>1900</OUTPUTCANID>')
        file_pointer.write('\n		</SCAN>')
        file_pointer.write('\n	</DECODESCANCANID>')
        file_pointer.write('\n')
        file_pointer.write("\n<!-- To Decode BPillar Input and Output CANID's -->")
        file_pointer.write('\n	 <!-- A390 -> INPUTCANID  : 	1600 Left')
        file_pointer.write('\n							  :  	1500 Right')
        file_pointer.write('\n				  OUTPUTCANID :  	1338 Left')
        file_pointer.write('\n							  :  	1138 Right-->')
        file_pointer.write('\n						 ')
        file_pointer.write('\n	 <!-- A370 -> INPUTCANID  : 	1600 Left')
        file_pointer.write('\n						      :     1500 Right')
        file_pointer.write('\n				  OUTPUTCANID :     1338 Left')
        file_pointer.write('\n						      :     1138 Right-->')
        file_pointer.write('\n						 ')
        file_pointer.write('\n	 <!-- A350 -> INPUTCANID  : 	1220 Left')
        file_pointer.write('\n							  :     1138 Right')
        file_pointer.write('\n				  OUTPUTCANID :     1600 Left')
        file_pointer.write('\n						      :     1500 Right-->')
        file_pointer.write('\n						 ')
        file_pointer.write('\n	 <!-- A310 -> INPUTCANID  : 	1330 Left')
        file_pointer.write('\n						      :     1130 Right')
        file_pointer.write('\n				  OUTPUTCANID :     1338 Left')
        file_pointer.write('\n						      :     1138 Right-->')
        file_pointer.write('\n    <DECODEBPILLARCANID>')
        file_pointer.write('\n      <BUSSPECLEFT>')
        if Other_Options_List[2] == 'A_310':
            file_pointer.write('\n        <INPUTCANID>1330</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1338</OUTPUTCANID>')
            file_pointer.write('\n      </BUSSPECLEFT>')
            file_pointer.write('\n      <BUSSPECRIGHT>')
            file_pointer.write('\n        <INPUTCANID>1130</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1138</OUTPUTCANID>')
        elif Other_Options_List[2] == 'A_350':
            file_pointer.write('\n        <INPUTCANID>1220</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1600</OUTPUTCANID>')
            file_pointer.write('\n      </BUSSPECLEFT>')
            file_pointer.write('\n      <BUSSPECRIGHT>')
            file_pointer.write('\n        <INPUTCANID>1138</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1500</OUTPUTCANID>')
        elif Other_Options_List[2] == 'A_370':
            file_pointer.write('\n        <INPUTCANID>1600</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1338</OUTPUTCANID>')
            file_pointer.write('\n      </BUSSPECLEFT>')
            file_pointer.write('\n      <BUSSPECRIGHT>')
            file_pointer.write('\n        <INPUTCANID>1500</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1138</OUTPUTCANID>')
        elif Other_Options_List[2] == 'A_390':
            file_pointer.write('\n        <INPUTCANID>1600</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1338</OUTPUTCANID>')
            file_pointer.write('\n      </BUSSPECLEFT>')
            file_pointer.write('\n      <BUSSPECRIGHT>')
            file_pointer.write('\n        <INPUTCANID>1500</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1138</OUTPUTCANID>')
        else:
            file_pointer.write('\n        <INPUTCANID>1600</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1338</OUTPUTCANID>')
            file_pointer.write('\n      </BUSSPECLEFT>')
            file_pointer.write('\n      <BUSSPECRIGHT>')
            file_pointer.write('\n        <INPUTCANID>1500</INPUTCANID>')
            file_pointer.write('\n        <OUTPUTCANID>1138</OUTPUTCANID>')
        file_pointer.write('\n      </BUSSPECRIGHT>')
        file_pointer.write('\n    </DECODEBPILLARCANID>')
        file_pointer.write('\n  </EXECUTIONINFO>')
        file_pointer.write('\n</Configuration>')
        file_pointer.write('\n')
        file_pointer.write('\n')

