from MUDP_Tool_spec_widgets import *
import threading
from datetime import date
from os import system
from tkinter import scrolledtext
import subprocess
from main_interface import *
from SIL_TooL_spec_widgets import *


# global exe_command
# exe_command = None

global output_text_sil
global text_box_sil_label


def Write_SIL_TOOL_XML(Global_var, SIL_Data, SIL_ENET_data, Sensor_and_ECU):
    with open('SIL_Engine_Config_v_2p9.xml', 'w+', encoding='cp1252') as file_pointer:
        file_pointer.write('<?xml version="1.0" encoding="UTF-8" ?> ')
        file_pointer.write("\n  <!-- SIL SRR5 Configuration XML version -->")
        file_pointer.write("\n<SIL_ENGINE_Configuration>")
        file_pointer.write("\n  <!-- SIL SRR5 Configuration XML version -->")
        file_pointer.write("\n  <!-- Version X.Y where:")
        file_pointer.write("\n		          X - major change where some new parameters were added")
        file_pointer.write("\n		          Y - minor change with no influence on parsing (comment or value change) -->	")
        file_pointer.write("\n	      <SIL_ENGINE_Config_XML_Version>2.9</SIL_ENGINE_Config_XML_Version>")
        file_pointer.write("\n")
        file_pointer.write("\n	<!-- To define the CUSTOMER for which the RESIM is Executed. ")
        file_pointer.write("\n           	   Options available are: SRR5: RNA_SUV, RNA_CDV, GEELY_SRR5, GEELY_SRR5_INTERNAL ,CHANGAN_SRR5, SGM_358_SRR5,GWM_SRR5, BMW_LOW, BMW_MID, BMW_HIGH, BMW_MID_LOW, MAN_SRR3 -->")
        file_pointer.write("\n	<Customer_Name>" + Global_var.Customer_Name + "</Customer_Name>")
        file_pointer.write("\n")
        file_pointer.write("\n	<!-- Resim output path selection. Options are SAME_AS_INPUT or NEW_OUTPUT_PATH -->")
        file_pointer.write("\n	         If resim output path selection is NEW_OUTPUT_PATH use Output_Path_Location tag to enter valid folder path-->")
        file_pointer.write("\n	    <RESIM_OUTPUT_PATH>")
        file_pointer.write("\n")
        file_pointer.write("\n	        <Output_Path_Options>" + str(SIL_Data.output_Path_options) + "</Output_Path_Options>")
        file_pointer.write("\n	        <Output_Path_Location>" + str(SIL_Data.output_Path_Location) + "</Output_Path_Location>")
        file_pointer.write("\n	    </RESIM_OUTPUT_PATH>")
        file_pointer.write("\n	<!--Additional DEBUG Data can be enabled using the EB Configuration file")
        file_pointer.write("\n	    Options are NONE or Name of the EB config .xml file including full File Path")
        file_pointer.write("\n	    Read independent of options selected in RESIM_Execution_User -->")
        file_pointer.write("\n	<EMBEDDED_LIB_CONFIG_PATH>")
        file_pointer.write("\n	    <SENSOR_CONFIG>" + str(SIL_Data.Sensor_Config) + "</SENSOR_CONFIG>")
        file_pointer.write("\n	    <RECU_CONFIG>" + str(SIL_Data.RECU_Config) + "</RECU_CONFIG>")
        file_pointer.write("\n	</EMBEDDED_LIB_CONFIG_PATH>")
        file_pointer.write("\n	<!-- Output Mode Options available are -")
        file_pointer.write("\n	    SINGLE_DVSU_OUTPUT: Single dvsu enabled to handle Single input DVSU file , proceed resim with Single dvsu file")
        file_pointer.write("\n	    FOUR_DVSU_OUTPUT : FOUR dvsu enabled to handle four  input DVSU file ,proceed  resim with 4 dvsu's file.(default option)")
        file_pointer.write("\n	    ORCAS_MDF4_OUTPUT: To Handle ORCAS Logs")
        file_pointer.write("\n	    CANAPE_MDF4_OUTPUT: To Handle Canape Logs")
        file_pointer.write("\n	    VIGEM_MDF4_OUTPUT :  VIGEM_MDF4_DVSU_ENABLED to handle MDF4 file proceed resim with mdf4 file")
        file_pointer.write("\n	    VIGEM_VPCAP: To handle ViGEM VPCAP logs")
        file_pointer.write("\n	    X2E_VECTOR_MDF4: To handle X2E / Magna Logs")
        file_pointer.write("\n	    CANOE_VECTOR_MF4: To handle CANOE Logs -->")
        file_pointer.write("\n	    <RESIM_OUTPUT_FILE_FORMAT>")
        file_pointer.write("\n	        <ORCAS_MDF4>" + str(SIL_Data.ORCAS_MDF4) + "</ORCAS_MDF4>")
        file_pointer.write("\n	        <CANAPE_MDF4>" + str(SIL_Data.CANAPE_MDF4) + "</CANAPE_MDF4>")
        file_pointer.write("\n	        <VIGEM_VECTOR_MDF4>" + str(SIL_Data.VIGEM_VECTOR_MDF4) + "</VIGEM_VECTOR_MDF4>")
        file_pointer.write("\n	        <VIGEM_VPCAP>" + str(SIL_Data.VIGEM_VPCAP) + "</VIGEM_VPCAP>")
        file_pointer.write("\n	        <VIGEM_CCA_MDF4>" + str(SIL_Data.VIGEM_CCA_MDF4) + "</VIGEM_CCA_MDF4>")
        file_pointer.write("\n	        <X2E_VECTOR_MDF4>" + str(SIL_Data.X2E_VECTOR_MDF4) + "</X2E_VECTOR_MDF4>")
        file_pointer.write("\n	        <CANOE_VECTOR_MF4>" + str(SIL_Data.CANOE_VECTOR_MF4) + "</CANOE_VECTOR_MF4>")
        file_pointer.write("\n	    </RESIM_OUTPUT_FILE_FORMAT>")
        file_pointer.write("\n  <!-- Sensor selection values:")
        file_pointer.write("\n        1: Resim is executed for that Sensor Position")
        file_pointer.write("\n	0: Resim is not executed for that Sensor Position -->")
        file_pointer.write("\n	<SENSOR_STATUS>")
        file_pointer.write("\n		    <REAR_LEFT>" + str(Sensor_and_ECU.REAR_LEFT.get()) + "</REAR_LEFT>")
        file_pointer.write("\n		    <REAR_RIGHT>" + str(Sensor_and_ECU.REAR_RIGHT.get()) + "</REAR_RIGHT>")
        file_pointer.write("\n		    <FRONT_RIGHT>" + str(Sensor_and_ECU.FRONT_RIGHT.get()) + "</FRONT_RIGHT>")
        file_pointer.write("\n		    <FRONT_LEFT>" + str(Sensor_and_ECU.FRONT_LEFT.get()) + "</FRONT_LEFT>")
        file_pointer.write("\n		    <FRONT_CENTRE>" + str(Sensor_and_ECU.FRONT_CENTRE.get()) + "</FRONT_CENTRE>")
        file_pointer.write("\n		    <BP_RIGHT>" + str(Sensor_and_ECU.BP_RIGHT.get()) + "</BP_RIGHT>")
        file_pointer.write("\n		    <BP_LEFT>" + str(Sensor_and_ECU.BP_LEFT.get()) + "</BP_LEFT>")
        file_pointer.write("\n		    <RADAR_ECU>" + str(Sensor_and_ECU.RADAR_ECU.get()) + "</RADAR_ECU>")
        file_pointer.write("\n	</SENSOR_STATUS>")
        file_pointer.write("\n")
        file_pointer.write("\n <OUTPUT_FILE_FOLDER>")
        file_pointer.write("\n		<!-- CUSTOMER_CAN_OUTPUT_ENABLE - BMW CANFD Folder BN_CALIFR to generate FAS CAN & SENSOR CAN Output Files.")
        file_pointer.write("\n				1:  To enable the output BN_CALIFR folder creation and CAN data written to  CALIFR files")
        file_pointer.write("\n				0: To disable the BN_CALIFR folder creation-->")
        file_pointer.write("\n 	<CUSTOMER_CAN_OUTPUT_ENABLE>" + str(SIL_Data.CAN_Output) + "</CUSTOMER_CAN_OUTPUT_ENABLE>")
        file_pointer.write("\n		<!-- APTIV_INTERNAL_OUTPUT_ENABLE - To enable or disable the RAW_DEBUG_UDP Data files ")
        file_pointer.write("\n				1.  to enable the output SRR_RAW_DEBUG folder creation and APTIV raw debug UDP data written to SRR_DEBUG files")
        file_pointer.write("\n				0.  disable the creation of SRR_RAW_DEBUG folder-->")
        file_pointer.write("\n	<APTIV_INTERNAL_OUTPUT_ENABLE>" + str(SIL_Data.APTIV_Internal_Output) + "</APTIV_INTERNAL_OUTPUT_ENABLE>")
        file_pointer.write("\n </OUTPUT_FILE_FOLDER>")
        file_pointer.write("\n")
        file_pointer.write("\n  <!-- CDC_WRITE_OUTPUT_ENABLE - To write CDC data to output Files.")
        file_pointer.write("\n									  1:  To enable the option of writing CDC data to resimulated output UDP files")
        file_pointer.write("\n					                  0:  To Disable the writing of CDC data to resimulated output UDP files-->")
        file_pointer.write("\n	<CDC_WRITE_OUTPUT_ENABLE>" + str(SIL_Data.CDC_Write_output) + "</CDC_WRITE_OUTPUT_ENABLE>")
        file_pointer.write("\n")
        file_pointer.write("\n <TRACKER_INTERNAL_PERIODIC_INJECTION>")
        file_pointer.write("\n <!-- GDSR_F360_PERIODIC_INJECTION_ENABLE - To inject periodic injection of GDSR for the customers BMW_LOW and BMW_HIGH and F360 injection for radar ecu")
        file_pointer.write("\n				1:  To enable the periodic injection of GDSR/F360 tracker internals + init  during resimulation")
        file_pointer.write("\n				0:  To disable the periodic injection of GDSR/F360 tracker internals + init during resimulation -->")
        file_pointer.write("\n	<GDSR_F360_INIT_INJECTION_ENABLE>" + str(SIL_Data.GDSR_Init_Status) + "</GDSR_F360_INIT_INJECTION_ENABLE>")
        file_pointer.write("\n <!-- GDSR_F360_INIT_INJECTION_ENABLE - To inject f360/gdsr injection at the init API")
        file_pointer.write("\n       		1:  To enable the injection of gdsr/F360 at init during resimulation")
        file_pointer.write("\n				0:  To disable the injection of gdsr/F360 at init during resimulation -->")
        file_pointer.write("\n	<GDSR_F360_PERIODIC_INJECTION_ENABLE>" + str(SIL_Data.GDSR_Periodic_Status) + "</GDSR_F360_PERIODIC_INJECTION_ENABLE>")
        file_pointer.write("\n </TRACKER_INTERNAL_PERIODIC_INJECTION>")
        file_pointer.write("\n")
        file_pointer.write("\n  <!-- SIL_Injection Mode  -")
        file_pointer.write("\n		VEHICLE_EXPEDITION_FILE - SIL Input is vehicle collected Files")
        file_pointer.write("\n													(Internally RESIM uses SIL_SRR3_UDP_Frame_process API)")
        file_pointer.write("\n	    VIRTUAL_SIMULATION_FILE - SIL Input is Virtual Simulation Tools IPG/VTD/DSPACE ASM created Virtual simulation files.")
        file_pointer.write("\n													(Internally RESIM uses SIL_SRR_VV_Frame_process API)")
        file_pointer.write("\n	    VIRTUAL_SIMULATION_LIVE - SIL Input is Live streams from Virtual Simulation tools IPG/VTD/DSPACE ASM.")
        file_pointer.write("\n                                                  (Internally RESIM uses SIL_SRR_VV_Frame_process API)-->")
        file_pointer.write("\n	<SIL_INJECTION_MODE>" + str(SIL_Data.SIL_Injection_Mode) + "</SIL_INJECTION_MODE>")
        file_pointer.write("\n")
        file_pointer.write("\n  <!-- LOG REPLAY mode selection: User shall provide the list of filenames the RESIM should execute in the Input_Log.txt file")
        file_pointer.write("\n		Sequential_FILE_Input -  RESIM shall execute in a sequential order of the Filenames provided")
        file_pointer.write("\n								 Ensuring that each input file is processed uniquely by resetting the memory after each file.")
        file_pointer.write("\n								 Hence history is not maintained between the input files.")
        file_pointer.write("\n	    Continuous_FILE_Input -  RESIM shall execute in a sequential order of the Filenames provided")
        file_pointer.write("\n	                             Ensuring that each input file is processed in continuity between the files.")
        file_pointer.write("\n	                             The memory is NOT reset after each file. Hence history is maintained between the input files.")
        file_pointer.write("\n	                             Please ensure hat the Logs are collected in a continuous manner from the Vehicle Expedition to use this mode ")
        file_pointer.write("\n	                             This Mode provides results with more correlation with actual Sensor behaviour ")
        file_pointer.write("\n	                             User is responsible to make sure that the file list is sequential the RESIM shall not check this.")
        file_pointer.write("\n	                             USE THIS MODE WITH CAUTION -->")
        file_pointer.write("\n	    <LOG_REPLAY_MODE>" + str(SIL_Data.LOG_Replay_Mode) + "</LOG_REPLAY_MODE>")
        file_pointer.write("\n")
        file_pointer.write("\n	<!-- SIL_Entrypoint -")
        file_pointer.write("\n	CDC					- CDC Data processing")
        file_pointer.write("\n						  The SIL component receives Front-End data over a reference parameter of the SIL function call")
        file_pointer.write("\n	                      The SIL component processes Front-End data to raw targets, object hypotheses, Fences.")
        file_pointer.write("\n	                      NOTE: Input Logs should be of larger size as USC Calibrations need to be extracted from UDP MUX Message")
        file_pointer.write("\n	                      (Internally RESIM uses SIL_SRR3_UDP_Frame_process API)")
        file_pointer.write("\n	                      [This can be selected for LOW/MID variant]")
        file_pointer.write("\n	DETECTIONS_UDP		- Data processing of raw target detections")
        file_pointer.write("\n                        The SIL component receives UDP data via a reference parameter of the SIL function call,")
        file_pointer.write("\n                        SIL component is processing raw targets to Tracks, object hypotheses, fences, function outputs.")
        file_pointer.write("\n                        (Internally RESIM uses SIL_SRR3_UDP_Frame_process API)")
        file_pointer.write("\n                        [This can be selected for LOW/MID variant]")
        file_pointer.write("\n	DSPACE_MODE         - Running dSPACE data BMW_LOW, BMW_MID & BMW_HIGH closed loop SIL. ")
        file_pointer.write("\n	                      Inputs are dSPACE UDP streams & SOME IP. ")
        file_pointer.write("\n	                      Decoded Detections from dSPACE stream are fed to radar emb libraries and")
        file_pointer.write("\n	                      processed PCAN detections are fed to ECU lib through Symbol interface.")
        file_pointer.write("\n	IGNORE_RESIM_KPI_BAD_LOGS_DETECTION_MODE")
        file_pointer.write("\n						- Developers can use this mode to execute resim on Poor Logs collected from road.")
        file_pointer.write("\n						  This mode of execution ignores all the bad logs check(Queue Size 50).")
        file_pointer.write("\n						  This Mode runs Detection Mode Only.")
        file_pointer.write("\n						  Resim Team DOES NOT Recommend this mode to be used.")
        file_pointer.write("\n						  This mode should NOT be used for any Resim Performance analysis.")
        file_pointer.write("\n						  This mode should NOT be used for any customer deliverables.")
        file_pointer.write("\n						  Resim Performance is Very POOR in this mode.")
        file_pointer.write("\n						  Results from this mode are INACCURATE")
        file_pointer.write("\n						  Tickets CANNOT be created if developers are using this mode. -->")
        file_pointer.write("\n	<SIL_Entrypoint>" + str(SIL_Data.SIL_Entrypoint) + "</SIL_Entrypoint>")
        file_pointer.write("\n")
        file_pointer.write("\n	<RESIM_UDP_FRAME_TRANSMISSION STATUS = " + str(SIL_ENET_data.TRANSMISSION_STATUS) + ">")
        file_pointer.write("\n	<!-- UDP_OUTPUT_TRANSMISSION -->")
        file_pointer.write("\n	<!-- 1> ENABLE = When selected, FRAMES will get transmitted ")
        file_pointer.write("\n	     2> DISABLE = When selected, FRAMES will not get transmitted ,-->")
        file_pointer.write("\n	    <RESIM_OUTPUT_UDP_TRANSMISSION> " + SIL_ENET_data.OUTPUT_UDP_TRANSMISSION + "</RESIM_OUTPUT_UDP_TRANSMISSION>")
        file_pointer.write("\n	<!-- UDP_INPUT_TRANSMISSION -->")
        file_pointer.write("\n	<!-- 1> ENABLE = When selected, FRAMES will get transmitted")
        file_pointer.write("\n	     2> DISABLE = When selected, FRAMES will not get transmitted ,")
        file_pointer.write("\n	     Note:- INPUT UDP frame transmission is not valid for DSPACE MODE-->")
        file_pointer.write("\n	    <RESIM_INPUT_UDP_TRANSMISSION> " + SIL_ENET_data.INPUT_UDP_TRANSMISSION + " </RESIM_INPUT_UDP_TRANSMISSION>")
        file_pointer.write("\n	<!-- When using two PCs.")
        file_pointer.write("\n			Set Destination IP :- 192.168.1.41")
        file_pointer.write("\n	        PORT number :- 5555 -->")
        file_pointer.write("\n	<!-- In case of loop back mode (Using only one PC)")
        file_pointer.write("\n			Set Destination IP :- 127.0.0.1")
        file_pointer.write("\n	        Output PORT number :- 5555")
        file_pointer.write("\n	        Input PORT number :- 5556 -->")
        file_pointer.write("\n		<DESTINATION_IP>" + SIL_ENET_data.DESTINATION_IP + "</DESTINATION_IP>")
        file_pointer.write("\n		<DESTINATION_OUTPUT_PORT>" + str(SIL_ENET_data.DEST_OUTPUT_PORT) + "</DESTINATION_OUTPUT_PORT>")
        file_pointer.write("\n		<DESTINATION_INPUT_PORT>" + str(SIL_ENET_data.DEST_INPUT_PORT) + "</DESTINATION_INPUT_PORT>")
        file_pointer.write("\n	</RESIM_UDP_FRAME_TRANSMISSION>")
        file_pointer.write("\n")
        file_pointer.write("\n  <!-- Source of Calibrations. Possible options:")
        file_pointer.write("\n		LOAD_DEFAULT_CAL - Load calibrations from Source Code (All Customers)")
        file_pointer.write("\n		LOAD_UDP_CAL     - using all calibrations from UDP -->")
        file_pointer.write("\n	<CALIBRATION_SOURCE>" + str(SIL_Data.Calibration_Source) + "</CALIBRATION_SOURCE>")
        file_pointer.write("\n")
        file_pointer.write("\n	<RESIM_LOG_INFO>")
        file_pointer.write("\n		<!-- 	LogLevel")
        file_pointer.write("\n				to generate the error log traces")
        file_pointer.write("\n				Set the log levels to get printed on log tracing file")
        file_pointer.write("\n                    0 - DisableLogTrace, log tracing will be disabled")
        file_pointer.write("\n                    1 - Critical")
        file_pointer.write("\n                    2 - Error")
        file_pointer.write("\n                    3 - Warnings and Error")
        file_pointer.write("\n                    4 - Info, Warnings and Error -->")
        file_pointer.write("\n          	  <LogLevel>" + str(SIL_Data.Log_Level) + "</LogLevel>")
        file_pointer.write("\n")
        file_pointer.write("\n			      <!-- LogIncludeDateTime.")
        file_pointer.write("\n				                  Options are")
        file_pointer.write("\n				 	                      1. Include Date time")
        file_pointer.write("\n					                      2. Doesn't include date time.-->")
        file_pointer.write("\n	    <LogIncludeDateTime>" + str(SIL_Data.Log_Include_Date_Time) + "</LogIncludeDateTime>")
        file_pointer.write("\n")
        file_pointer.write("\n		<!-- LogTracingPath selection.")
        file_pointer.write("\n				        Options are")
        file_pointer.write("\n				        SAME_AS_INPUT,")
        file_pointer.write("\n				        NONE,")
        file_pointer.write("\n				        SAME_AS_OUTPUT and")
        file_pointer.write("\n				        valid folder path with below Supported file formats")
        file_pointer.write("\n						                .xml")
        file_pointer.write("\n                        .txt")
        file_pointer.write("\n                        .log -->")
        file_pointer.write("\n	              <LogTracingPath>" + str(SIL_Data.Log_Tracing_Path) + "</LogTracingPath>")
        file_pointer.write("\n")
        file_pointer.write("\n	              <!-- TimestampTracePath - Create a Debug information / report containing Timestamp information.")
        file_pointer.write("\n				                  Options are")
        file_pointer.write("\n				                  SAME_AS_INPUT,")
        file_pointer.write("\n				                  NONE,")
        file_pointer.write("\n				                  SAME_AS_OUTPUT -->")
        file_pointer.write("\n	              <TimestampTracePath>" + str(SIL_Data.TS_TRACE) + "</TimestampTracePath> ")
        file_pointer.write("\n")
        file_pointer.write("\n		          <!-- ResimErrorTracepath - Create a Debug information / report containing Errors in RESIM.")
        file_pointer.write("\n				                  Options are ")
        file_pointer.write("\n				                  SAME_AS_INPUT,")
        file_pointer.write("\n				                  NONE,")
        file_pointer.write("\n				                  SAME_AS_OUTPUT -->")
        file_pointer.write("\n		          <ResimErrorTracepath>" + str(SIL_Data.RESIM_ERROR_TRACE_Path) + "</ResimErrorTracepath>")
        file_pointer.write("\n")
        file_pointer.write("\n")
        file_pointer.write("\n	              <!-- LogScanDropTracePath - Create a debug information / Report for Scan drops in the input log.")
        file_pointer.write("\n				                  Options are")
        file_pointer.write("\n				                  SAME_AS_INPUT,")
        file_pointer.write("\n				                  NONE,")
        file_pointer.write("\n				                  SAME_AS_OUTPUT -->")
        file_pointer.write("\n	              <LogScanDropTracePath>" + str(SIL_Data.DEBUG_TRACE) + "</LogScanDropTracePath>")
        file_pointer.write("\n")
        file_pointer.write("\n		          <!--PLP_TIMESTAMP Selection : Options Are SAME_AS_INPUT, NONE , SAME_AS_OUTPUT and valid folder path")
        file_pointer.write("\n			              PLP_TIMESTAMP tag to enter valid folder path only if options such as SAME AS INPUT OR NONE , SAME_AS_OUTPUTis not selected  -->")
        file_pointer.write("\n        <PLP_TIMESTAMP>" + str(SIL_Data.PLP_TIMESTAMP) + "</PLP_TIMESTAMP>")
        file_pointer.write("\n")
        file_pointer.write("\n		          <!--  To get SCanIndex/checksum/crc error text file ")
        file_pointer.write("\n				                  Options are")
        file_pointer.write("\n					                      1. A text file will be created with Packet loss Info")
        file_pointer.write("\n					                      0. NO text file with packet loss info is created")
        file_pointer.write("\n				                  This is applicable only for RNA_SRR5")
        file_pointer.write("\n")
        file_pointer.write("\n	                              Enable or Disable Timing profile")
        file_pointer.write("\n	                                      1. Enable Timing profile")
        file_pointer.write("\n	                                      0. Disable Timing profile  -->")
        file_pointer.write("\n	              <TIMING_PROFILE>" + str(SIL_Data.TIMING_PROFILE) + "</TIMING_PROFILE>")
        file_pointer.write("\n")
        file_pointer.write("\n		          <!-- TIMING_PROFILE_PATH selection. Options are SAME_AS_INPUT, NONE , SAME_AS_OUTPUT and valid folder path")
        file_pointer.write("\n			              TIMING_PROFILE_PATH tag to enter valid folder path only if options such as SAME_AS_INPUT OR NONE ,SAME_AS_OUTPUT is not selected")
        file_pointer.write("\n			              Provide the path to generate log timing profile files.-->")
        file_pointer.write("\n		<TIMING_PROFILE_PATH>" + str(SIL_Data.TIMING_PROFILE_Path) + "</TIMING_PROFILE_PATH>")
        file_pointer.write("\n		<!-- STATISTIC_REPORT_PATH selection. Options are SAME_AS_INPUT , NONE , SAME_AS_OUTPUT and valid folder path")
        file_pointer.write("\n			       If STATISTIC_REPORT_PATH selection is neither SAME_AS_INPUT or NONE , SAME_AS_OUTPUT then use STATISTIC_REPORT_PATH tag to enter valid folder path")
        file_pointer.write("\n			       Provide the path to generate Statistic Report")
        file_pointer.write("\n			       Warning Note:- Statistic Report feature is currently available for LINUX platform")
        file_pointer.write("\n				           In WINDOWS use NONE.")
        file_pointer.write("\n				           If want to avail this feature in windows, Please make sure to use same configured built dlls from all the libraries")
        file_pointer.write("\n				           FW:- RELEASE SENSORS:- RELEASE RECU:- RELEASE")
        file_pointer.write("\n				           FW:- DEBUG SENSORS:- DEBUG RECU:- DEBUG -->")
        file_pointer.write("\n	    <STATISTIC_REPORT_PATH>" + str(SIL_Data.STATISTIC_REPORT_PATH) + "</STATISTIC_REPORT_PATH>")
        file_pointer.write("\n")
        file_pointer.write("\n		  <!-- Create Signal MF4 File")
        file_pointer.write("\n				        Options are")
        file_pointer.write("\n					            1. ENABLE -Create Signal MF4 File")
        file_pointer.write("\n					            2. DISABLE - No Signal File creation-->")
        file_pointer.write("\n		  <SIGNAL_CREATION>" + str(SIL_Data.SIGNAL_CREATION) + "</SIGNAL_CREATION>")
        file_pointer.write("\n</RESIM_LOG_INFO>")
        file_pointer.write("\n")
        file_pointer.write("\n</SIL_ENGINE_Configuration>")
        file_pointer.write("\n")
    # progress_update(80)
    return


def sil_output_txt_box(SIL_output_display):
    global output_text_sil
    global text_box_sil_label
    text_box_sil_label = Label(text="SIL Output:", font=('arial', 20, 'bold'), bg='slate gray1').place(x=20, y=390)
    output_text_sil = scrolledtext.ScrolledText(root, height=3, width=80)
    output_text_sil.place(x=20, y=470)
    output_text_sil.insert(END, SIL_output_display)
    return


def Execute_SIL_Command(output_Path, Output, bn_califr_log_SIL_list, faseth_log_SIL_list, srr_debug_log_SIL_list, srr_reference_log_SIL_list):
    # global exe_command
    global exe_command
    exe_path_name = os.path.normpath("../../RESIM_SIL/SIL_ENGINE/APT_SRR_RESIM.exe")
    if len(bn_califr_log_SIL_list and faseth_log_SIL_list and srr_reference_log_SIL_list) == 0 and len(srr_debug_log_SIL_list) >= 1 and Output == 'SAME_AS_INPUT':
        exe_command = exe_path_name + " SIL_Engine_Config_v_2p9.xml " + "SIL_flist.txt"
    elif len(bn_califr_log_SIL_list) == len(faseth_log_SIL_list) == len(srr_debug_log_SIL_list) == len(srr_reference_log_list) and Output == 'SAME_AS_OUTPUT' or 'NEW_OUTPUT_PATH':
        exe_command = exe_path_name + " SIL_Engine_Config_v_2p9.xml " + "SIL_json.json " + output_Path
    else:
        messagebox.showerror(title='Execution Error', message='!!! PLEASE BROWSE THE LOG FILES, Create Json/ Flist !!!')
    # + str(output_Path)
    print("exe_command: \n", exe_command)
    print("--------------")
    # progress_update(100)
    '''t = threading.Thread(target=subprocess.call(exe_command))
    t.daemon = True
    t.start()
    t.join(10)'''
    pro = subprocess.Popen(exe_command, stdout=subprocess.PIPE, shell=True)

    global SIL_output_display
    SIL_output_display = pro.communicate()
    sil_output_txt_box(SIL_output_display)
    print("exe_command: ", exe_command)
    messagebox.showinfo(title='SIL Tool', message='SIL Tool Run Completed Successfully')
    # print("Global_var_class_obj.log_path :\n", Global_var_class_obj.log_path)
    return


'''def progress_update(val):
    # SIL_widgets_obj.progress_bar['value'] = val
    root.update_idletasks()
    return'''
