name: Building Block CI Verification

on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: bb-ci-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  verify:
    if: always()
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
    uses: GPO/Core_Radar_CICD/.github/workflows/common-bb-verification.yml@v0.3.2
    secrets:
      NETRC_CONTENT: ${{ secrets.ADVRADAR_NETRC_CONTENT }}
      ARB_TOKEN: ${{ secrets.ADVRADAR_ARB_TOKEN }}
      JIRA_TOKEN: ${{ secrets.ADVRADAR_SID_JIRA_API_KEY }}
    with:
      # Common controls
      run-ut: false
      run-build: false

      # PR validation
      run-pr-validation: true
      jira-url: ${{ vars.JIRA_URL }}

  post_merge:
    if: github.event_name == 'push'
    # if: false disable post merge for now
    uses: GPO/Core_Radar_CICD/.github/workflows/common-bb-post-merge.yml@v0.3.2
    with:
      project-name: core-radar-gen7-rsp-sil
      base-sha: ${{ github.event.before }}
      head-sha: ${{ github.sha }}
      version-file: version.yaml
      package-include-patterns: "*.c *.cpp *.h *.inc *.S *.cc BUILD WORKSPACE version.yaml *.bzl"
    secrets:
      app-id: ${{ secrets.DSO_BOT_APP_ID }}
      app-private-key: ${{ secrets.DSO_BOT_PRIVATE_KEY }}
      jfrog-username: ${{ secrets.ADVRADAR_SID_USERNAME }}
      jfrog-password: ${{ secrets.ADVRADAR_JFROG_API_KEY }}
