target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_FILE})

target_include_directories(SCW PUBLIC ${CMAKE_CURRENT_LIST_DIR})
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw_debug_interface.h)
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw_debug_writer.h)
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw.h)
target_sources(SCW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/scw_iface.h)
target_sources(SCW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/scw_core_input_t.h)
target_sources(SCW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/scw_core_output_t.h)
target_sources(SCW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/scw_instance_t.h)
target_sources(SCW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/scw_persistent_t.h)
target_sources(SCW PUBLIC ${CMAKE_CURRENT_LIST_DIR}/scw_types.h)
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw_helper_functions.h)

target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw_debug_interface.c)
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw_debug_writer.c)
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw.c)
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw_iface.c)
target_sources(SCW PRIVATE ${CMAKE_CURRENT_LIST_DIR}/scw_helper_functions.c)
