set(REL_PATH SharedTrackerAPI)

set(IFACE_SRC
    ${REL_PATH}/Logging/f360_detection_log.h
    ${REL_PATH}/Logging/f360_functional_safety_faults_log.h
    ${REL_PATH}/Logging/f360_internal_cluster.h
    ${REL_PATH}/Logging/f360_internal_cwd.h
    ${REL_PATH}/Logging/f360_internal_detection_history.h
    ${REL_PATH}/Logging/f360_internal_object.h
    ${REL_PATH}/Logging/f360_internal_reflection_buffer.h
    ${REL_PATH}/Logging/f360_internal_underdrivability.h
    ${REL_PATH}/Logging/f360_log_data.h
    ${REL_PATH}/Logging/f360_log_types.h
    ${REL_PATH}/Logging/f360_object_log.h
    ${REL_PATH}/Logging/f360_rot_object_log.h
    ${REL_PATH}/Logging/f360_sensor_calib_log.h
    ${REL_PATH}/Logging/F360HostPropsLog.h
    ${REL_PATH}/Logging/HostCalibsLog.h
    ${REL_PATH}/Logging/HostRawDataLog.h
    ${REL_PATH}/Logging/SensorInfoLog.h
    ${REL_PATH}/Logging/StaticEnvPolysLog.h
    ${REL_PATH}/Logging/SyncInfoLog.h
    ${REL_PATH}/Logging/TimingInfoLog.h
    ${REL_PATH}/Logging/TrackerInfoLog.h
    ${REL_PATH}/Logging/TrackerInternal.h
    ${REL_PATH}/Logging/VehicleInfoLog.h
    ${REL_PATH}/Logging/VSEInternalDataLog.h
    ${REL_PATH}/Logging/VSEOutputLog.h
    ${REL_PATH}/Logging/F360_CSLPTracker_Log.h
    ${REL_PATH}/Logging/TrailerDetectorLog.h
    ${REL_PATH}/Logging/TrailerDetectorInternalLog.h
    ${REL_PATH}/Logging/CVTrailerOutputLog.h
    ${REL_PATH}/Logging/SGOutputLog.h
    ${REL_PATH}/Logging/SGTimingLog.h
    ${REL_PATH}/Types/f360_range_type.h
    ${REL_PATH}/Types/f360_reuse.h
    ${REL_PATH}/Types/f360_sensor_mounting_position.h
    ${REL_PATH}/Types/f360_sensor_type.h
    ${REL_PATH}/Types/f360_velocity.h
    ${REL_PATH}/Types/T360_Types.h
    ${REL_PATH}/Types/f360_look_ID.h
    ${REL_PATH}/Types/f360_look_type.h
    ${REL_PATH}/Types/f360_mounting_location.h
    ${REL_PATH}/Types/f360_position.h
    ${REL_PATH}/Types/f360_variant_type.h
    ${REL_PATH}/Types/f360_core_info.h
    ${REL_PATH}/Types/f360_host.h
    ${REL_PATH}/Types/f360_host_calib.h
    ${REL_PATH}/Types/f360_host_raw.h
    ${REL_PATH}/Types/f360_radar_sensor.h
    ${REL_PATH}/Types/f360_trk_fltr_cca_states_logging.h
    ${REL_PATH}/Types/f360_trk_fltr_ccv_states.h
    ${REL_PATH}/Types/f360_trk_fltr_cca_states.h
    ${REL_PATH}/Types/f360_trk_fltr_ctca_states.h
    ${REL_PATH}/core/f360_constants.h
    ${REL_PATH}/core/f360_get_wall_time.h
    ${REL_PATH}/core/f360_input_diagnostics.h
    ${REL_PATH}/core/f360_input_faults.h
    ${REL_PATH}/core/f360_ocg_interface.h
    ${REL_PATH}/core/f360_sg_interface.h
    ${REL_PATH}/core/f360_output_diagnostics.h
    ${REL_PATH}/core/f360_previous_cycle_info.h
    ${REL_PATH}/core/f360_safety_control_logic.h
    ${REL_PATH}/core/f360_tracker.h
    ${REL_PATH}/core/f360_tracker_version.h
    ${REL_PATH}/core/f360_variant.h
    ${REL_PATH}/core/f360_variant_definition.h
    ${REL_PATH}/core/State_Manager.h
    ${REL_PATH}/core/variants/f360_variant_definition_a.h
    ${REL_PATH}/core/variants/f360_variant_definition_b.h
    ${REL_PATH}/core/variants/f360_variant_definition_c.h
    ${REL_PATH}/core/variants/f360_variant_definition_d.h
    ${REL_PATH}/core/variants/f360_variant_definition_e.h
    ${REL_PATH}/core/variants/f360_variant_definition_f.h
    ${REL_PATH}/core/variants/f360_variant_definition_g.h
    ${REL_PATH}/core/variants/f360_variant_definition_h.h
    ${REL_PATH}/core/variants/f360_variant_definition_i.h
    ${REL_PATH}/core/variants/f360_variant_definition_j.h
    ${REL_PATH}/core/variants/f360_variant_definition_k.h
    ${REL_PATH}/core/variants/f360_variant_definition_l.h
    ${REL_PATH}/core/variants/f360_variant_definition_m.h
    ${REL_PATH}/core/variants/f360_variant_definition_n.h
    ${REL_PATH}/core/variants/f360_variant_definition_o.h
    ${REL_PATH}/core/variants/f360_variant_definition_p.h
    ${REL_PATH}/core/variants/f360_variant_definition_q.h
)

